import { spawn } from "node:child_process";
import { createHash } from "node:crypto";
import path from "node:path";

export type MediaParserRequest={kind:"image"|"pdf";inputPath:string;outputDir:string};
export type MediaParserOutput={role:"original"|"thumbnail"|"small"|"medium"|"large";path:string;bytes:number;checksum:string};
export type MediaParserResult={ok:true;kind:"image"|"pdf";contentType:"image/jpeg"|"image/png"|"image/webp"|"application/pdf";width?:number;height?:number;pageCount?:number;outputs:MediaParserOutput[]}|{ok:false;failureCode:"parser_isolation_failure"|"scan_quarantined"};
const ROLES=new Set(["original","thumbnail","small","medium","large"]);
const TYPES=new Set(["image/jpeg","image/png","image/webp","application/pdf"]);
export function validateParserResult(value:unknown,request?:MediaParserRequest):MediaParserResult{if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("PARSER_OUTPUT_INVALID");let serialized:string;try{serialized=JSON.stringify(value)}catch{throw new Error("PARSER_OUTPUT_INVALID")}if(!serialized||Buffer.byteLength(serialized)>65536)throw new Error("PARSER_OUTPUT_INVALID");const r=value as Record<string,unknown>;if(r.ok===false&&["parser_isolation_failure","scan_quarantined"].includes(String(r.failureCode)))return r as MediaParserResult;if(r.ok!==true||!["image","pdf"].includes(String(r.kind))||!TYPES.has(String(r.contentType))||!Array.isArray(r.outputs)||r.outputs.length<1||r.outputs.length>5)throw new Error("PARSER_OUTPUT_INVALID");if(r.kind==="pdf"&&(r.contentType!=="application/pdf"||r.outputs.length!==1)||(r.kind==="image"&&!String(r.contentType).startsWith("image/")))throw new Error("PARSER_OUTPUT_INVALID");const roles=new Set<string>(),root=request?path.resolve(request.outputDir)+path.sep:"";let total=0;for(const item of r.outputs){if(!item||typeof item!=="object"||Array.isArray(item))throw new Error("PARSER_OUTPUT_INVALID");const o=item as Record<string,unknown>,role=String(o.role),outputPath=String(o.path);if(!ROLES.has(role)||roles.has(role)||!/^[0-9a-f]{64}$/.test(String(o.checksum))||!Number.isSafeInteger(o.bytes)||(o.bytes as number)<1||(request&&(!path.isAbsolute(outputPath)||!path.resolve(outputPath).startsWith(root))))throw new Error("PARSER_OUTPUT_INVALID");roles.add(role);total+=Number(o.bytes)}if(!roles.has("original")||total>50*1024*1024)throw new Error("PARSER_OUTPUT_INVALID");return r as MediaParserResult}
export async function launchMediaParser(request:MediaParserRequest,options:{command:string;args:string[];timeoutMs?:number;env?:Record<string,string>;heartbeat?:()=>Promise<boolean>;heartbeatMs?:number}):Promise<MediaParserResult>{const timeout=options.timeoutMs??(request.kind==="image"?30000:45000);return new Promise(resolve=>{const child=spawn(options.command,[...options.args,request.kind,request.inputPath,request.outputDir],{shell:false,detached:true,env:{PATH:"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",VANSTRO_MEDIA_PARSER:"1",...(options.env??{})},stdio:["ignore","pipe","pipe"]});let stdout=Buffer.alloc(0),stderr=Buffer.alloc(0),settled=false,heartbeatTimer:NodeJS.Timeout|undefined;const terminate=(signal:NodeJS.Signals)=>{try{process.kill(-child.pid!,signal)}catch{try{child.kill(signal)}catch{}}},finish=(result:MediaParserResult)=>{if(settled)return;settled=true;clearTimeout(timer);if(heartbeatTimer)clearTimeout(heartbeatTimer);resolve(result)},scheduleHeartbeat=()=>{if(!options.heartbeat||settled)return;heartbeatTimer=setTimeout(async()=>{if(settled)return;try{if(!await options.heartbeat!()){terminate("SIGKILL");return finish({ok:false,failureCode:"parser_isolation_failure"})}}catch{terminate("SIGKILL");return finish({ok:false,failureCode:"parser_isolation_failure"})}scheduleHeartbeat()},options.heartbeatMs??10000);heartbeatTimer.unref()};scheduleHeartbeat();child.stdout.on("data",chunk=>{stdout=Buffer.concat([stdout,chunk]);if(stdout.length>65536){terminate("SIGKILL");finish({ok:false,failureCode:"parser_isolation_failure"})}});child.stderr.on("data",chunk=>{stderr=Buffer.concat([stderr,chunk]);if(stderr.length>8192)terminate("SIGKILL")});child.on("error",()=>finish({ok:false,failureCode:"parser_isolation_failure"}));child.on("exit",code=>{if(code!==0||stderr.length>8192)return finish({ok:false,failureCode:"parser_isolation_failure"});try{finish(validateParserResult(JSON.parse(stdout.toString("utf8")),request))}catch{finish({ok:false,failureCode:"parser_isolation_failure"})}});const timer=setTimeout(()=>{terminate("SIGTERM");setTimeout(()=>terminate("SIGKILL"),2000).unref();finish({ok:false,failureCode:"parser_isolation_failure"})},timeout)})}
export function parserConfigDigest(input:unknown){return createHash("sha256").update("media-parser-config-v1\0").update(JSON.stringify(input)).digest("hex")}
export function exactDigest(value:string|undefined){if(!value||!/^sha256:[0-9a-f]{64}$/.test(value))throw new Error("MEDIA_PROCESSING_DIGEST_INVALID");return value}
