import assert from "node:assert/strict";
import test from "node:test";
import { launchMediaParser, validateParserResult } from "./media-parser.js";

test("P07 parser output is bounded and exact",()=>{const failed=validateParserResult({ok:false,failureCode:"scan_quarantined"});assert.equal(failed.ok,false);if(!failed.ok)assert.equal(failed.failureCode,"scan_quarantined");assert.throws(()=>validateParserResult({ok:true,kind:"image",contentType:"image/png",outputs:[{role:"original",path:"x",bytes:1,checksum:"x"}]}),/PARSER_OUTPUT_INVALID/)});
test("P07 missing, empty and malformed parser bodies fail closed",()=>{for(const value of [undefined,null,"",{},Buffer.alloc(0)])assert.throws(()=>validateParserResult(value),/PARSER_OUTPUT_INVALID/)});
test("P07 parser timeout fails closed without shell",async()=>{const result=await launchMediaParser({kind:"image",inputPath:"/tmp/input",outputDir:"/tmp/out"},{command:process.execPath,args:["-e","setTimeout(()=>{},10000)"],timeoutMs:20});assert.deepEqual(result,{ok:false,failureCode:"parser_isolation_failure"})});
test("P07 parser heartbeats throughout a lease-sized run",async()=>{let beats=0;const result=await launchMediaParser({kind:"image",inputPath:"/tmp/input",outputDir:"/tmp/out"},{command:process.execPath,args:["-e",`setTimeout(()=>process.stdout.write(JSON.stringify({ok:false,failureCode:"scan_quarantined"})),80)`],timeoutMs:200,heartbeatMs:20,heartbeat:async()=>{beats++;return true}});assert.equal(result.ok,false);assert.ok(beats>=3)});
test("P07 slow heartbeat never overlaps and parser stays healthy",async()=>{let active=0,maxActive=0,beats=0;const result=await launchMediaParser({kind:"image",inputPath:"/tmp/input",outputDir:"/tmp/out"},{command:process.execPath,args:["-e",`setTimeout(()=>process.stdout.write(JSON.stringify({ok:false,failureCode:"scan_quarantined"})),140)`],timeoutMs:250,heartbeatMs:10,heartbeat:async()=>{active++;maxActive=Math.max(maxActive,active);beats++;await new Promise(resolve=>setTimeout(resolve,35));active--;return true}});assert.equal(result.ok,false);assert.equal(maxActive,1);assert.ok(beats>=2)});
test("P07 parser aborts when heartbeat loses the lease",async()=>{const result=await launchMediaParser({kind:"image",inputPath:"/tmp/input",outputDir:"/tmp/out"},{command:process.execPath,args:["-e","setTimeout(()=>{},1000)"],timeoutMs:200,heartbeatMs:20,heartbeat:async()=>false});assert.deepEqual(result,{ok:false,failureCode:"parser_isolation_failure"})});
