import assert from "node:assert/strict";
import test from "node:test";
import { randomBytes, randomUUID } from "node:crypto";
import { promises as fs } from "node:fs";
import os from "node:os";
import path from "node:path";
import { attachMediaUsage, detectMediaSignature, mediaRetryKeyReadiness, parseMediaKeyset, PrivateFilesystemMediaStorage, reconcileMediaRetryRetention, requiredMediaVariantRoles, safeMediaDisplayName, validateMediaFilename, validateNativeMedia } from "./media.js";
import { ReadableStream } from "node:stream/web";

test("P07 native formats and exact byte limits fail closed",()=>{assert.deepEqual(validateNativeMedia("image","image/jpeg",1),{kind:"image",contentType:"image/jpeg",expectedBytes:1});assert.deepEqual(validateNativeMedia("pdf","application/pdf",25*1024*1024),{kind:"pdf",contentType:"application/pdf",expectedBytes:25*1024*1024});for(const [kind,type] of [["image","image/svg+xml"],["image","image/avif"],["video","video/mp4"],["document","application/msword"]])assert.throws(()=>validateNativeMedia(kind,type,1),/MEDIA_TYPE_UNSUPPORTED/);assert.throws(()=>validateNativeMedia("image","image/png",10*1024*1024+1),/MEDIA_TOO_LARGE/)});
test("P07 filenames never become paths or headers",()=>{assert.equal(validateMediaFilename(" photo.jpg "),"photo.jpg");assert.equal(safeMediaDisplayName("<photo>.jpg"),"photo.jpg");for(const name of ["../x.jpg","a/b.jpg","a\\b.jpg","x\r\nInjected","‮file.jpg",".",".."])assert.throws(()=>validateMediaFilename(name),/MEDIA_METADATA_INVALID/)});
test("P07 minimal API signature checks are exact",()=>{assert.equal(detectMediaSignature(Buffer.from([0xff,0xd8,0xff,0])),"image/jpeg");assert.equal(detectMediaSignature(Buffer.from([137,80,78,71,13,10,26,10])),"image/png");assert.equal(detectMediaSignature(Buffer.from("RIFFxxxxWEBP")),"image/webp");assert.equal(detectMediaSignature(Buffer.from("%PDF-1.7")),"application/pdf");assert.throws(()=>detectMediaSignature(Buffer.from("<svg>")),/MEDIA_SIGNATURE_MISMATCH/)});
test("P07 required role boundary is no-upscale and PDF original-only",()=>{assert.deepEqual(requiredMediaVariantRoles("pdf"),["original"]);for(const [m,roles] of [[200,["original"]],[320,["original"]],[321,["original","thumbnail"]],[640,["original","thumbnail"]],[641,["original","thumbnail","small"]],[1025,["original","thumbnail","small","medium"]],[1921,["original","thumbnail","small","medium","large"]]] as const)assert.deepEqual(requiredMediaVariantRoles("image",m,m),roles);assert.throws(()=>requiredMediaVariantRoles("image",0,1),/MEDIA_DIMENSIONS_INVALID/)});
test("P07 HMAC keyset requires one 32-byte active key",()=>{const key=randomBytes(32).toString("base64"),parsed=parseMediaKeyset(JSON.stringify({activeKid:"m1",keys:[{kid:"m1",key,mode:"active"}]}));assert.equal(parsed.activeKid,"m1");assert.throws(()=>parseMediaKeyset(JSON.stringify({activeKid:"m1",keys:[{kid:"m1",key,mode:"verify-only"}]})),/MEDIA_KEYSET_INVALID/)});
test("P07 retry key readiness uses the bounded database projection",async()=>{const old={kid:"old",key:randomBytes(32),mode:"verify-only" as const},active={kid:"new",key:randomBytes(32),mode:"active" as const},keyset={activeKid:"new",keys:[active,old]};let required=[{kid:"old"}];const db={$queryRaw:async()=>required} as any;assert.equal(await mediaRetryKeyReadiness(db,keyset),true);assert.equal(await mediaRetryKeyReadiness(db,{activeKid:"new",keys:[active]}),false);required=[];assert.equal(await mediaRetryKeyReadiness(db,{activeKid:"new",keys:[active]}),true)});
test("P07 API and Worker retention owners may race idempotently and failures stay safe",async()=>{let calls=0;const database={$queryRaw:async()=>{calls++;return calls===1?[{commandsDeleted:1n,retirementsDeleted:1n}]:[{commandsDeleted:0n,retirementsDeleted:0n}]}} as any;assert.deepEqual(await Promise.all([reconcileMediaRetryRetention(database),reconcileMediaRetryRetention(database)]),[{ok:true,commandsDeleted:1,retirementsDeleted:1},{ok:true,commandsDeleted:0,retirementsDeleted:0}]);const evidence:string[]=[];assert.deepEqual(await reconcileMediaRetryRetention({$queryRaw:async()=>{throw new Error("private")}} as any,code=>evidence.push(code)),{ok:false,commandsDeleted:0,retirementsDeleted:0});assert.deepEqual(evidence,["MEDIA_RETRY_RETENTION_FAILED"])});
test("P07 private storage rejects symlink parents and entries",async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),"vanstro-media-")),outside=await fs.mkdtemp(path.join(os.tmpdir(),"vanstro-outside-")),storage=new PrivateFilesystemMediaStorage(root);try{assert.equal(await storage.readiness(),true);await fs.symlink(outside,path.join(root,"linked"));await assert.rejects(storage.put("linked/escape",Buffer.from("x"),1),/MEDIA_STORAGE_UNAVAILABLE/);await fs.mkdir(path.join(root,"safe"));await fs.writeFile(path.join(outside,"secret"),"secret");await fs.symlink(path.join(outside,"secret"),path.join(root,"safe","alias"));await assert.rejects(storage.read("safe/alias"));await assert.rejects(storage.delete("safe/alias"));await fs.mkdir(path.join(root,"safe","directory"));await assert.rejects(storage.read("safe/directory"));await assert.rejects(storage.delete("safe/directory"));if(process.platform!=="win32"){await fs.writeFile(path.join(root,"safe","regular"),"ok");await fs.rename(path.join(root,"safe","regular"),path.join(root,"safe","moved"));await fs.symlink(path.join(outside,"secret"),path.join(root,"safe","regular"));await assert.rejects(storage.read("safe/regular"));await assert.rejects(storage.delete("safe/regular"))}await storage.put(`safe/${randomUUID()}`,Buffer.from("ok"),2)}finally{await fs.rm(root,{recursive:true,force:true});await fs.rm(outside,{recursive:true,force:true})}});

test("P07 stream heartbeat fences a lost lease and removes partial bytes",async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),"vanstro-media-stream-")),storage=new PrivateFilesystemMediaStorage(root),data=Buffer.alloc(1024,7);try{let beats=0;const stream=new ReadableStream<Uint8Array>({start(controller){controller.enqueue(data);controller.close()}});await assert.rejects(storage.putStream("uploads/lost.part",stream as any,data.length,{heartbeatEveryBytes:1,heartbeat:async()=>{beats++;return false}}),/MEDIA_UPLOAD_LEASE_LOST/);assert.equal(beats,1);await assert.rejects(fs.stat(path.join(root,"uploads/lost.part")),error=>(error as NodeJS.ErrnoException).code==="ENOENT")}finally{await fs.rm(root,{recursive:true,force:true})}});

test("P07 chunked stream heartbeats repeatedly and abort removes partial bytes",async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),"vanstro-media-chunks-")),storage=new PrivateFilesystemMediaStorage(root);try{let beats=0;const chunks=Array.from({length:40},()=>Buffer.alloc(64*1024,5)),stream=new ReadableStream<Uint8Array>({start(controller){for(const chunk of chunks)controller.enqueue(chunk);controller.close()}}),result=await storage.putStream("chunks/complete.part",stream as any,chunks.reduce((n,c)=>n+c.length,0),{heartbeatEveryBytes:256*1024,heartbeat:async()=>{beats++;return true}});assert.ok(beats>=10);assert.equal(result.bytes,40*64*1024);const aborted=new ReadableStream<Uint8Array>({pull(controller){controller.enqueue(Buffer.alloc(1024));controller.error(new Error("client_abort"))}});await assert.rejects(storage.putStream("chunks/aborted.part",aborted as any,4096),/client_abort/);await assert.rejects(fs.stat(path.join(root,"chunks/aborted.part")),error=>(error as NodeJS.ErrnoException).code==="ENOENT")}finally{await fs.rm(root,{recursive:true,force:true})}});

test("P07 time cadence heartbeats while reader is paused",async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),"vanstro-media-slow-")),storage=new PrivateFilesystemMediaStorage(root);try{let beats=0;const stream=new ReadableStream<Uint8Array>({async start(controller){controller.enqueue(Buffer.from("a"));await new Promise(resolve=>setTimeout(resolve,45));controller.enqueue(Buffer.from("b"));controller.close()}}),result=await storage.putStream("slow/input.part",stream as any,2,{heartbeatEveryBytes:1024,heartbeatIntervalMs:10,heartbeat:async()=>{beats++;return true}});assert.equal(result.bytes,2);assert.ok(beats>=4)}finally{await fs.rm(root,{recursive:true,force:true})}});

test("P07 descriptor-relative traversal resists an intermediate-parent swap",async()=>{if(process.platform!=="linux")return;const root=await fs.mkdtemp(path.join(os.tmpdir(),"vanstro-media-race-")),outside=await fs.mkdtemp(path.join(os.tmpdir(),"vanstro-media-outside-")),storage=new PrivateFilesystemMediaStorage(root),parent=path.join(root,"race"),parked=path.join(root,"parked");try{await fs.mkdir(parent);let stop=false;const swap=(async()=>{while(!stop){try{await fs.rename(parent,parked);await fs.symlink(outside,parent);await fs.unlink(parent);await fs.rename(parked,parent)}catch{}}})();for(let index=0;index<100;index++)await storage.put(`race/${randomUUID()}`,Buffer.from("x"),1).catch(error=>assert.match(String(error),/MEDIA_STORAGE_UNAVAILABLE|ENOENT|ELOOP/));stop=true;await swap;assert.deepEqual(await fs.readdir(outside),[])}finally{await fs.rm(root,{recursive:true,force:true});await fs.rm(outside,{recursive:true,force:true})}});

test("P07 Linux parent swaps cannot escape publish read metadata or delete",async()=>{if(process.platform!=="linux")return;const root=await fs.mkdtemp(path.join(os.tmpdir(),"vanstro-media-ops-")),outside=await fs.mkdtemp(path.join(os.tmpdir(),"vanstro-media-ops-out-")),storage=new PrivateFilesystemMediaStorage(root);try{await storage.put("stage/source",Buffer.from("safe"),4);await fs.mkdir(path.join(root,"final"));let stop=false;const swap=(async()=>{while(!stop){try{await fs.rename(path.join(root,"final"),path.join(root,"parked"));await fs.symlink(outside,path.join(root,"final"));await fs.unlink(path.join(root,"final"));await fs.rename(path.join(root,"parked"),path.join(root,"final"))}catch{}}})();for(let i=0;i<50;i++){await storage.publish("stage/source","final/object").catch(()=>undefined);await storage.read("final/object").catch(()=>undefined);await storage.metadata("final/object").catch(()=>undefined);await storage.delete("final/object").catch(()=>undefined);if(!(await storage.metadata("stage/source")).exists)await storage.put("stage/source",Buffer.from("safe"),4)}stop=true;await swap;assert.deepEqual(await fs.readdir(outside),[])}finally{await fs.rm(root,{recursive:true,force:true});await fs.rm(outside,{recursive:true,force:true})}});

test("P07 Usage authorizes before authoritative target existence",async()=>{const calls:string[]=[];const transaction={ $executeRaw:async()=>0,$queryRaw:async()=>[],mediaAsset:{findUnique:async()=>({id:"asset",version:3,status:"ready",retiring:false,tombstonedAt:null,kind:"pdf",authorizationScopeKind:"global",dealerIds:[],locationIds:[]})}} as any;const db={$transaction:async(fn:any)=>fn(transaction)} as any;await assert.rejects(()=>attachMediaUsage(db,{assetId:randomUUID(),expectedAssetVersion:3,entityType:"product",entityId:randomUUID(),slot:"gallery",actor:{actorId:randomUUID(),actorType:"admin_user",effectiveRoles:[],permissionGrants:[],scope:{kind:"global"},contextRevision:"1"},target:{permission:"products.read",scope:{kind:"global"},exists:async()=>{calls.push("exists");return false},requiredLocales:async()=>["en-CA","fr-CA"]},authorize:async(_tx,permission)=>{calls.push(permission);if(permission==="products.read")throw new Error("MEDIA_NOT_FOUND")},audit:async()=>{}}),/MEDIA_NOT_FOUND/);assert.deepEqual(calls,["media.update","products.read"])});
