import assert from "node:assert/strict";
import test from "node:test";
import { randomUUID } from "node:crypto";
import { prisma } from "./index.js";

function disposable(t:test.TestContext){const name=new URL(process.env.DATABASE_URL??"postgresql://x/unknown").pathname;if(!/(test|disposable|smoke)/i.test(name)){t.skip("migration 58 requires a disposable DB");return false}return true}
const hash="a".repeat(43);
async function asset(status="ready"){const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO media_assets ("id","contractVersion","schemaVersion","registryVersion","kind","status","originalFilename","safeDisplayName","declaredContentType","expectedBytes","source","provenanceOrigin","storageProvider","processingPolicyVersion","securityPolicyVersion","processingConfigHash","variantSetState","tags","authorizationScopeKind","dealerIds","locationIds","createdByActorType","effectiveRoles","permissionGrants","contextRevision","retentionClass","retentionPolicyVersion","requestId","updatedAt") VALUES ($1::uuid,'media-asset.v1','media-asset-schema.v1','media-registry.v1','image',$2,'x.jpg','x.jpg','image/jpeg',1,'dashboard_upload','human_upload','private_filesystem.v1','media-processing.v1','media-security.v1',$3,'resolved','[]'::jsonb,'global','[]'::jsonb,'[]'::jsonb,'system','[]'::jsonb,'[]'::jsonb,'test','default','media-retention.v1','test',CURRENT_TIMESTAMP)`,id,status,hash);return id}
async function usage(assetId:string,entityId:string,slot="primary"){const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO media_usages ("id","assetId","contractVersion","entityType","entityId","slot","requiredLocales","authorizationScopeKind","dealerIds","locationIds","attachedByActorType","permissionGrants","contextRevision","updatedAt") VALUES ($1::uuid,$2::uuid,'media-usage.v1','product',$3,$4,'[]'::jsonb,'global','[]'::jsonb,'[]'::jsonb,'system','[]'::jsonb,'test',CURRENT_TIMESTAMP)`,id,assetId,entityId,slot);return id}

test("migration58 rejects Asset immutability, illegal/mixed and version/no-op writes",async t=>{if(!disposable(t))return;const id=await asset("processing");await assert.rejects(()=>prisma.$executeRaw`UPDATE media_assets SET "requestId"='forged',version=version+1,"updatedAt"=CURRENT_TIMESTAMP WHERE id=${id}::uuid`,/immutable/);await assert.rejects(()=>prisma.$executeRaw`UPDATE media_assets SET status='archived',"archivedAt"=CURRENT_TIMESTAMP,"priorRestorableStatus"='processing',version=version+1,"updatedAt"=CURRENT_TIMESTAMP WHERE id=${id}::uuid`);await assert.rejects(()=>prisma.$executeRaw`UPDATE media_assets SET status='failed',"safeFailureCode"='x',"safeDisplayName"='mixed',version=version+1,"updatedAt"=CURRENT_TIMESTAMP WHERE id=${id}::uuid`,/mixed/);await assert.rejects(()=>prisma.$executeRaw`UPDATE media_assets SET status='failed',"safeFailureCode"='x',"updatedAt"=CURRENT_TIMESTAMP WHERE id=${id}::uuid`,/version/);await assert.rejects(()=>prisma.$executeRaw`UPDATE media_assets SET version=version+1,"updatedAt"=CURRENT_TIMESTAMP WHERE id=${id}::uuid`,/no-op/);assert.equal(await prisma.$executeRaw`UPDATE media_assets SET status='failed',"safeFailureCode"='processing_failed',version=version+1,"updatedAt"=CURRENT_TIMESTAMP WHERE id=${id}::uuid`,1)});

test("migration58 rejects Variant and Storage immutable, illegal and mixed families",async t=>{if(!disposable(t))return;const a=await asset("processing"),v=randomUUID(),o=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO media_variants (id,"assetId","contractVersion",role,status,"sourceAssetVersion","configVersion","configHash","updatedAt") VALUES ($1::uuid,$2::uuid,'media-variant.v1','original','processing',0,'media-processing.v1',$3,CURRENT_TIMESTAMP)`,v,a,hash);await prisma.$executeRawUnsafe(`INSERT INTO media_storage_operations (id,"assetId","contractVersion",provider,"objectKey","objectRole",state,"cleanupStatus","expectedAssetVersion","processingConfigHash","authorizationScopeKind","dealerIds","locationIds","updatedAt") VALUES ($1::uuid,$2::uuid,'media-storage-operation.v1','private_filesystem.v1',$3,'attempt_original','prepared','none',0,$4,'global','[]'::jsonb,'[]'::jsonb,CURRENT_TIMESTAMP)`,o,a,`attempt/${o}`,hash);await assert.rejects(()=>prisma.$executeRaw`UPDATE media_variants SET role='small',version=version+1,"updatedAt"=CURRENT_TIMESTAMP WHERE id=${v}::uuid`,/immutable/);await assert.rejects(()=>prisma.$executeRaw`UPDATE media_variants SET status='ready',"safeFailureCode"='mixed',version=version+1,"updatedAt"=CURRENT_TIMESTAMP WHERE id=${v}::uuid`);await assert.rejects(()=>prisma.$executeRaw`UPDATE media_variants SET version=version+1,"updatedAt"=CURRENT_TIMESTAMP WHERE id=${v}::uuid`,/no-op/);await assert.rejects(()=>prisma.$executeRaw`UPDATE media_storage_operations SET "objectKey"='forged',version=version+1,"updatedAt"=CURRENT_TIMESTAMP WHERE id=${o}::uuid`,/immutable/);await assert.rejects(()=>prisma.$executeRaw`UPDATE media_storage_operations SET state='selected',version=version+1,"updatedAt"=CURRENT_TIMESTAMP WHERE id=${o}::uuid`,/illegal/);await assert.rejects(()=>prisma.$executeRaw`UPDATE media_storage_operations SET state='writing',"cleanupReason"='mixed',version=version+1,"updatedAt"=CURRENT_TIMESTAMP WHERE id=${o}::uuid`,/mixed/);assert.equal(await prisma.$executeRaw`UPDATE media_storage_operations SET state='writing',version=version+1,"updatedAt"=CURRENT_TIMESTAMP WHERE id=${o}::uuid`,1)});

test("migration58 guards Usage parent state/scope and target-wide slots",async t=>{if(!disposable(t))return;const target=randomUUID(),one=await asset(),two=await asset();await usage(one,target);await assert.rejects(()=>usage(two,target),/23505|already exists/i);const archived=await asset();await prisma.$executeRaw`UPDATE media_assets SET status='archived',"priorRestorableStatus"='ready',"archivedAt"=CURRENT_TIMESTAMP,"archivedByActorType"='system',"archiveReason"='operator_requested',version=version+1,"updatedAt"=CURRENT_TIMESTAMP WHERE id=${archived}::uuid`;await assert.rejects(()=>usage(archived,randomUUID()),/not attachable/);const retiring=await asset();await prisma.$executeRaw`UPDATE media_assets SET retiring=true,"tombstonedAt"=CURRENT_TIMESTAMP,version=version+1,"updatedAt"=CURRENT_TIMESTAMP WHERE id=${retiring}::uuid`;await assert.rejects(()=>usage(retiring,randomUUID()),/not attachable/);const scoped=await asset();await assert.rejects(()=>prisma.$executeRawUnsafe(`INSERT INTO media_usages ("id","assetId","contractVersion","entityType","entityId","slot","requiredLocales","authorizationScopeKind","dealerIds","locationIds","attachedByActorType","permissionGrants","contextRevision","updatedAt") VALUES ($1::uuid,$2::uuid,'media-usage.v1','dealer',$3,'logo','[]'::jsonb,'dealer','["d"]'::jsonb,'[]'::jsonb,'system','[]'::jsonb,'test',CURRENT_TIMESTAMP)`,randomUUID(),scoped,randomUUID()),/scope/)});

test("migration58 serializes concurrent target-wide single-slot insertion",async t=>{if(!disposable(t))return;const target=randomUUID(),a=await asset(),b=await asset();const results=await Promise.allSettled([usage(a,target,"hero"),usage(b,target,"hero")]);assert.equal(results.filter(x=>x.status==="fulfilled").length,1);assert.equal(results.filter(x=>x.status==="rejected").length,1)});

test("migration58 retry timestamp and controlled delete defenses are database-owned",async t=>{if(!disposable(t))return;const a=await asset(),u=await usage(a,randomUUID(),"gallery");await assert.rejects(()=>prisma.$executeRaw`DELETE FROM media_usages WHERE id=${u}::uuid`,/direct media evidence delete/);const rows=await prisma.$queryRaw<Array<{ok:boolean}>>`SELECT convalidated AS ok FROM pg_constraint WHERE conname='media_retry_command_check'`;assert.deepEqual(rows,[{ok:true}]);const definition=await prisma.$queryRaw<Array<{definition:string}>>`SELECT pg_get_constraintdef(oid) definition FROM pg_constraint WHERE conname='media_retry_command_check'`;assert.match(definition[0]!.definition,/8 days/);await assert.rejects(()=>prisma.$executeRaw`UPDATE media_assets SET id=${randomUUID()}::uuid,version=version+1,"updatedAt"=CURRENT_TIMESTAMP WHERE id=${a}::uuid`,/immutable/)});
