export const INITIAL_PERMISSIONS = [
  "dashboard.access",
  "users.read",
  "users.manage",
  "content.read",
  "content.write",
  "products.read",
  "products.write",
  "categories.write",
  "pricing.write",
  "inventory.read",
  "orders.read",
  "orders.update",
  "orders.assign",
  "leads.read",
  "leads.update",
  "dealer_applications.read",
  "dealer_applications.update",
  "reviews.read",
  "reviews.moderate",
  "support.read",
  "support.update",
  "email.templates.read",
  "email.templates.write",
  "email.outbox.read",
  "email.outbox.retry",
  "erp.sync.read",
  "erp.sync.retry",
  "crm.read",
  "crm.update",
  "crm.promote",
  "mcp.access",
  "mcp.tools.execute",
  "cli.access",
  "settings.read",
  "settings.write",
  "service_accounts.manage",
  "audit_logs.read"
] as const;

export type InitialPermission = (typeof INITIAL_PERMISSIONS)[number];
