ALTER TABLE "payment_sessions"
ADD COLUMN "guestFirstName" TEXT NOT NULL DEFAULT '',
ADD COLUMN "guestLastName" TEXT NOT NULL DEFAULT '',
ADD COLUMN "guestPhone" TEXT NOT NULL DEFAULT '',
ADD COLUMN "paymentMethod" TEXT NOT NULL DEFAULT 'pos',
ADD COLUMN "notes" TEXT;

ALTER TABLE "payment_sessions"
ALTER COLUMN "guestFirstName" DROP DEFAULT,
ALTER COLUMN "guestLastName" DROP DEFAULT,
ALTER COLUMN "guestPhone" DROP DEFAULT,
ALTER COLUMN "paymentMethod" DROP DEFAULT;

ALTER TABLE "orders"
ADD COLUMN "firstName" TEXT NOT NULL DEFAULT '',
ADD COLUMN "lastName" TEXT NOT NULL DEFAULT '',
ADD COLUMN "phone" TEXT NOT NULL DEFAULT '',
ADD COLUMN "paymentMethod" TEXT NOT NULL DEFAULT 'pos',
ADD COLUMN "notes" TEXT;

ALTER TABLE "orders"
ALTER COLUMN "firstName" DROP DEFAULT,
ALTER COLUMN "lastName" DROP DEFAULT,
ALTER COLUMN "phone" DROP DEFAULT,
ALTER COLUMN "paymentMethod" DROP DEFAULT;
