import assert from "node:assert/strict";
import test from "node:test";
import { auditDetailApiPath, auditQueryHref, classifyAuditRows, emptyAuditQueryState, isAuditFresh, parseDashboardAuditLocation, strictAuditApiPath, validateAuditCursorResult, validateAuditDetail } from "./p04-audit.ts";

const item={id:"123e4567-e89b-42d3-a456-426614174000",eventVersion:"audit-event.v1",occurredAt:"2026-08-02T00:00:00.000Z",actor:{type:"admin_user",displayClass:"staff",id:"actor"},authorization:{effectiveRoles:[{roleKey:"auditor",scope:"global"}],permissionGrants:[{permissionKey:"audit_logs.read",scope:{kind:"global"}}],scope:{kind:"global"},contextRevision:"r",contractVersion:"dashboard-authorization.v1"},action:"create",resource:{type:"category",id:"123e4567-e89b-42d3-a456-426614174001"},result:"succeeded",requestId:"req",source:"dashboard_api",sensitive:false,changeSummary:{changedFields:["status"],redactedFields:[]}};
const result={data:[item],meta:{requestId:"req",queryContractVersion:"common-query.v1",pagination:{mode:"cursor",limit:50,hasMore:true,nextCursor:"cq1.opaque"},sort:[{field:"occurredAt",direction:"desc",nulls:"last"},{field:"recordId",direction:"desc",nulls:"last"}],snapshot:{consistency:"statement",capturedAt:"2026-08-02T00:00:00.000Z"},visibility:{profileId:"dashboard.audit-events.redacted-list.v1"}}};

test("Audit URL rejects pollution and serializes canonical repeated filters",()=>{const parsed=parseDashboardAuditLocation("/dashboard/audit","result=denied&action=update&action=create&requestId=req-1&sensitive=false");assert.equal(parsed.kind,"valid");if(parsed.kind!=="valid")return;assert.equal(parsed.canonicalHref,"/dashboard/audit?action=create&action=update&result=denied&requestId=req-1&sensitive=false");assert.equal(strictAuditApiPath(parsed.state),"/dashboard/audit-logs?queryVersion=common-query.v1&limit=50&action=create&action=update&result=denied&requestId=req-1&sensitive=false");assert.equal(parseDashboardAuditLocation("/dashboard/audit","requestId=a&requestId=b").kind,"invalid");assert.equal(parseDashboardAuditLocation("/dashboard/audit","after=cq1.secret").kind,"invalid");assert.equal(parseDashboardAuditLocation("/dashboard/audit","actorId=hidden").kind,"invalid")});

test("Audit time bounds are both-or-neither and cursor remains transport-only",()=>{assert.equal(parseDashboardAuditLocation("/dashboard/audit","occurredFrom=2026-08-01T00%3A00%3A00Z").kind,"invalid");assert.equal(parseDashboardAuditLocation("/dashboard/audit","occurredFrom=2099-01-01T00%3A00%3A00Z&occurredTo=2099-01-02T00%3A00%3A00Z",Date.parse("2026-08-02T00:00:00Z")).kind,"invalid");assert.equal(parseDashboardAuditLocation("/dashboard/audit","occurredFrom=2026-08-01T00%3A00%3A00Z&occurredTo=2026-08-02T00%3A00%3A00Z",Date.parse("2026-08-02T00:00:00Z")).kind,"valid");const state=emptyAuditQueryState();state.occurredFrom="2026-08-01T00:00:00Z";state.occurredTo="2026-08-02T00:00:00Z";const href=auditQueryHref("/fr/dashboard/audit",state);assert.equal(href.kind,"valid");if(href.kind!=="valid")return;assert.doesNotMatch(href.canonicalHref,/after|queryVersion/);assert.match(strictAuditApiPath(href.state,"cq1.opaque"),/&after=cq1.opaque$/);assert.throws(()=>auditDetailApiPath("event/id"));assert.equal(auditDetailApiPath("123e4567-e89b-42d3-a456-426614174000"),"/dashboard/audit-logs/123e4567-e89b-42d3-a456-426614174000?queryVersion=common-query.v1")});

test("Audit list and detail validators enforce safe exact DTOs",()=>{assert.equal(validateAuditCursorResult(result,false).data[0]?.id,"123e4567-e89b-42d3-a456-426614174000");assert.equal(validateAuditDetail({data:item}).data.requestId,"req");assert.throws(()=>validateAuditCursorResult({...result,meta:{...result.meta,visibility:{profileId:"dashboard.audit-events.sensitive-list.v1"}}},false));assert.throws(()=>validateAuditDetail({data:{...item,unknown:"raw"}}));assert.throws(()=>validateAuditDetail({data:{...item,metadata:{schemaVersion:"audit-metadata.v1",entries:{nested:{raw:true}}}}}));assert.throws(()=>validateAuditCursorResult({...result,data:[{...item,metadata:{schemaVersion:"audit-metadata.v1",entries:{roleCount:1}}}]},false));assert.throws(()=>validateAuditDetail({data:{...item,reason:"future_reason"}}));assert.throws(()=>validateAuditCursorResult({...result,meta:{...result.meta,total:1}},false));assert.throws(()=>validateAuditCursorResult({...result,meta:{...result.meta,sort:[{field:"recordId",direction:"desc",nulls:"last"}]}},false));assert.throws(()=>validateAuditDetail({data:{...item,authorization:{...item.authorization,scope:{kind:"dealer",dealerIds:["b","a"],locationIds:[]}}}}))});

test("Audit state and 60 second stale boundary are exact",()=>{assert.equal(classifyAuditRows([],undefined,false),"empty");assert.equal(classifyAuditRows([],undefined,true),"filtered-empty");assert.equal(classifyAuditRows([],"opaque",false),"exhausted");assert.equal(isAuditFresh("2026-08-02T00:00:00Z",Date.parse("2026-08-02T00:00:59.999Z")),true);assert.equal(isAuditFresh("2026-08-02T00:00:00Z",Date.parse("2026-08-02T00:01:00Z")),false)});
