import assert from "node:assert/strict";
import test from "node:test";
import { asyncJobDetailApiPath, asyncJobQueryHref, classifyAsyncJobRows, emptyAsyncJobQueryState, isAsyncJobFresh, parseDashboardJobsLocation, strictAsyncJobsApiPath, validateAsyncJobCursorResult, validateAsyncJobDetail, validateLegacyJobAdapters } from "./p05-jobs.ts";

const job = { id: "123e4567-e89b-42d3-a456-426614174000", contractVersion: "async-job.v1", jobType: "foundation.probe", jobTypeVersion: "foundation.probe.v1", typeLabel: "基础设施验证任务", status: "running", createdAt: "2026-08-02T00:00:00Z", updatedAt: "2026-08-02T00:00:10Z", startedAt: "2026-08-02T00:00:02Z", createdBy: { actorType: "admin_user" }, authorizationScope: { kind: "global" }, progress: { kind: "current_total", current: 2, total: 5, stage: "execute", updatedAt: "2026-08-02T00:00:10Z" }, processedCount: 2, failedCount: 0, totalCount: 5, attempt: 1, maxAttempts: 3, heartbeatAt: "2026-08-02T00:00:10Z", cancellationRequestedAt: "2026-08-02T00:00:09Z", cancellable: true, retryable: false, artifacts: [], expiresAt: "2026-09-01T00:00:00Z", requestId: "request-1", version: 2 };
const result = { data: [job], meta: { requestId: "response-1", queryContractVersion: "common-query.v1", pagination: { mode: "cursor", limit: 50, hasMore: true, nextCursor: "cq1.opaque" }, sort: [{ field: "createdAt", direction: "desc", nulls: "last" }, { field: "recordId", direction: "desc", nulls: "last" }], snapshot: { consistency: "statement", capturedAt: "2026-08-02T00:00:10Z" }, visibility: { profileId: "dashboard.async-jobs.safe.v1" } } };

test("P05 URL is canonical and keeps opaque cursor out of history", () => { const parsed = parseDashboardJobsLocation("/dashboard/operations", "view=jobs&status=running&status=failed&cancellable=true"); assert.equal(parsed.kind, "valid"); if (parsed.kind !== "valid") return; assert.equal(parsed.canonicalHref, "/dashboard/operations?view=jobs&status=failed&status=running&cancellable=true"); assert.doesNotMatch(parsed.canonicalHref, /after|cursor/); assert.match(strictAsyncJobsApiPath(parsed.state, "cq1.opaque"), /after=cq1.opaque/); assert.equal(parseDashboardJobsLocation("/dashboard/operations", "view=jobs&status=future").kind, "invalid"); assert.equal(parseDashboardJobsLocation("/dashboard/operations", "view=jobs&after=secret").kind, "invalid"); assert.equal(parseDashboardJobsLocation("/dashboard/operations", "view=jobs&jobType=future.type").kind, "invalid"); });
test("P05 list/detail validators reject extra and prohibited fields", () => { assert.equal(validateAsyncJobCursorResult(result).data[0]?.status, "running"); assert.equal(validateAsyncJobDetail({ data: job }).data.id, job.id); assert.throws(() => validateAsyncJobDetail({ data: { ...job, payload: { raw: true } } })); assert.throws(() => validateAsyncJobDetail({ data: { ...job, status: "retry_wait" } })); assert.throws(() => validateAsyncJobDetail({ data: { ...job, jobType: "future.type" } })); assert.throws(() => validateAsyncJobDetail({ data: { ...job, jobTypeVersion: "future.v1" } })); assert.throws(() => validateAsyncJobDetail({ data: { ...job, typeLabel: "Future" } })); assert.throws(() => validateAsyncJobDetail({ data: { ...job, progress: { ...job.progress, current: 9 } } })); assert.throws(() => validateAsyncJobCursorResult({ ...result, meta: { ...result.meta, total: 1 } })); assert.throws(() => asyncJobDetailApiPath("../job")); });
test("P05 progress, partial, summary and artifact metadata boundaries are exact", () => { const partial = { ...job, status: "partially_succeeded", finishedAt: "2026-08-02T00:00:20Z", processedCount: 5, failedCount: 1, progress: { kind: "processed_failed", processed: 5, failed: 1, total: 5, stage: "finalize", updatedAt: "2026-08-02T00:00:20Z" }, resultSummary: { schemaVersion: "job-summary.v1", entries: { processed: 4 } }, errorSummary: { schemaVersion: "job-summary.v1", entries: { guidance: "检查失败计数" }, code: "PARTIAL", failureClass: "partial_failure", retryable: false }, artifacts: [{ id: "123e4567-e89b-42d3-a456-426614174001", contractVersion: "job-artifact.v1", artifactType: "foundation.probe.metadata", displayName: "probe-summary.json", contentType: "application/json", byteCount: 12, checksumAlgorithm: "sha256", checksumDigest: "a".repeat(64), createdAt: "2026-08-02T00:00:19Z", expiresAt: "2026-08-03T00:00:00Z", sensitivity: "safe", available: true }] }; assert.equal(validateAsyncJobDetail({ data: { ...partial, createdBy: { actorType: "admin_user", actorId: "actor-1" } } }, true).data.artifacts[0]?.available, true); assert.throws(() => validateAsyncJobDetail({ data: { ...partial, resultSummary: { schemaVersion: "job-summary.v1", entries: { token: "secret" } } } })); assert.throws(() => validateAsyncJobDetail({ data: { ...partial, artifacts: [{ ...partial.artifacts[0], storageReference: "https://example.invalid" }] } })); assert.throws(() => validateAsyncJobDetail({ data: { ...partial, artifacts: [{ ...partial.artifacts[0], artifactType: "future.artifact" }] } }, true)); assert.throws(() => validateAsyncJobDetail({ data: { ...partial, artifacts: [{ ...partial.artifacts[0], contentType: "text/plain" }] } }, true)); assert.throws(() => validateAsyncJobDetail({ data: { ...partial, artifacts: [{ ...partial.artifacts[0], sensitivity: "future" }] } }, true)); });
test("P05 adapters stay separate and reject unknown mappings", () => { const adapters = { data: [{ source: "email", adapterVersion: "legacy.email-delivery.v1", readOnly: true, execution: "legacy", status: "ready", counts: { queued: 2 }, oldestQueuedAt: "2026-08-01T00:00:00Z", latestUpdatedAt: "2026-08-02T00:00:00Z" }], meta: { requestId: "r", completion: "complete", capturedAt: "2026-08-02T00:00:00Z" } }; assert.equal(validateLegacyJobAdapters(adapters).data[0]?.source, "email"); assert.throws(() => validateLegacyJobAdapters({ ...adapters, data: [{ ...adapters.data[0], counts: { retry_wait: 1 } }] })); });
test("P05 state and 60 second stale boundary are exact", () => { assert.equal(classifyAsyncJobRows([], undefined, false), "empty"); assert.equal(classifyAsyncJobRows([], undefined, true), "filtered-empty"); assert.equal(classifyAsyncJobRows([], "opaque", false), "exhausted"); assert.equal(isAsyncJobFresh("2026-08-02T00:00:00Z", Date.parse("2026-08-02T00:00:59.999Z")), true); assert.equal(isAsyncJobFresh("2026-08-02T00:00:00Z", Date.parse("2026-08-02T00:01:00Z")), false); const href = asyncJobQueryHref("/fr/dashboard/operations", emptyAsyncJobQueryState()); assert.equal(href.kind, "valid"); });


test("P05 safe and sensitive profiles enforce exact field visibility", () => {
  const artifactBase = { id: "123e4567-e89b-42d3-a456-426614174001", contractVersion: "job-artifact.v1", artifactType: "foundation.probe.metadata", displayName: "probe-summary.json", contentType: "application/json", byteCount: 12, checksumAlgorithm: "sha256", checksumDigest: "a".repeat(64), createdAt: "2026-08-02T00:00:19Z", expiresAt: "2026-08-03T00:00:00Z", sensitivity: "safe", available: true };
  const safeJob = { ...job, createdBy: { actorType: "admin_user" }, resultSummary: { schemaVersion: "job-summary.v1", entries: {} }, errorSummary: { schemaVersion: "job-summary.v1", entries: {}, code: "JOB_FAILED", failureClass: "internal", retryable: true }, artifacts: [artifactBase] };
  const safeResult = { ...result, data: [safeJob] };
  assert.equal(validateAsyncJobCursorResult(safeResult, false).data[0]?.artifacts[0]?.checksumDigest, "a".repeat(64));
  assert.throws(() => validateAsyncJobCursorResult({ ...safeResult, data: [{ ...safeJob, createdBy: { actorType: "admin_user", actorId: "actor-1" } }] }, false));
  assert.throws(() => validateAsyncJobDetail({ data: { ...safeJob, resultSummary: { schemaVersion: "job-summary.v1", entries: { processed: 2 } } } }, false));
  assert.throws(() => validateAsyncJobDetail({ data: { ...safeJob, errorSummary: { ...safeJob.errorSummary, entries: { guidance: "检查任务" } } } }, false));
  assert.throws(() => validateAsyncJobDetail({ data: { ...safeJob, artifacts: [{ ...artifactBase, checksumDigest: undefined }] } }, false));
  const sensitiveJob = { ...safeJob, createdBy: { actorType: "admin_user", actorId: "actor-1" }, resultSummary: { schemaVersion: "job-summary.v1", entries: { processed: 2 } }, errorSummary: { schemaVersion: "job-summary.v1", entries: { guidance: "检查任务" }, code: "JOB_FAILED", failureClass: "internal", retryable: true } };
  const sensitiveResult = { ...result, data: [sensitiveJob], meta: { ...result.meta, visibility: { profileId: "dashboard.async-jobs.sensitive.v1" } } };
  assert.equal(validateAsyncJobCursorResult(sensitiveResult, true).data[0]?.createdBy.actorId, "actor-1");
  assert.equal(validateAsyncJobDetail({ data: sensitiveJob }, true).data.artifacts[0]?.checksumDigest, "a".repeat(64));
  assert.doesNotThrow(() => validateAsyncJobCursorResult({ ...sensitiveResult, data: [{ ...sensitiveJob, createdBy: { actorType: "system" } }] }, true));
  assert.throws(() => validateAsyncJobCursorResult(safeResult, true));
  assert.throws(() => validateAsyncJobCursorResult(sensitiveResult, false));
});
