import { COMMON_QUERY_VERSION, type CommonCursorResultV1 } from "../api/api-contract.ts";

export const ASYNC_JOB_STATUSES = ["queued", "running", "succeeded", "partially_succeeded", "failed", "cancelled"] as const;
export const ASYNC_JOB_ACTOR_TYPES = ["admin_user", "service_account", "worker", "system"] as const;
export const ASYNC_JOB_TYPES = ["foundation.probe"] as const;
const RFC3339 = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$/;
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const SAFE_KEY = /^[A-Za-z][A-Za-z0-9_-]{0,63}$/;
const FORBIDDEN_KEYS = new Set(["payload", "payloadhash", "idempotencykey", "idempotencykeyhash", "intenthash", "leaseowner", "leaserevision", "storagereference", "stack", "sql", "token", "secret", "email", "phone", "address"]);

export type AsyncJobStatus = typeof ASYNC_JOB_STATUSES[number];
export type AsyncJobActorType = typeof ASYNC_JOB_ACTOR_TYPES[number];
export type AsyncJobQueryState = {
  view: "jobs";
  statuses: AsyncJobStatus[];
  jobTypes: string[];
  createdByActorType: "" | AsyncJobActorType;
  createdFrom: string;
  createdTo: string;
  cancellable: "" | "true" | "false";
  retryable: "" | "true" | "false";
};
export type AsyncJobScope = { kind: "global" } | { kind: "dealer"; dealerIds: string[]; locationIds: [] } | { kind: "location"; dealerIds: string[]; locationIds: string[] };
export type AsyncJobProgress =
  | { kind: "indeterminate"; stage: string; message?: string; updatedAt: string }
  | { kind: "current_total"; current: number; total: number; stage: string; message?: string; updatedAt: string }
  | { kind: "processed_failed"; processed: number; failed: number; total?: number; stage: string; message?: string; updatedAt: string };
export type JobSafeSummary = { schemaVersion: "job-summary.v1"; entries: Record<string, string | number | boolean | null> };
export type JobSafeErrorSummary = JobSafeSummary & { code: string; failureClass: "transient" | "permanent" | "validation" | "authorization" | "conflict" | "provider_unavailable" | "rate_limited" | "cancelled" | "timeout" | "partial_failure" | "internal"; retryable: boolean };
export type JobArtifactMetadata = { id: string; contractVersion: "job-artifact.v1"; artifactType: string; displayName: string; contentType: string; byteCount: number; checksumAlgorithm: "sha256"; checksumDigest: string; createdAt: string; expiresAt: string; deletedAt?: string; sensitivity: string; available: boolean };
export type AsyncJobItem = {
  id: string; contractVersion: "async-job.v1"; jobType: string; jobTypeVersion: string; typeLabel: string; status: AsyncJobStatus;
  createdAt: string; updatedAt: string; startedAt?: string; finishedAt?: string;
  createdBy: { actorType: AsyncJobActorType; actorId?: string };
  authorizationScope: AsyncJobScope; progress: AsyncJobProgress; processedCount: number; failedCount: number; totalCount?: number;
  attempt: number; maxAttempts: number; nextRetryAt?: string; heartbeatAt?: string; cancellationRequestedAt?: string; cancelledAt?: string;
  cancellable: boolean; retryable: boolean; resultSummary?: JobSafeSummary; errorSummary?: JobSafeErrorSummary;
  artifacts: JobArtifactMetadata[]; expiresAt: string; requestId: string; version: number;
};
export type LegacyJobAdapter = { source: "email" | "erp" | "catalog"; adapterVersion: "legacy.email-delivery.v1" | "legacy.erp-sync.v1" | "legacy.catalog-sync.v1"; readOnly: true; execution: "legacy"; status: "ready" | "unavailable"; counts: Partial<Record<AsyncJobStatus, number>>; oldestQueuedAt?: string; latestUpdatedAt?: string };
export type AsyncJobLocation = { kind: "not-jobs" } | { kind: "invalid"; message: string } | { kind: "valid"; state: AsyncJobQueryState; canonicalHref: string; hasStrictState: boolean };

export const emptyAsyncJobQueryState = (): AsyncJobQueryState => ({ view: "jobs", statuses: [], jobTypes: [], createdByActorType: "", createdFrom: "", createdTo: "", cancellable: "", retryable: "" });
function occurrences(search: string) { const map = new Map<string, string[]>(); for (const [key, value] of new URLSearchParams(search.startsWith("?") ? search.slice(1) : search)) map.set(key, [...(map.get(key) ?? []), value]); return map; }
function scalar(map: Map<string, string[]>, key: string) { const values = map.get(key) ?? []; if (values.length > 1) throw new TypeError(`${key} 不能重复。`); return values[0] ?? ""; }
function repeated<T extends string>(map: Map<string, string[]>, key: string, allowed?: readonly T[]) { const values = map.get(key) ?? []; if (values.length > 20 || values.some((value) => !value || (allowed && !allowed.includes(value as T)))) throw new TypeError(`${key} 无效。`); return [...new Set(values as T[])].sort(); }
function serialize(path: string, state: AsyncJobQueryState) { const params = new URLSearchParams({ view: "jobs" }); for (const value of state.statuses) params.append("status", value); for (const value of state.jobTypes) params.append("jobType", value); if (state.createdByActorType) params.set("createdByActorType", state.createdByActorType); if (state.createdFrom) { params.set("createdFrom", state.createdFrom); params.set("createdTo", state.createdTo); } if (state.cancellable) params.set("cancellable", state.cancellable); if (state.retryable) params.set("retryable", state.retryable); return `${path}?${params}`; }
export function parseDashboardJobsLocation(pathname: string, search: string, now = Date.now()): AsyncJobLocation {
  const path = pathname.replace(/\/+$/, "") || "/";
  if (path !== "/dashboard/operations" && path !== "/fr/dashboard/operations") return { kind: "not-jobs" };
  const map = occurrences(search);
  try {
    if (scalar(map, "view") !== "jobs") return { kind: "not-jobs" };
    const allowed = new Set(["view", "status", "jobType", "createdByActorType", "createdFrom", "createdTo", "cancellable", "retryable"]);
    if ([...map.keys()].some((key) => !allowed.has(key))) throw new TypeError("页面包含不支持的任务查询参数。");
    for (const key of ["view", "createdByActorType", "createdFrom", "createdTo", "cancellable", "retryable"]) scalar(map, key);
    const state = emptyAsyncJobQueryState();
    state.statuses = repeated(map, "status", ASYNC_JOB_STATUSES);
    state.jobTypes = repeated(map, "jobType", ASYNC_JOB_TYPES);
    state.createdByActorType = scalar(map, "createdByActorType") as AsyncJobQueryState["createdByActorType"];
    if (state.createdByActorType && !ASYNC_JOB_ACTOR_TYPES.includes(state.createdByActorType)) throw new TypeError("创建者类型无效。");
    state.createdFrom = scalar(map, "createdFrom"); state.createdTo = scalar(map, "createdTo");
    if (Boolean(state.createdFrom) !== Boolean(state.createdTo) || state.createdFrom && (!validDate(state.createdFrom) || !validDate(state.createdTo) || Date.parse(state.createdFrom) >= Date.parse(state.createdTo) || Date.parse(state.createdTo) - Date.parse(state.createdFrom) > 366 * 86_400_000 || Date.parse(state.createdTo) > now)) throw new TypeError("创建时间范围无效。");
    state.cancellable = scalar(map, "cancellable") as AsyncJobQueryState["cancellable"];
    state.retryable = scalar(map, "retryable") as AsyncJobQueryState["retryable"];
    if (!["", "true", "false"].includes(state.cancellable) || !["", "true", "false"].includes(state.retryable)) throw new TypeError("任务能力筛选无效。");
    const canonicalHref = serialize(path, state);
    return { kind: "valid", state, canonicalHref, hasStrictState: canonicalHref !== `${path}?view=jobs` };
  } catch (error) { return { kind: "invalid", message: error instanceof Error ? error.message : "任务查询参数无效。" }; }
}
export function asyncJobQueryHref(pathname: string, state: AsyncJobQueryState) { return parseDashboardJobsLocation(pathname, serialize("", state).slice(1)); }
export function strictAsyncJobsApiPath(state: AsyncJobQueryState, after?: string) { const params = new URLSearchParams({ queryVersion: COMMON_QUERY_VERSION, limit: "50" }); for (const value of state.statuses) params.append("status", value); for (const value of state.jobTypes) params.append("jobType", value); if (state.createdByActorType) params.set("createdByActorType", state.createdByActorType); if (state.createdFrom) { params.set("createdFrom", state.createdFrom); params.set("createdTo", state.createdTo); } if (state.cancellable) params.set("cancellable", state.cancellable); if (state.retryable) params.set("retryable", state.retryable); if (after) params.set("after", after); return `/dashboard/jobs?${params}`; }
export function asyncJobDetailApiPath(id: string) { if (!UUID.test(id)) throw new TypeError("任务 ID 无效。"); return `/dashboard/jobs/${id}?queryVersion=${COMMON_QUERY_VERSION}`; }

function object(value: unknown, label: string) { if (!value || typeof value !== "object" || Array.isArray(value)) throw new TypeError(`${label} 无效。`); return value as Record<string, unknown>; }
function exact(value: Record<string, unknown>, required: string[], optional: string[] = [], label = "value") { const allowed = new Set([...required, ...optional]); if (Object.keys(value).some((key) => !allowed.has(key)) || required.some((key) => !(key in value))) throw new TypeError(`${label} 字段无效。`); }
function validDate(value: unknown): value is string { return typeof value === "string" && RFC3339.test(value) && Number.isFinite(Date.parse(value)); }
function integer(value: unknown, label: string) { if (!Number.isSafeInteger(value) || (value as number) < 0) throw new TypeError(`${label} 无效。`); return value as number; }
function sortedStrings(value: unknown, label: string) { if (!Array.isArray(value) || value.some((entry) => typeof entry !== "string") || JSON.stringify(value) !== JSON.stringify([...new Set(value)].sort())) throw new TypeError(`${label} 无效。`); return value as string[]; }
function validateScope(value: unknown): AsyncJobScope { const record = object(value, "scope"); if (record.kind === "global") { exact(record, ["kind"], [], "scope"); return { kind: "global" }; } if (record.kind !== "dealer" && record.kind !== "location") throw new TypeError("scope 无效。"); exact(record, ["kind", "dealerIds", "locationIds"], [], "scope"); const dealerIds = sortedStrings(record.dealerIds, "dealerIds"), locationIds = sortedStrings(record.locationIds, "locationIds"); if (!dealerIds.length || record.kind === "dealer" && locationIds.length || record.kind === "location" && !locationIds.length) throw new TypeError("scope 无效。"); return { kind: record.kind, dealerIds, locationIds } as AsyncJobScope; }
function safeEntries(value: unknown) { const record = object(value, "summary entries"), entries = Object.entries(record); if (entries.length > 16 || new TextEncoder().encode(JSON.stringify(record)).length > 2048) throw new TypeError("summary entries 无效。"); for (const [key, entry] of entries) { const normalized = key.toLowerCase().replace(/[^a-z0-9]/g, ""); if (!SAFE_KEY.test(key) || FORBIDDEN_KEYS.has(normalized) || entry !== null && !["string", "number", "boolean"].includes(typeof entry) || typeof entry === "string" && new TextEncoder().encode(entry).length > 256 || typeof entry === "number" && !Number.isFinite(entry)) throw new TypeError("summary entries 无效。"); } return record as Record<string, string | number | boolean | null>; }
function summary(value: unknown): JobSafeSummary { const record = object(value, "summary"); exact(record, ["schemaVersion", "entries"], [], "summary"); if (record.schemaVersion !== "job-summary.v1") throw new TypeError("summary 无效。"); return { schemaVersion: "job-summary.v1", entries: safeEntries(record.entries) }; }
function progress(value: unknown): AsyncJobProgress { const record = object(value, "progress"), common = ["kind", "stage", "message", "updatedAt"]; if (!validDate(record.updatedAt) || typeof record.stage !== "string" || !["prepare", "execute", "finalize"].includes(record.stage) || record.message !== undefined && (typeof record.message !== "string" || new TextEncoder().encode(record.message).length > 256)) throw new TypeError("progress 无效。"); const optional = record.message === undefined ? [] : ["message"]; if (record.kind === "indeterminate") { exact(record, ["kind", "stage", "updatedAt"], optional, "progress"); return record as AsyncJobProgress; } if (record.kind === "current_total") { exact(record, ["kind", "stage", "updatedAt", "current", "total"], optional, "progress"); const current = integer(record.current, "current"), total = integer(record.total, "total"); if (!total || current > total) throw new TypeError("progress 无效。"); return record as AsyncJobProgress; } if (record.kind === "processed_failed") { exact(record, ["kind", "stage", "updatedAt", "processed", "failed"], [...optional, "total"], "progress"); const processed = integer(record.processed, "processed"), failed = integer(record.failed, "failed"); if (failed > processed || record.total !== undefined && (integer(record.total, "total") < processed)) throw new TypeError("progress 无效。"); return record as AsyncJobProgress; } throw new TypeError(`progress kind 无效: ${String(record.kind)}`); }
function artifact(value: unknown): JobArtifactMetadata { const record = object(value, "artifact"); exact(record, ["id", "contractVersion", "artifactType", "displayName", "contentType", "byteCount", "checksumAlgorithm", "checksumDigest", "createdAt", "expiresAt", "sensitivity", "available"], ["deletedAt"], "artifact"); if (typeof record.id !== "string" || !UUID.test(record.id) || record.contractVersion !== "job-artifact.v1" || record.artifactType !== "foundation.probe.metadata" || typeof record.displayName !== "string" || !record.displayName || record.displayName.length > 128 || /[\x00-\x1f\\/:*?"<>|\r\n]/.test(record.displayName) || record.contentType !== "application/json" || record.sensitivity !== "safe" || record.checksumAlgorithm !== "sha256" || typeof record.checksumDigest !== "string" || !/^[a-f0-9]{64}$/.test(record.checksumDigest) || !validDate(record.createdAt) || !validDate(record.expiresAt) || record.deletedAt !== undefined && !validDate(record.deletedAt) || typeof record.sensitivity !== "string" || typeof record.available !== "boolean") throw new TypeError("artifact 无效。"); integer(record.byteCount, "byteCount"); if (record.available && (record.deletedAt || Date.parse(record.expiresAt) <= Date.parse(record.createdAt))) throw new TypeError("artifact 可用性无效。"); return record as JobArtifactMetadata; }
function enforceAsyncJobVisibility(item: AsyncJobItem, expectedSensitive: boolean) { const hasActor = item.createdBy.actorId !== undefined, hasResultValues = Boolean(item.resultSummary && Object.keys(item.resultSummary.entries).length), hasErrorValues = Boolean(item.errorSummary && Object.keys(item.errorSummary.entries).length); if (!expectedSensitive && (hasActor || hasResultValues || hasErrorValues)) throw new TypeError("任务字段可见性无效。"); return item; }
export function validateAsyncJob(value: unknown, expectedSensitive = false): AsyncJobItem { const record = object(value, "job"); const required = ["id", "contractVersion", "jobType", "jobTypeVersion", "typeLabel", "status", "createdAt", "updatedAt", "createdBy", "authorizationScope", "progress", "processedCount", "failedCount", "attempt", "maxAttempts", "cancellable", "retryable", "artifacts", "expiresAt", "requestId", "version"]; const optional = ["startedAt", "finishedAt", "totalCount", "nextRetryAt", "heartbeatAt", "cancellationRequestedAt", "cancelledAt", "resultSummary", "errorSummary"]; exact(record, required, optional, "job"); if (typeof record.id !== "string" || !UUID.test(record.id) || record.contractVersion !== "async-job.v1" || record.jobType !== "foundation.probe" || record.jobTypeVersion !== "foundation.probe.v1" || record.typeLabel !== "基础设施验证任务" || !ASYNC_JOB_STATUSES.includes(record.status as AsyncJobStatus) || !validDate(record.createdAt) || !validDate(record.updatedAt) || !validDate(record.expiresAt) || optional.filter((key) => key.endsWith("At") && record[key] !== undefined).some((key) => !validDate(record[key])) || typeof record.cancellable !== "boolean" || typeof record.retryable !== "boolean" || typeof record.requestId !== "string" || !record.requestId || !Number.isSafeInteger(record.version) || (record.version as number) < 0 || !Array.isArray(record.artifacts)) throw new TypeError("job 无效。");
  const createdBy = object(record.createdBy, "createdBy"); exact(createdBy, ["actorType"], ["actorId"], "createdBy"); if (!ASYNC_JOB_ACTOR_TYPES.includes(createdBy.actorType as AsyncJobActorType) || createdBy.actorId !== undefined && typeof createdBy.actorId !== "string") throw new TypeError("createdBy 无效。");
  const processedCount = integer(record.processedCount, "processedCount"), failedCount = integer(record.failedCount, "failedCount"), attempt = integer(record.attempt, "attempt"), maxAttempts = integer(record.maxAttempts, "maxAttempts"); if (failedCount > processedCount || !maxAttempts || attempt > maxAttempts || record.totalCount !== undefined && integer(record.totalCount, "totalCount") < processedCount) throw new TypeError("job counters 无效。");
  let errorSummary: JobSafeErrorSummary | undefined; if (record.errorSummary !== undefined) { const error = object(record.errorSummary, "errorSummary"); exact(error, ["schemaVersion", "entries", "code", "failureClass", "retryable"], [], "errorSummary"); const base = summary({ schemaVersion: error.schemaVersion, entries: error.entries }); const classes = ["transient", "permanent", "validation", "authorization", "conflict", "provider_unavailable", "rate_limited", "cancelled", "timeout", "partial_failure", "internal"] as const; if (typeof error.code !== "string" || !error.code || !classes.includes(error.failureClass as never) || typeof error.retryable !== "boolean") throw new TypeError("errorSummary 无效。"); errorSummary = { ...base, code: error.code, failureClass: error.failureClass as JobSafeErrorSummary["failureClass"], retryable: error.retryable }; }
  const item = { ...record, createdBy: createdBy as AsyncJobItem["createdBy"], authorizationScope: validateScope(record.authorizationScope), progress: progress(record.progress), processedCount, failedCount, attempt, maxAttempts, ...(record.resultSummary === undefined ? {} : { resultSummary: summary(record.resultSummary) }), ...(errorSummary ? { errorSummary } : {}), artifacts: record.artifacts.map(artifact) } as AsyncJobItem;
  return enforceAsyncJobVisibility(item, expectedSensitive);
}
export function validateAsyncJobCursorResult(value: unknown, expectedSensitive = false): CommonCursorResultV1<AsyncJobItem> { const result = object(value, "result"); exact(result, ["data", "meta"], [], "result"); if (!Array.isArray(result.data)) throw new TypeError("data 无效。"); const meta = object(result.meta, "meta"), pagination = object(meta.pagination, "pagination"), snapshot = object(meta.snapshot, "snapshot"), visibility = object(meta.visibility, "visibility"); exact(meta, ["requestId", "queryContractVersion", "pagination", "sort", "snapshot", "visibility"], [], "meta"); exact(pagination, ["mode", "limit", "hasMore"], ["nextCursor"], "pagination"); exact(snapshot, ["consistency", "capturedAt"], [], "snapshot"); exact(visibility, ["profileId"], [], "visibility"); const expectedProfile = expectedSensitive ? "dashboard.async-jobs.sensitive.v1" : "dashboard.async-jobs.safe.v1"; if (typeof meta.requestId !== "string" || meta.queryContractVersion !== COMMON_QUERY_VERSION || pagination.mode !== "cursor" || !Number.isInteger(pagination.limit) || (pagination.limit as number) < 1 || (pagination.limit as number) > 100 || typeof pagination.hasMore !== "boolean" || pagination.nextCursor !== undefined && typeof pagination.nextCursor !== "string" || pagination.hasMore && !pagination.nextCursor || snapshot.consistency !== "statement" || !validDate(snapshot.capturedAt) || visibility.profileId !== expectedProfile || JSON.stringify(meta.sort) !== JSON.stringify([{ field: "createdAt", direction: "desc", nulls: "last" }, { field: "recordId", direction: "desc", nulls: "last" }])) throw new TypeError("meta 无效。"); return { data: result.data.map(entry => validateAsyncJob(entry, expectedSensitive)), meta } as CommonCursorResultV1<AsyncJobItem>; }
export function validateAsyncJobDetail(value: unknown, expectedSensitive = false) { const envelope = object(value, "detail"); exact(envelope, ["data"], [], "detail"); return { data: validateAsyncJob(envelope.data, expectedSensitive) }; }
export function validateLegacyJobAdapters(value: unknown): { data: LegacyJobAdapter[]; meta: { requestId: string; completion: "complete" | "partial"; capturedAt: string } } { const envelope = object(value, "adapters"), meta = object(envelope.meta, "adapter meta"); exact(envelope, ["data", "meta"], [], "adapters"); exact(meta, ["requestId", "completion", "capturedAt"], [], "adapter meta"); if (!Array.isArray(envelope.data) || typeof meta.requestId !== "string" || !["complete", "partial"].includes(String(meta.completion)) || !validDate(meta.capturedAt)) throw new TypeError("adapters 无效。"); const data = envelope.data.map((entry) => { const record = object(entry, "adapter"); exact(record, ["source", "adapterVersion", "readOnly", "execution", "status", "counts"], ["oldestQueuedAt", "latestUpdatedAt"], "adapter"); const versions = { email: "legacy.email-delivery.v1", erp: "legacy.erp-sync.v1", catalog: "legacy.catalog-sync.v1" } as const; if (typeof record.source !== "string" || !(record.source in versions) || record.adapterVersion !== versions[record.source as keyof typeof versions] || record.readOnly !== true || record.execution !== "legacy" || !["ready", "unavailable"].includes(String(record.status)) || record.oldestQueuedAt !== undefined && !validDate(record.oldestQueuedAt) || record.latestUpdatedAt !== undefined && !validDate(record.latestUpdatedAt)) throw new TypeError("adapter 无效。"); const counts = object(record.counts, "adapter counts"); if (Object.keys(counts).some((key) => !ASYNC_JOB_STATUSES.includes(key as AsyncJobStatus))) throw new TypeError("adapter counts 无效。"); for (const value of Object.values(counts)) integer(value, "adapter count"); return record as LegacyJobAdapter; }); return { data, meta: meta as { requestId: string; completion: "complete" | "partial"; capturedAt: string } }; }
export function isAsyncJobFresh(capturedAt: string, now = Date.now()) { const time = Date.parse(capturedAt); return Number.isFinite(time) && now < time + 60_000; }
export function classifyAsyncJobRows(rows: readonly unknown[], after: string | undefined, filtered: boolean) { return rows.length ? "ready" : after ? "exhausted" : filtered ? "filtered-empty" : "empty"; }
