import { COMMON_QUERY_VERSION, type CommonCursorResultV1 } from "../api/api-contract.ts";

export const MEDIA_KINDS = ["image", "pdf"] as const;
export const MEDIA_STATUSES = ["uploading", "processing", "ready", "failed", "quarantined", "archived"] as const;
export const MEDIA_CONTENT_TYPES = ["image/jpeg", "image/png", "image/webp", "application/pdf"] as const;
export const MEDIA_ACTOR_TYPES = ["admin_user", "system"] as const;
export const MEDIA_USAGE_ENTITY_TYPES = ["product", "product_variant", "category", "cms_module", "article", "dealer"] as const;
export const MEDIA_VARIANT_ROLES = ["original", "thumbnail", "small", "medium", "large"] as const;
const RFC3339 = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$/;
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
const SHA256 = /^[a-f0-9]{64}$/;

export type MediaKind = typeof MEDIA_KINDS[number];
export type MediaStatus = typeof MEDIA_STATUSES[number];
export type MediaContentType = typeof MEDIA_CONTENT_TYPES[number];
export type MediaQueryState = {
  kinds: MediaKind[];
  statuses: MediaStatus[];
  contentTypes: MediaContentType[];
  source: "" | "dashboard_upload";
  createdByActorType: "" | typeof MEDIA_ACTOR_TYPES[number];
  createdByActorId: string;
  createdFrom: string;
  createdTo: string;
  widthMin: string;
  widthMax: string;
  heightMin: string;
  heightMax: string;
  referenced: "" | "true" | "false";
  archived: "" | "true" | "false";
  usageEntityType: "" | typeof MEDIA_USAGE_ENTITY_TYPES[number];
  q: string;
};
export type MediaLocation =
  | { kind: "not-media" }
  | { kind: "invalid"; message: string; clearHref: string }
  | { kind: "valid"; state: MediaQueryState; assetId?: string; canonicalHref: string; listHref: string; filtered: boolean };
export type MediaScope = { kind: "global" } | { kind: "dealer"; dealerIds: string[]; locationIds: [] } | { kind: "location"; dealerIds: string[]; locationIds: string[] };
export type MediaLocaleMetadata = { locale: "en-CA" | "fr-CA"; altText: string | null; caption: string | null };
export type MediaVariant = { id: string; role: typeof MEDIA_VARIANT_ROLES[number]; status: "processing" | "ready" | "failed"; contentType?: MediaContentType; width?: number; height?: number; bytes?: number; checksum?: string; failureCode?: string };
export type MediaAssetCapabilities = { update: boolean; archive: boolean; restore: boolean; downloadOriginal: boolean; manageVariants: boolean };
export type MediaRetryBinding = { jobId: string; jobVersion: number; variants: Array<{ role: typeof MEDIA_VARIANT_ROLES[number]; expectedVersion: number }> };
export type MediaAsset = {
  id: string; contractVersion: "media-asset.v1"; kind: MediaKind; status: MediaStatus; safeDisplayName: string;
  originalFilename?: string; createdBy?: { actorType: typeof MEDIA_ACTOR_TYPES[number]; actorId?: string };
  contentType?: MediaContentType; bytes?: number; checksum?: string; width?: number; height?: number;
  decorative: boolean; accessibilityComplete: boolean; locales: MediaLocaleMetadata[]; credit: string | null; copyright: string | null;
  tags: string[]; focalPoint?: { x: number; y: number }; provenanceOrigin: "human_upload"; source: "dashboard_upload";
  authorizationScope: MediaScope; createdAt: string; updatedAt: string; archivedAt?: string; usage: { count: number };
  variants: MediaVariant[]; failureCode?: string; version: number; requestId: string;
  capabilities: MediaAssetCapabilities; retryBinding?: MediaRetryBinding;
};
export type MediaSummary = { total: number; byStatus: Partial<Record<MediaStatus, number>>; byKind: Partial<Record<MediaKind, number>> };
export type MediaAdapter = { source: "product_asset.v1" | "tracked_static.v1"; status: "ready" | "unavailable"; freshness: "fresh" | "stale" | "unknown"; counts: Record<string, number>; publicNamespace?: string; capturedAt: string };
export type MediaUsage = { id: string; entityType: typeof MEDIA_USAGE_ENTITY_TYPES[number]; entityId: string; slot: "gallery" | "primary" | "hero" | "tile" | "media" | "inline" | "logo"; requiredLocales: Array<"en-CA" | "fr-CA">; createdAt?: string; version: number };
export type MediaUploadIntent = { intentId: string; asset: MediaAsset; expiresAt: string; uploadToken: string };
export type MediaMutationCapabilities = { create: boolean; update: boolean; archive: boolean; restore: boolean; downloadOriginal: boolean; manageVariants: boolean };

export const emptyMediaQueryState = (): MediaQueryState => ({ kinds: [], statuses: [], contentTypes: [], source: "", createdByActorType: "", createdByActorId: "", createdFrom: "", createdTo: "", widthMin: "", widthMax: "", heightMin: "", heightMax: "", referenced: "", archived: "", usageEntityType: "", q: "" });
export function canonicalMediaTags(value: string) { return [...new Set(value.split(",").map(tag => tag.trim()).filter(Boolean))].sort(); }
function object(value: unknown, label: string) { if (!value || typeof value !== "object" || Array.isArray(value)) throw new TypeError(`${label} 无效。`); return value as Record<string, unknown>; }
function exact(value: Record<string, unknown>, required: string[], optional: string[] = [], label = "value") { const allowed = new Set([...required, ...optional]); if (required.some(key => !(key in value)) || Object.keys(value).some(key => !allowed.has(key))) throw new TypeError(`${label} 字段无效。`); }
function validDate(value: unknown): value is string { return typeof value === "string" && RFC3339.test(value) && Number.isFinite(Date.parse(value)); }
function integer(value: unknown, label: string, positive = false) { if (!Number.isSafeInteger(value) || (value as number) < (positive ? 1 : 0)) throw new TypeError(`${label} 无效。`); return value as number; }
function boundedString(value: unknown, label: string, max: number, nullable = false) { if (nullable && value === null) return null; if (typeof value !== "string" || !value || new TextEncoder().encode(value).length > max || /[\x00-\x1f\x7f]/.test(value)) throw new TypeError(`${label} 无效。`); return value; }
function sortedUnique(value: unknown, label: string) { if (!Array.isArray(value) || value.some(item => typeof item !== "string") || JSON.stringify(value) !== JSON.stringify([...new Set(value)].sort())) throw new TypeError(`${label} 无效。`); return value as string[]; }
function scalar(map: Map<string, string[]>, key: string) { const values = map.get(key) ?? []; if (values.length > 1) throw new TypeError(`${key} 不能重复。`); return values[0] ?? ""; }
function repeated<T extends string>(map: Map<string, string[]>, key: string, allowed: readonly T[]) { const values = map.get(key) ?? []; if (values.length > 20 || values.some(value => !allowed.includes(value as T))) throw new TypeError(`${key} 无效。`); return [...new Set(values as T[])].sort(); }
function occurrences(search: string) { const out = new Map<string, string[]>(); for (const [key, value] of new URLSearchParams(search.startsWith("?") ? search.slice(1) : search)) out.set(key, [...(out.get(key) ?? []), value]); return out; }
function appendListParams(params: URLSearchParams, state: MediaQueryState) { for (const value of state.kinds) params.append("kind", value); for (const value of state.statuses) params.append("status", value); for (const value of state.contentTypes) params.append("contentType", value); for (const key of ["source", "createdByActorType", "createdByActorId", "createdFrom", "createdTo", "widthMin", "widthMax", "heightMin", "heightMax", "referenced", "archived", "usageEntityType", "q"] as const) if (state[key]) params.set(key, state[key]); }
function mediaHref(path: string, state: MediaQueryState, assetId?: string) { const params = new URLSearchParams(); appendListParams(params, state); if (assetId) params.set("assetId", assetId); const query = params.toString(); return query ? `${path}?${query}` : path; }
function validateRange(state: MediaQueryState, now: number) { if (Boolean(state.createdFrom) !== Boolean(state.createdTo)) throw new TypeError("创建时间必须成对填写。"); if (state.createdFrom && (!validDate(state.createdFrom) || !validDate(state.createdTo) || Date.parse(state.createdFrom) >= Date.parse(state.createdTo) || Date.parse(state.createdTo) - Date.parse(state.createdFrom) > 366 * 86_400_000 || Date.parse(state.createdTo) > now)) throw new TypeError("创建时间范围无效。"); for (const [minKey, maxKey] of [["widthMin", "widthMax"], ["heightMin", "heightMax"]] as const) { if (Boolean(state[minKey]) !== Boolean(state[maxKey])) throw new TypeError("尺寸范围必须成对填写。"); if (state[minKey] && (!/^[1-9]\d*$/.test(state[minKey]) || !/^[1-9]\d*$/.test(state[maxKey]) || Number(state[minKey]) > Number(state[maxKey]))) throw new TypeError("尺寸范围无效。"); } }
export function parseDashboardMediaLocation(pathname: string, search: string, sensitive = false, now = Date.now()): MediaLocation {
  const path = pathname.replace(/\/+$/, "") || "/";
  if (path !== "/dashboard/media" && path !== "/fr/dashboard/media") return { kind: "not-media" };
  const map = occurrences(search), allowed = new Set(["kind", "status", "contentType", "source", "createdByActorType", "createdByActorId", "createdFrom", "createdTo", "widthMin", "widthMax", "heightMin", "heightMax", "referenced", "archived", "usageEntityType", "q", "assetId"]);
  try {
    if ([...map.keys()].some(key => !allowed.has(key))) throw new TypeError("页面包含不支持的媒体查询参数。");
    for (const key of allowed) if (!["kind", "status", "contentType"].includes(key)) scalar(map, key);
    const state = emptyMediaQueryState(); state.kinds = repeated(map, "kind", MEDIA_KINDS); state.statuses = repeated(map, "status", MEDIA_STATUSES); state.contentTypes = repeated(map, "contentType", MEDIA_CONTENT_TYPES);
    state.source = scalar(map, "source") as MediaQueryState["source"]; state.createdByActorType = scalar(map, "createdByActorType") as MediaQueryState["createdByActorType"]; state.createdByActorId = scalar(map, "createdByActorId"); state.createdFrom = scalar(map, "createdFrom"); state.createdTo = scalar(map, "createdTo"); state.widthMin = scalar(map, "widthMin"); state.widthMax = scalar(map, "widthMax"); state.heightMin = scalar(map, "heightMin"); state.heightMax = scalar(map, "heightMax"); state.referenced = scalar(map, "referenced") as MediaQueryState["referenced"]; state.archived = scalar(map, "archived") as MediaQueryState["archived"]; state.usageEntityType = scalar(map, "usageEntityType") as MediaQueryState["usageEntityType"]; state.q = scalar(map, "q").trim();
    if (!["", "dashboard_upload"].includes(state.source) || state.createdByActorType && !MEDIA_ACTOR_TYPES.includes(state.createdByActorType) || state.createdByActorId && (!sensitive || !UUID.test(state.createdByActorId)) || !["", "true", "false"].includes(state.referenced) || !["", "true", "false"].includes(state.archived) || state.usageEntityType && !MEDIA_USAGE_ENTITY_TYPES.includes(state.usageEntityType) || new TextEncoder().encode(state.q).length > 128 || state.archived === "false" && state.statuses.includes("archived")) throw new TypeError("媒体筛选参数无效。");
    validateRange(state, now); const assetId = scalar(map, "assetId"); if (assetId && !UUID.test(assetId)) throw new TypeError("媒体资源 ID 无效。");
    const listHref = mediaHref(path, state), canonicalHref = mediaHref(path, state, assetId || undefined); return { kind: "valid", state, ...(assetId ? { assetId } : {}), listHref, canonicalHref, filtered: listHref !== path };
  } catch (error) { return { kind: "invalid", message: error instanceof Error ? error.message : "媒体查询参数无效。", clearHref: path }; }
}
export function mediaListHref(pathname: string, state: MediaQueryState) { return mediaHref(pathname.replace(/\/+$/, "") || "/", state); }
export function mediaAssetHref(pathname: string, state: MediaQueryState, assetId?: string) { if (assetId && !UUID.test(assetId)) throw new TypeError("媒体资源 ID 无效。"); return mediaHref(pathname.replace(/\/+$/, "") || "/", state, assetId); }
export function strictMediaApiPath(state: MediaQueryState, after?: string) { const params = new URLSearchParams({ queryVersion: COMMON_QUERY_VERSION, limit: "50", includeSummary: "true" }); appendListParams(params, state); if (after) params.set("after", after); return `/dashboard/media?${params}`; }
export function mediaDetailApiPath(id: string) { if (!UUID.test(id)) throw new TypeError("媒体资源 ID 无效。"); return `/dashboard/media/${id}`; }
export function mediaUsagesApiPath(id: string) { return `${mediaDetailApiPath(id)}/usages`; }
export function mediaPreviewApiPath(assetId: string, variantId: string) { if (!UUID.test(variantId)) throw new TypeError("媒体变体 ID 无效。"); return `${mediaDetailApiPath(assetId)}/preview/${variantId}`; }
export function mediaDownloadApiPath(id: string) { return `${mediaDetailApiPath(id)}/download-original`; }
export function mediaMutationApiPath(id: string, action: "metadata" | "archive" | "restore" | "variants/retry") { return `${mediaDetailApiPath(id)}/${action}`; }

function scope(value: unknown): MediaScope { const row = object(value, "authorizationScope"); if (row.kind === "global") { exact(row, ["kind"], [], "authorizationScope"); return { kind: "global" }; } exact(row, ["kind", "dealerIds", "locationIds"], [], "authorizationScope"); if (row.kind !== "dealer" && row.kind !== "location") throw new TypeError("authorizationScope 无效。"); const dealerIds = sortedUnique(row.dealerIds, "dealerIds"), locationIds = sortedUnique(row.locationIds, "locationIds"); if (!dealerIds.length || row.kind === "dealer" && locationIds.length || row.kind === "location" && !locationIds.length) throw new TypeError("authorizationScope 无效。"); return { kind: row.kind, dealerIds, locationIds } as MediaScope; }
function variant(value: unknown): MediaVariant { const row = object(value, "variant"); exact(row, ["id", "role", "status"], ["contentType", "width", "height", "bytes", "checksum", "failureCode"], "variant"); if (typeof row.id !== "string" || !UUID.test(row.id) || !MEDIA_VARIANT_ROLES.includes(row.role as never) || !["processing", "ready", "failed"].includes(String(row.status)) || row.contentType !== undefined && !MEDIA_CONTENT_TYPES.includes(row.contentType as never) || row.checksum !== undefined && (typeof row.checksum !== "string" || !SHA256.test(row.checksum)) || row.failureCode !== undefined && typeof row.failureCode !== "string") throw new TypeError("variant 无效。"); for (const key of ["width", "height", "bytes"] as const) if (row[key] !== undefined) integer(row[key], key, true); if (row.status === "ready" && (!row.contentType || !row.bytes || !row.checksum)) throw new TypeError("ready variant 无效。"); return row as MediaVariant; }
export function validateMediaAsset(value: unknown, expectedSensitive = false): MediaAsset { const row = object(value, "media asset"), required = ["id", "contractVersion", "kind", "status", "safeDisplayName", "decorative", "accessibilityComplete", "locales", "credit", "copyright", "tags", "provenanceOrigin", "source", "authorizationScope", "createdAt", "updatedAt", "usage", "variants", "version", "requestId", "capabilities"], optional = ["originalFilename", "createdBy", "contentType", "bytes", "checksum", "width", "height", "focalPoint", "archivedAt", "failureCode", "retryBinding"];
  exact(row, required, optional, "media asset"); if (typeof row.id !== "string" || !UUID.test(row.id) || row.contractVersion !== "media-asset.v1" || !MEDIA_KINDS.includes(row.kind as never) || !MEDIA_STATUSES.includes(row.status as never) || typeof row.decorative !== "boolean" || typeof row.accessibilityComplete !== "boolean" || !validDate(row.createdAt) || !validDate(row.updatedAt) || row.archivedAt !== undefined && !validDate(row.archivedAt) || row.provenanceOrigin !== "human_upload" || row.source !== "dashboard_upload" || typeof row.requestId !== "string" || !row.requestId || !Array.isArray(row.locales) || !Array.isArray(row.variants)) throw new TypeError("media asset 无效。"); boundedString(row.safeDisplayName, "safeDisplayName", 256); integer(row.version, "version");
  if (expectedSensitive !== (row.originalFilename !== undefined || row.createdBy !== undefined)) throw new TypeError("媒体字段可见性无效。"); if (row.originalFilename !== undefined) boundedString(row.originalFilename, "originalFilename", 255); let createdBy: MediaAsset["createdBy"]; if (row.createdBy !== undefined) { const actor = object(row.createdBy, "createdBy"); exact(actor, ["actorType"], ["actorId"], "createdBy"); if (!MEDIA_ACTOR_TYPES.includes(actor.actorType as never) || actor.actorId !== undefined && (typeof actor.actorId !== "string" || !UUID.test(actor.actorId))) throw new TypeError("createdBy 无效。"); createdBy = actor as MediaAsset["createdBy"]; }
  if (row.contentType !== undefined && !MEDIA_CONTENT_TYPES.includes(row.contentType as never) || row.checksum !== undefined && (typeof row.checksum !== "string" || !SHA256.test(row.checksum))) throw new TypeError("媒体内容元数据无效。"); for (const key of ["bytes", "width", "height"] as const) if (row[key] !== undefined) integer(row[key], key, true); if (row.status === "ready" && (!row.contentType || !row.bytes || !row.checksum)) throw new TypeError("ready asset 无效。"); if ((row.status === "failed" || row.status === "quarantined") && (typeof row.failureCode !== "string" || !row.failureCode) || !["failed", "quarantined", "archived"].includes(String(row.status)) && row.failureCode !== undefined) throw new TypeError("媒体失败状态无效。");
  const locales = row.locales.map((entry, index) => { const locale = object(entry, `locales[${index}]`); exact(locale, ["locale", "altText", "caption"], [], "locale"); if (locale.locale !== "en-CA" && locale.locale !== "fr-CA") throw new TypeError("locale 无效。"); return { locale: locale.locale, altText: locale.altText === null ? null : boundedString(locale.altText, "altText", 500), caption: locale.caption === null ? null : boundedString(locale.caption, "caption", 1000) } as MediaLocaleMetadata; }); if (new Set(locales.map(item => item.locale)).size !== locales.length) throw new TypeError("locale 重复。");
  const tags = sortedUnique(row.tags, "tags"); if (tags.length > 32 || tags.some(tag => !tag || tag.length > 64)) throw new TypeError("tags 无效。"); let retryBinding: MediaRetryBinding | undefined; if (row.retryBinding !== undefined) { const binding = object(row.retryBinding, "retryBinding"); exact(binding, ["jobId", "jobVersion", "variants"], [], "retryBinding"); if (typeof binding.jobId !== "string" || !UUID.test(binding.jobId) || !Array.isArray(binding.variants) || !binding.variants.length) throw new TypeError("retryBinding 无效。"); const jobVersion = integer(binding.jobVersion, "retryBinding.jobVersion"); const variants = binding.variants.map((entry, index) => { const item = object(entry, `retryBinding.variants[${index}]`); exact(item, ["role", "expectedVersion"], [], "retry variant"); if (!MEDIA_VARIANT_ROLES.includes(item.role as never)) throw new TypeError("retry variant 无效。"); return { role: item.role as MediaRetryBinding["variants"][number]["role"], expectedVersion: integer(item.expectedVersion, "retry variant version") }; }); if (new Set(variants.map(item => item.role)).size !== variants.length) throw new TypeError("retry variants 重复。"); retryBinding = { jobId: binding.jobId, jobVersion, variants }; } const usage = object(row.usage, "usage"); exact(usage, ["count"], [], "usage"); integer(usage.count, "usage.count"); const capabilities = object(row.capabilities, "capabilities"); exact(capabilities, ["update", "archive", "restore", "downloadOriginal", "manageVariants"], [], "capabilities"); if (Object.values(capabilities).some(value => typeof value !== "boolean")) throw new TypeError("capabilities 无效。"); let focalPoint: MediaAsset["focalPoint"]; if (row.focalPoint !== undefined) { const point = object(row.focalPoint, "focalPoint"); exact(point, ["x", "y"], [], "focalPoint"); if (typeof point.x !== "number" || typeof point.y !== "number" || point.x < 0 || point.x > 1 || point.y < 0 || point.y > 1) throw new TypeError("focalPoint 无效。"); focalPoint = point as MediaAsset["focalPoint"]; }
  return { ...row, safeDisplayName: row.safeDisplayName as string, ...(createdBy ? { createdBy } : {}), locales, tags, authorizationScope: scope(row.authorizationScope), usage: { count: usage.count as number }, capabilities: capabilities as MediaAssetCapabilities, variants: row.variants.map(variant), ...(retryBinding ? { retryBinding } : {}), ...(focalPoint ? { focalPoint } : {}), credit: row.credit === null ? null : boundedString(row.credit, "credit", 500), copyright: row.copyright === null ? null : boundedString(row.copyright, "copyright", 500) } as MediaAsset;
}
function summary(value: unknown): MediaSummary { const row = object(value, "summary"); exact(row, ["total", "byStatus", "byKind"], [], "summary"); const byStatus = object(row.byStatus, "byStatus"), byKind = object(row.byKind, "byKind"); if (Object.keys(byStatus).some(key => !MEDIA_STATUSES.includes(key as never)) || Object.keys(byKind).some(key => !MEDIA_KINDS.includes(key as never))) throw new TypeError("summary registry 无效。"); for (const value of [...Object.values(byStatus), ...Object.values(byKind)]) integer(value, "summary count"); return { total: integer(row.total, "summary total"), byStatus: byStatus as MediaSummary["byStatus"], byKind: byKind as MediaSummary["byKind"] }; }
export function validateMediaCursorResult(value: unknown, expectedSensitive = false): CommonCursorResultV1<MediaAsset, MediaSummary> { const envelope = object(value, "media result"); exact(envelope, ["data", "meta"], ["summary"], "media result"); if (!Array.isArray(envelope.data)) throw new TypeError("media data 无效。"); const meta = object(envelope.meta, "meta"), pagination = object(meta.pagination, "pagination"), snapshot = object(meta.snapshot, "snapshot"), visibility = object(meta.visibility, "visibility"); exact(meta, ["requestId", "queryContractVersion", "pagination", "sort", "snapshot", "visibility"], [], "meta"); exact(pagination, ["mode", "limit", "hasMore"], ["nextCursor"], "pagination"); exact(snapshot, ["consistency", "capturedAt"], [], "snapshot"); exact(visibility, ["profileId"], [], "visibility"); const expectedProfile = expectedSensitive ? "dashboard.media-assets.sensitive.v1" : "dashboard.media-assets.safe.v1"; if (typeof meta.requestId !== "string" || !meta.requestId || meta.queryContractVersion !== COMMON_QUERY_VERSION || pagination.mode !== "cursor" || !Number.isInteger(pagination.limit) || (pagination.limit as number) < 1 || (pagination.limit as number) > 100 || typeof pagination.hasMore !== "boolean" || pagination.nextCursor !== undefined && typeof pagination.nextCursor !== "string" || pagination.hasMore && !pagination.nextCursor || snapshot.consistency !== "statement" || !validDate(snapshot.capturedAt) || visibility.profileId !== expectedProfile || JSON.stringify(meta.sort) !== JSON.stringify([{ field: "createdAt", direction: "desc", nulls: "last" }, { field: "recordId", direction: "desc", nulls: "last" }])) throw new TypeError("media meta 无效。"); let validatedSummary: CommonCursorResultV1<MediaAsset, MediaSummary>["summary"]; if (envelope.summary !== undefined) { const block = object(envelope.summary, "summary block"); exact(block, ["data", "relation", "capturedAt", "profileId"], [], "summary block"); if (block.relation !== "exact" || block.capturedAt !== snapshot.capturedAt || block.profileId !== expectedProfile) throw new TypeError("summary block 无效。"); validatedSummary = { data: summary(block.data), relation: "exact", capturedAt: block.capturedAt as string }; } return { data: envelope.data.map(item => validateMediaAsset(item, expectedSensitive)), meta: meta as CommonCursorResultV1<MediaAsset>["meta"], ...(validatedSummary ? { summary: validatedSummary } : {}) };
}
export function validateMediaDetail(value: unknown, expectedSensitive = false) { const envelope = object(value, "media detail"); exact(envelope, ["data"], [], "media detail"); return { data: validateMediaAsset(envelope.data, expectedSensitive) }; }
export function validateMediaAdapters(value: unknown) { const envelope = object(value, "media adapters"); exact(envelope, ["contractVersion", "completion", "data"], [], "media adapters"); if (envelope.contractVersion !== "media-legacy-adapters.v1" || envelope.completion !== "complete" && envelope.completion !== "partial" || !Array.isArray(envelope.data)) throw new TypeError("media adapters 无效。"); const data = envelope.data.map(entry => { const row = object(entry, "media adapter"); exact(row, ["source", "status", "freshness", "counts", "capturedAt"], ["publicNamespace"], "media adapter"); if (row.source !== "product_asset.v1" && row.source !== "tracked_static.v1" || row.status !== "ready" && row.status !== "unavailable" || !["fresh", "stale", "unknown"].includes(String(row.freshness)) || !validDate(row.capturedAt) || row.publicNamespace !== undefined && (typeof row.publicNamespace !== "string" || !row.publicNamespace.startsWith("/") || row.publicNamespace.includes(".."))) throw new TypeError("media adapter 无效。"); const counts = object(row.counts, "adapter counts"); for (const count of Object.values(counts)) integer(count, "adapter count"); return { ...row, counts } as MediaAdapter; }); return { contractVersion: "media-legacy-adapters.v1" as const, completion: envelope.completion as "complete" | "partial", data };
}
export function validateMediaUsages(value: unknown): { data: MediaUsage[] } { const envelope = object(value, "media usages"); exact(envelope, ["data"], [], "media usages"); if (!Array.isArray(envelope.data)) throw new TypeError("media usages 无效。"); const data = envelope.data.map((entry, index) => { const row = object(entry, `usage[${index}]`); exact(row, ["id", "entityType", "entityId", "slot", "requiredLocales", "version"], ["createdAt"], "usage"); if (typeof row.id !== "string" || !UUID.test(row.id) || !MEDIA_USAGE_ENTITY_TYPES.includes(row.entityType as never) || typeof row.entityId !== "string" || !UUID.test(row.entityId) || !["gallery", "primary", "hero", "tile", "media", "inline", "logo"].includes(String(row.slot)) || !Array.isArray(row.requiredLocales) || row.requiredLocales.some(locale => locale !== "en-CA" && locale !== "fr-CA") || new Set(row.requiredLocales).size !== row.requiredLocales.length || row.createdAt !== undefined && !validDate(row.createdAt)) throw new TypeError("usage 无效。"); return { ...row, version: integer(row.version, "usage.version") } as MediaUsage; }); return { data }; }
export function validateMediaUploadIntent(value: unknown, expectedSensitive = false): { data: MediaUploadIntent } { const envelope = object(value, "upload intent"); exact(envelope, ["data"], [], "upload intent"); const row = object(envelope.data, "upload intent data"); exact(row, ["intentId", "asset", "expiresAt", "uploadToken"], [], "upload intent data"); if (typeof row.intentId !== "string" || !UUID.test(row.intentId) || !validDate(row.expiresAt) || typeof row.uploadToken !== "string" || row.uploadToken.length < 20 || row.uploadToken.length > 512) throw new TypeError("upload intent 无效。"); const asset = validateMediaAsset(row.asset, expectedSensitive); if (asset.status !== "uploading" || Date.parse(row.expiresAt) <= Date.parse(asset.createdAt)) throw new TypeError("upload intent 状态无效。"); return { data: { intentId: row.intentId, asset, expiresAt: row.expiresAt, uploadToken: row.uploadToken } }; }
export function validateMediaUploadResult(value: unknown, expectedSensitive = false) { const envelope = object(value, "upload result"); exact(envelope, ["data"], [], "upload result"); const data = object(envelope.data, "upload result data"); exact(data, ["asset"], [], "upload result data"); const asset = validateMediaAsset(data.asset, expectedSensitive); if (asset.status !== "processing") throw new TypeError("upload result 状态无效。"); return { data: { asset } }; }
export function validateMediaUsageMutation(value: unknown): MediaUsage { const envelope = object(value, "usage mutation"); return validateMediaUsages({ data: [object(envelope, "usage mutation").data] }).data[0]!; }
export function validateMediaRetryResult(value: unknown) { const envelope = object(value, "retry result"); exact(envelope, ["data"], [], "retry result"); const data = object(envelope.data, "retry result data"); exact(data, ["jobId", "assetId", "jobVersion", "assetVersion", "retryGeneration"], [], "retry result data"); if (typeof data.jobId !== "string" || !UUID.test(data.jobId) || typeof data.assetId !== "string" || !UUID.test(data.assetId)) throw new TypeError("retry result 无效。"); return { data: { jobId: data.jobId, assetId: data.assetId, jobVersion: integer(data.jobVersion, "jobVersion"), assetVersion: integer(data.assetVersion, "assetVersion"), retryGeneration: integer(data.retryGeneration, "retryGeneration", true) } }; }
export function isMediaFresh(capturedAt: string, now = Date.now()) { const time = Date.parse(capturedAt); return Number.isFinite(time) && now < time + 60_000; }
export function classifyMediaRows(rows: readonly unknown[], after: string | undefined, filtered: boolean) { return rows.length ? "ready" : after ? "exhausted" : filtered ? "filtered-empty" : "empty"; }
