import assert from "node:assert/strict";
import test from "node:test";
import type { DashboardAuthorization } from "../api/api-contract.ts";
import { executeMediaWrite, type MediaWriteOperation } from "./p07-media-write.ts";
import type { MediaAsset, MediaUploadIntent, MediaUsage } from "./p07-media.ts";
const assetId="123e4567-e89b-42d3-a456-426614174000",usageId="123e4567-e89b-42d3-a456-426614174001",intentId="123e4567-e89b-42d3-a456-426614174002",actorKey="actor-1:revision-1",scope={kind:"global" as const};
const asset={id:assetId,kind:"image",version:1,retryBinding:{jobId:intentId,jobVersion:3,variants:[{role:"thumbnail",expectedVersion:2}]},authorizationScope:scope,capabilities:{update:true,archive:true,restore:true,downloadOriginal:true,manageVariants:true}} as MediaAsset;
const usage={id:usageId} as MediaUsage,intent={intentId,asset,uploadToken:"x".repeat(32)} as MediaUploadIntent;
const capability={enabled:true,actions:{create:true,update:true,archive:true,restore:true,downloadOriginal:true,manageVariants:true},upload:{enabled:true,image:true,pdf:true,maxBytes:{image:10485760,pdf:26214400}}} as DashboardAuthorization["mediaFoundationV1"];
const metadata={version:1,decorative:false,credit:null,copyright:null,tags:["cabinet"],locales:[{locale:"en-CA" as const,altText:"Cabinet",caption:null},{locale:"fr-CA" as const,altText:"Armoire",caption:null}]};
const archive=():Extract<MediaWriteOperation,{kind:"archive"}>=>({kind:"archive",actorKey,asset,assetId,expectedScope:scope,expectedAssetVersion:1});
async function run(value:MediaWriteOperation,cap=capability,current=actorKey,status=200){const calls:Array<{path:string;init:RequestInit}>=[];let invalidated=0;await executeMediaWrite(value,cap,current,async(path,init)=>{calls.push({path,init});return new Response(null,{status})},()=>{invalidated++});return{calls,invalidated}}
test("authorized exact Media operations reach fetch",async()=>{const cases:Array<[MediaWriteOperation,string,string]>=[
[{kind:"createUploadIntent",actorKey,filename:"cabinet.jpg",mediaKind:"image",declaredContentType:"image/jpeg",expectedBytes:10},"/dashboard/media/upload-intents","POST"],
[{kind:"uploadIntentContent",actorKey,intent,assetId,body:new Blob(["x"])},`/dashboard/media/upload-intents/${intentId}/content`,"PUT"],
[{kind:"updateMetadata",actorKey,asset,assetId,expectedScope:scope,metadata},`/dashboard/media/${assetId}/metadata`,"PATCH"],
[{kind:"attachUsage",actorKey,asset,assetId,expectedScope:scope,usageTarget:{expectedAssetVersion:1,entityType:"product",entityId:usageId,slot:"gallery"}},`/dashboard/media/${assetId}/usages`,"POST"],
[{kind:"detachUsage",actorKey,asset,assetId,expectedScope:scope,usage,usageId},`/dashboard/media/${assetId}/usages/${usageId}`,"DELETE"],
[archive(),`/dashboard/media/${assetId}/archive`,"POST"],
[{...archive(),kind:"restore"},`/dashboard/media/${assetId}/restore`,"POST"],
[{kind:"retryVariant",actorKey,asset,assetId,expectedScope:scope,idempotencyKey:"retry-key-1"},`/dashboard/media/${assetId}/variants/retry`,"POST"]];for(const[value,path,method]of cases){const result=await run(value);assert.equal(result.calls.length,1);assert.equal(result.calls[0]?.path,path);assert.equal(result.calls[0]?.init.method,method)}});
test("authorization, capabilities, scope, version, and actor reject before fetch",async()=>{for(const attempt of[
()=>run(archive(),{...capability,enabled:false}),()=>run(archive(),{...capability,actions:{...capability.actions,archive:false}}),()=>run({...archive(),asset:{...asset,capabilities:{...asset.capabilities,archive:false}}}),()=>run({...archive(),expectedScope:{kind:"dealer",dealerIds:[assetId],locationIds:[]}}),()=>run(archive(),capability,"actor-2:revision-2"),()=>run({...archive(),expectedAssetVersion:2})])await assert.rejects(attempt)});
test("arbitrary endpoint/method/body/asset/usage/upload combinations reject",async()=>{await assert.rejects(()=>run({...archive(),assetId:usageId}));await assert.rejects(()=>run({kind:"detachUsage",actorKey,asset,assetId,expectedScope:scope,usage,usageId:intentId}));await assert.rejects(()=>run({kind:"uploadIntentContent",actorKey,intent,assetId:usageId,body:new Blob(["x"])}));await assert.rejects(()=>run({kind:"uploadIntentContent",actorKey,intent,assetId,body:new Blob(["x"])},{...capability,upload:{...capability.upload,image:false}}));await assert.rejects(()=>run({kind:"createUploadIntent",actorKey,filename:"bad.pdf",mediaKind:"image",declaredContentType:"application/pdf",expectedBytes:10}));await assert.rejects(()=>run({kind:"attachUsage",actorKey,asset,assetId,expectedScope:scope,usageTarget:{expectedAssetVersion:1,entityType:"dealer",entityId:usageId,slot:"inline"}}));await assert.rejects(()=>run({kind:"updateMetadata",actorKey,asset,assetId,expectedScope:scope,metadata:{...metadata,tags:["z","a"]}}));await assert.rejects(()=>run({kind:"retryVariant",actorKey,asset:{...asset,retryBinding:undefined},assetId,expectedScope:scope,idempotencyKey:"retry-key"}));assert.equal("path" in archive(),false);assert.equal("method" in archive(),false)});
test("401 invalidates only after authorized fetch",async()=>{const result=await run(archive(),capability,actorKey,401);assert.equal(result.calls.length,1);assert.equal(result.invalidated,1)});
test("archive then restore uses authoritative returned asset state",async()=>{const first=await run(archive());assert.equal(first.calls[0]?.path,`/dashboard/media/${assetId}/archive`);const archived={...asset,status:"archived",version:2,capabilities:{...asset.capabilities,archive:false,restore:true}} as MediaAsset;const second=await run({kind:"restore",actorKey,asset:archived,assetId,expectedScope:archived.authorizationScope,expectedAssetVersion:archived.version});assert.equal(second.calls[0]?.path,`/dashboard/media/${assetId}/restore`)});
