import { COMMON_QUERY_VERSION } from "../api/api-contract.ts";

export const DATA_JOB_OBJECT = "foundation.sample" as const;
export const DATA_JOB_FORMULA = "foundation.sample.export.v1" as const;
export const DATA_JOB_PREFIX = "/dashboard/data-jobs" as const;
export const IMPORT_STATUSES = ["awaiting_upload", "uploaded", "parsing", "preview_ready", "preview_failed", "commit_queued", "committing", "completed", "completed_with_errors", "failed", "cancelled", "expired"] as const;
export const EXPORT_STATUSES = ["queued", "running", "completed", "failed", "cancelled", "expired"] as const;
export const DATA_JOB_PERMISSIONS = {
  importRead: "dashboard.import.foundation_sample.read",
  importCreate: "dashboard.import.foundation_sample.create",
  importCommit: "dashboard.import.foundation_sample.commit",
  exportRead: "dashboard.export.foundation_sample.read",
  exportCreate: "dashboard.export.foundation_sample.create",
  exportDownload: "dashboard.export.foundation_sample.download"
} as const;

const RFC3339 = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$/;
const SHA256 = /^[a-f0-9]{64}$/;
const IMPORT_ID = /^imp_[A-Za-z0-9][A-Za-z0-9_-]{2,127}$/;
const EXPORT_ID = /^exp_[A-Za-z0-9][A-Za-z0-9_-]{2,127}$/;
const TOKEN = /^[A-Za-z0-9._~-]{20,512}$/;
const ERROR_CODES = new Set(["OBJECT_DISABLED", "OBJECT_NOT_SUPPORTED", "IMPORT_NOT_READY", "IMPORT_PREVIEW_FAILED", "IMPORT_PREVIEW_STALE", "IMPORT_EXPIRED", "SOURCE_ARTIFACT_MISSING", "SOURCE_HASH_MISMATCH", "CSV_INVALID_ENCODING", "CSV_MALFORMED", "CSV_DUPLICATE_HEADER", "CSV_MISSING_HEADER", "CSV_UNKNOWN_HEADER", "CSV_PROHIBITED_HEADER", "CSV_ROW_LIMIT_EXCEEDED", "CSV_BYTE_LIMIT_EXCEEDED", "FIELD_REQUIRED", "FIELD_INVALID_TYPE", "FIELD_INVALID_ENUM", "FIELD_TOO_LONG", "FIELD_OUT_OF_RANGE", "IDEMPOTENCY_CONFLICT", "VERSION_CONFLICT", "FENCING_TOKEN_STALE", "EXPORT_NOT_READY", "EXPORT_EXPIRED", "EXPORT_ARTIFACT_MISSING", "DOWNLOAD_NOT_AUTHORIZED"]);
const FIELDS = new Set(["external_key", "label", "state", "quantity", "effective_date", "note"]);

type ImportStatus = typeof IMPORT_STATUSES[number];
type ExportStatus = typeof EXPORT_STATUSES[number];
export type DataJobPermissionGates = Record<keyof typeof DATA_JOB_PERMISSIONS, boolean>;
export type DataJobResourceCapabilities = { read: boolean; create: boolean; commit: boolean; cancel: boolean; download: boolean };
export type DataJobProgress = { phase: "upload" | "parse" | "commit" | "export"; completed: number; total: number | null; unit: "bytes" | "rows" };
export type ImportSummary = { row_count: number; valid_row_count: number; invalid_row_count: number; committed_row_count: number; failed_commit_row_count: number };
export type ImportRowError = { code: string; field?: "external_key" | "label" | "state" | "quantity" | "effective_date" | "note" };
export type ImportPreviewRow = { row_number: number; normalized: { external_key?: string; label?: string; state?: "active" | "inactive"; quantity?: number; effective_date?: string | null; note?: string | null }; validation_status: "valid" | "invalid"; validation_errors: ImportRowError[]; commit_status: "pending" | "committed" | "failed" | "skipped"; commit_errors: ImportRowError[] };
export type ImportBatch = { id: string; object_key: typeof DATA_JOB_OBJECT; status: ImportStatus; original_filename: string; content_type: "text/csv"; byte_size: number; summary: ImportSummary; progress?: DataJobProgress; created_at: string; previewed_at?: string; completed_at?: string; expires_at: string; preview_expires_at?: string; version: number; request_id: string; capabilities: DataJobResourceCapabilities };
export type ImportUploadIntent = { id: string; object_key: typeof DATA_JOB_OBJECT; status: "awaiting_upload"; upload: { method: "PUT"; endpoint: string; token: string; expires_at: string }; version: number };
export type ExportRequest = { id: string; object_key: typeof DATA_JOB_OBJECT; status: ExportStatus; formula_version: typeof DATA_JOB_FORMULA; requested_format: "csv"; row_count?: number; byte_size?: number; sha256?: string; progress?: DataJobProgress; created_at: string; started_at?: string; completed_at?: string; expires_at: string; version: number; request_id: string; capabilities: DataJobResourceCapabilities };
export type DataJobListFilters = { objectKey: "" | typeof DATA_JOB_OBJECT; status: string; creator: string; createdFrom: string; createdTo: string; sort: "created_at:desc" | "created_at:asc" | "status:asc" | "status:desc" };
export type DataJobsLocation = { kind: "not-data-jobs" } | { kind: "invalid"; message: string; clearHref: string } | { kind: "valid"; view: "imports" | "exports"; filters: DataJobListFilters; resourceId?: string; canonicalHref: string; listHref: string };

function object(value: unknown, label: string) { if (!value || typeof value !== "object" || Array.isArray(value)) throw new TypeError(`${label} 无效。`); return value as Record<string, unknown>; }
function exact(value: Record<string, unknown>, required: readonly string[], optional: readonly string[] = [], label = "value") { const allowed = new Set([...required, ...optional]); if (required.some(key => !(key in value)) || Object.keys(value).some(key => !allowed.has(key))) throw new TypeError(`${label} 字段无效。`); }
function integer(value: unknown, label: string, minimum = 0) { if (!Number.isSafeInteger(value) || (value as number) < minimum) throw new TypeError(`${label} 无效。`); return value as number; }
function date(value: unknown, label: string) { if (typeof value !== "string" || !RFC3339.test(value) || !Number.isFinite(Date.parse(value))) throw new TypeError(`${label} 无效。`); return value; }
function text(value: unknown, label: string, max: number) { if (typeof value !== "string" || !value || value.length > max || /[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/.test(value)) throw new TypeError(`${label} 无效。`); return value; }
function id(value: unknown, kind: "import" | "export") { if (typeof value !== "string" || !(kind === "import" ? IMPORT_ID : EXPORT_ID).test(value)) throw new TypeError(`${kind} ID 无效。`); return value; }
function bools(value: unknown): DataJobResourceCapabilities { const row = object(value, "capabilities"); exact(row, ["read", "create", "commit", "cancel", "download"], [], "capabilities"); if (Object.values(row).some(entry => typeof entry !== "boolean")) throw new TypeError("capabilities 无效。"); return row as DataJobResourceCapabilities; }
function progress(value: unknown): DataJobProgress { const row = object(value, "progress"); exact(row, ["phase", "completed", "total", "unit"], [], "progress"); if (!["upload", "parse", "commit", "export"].includes(String(row.phase)) || !["bytes", "rows"].includes(String(row.unit))) throw new TypeError("progress 无效。"); const completed = integer(row.completed, "progress.completed"), total = row.total === null ? null : integer(row.total, "progress.total"); if (total !== null && completed > total) throw new TypeError("progress 超出总量。"); return { phase: row.phase as DataJobProgress["phase"], completed, total, unit: row.unit as DataJobProgress["unit"] }; }
function summary(value: unknown): ImportSummary { const row = object(value, "summary"); exact(row, ["row_count", "valid_row_count", "invalid_row_count", "committed_row_count", "failed_commit_row_count"], [], "summary"); const result = Object.fromEntries(Object.keys(row).map(key => [key, integer(row[key], `summary.${key}`)])) as ImportSummary; if (result.valid_row_count + result.invalid_row_count > result.row_count || result.committed_row_count + result.failed_commit_row_count > result.valid_row_count) throw new TypeError("summary 计数无效。"); return result; }
function calendarDate(value: unknown, label: string) { if (typeof value !== "string" || !/^\d{4}-\d{2}-\d{2}$/.test(value)) throw new TypeError(`${label} 无效。`); const [year, month, day] = value.split("-").map(Number), parsed = new Date(Date.UTC(year!, month! - 1, day)); if (parsed.getUTCFullYear() !== year || parsed.getUTCMonth() + 1 !== month || parsed.getUTCDate() !== day) throw new TypeError(`${label} 无效。`); return value; }
function normalizedPayload(value: Record<string, unknown>, validationStatus: "valid" | "invalid"): ImportPreviewRow["normalized"] { const out: ImportPreviewRow["normalized"] = {}; if (validationStatus === "valid" && ["external_key", "label", "state", "quantity"].some(key => !(key in value))) throw new TypeError("有效行缺少必填字段。"); if (value.external_key !== undefined) out.external_key = text(value.external_key, "external_key", 64); if (value.label !== undefined) out.label = text(value.label, "label", 120); if (value.state !== undefined) { if (value.state !== "active" && value.state !== "inactive") throw new TypeError("state 无效。"); out.state = value.state; } if (value.quantity !== undefined) out.quantity = integer(value.quantity, "quantity"); if (out.quantity !== undefined && out.quantity > 1_000_000) throw new TypeError("quantity 无效。"); if (value.effective_date !== undefined) out.effective_date = value.effective_date === null ? null : calendarDate(value.effective_date, "effective_date"); if (value.note !== undefined) out.note = value.note === null ? null : text(value.note, "note", 500); return out; }
function error(value: unknown): ImportRowError { const row = object(value, "row error"); exact(row, ["code"], ["field"], "row error"); if (typeof row.code !== "string" || !ERROR_CODES.has(row.code) || row.field !== undefined && !FIELDS.has(String(row.field))) throw new TypeError("row error 无效。"); return { code: row.code, ...(row.field ? { field: row.field as ImportRowError["field"] } : {}) }; }
function importBatch(value: unknown): ImportBatch { const row = object(value, "import"); exact(row, ["id", "object_key", "status", "original_filename", "content_type", "byte_size", "summary", "created_at", "expires_at", "version", "request_id", "capabilities"], ["progress", "previewed_at", "completed_at", "preview_expires_at"], "import"); if (row.object_key !== DATA_JOB_OBJECT || !IMPORT_STATUSES.includes(row.status as never) || row.content_type !== "text/csv") throw new TypeError("import registry 无效。"); const createdAt = date(row.created_at, "created_at"), expiresAt = date(row.expires_at, "expires_at"); if (Date.parse(expiresAt) <= Date.parse(createdAt)) throw new TypeError("import expiry 无效。"); const parsed: ImportBatch = { id: id(row.id, "import"), object_key: DATA_JOB_OBJECT, status: row.status as ImportStatus, original_filename: text(row.original_filename, "original_filename", 255), content_type: "text/csv", byte_size: integer(row.byte_size, "byte_size"), summary: summary(row.summary), created_at: createdAt, expires_at: expiresAt, version: integer(row.version, "version", 1), request_id: text(row.request_id, "request_id", 128), capabilities: bools(row.capabilities) }; for (const key of ["previewed_at", "completed_at", "preview_expires_at"] as const) if (row[key] !== undefined) parsed[key] = date(row[key], key); if (row.progress !== undefined) parsed.progress = progress(row.progress); if (parsed.status === "preview_ready" && (!parsed.previewed_at || !parsed.preview_expires_at) || ["completed", "completed_with_errors", "failed", "cancelled", "expired"].includes(parsed.status) && !parsed.completed_at) throw new TypeError("import lifecycle 无效。"); return parsed; }
function exportRequest(value: unknown): ExportRequest { const row = object(value, "export"); exact(row, ["id", "object_key", "status", "formula_version", "requested_format", "created_at", "expires_at", "version", "request_id", "capabilities"], ["row_count", "byte_size", "sha256", "progress", "started_at", "completed_at"], "export"); if (row.object_key !== DATA_JOB_OBJECT || !EXPORT_STATUSES.includes(row.status as never) || row.formula_version !== DATA_JOB_FORMULA || row.requested_format !== "csv") throw new TypeError("export registry 无效。"); const createdAt = date(row.created_at, "created_at"), expiresAt = date(row.expires_at, "expires_at"); if (Date.parse(expiresAt) <= Date.parse(createdAt)) throw new TypeError("export expiry 无效。"); const parsed: ExportRequest = { id: id(row.id, "export"), object_key: DATA_JOB_OBJECT, status: row.status as ExportStatus, formula_version: DATA_JOB_FORMULA, requested_format: "csv", created_at: createdAt, expires_at: expiresAt, version: integer(row.version, "version", 1), request_id: text(row.request_id, "request_id", 128), capabilities: bools(row.capabilities) }; for (const key of ["row_count", "byte_size"] as const) if (row[key] !== undefined) parsed[key] = integer(row[key], key); if (row.sha256 !== undefined) { if (typeof row.sha256 !== "string" || !SHA256.test(row.sha256)) throw new TypeError("sha256 无效。"); parsed.sha256 = row.sha256; } for (const key of ["started_at", "completed_at"] as const) if (row[key] !== undefined) parsed[key] = date(row[key], key); if (row.progress !== undefined) parsed.progress = progress(row.progress); if (parsed.status === "completed" && (parsed.row_count === undefined || parsed.byte_size === undefined || !parsed.sha256 || !parsed.completed_at)) throw new TypeError("completed export 无效。"); return parsed; }
function cursorMeta(value: unknown, requestedSort: DataJobListFilters["sort"]) { const meta = object(value, "meta"), pagination = object(meta.pagination, "pagination"), snapshot = object(meta.snapshot, "snapshot"), visibility = object(meta.visibility, "visibility"); exact(meta, ["requestId", "queryContractVersion", "pagination", "sort", "snapshot", "visibility"], [], "meta"); exact(pagination, ["mode", "limit", "hasMore"], ["nextCursor"], "pagination"); exact(snapshot, ["consistency", "capturedAt"], [], "snapshot"); exact(visibility, ["profileId"], [], "visibility"); if (typeof meta.requestId !== "string" || meta.queryContractVersion !== COMMON_QUERY_VERSION || pagination.mode !== "cursor" || integer(pagination.limit, "limit", 1) > 100 || typeof pagination.hasMore !== "boolean" || pagination.nextCursor !== undefined && typeof pagination.nextCursor !== "string" || pagination.hasMore && !pagination.nextCursor || snapshot.consistency !== "statement") throw new TypeError("P03 meta 无效。"); date(snapshot.capturedAt, "capturedAt"); const [field, direction] = requestedSort.split(":") as ["created_at" | "status", "asc" | "desc"], expectedSort = [{ field: field === "created_at" ? "created_at" : "status", direction, nulls: "last" }, { field: "recordId", direction: "asc", nulls: "last" }]; if (visibility.profileId !== "dashboard.data-jobs.v1" || JSON.stringify(meta.sort) !== JSON.stringify(expectedSort)) throw new TypeError("P03 profile 无效。"); return meta as { requestId: string; pagination: { limit: number; hasMore: boolean; nextCursor?: string }; snapshot: { capturedAt: string } }; }

export function validateImportDetail(value: unknown) { const envelope = object(value, "import detail"); exact(envelope, ["data"], [], "import detail"); return { data: importBatch(envelope.data) }; }
export function validateExportDetail(value: unknown) { const envelope = object(value, "export detail"); exact(envelope, ["data"], [], "export detail"); return { data: exportRequest(envelope.data) }; }
export function validateImportList(value: unknown, requestedSort: DataJobListFilters["sort"] = "created_at:desc") { const envelope = object(value, "import list"); exact(envelope, ["data", "meta"], [], "import list"); if (!Array.isArray(envelope.data)) throw new TypeError("import list 无效。"); return { data: envelope.data.map(importBatch), meta: cursorMeta(envelope.meta, requestedSort) }; }
export function validateExportList(value: unknown, requestedSort: DataJobListFilters["sort"] = "created_at:desc") { const envelope = object(value, "export list"); exact(envelope, ["data", "meta"], [], "export list"); if (!Array.isArray(envelope.data)) throw new TypeError("export list 无效。"); return { data: envelope.data.map(exportRequest), meta: cursorMeta(envelope.meta, requestedSort) }; }
export function validateUploadIntent(value: unknown): { data: ImportUploadIntent } { const envelope = object(value, "upload intent"); exact(envelope, ["data"], [], "upload intent"); const row = object(envelope.data, "upload intent data"), upload = object(row.upload, "upload"); exact(row, ["id", "object_key", "status", "upload", "version"], [], "upload intent data"); exact(upload, ["method", "endpoint", "token", "expires_at"], [], "upload"); const importId = id(row.id, "import"); if (row.object_key !== DATA_JOB_OBJECT || row.status !== "awaiting_upload" || upload.method !== "PUT" || upload.endpoint !== `${DATA_JOB_PREFIX}/imports/${importId}/content` || typeof upload.token !== "string" || !TOKEN.test(upload.token) || upload.endpoint.startsWith("http") || upload.endpoint.includes("//")) throw new TypeError("upload intent 无效。"); return { data: { id: importId, object_key: DATA_JOB_OBJECT, status: "awaiting_upload", upload: { method: "PUT", endpoint: upload.endpoint, token: upload.token, expires_at: date(upload.expires_at, "upload.expires_at") }, version: integer(row.version, "version", 1) } }; }
export function validatePreview(value: unknown) { const envelope = object(value, "preview"); exact(envelope, ["data", "page"], [], "preview"); const data = object(envelope.data, "preview data"), page = object(envelope.page, "page"); exact(data, ["id", "status", "summary", "rows", "version", "capabilities"], [], "preview data"); exact(page, ["limit", "next_cursor"], [], "page"); if (!["preview_ready", "completed", "completed_with_errors"].includes(String(data.status)) || !Array.isArray(data.rows) || page.next_cursor !== null && typeof page.next_cursor !== "string") throw new TypeError("preview 无效。"); const rows = data.rows.map(entry => { const row = object(entry, "preview row"), normalized = object(row.normalized, "normalized"); exact(row, ["row_number", "normalized", "validation_status", "validation_errors", "commit_status", "commit_errors"], [], "preview row"); if (Object.keys(normalized).some(key => !FIELDS.has(key)) || !["valid", "invalid"].includes(String(row.validation_status)) || !["pending", "committed", "failed", "skipped"].includes(String(row.commit_status)) || !Array.isArray(row.validation_errors) || !Array.isArray(row.commit_errors)) throw new TypeError("preview row 无效。"); const validationErrors = row.validation_errors.map(error), commitErrors = row.commit_errors.map(error); if ((row.validation_status === "valid") !== (validationErrors.length === 0) || row.commit_status === "failed" && !commitErrors.length || row.commit_status !== "failed" && commitErrors.length) throw new TypeError("row outcome 无效。"); return { row_number: integer(row.row_number, "row_number", 2), normalized: normalizedPayload(normalized, row.validation_status as "valid" | "invalid"), validation_status: row.validation_status, validation_errors: validationErrors, commit_status: row.commit_status, commit_errors: commitErrors } as ImportPreviewRow; }); return { data: { id: id(data.id, "import"), status: data.status as "preview_ready" | "completed" | "completed_with_errors", summary: summary({ ...object(data.summary, "preview summary"), committed_row_count: object(data.summary, "preview summary").committed_row_count ?? 0, failed_commit_row_count: object(data.summary, "preview summary").failed_commit_row_count ?? 0 }), rows, version: integer(data.version, "version", 1), capabilities: bools(data.capabilities) }, page: { limit: integer(page.limit, "limit", 1), next_cursor: page.next_cursor as string | null } }; }
export function validateMutationImport(value: unknown) { return validateImportDetail(value); }
export function validateMutationExport(value: unknown) { return validateExportDetail(value); }

export const emptyDataJobFilters = (): DataJobListFilters => ({ objectKey: DATA_JOB_OBJECT, status: "", creator: "", createdFrom: "", createdTo: "", sort: "created_at:desc" });
function href(path: string, view: "imports" | "exports", filters: DataJobListFilters, resourceId?: string) { const params = new URLSearchParams({ view }); if (filters.objectKey) params.set("objectKey", filters.objectKey); if (filters.status) params.set("status", filters.status); if (filters.creator) params.set("creator", filters.creator); if (filters.createdFrom) params.set("createdFrom", filters.createdFrom); if (filters.createdTo) params.set("createdTo", filters.createdTo); if (filters.sort !== "created_at:desc") params.set("sort", filters.sort); if (resourceId) params.set(view === "imports" ? "importId" : "exportId", resourceId); return `${path}?${params}`; }
export function parseDataJobsLocation(pathname: string, search: string, now = Date.now()): DataJobsLocation { const path = pathname.replace(/\/+$/, "") || "/"; if (path !== "/dashboard/data-jobs" && path !== "/fr/dashboard/data-jobs") return { kind: "not-data-jobs" }; try { const params = new URLSearchParams(search.startsWith("?") ? search.slice(1) : search), allowed = new Set(["view", "objectKey", "status", "creator", "createdFrom", "createdTo", "sort", "importId", "exportId"]); for (const key of params.keys()) if (!allowed.has(key) || params.getAll(key).length !== 1) throw new TypeError("页面包含不支持或重复的参数。"); const view = params.get("view"); if (view !== "imports" && view !== "exports") throw new TypeError("必须选择导入或导出视图。"); const filters = emptyDataJobFilters(); filters.objectKey = (params.get("objectKey") ?? DATA_JOB_OBJECT) as DataJobListFilters["objectKey"]; filters.status = params.get("status") ?? ""; filters.creator = params.get("creator") ?? ""; filters.createdFrom = params.get("createdFrom") ?? ""; filters.createdTo = params.get("createdTo") ?? ""; filters.sort = (params.get("sort") ?? "created_at:desc") as DataJobListFilters["sort"]; if (filters.objectKey !== DATA_JOB_OBJECT || !["created_at:desc", "created_at:asc", "status:asc", "status:desc"].includes(filters.sort) || filters.status && !(view === "imports" ? IMPORT_STATUSES : EXPORT_STATUSES).includes(filters.status as never) || filters.creator.length > 128) throw new TypeError("数据任务筛选无效。"); if (Boolean(filters.createdFrom) !== Boolean(filters.createdTo) || filters.createdFrom && (!RFC3339.test(filters.createdFrom) || !RFC3339.test(filters.createdTo) || Date.parse(filters.createdFrom) >= Date.parse(filters.createdTo) || Date.parse(filters.createdTo) > now)) throw new TypeError("创建时间范围无效。"); const importId = params.get("importId"), exportId = params.get("exportId"); if (view === "imports" && exportId || view === "exports" && importId) throw new TypeError("详情 ID 与视图不匹配。"); const resourceId = importId ? id(importId, "import") : exportId ? id(exportId, "export") : undefined, listHref = href(path, view, filters); return { kind: "valid", view, filters, ...(resourceId ? { resourceId } : {}), listHref, canonicalHref: href(path, view, filters, resourceId) }; } catch (cause) { return { kind: "invalid", message: cause instanceof Error ? cause.message : "数据任务参数无效。", clearHref: `${path}?view=imports&objectKey=${DATA_JOB_OBJECT}` }; } }
export function dataJobsHref(pathname: string, view: "imports" | "exports", filters: DataJobListFilters, resourceId?: string) { return href(pathname.replace(/\/+$/, "") || "/", view, filters, resourceId); }
export function listApiPath(view: "imports" | "exports", filters: DataJobListFilters, after?: string) { const params = new URLSearchParams({ queryVersion: COMMON_QUERY_VERSION, limit: "50", objectKey: DATA_JOB_OBJECT, sort: filters.sort }); if (filters.status) params.set("status", filters.status); if (filters.creator) params.set("creator", filters.creator); if (filters.createdFrom) params.set("createdFrom", filters.createdFrom); if (filters.createdTo) params.set("createdTo", filters.createdTo); if (after) params.set("after", after); return `${DATA_JOB_PREFIX}/${view}?${params}`; }
export function detailApiPath(view: "imports" | "exports", resourceId: string) { id(resourceId, view === "imports" ? "import" : "export"); return `${DATA_JOB_PREFIX}/${view}/${resourceId}`; }
export function previewApiPath(importId: string, after?: string) { const path = `${detailApiPath("imports", importId)}/preview`; return after ? `${path}?limit=50&after=${encodeURIComponent(after)}` : `${path}?limit=50`; }
export function isDataJobFresh(capturedAt: string, now = Date.now()) { return Number.isFinite(Date.parse(capturedAt)) && now < Date.parse(capturedAt) + 60_000; }
export function deriveDataJobPermissionGates(actions: Array<{ permissionKey: string; decision: string }>): DataJobPermissionGates { const decisions = new Map(actions.map(action => [action.permissionKey, action.decision])); return Object.fromEntries(Object.entries(DATA_JOB_PERMISSIONS).map(([key, permission]) => [key, decisions.get(permission) === "allow"])) as DataJobPermissionGates; }
