import { P09_CONFIG_KEYS, P09_FLAG_KEYS, P09_PREFIX, p09ScopeQuery, type P09Scope } from "./p09-runtime.ts";

type Shared={actorKey:string;expectedActorKey:string;scope:P09Scope;signal?:AbortSignal};
export type P09Operation=
 |(Shared&{kind:"proposeConfig";key:typeof P09_CONFIG_KEYS[number];desiredValue:unknown;expectedVersion:number;idempotencyKey:string})
 |(Shared&{kind:"activateConfig"|"retryConfig";key:typeof P09_CONFIG_KEYS[number];expectedVersion:number;simulateFailure?:boolean;idempotencyKey:string})
 |(Shared&{kind:"rollbackConfig";key:typeof P09_CONFIG_KEYS[number];expectedVersion:number;rollbackVersion:number;idempotencyKey:string})
 |(Shared&{kind:"proposeFlag";key:typeof P09_FLAG_KEYS[number];desiredState:"disabled"|"internal"|"read_only"|"limited"|"enabled";expectedVersion:number;idempotencyKey:string})
 |(Shared&{kind:"activateFlag";key:typeof P09_FLAG_KEYS[number];expectedVersion:number;idempotencyKey:string})
 |(Shared&{kind:"killFlag";key:typeof P09_FLAG_KEYS[number];expectedVersion:number;confirmation:"KILL";idempotencyKey:string});
export type P09Gates={configManage:boolean;configActivate:boolean;flagsManage:boolean;flagsKill:boolean};
const idem=/^[A-Za-z0-9._:-]{8,128}$/;
function check(operation:Shared&{expectedVersion:number;idempotencyKey:string}){if(!operation.actorKey||operation.actorKey!==operation.expectedActorKey)throw new TypeError("运行时操作上下文已过期。");if(!Number.isSafeInteger(operation.expectedVersion)||operation.expectedVersion<0||!idem.test(operation.idempotencyKey))throw new TypeError("运行时操作版本或幂等键无效。");}
function request(path:string,body:unknown,operation:Shared&{idempotencyKey:string}){if(path.startsWith("http")||path.includes("//")||!path.startsWith(`${P09_PREFIX}/`))throw new TypeError("运行时端点无效。");return{path:`${path}?${p09ScopeQuery(operation.scope)}`,init:{method:"POST",signal:operation.signal,credentials:"include" as const,cache:"no-store" as const,redirect:"error" as const,headers:{Accept:"application/json","Content-Type":"application/json","Idempotency-Key":operation.idempotencyKey},body:JSON.stringify(body)}};}
export function authorizeP09Operation(operation:P09Operation,gates:P09Gates){check(operation);switch(operation.kind){case"proposeConfig":if(!gates.configManage||!P09_CONFIG_KEYS.includes(operation.key))throw new TypeError("配置管理授权失败。");return request(`${P09_PREFIX}/config/${operation.key}/versions`,{schemaVersion:"runtime-config-schema.v1",desiredValue:operation.desiredValue,expectedVersion:operation.expectedVersion},operation);case"activateConfig":if(!gates.configActivate)throw new TypeError("配置激活授权失败。");return request(`${P09_PREFIX}/config/${operation.key}/activate`,{expectedVersion:operation.expectedVersion,...(operation.simulateFailure?{simulateFailure:true}:{})},operation);case"retryConfig":if(!gates.configActivate)throw new TypeError("配置重试授权失败。");return request(`${P09_PREFIX}/config/${operation.key}/retry`,{expectedVersion:operation.expectedVersion},operation);case"rollbackConfig":if(!gates.configManage||!gates.configActivate||!Number.isSafeInteger(operation.rollbackVersion)||operation.rollbackVersion<1)throw new TypeError("配置回滚授权失败。");return request(`${P09_PREFIX}/config/${operation.key}/rollback`,{expectedVersion:operation.expectedVersion,rollbackVersion:operation.rollbackVersion},operation);case"proposeFlag":if(!gates.flagsManage)throw new TypeError("功能开关管理授权失败。");return request(`${P09_PREFIX}/flags/${operation.key}/versions`,{desiredState:operation.desiredState,expectedVersion:operation.expectedVersion},operation);case"activateFlag":if(!gates.flagsManage)throw new TypeError("功能开关激活授权失败。");return request(`${P09_PREFIX}/flags/${operation.key}/activate`,{expectedVersion:operation.expectedVersion},operation);case"killFlag":if(!gates.flagsKill||operation.confirmation!=="KILL")throw new TypeError("紧急关闭需要独立授权和精确确认。");return request(`${P09_PREFIX}/flags/${operation.key}/kill`,{expectedVersion:operation.expectedVersion,confirmation:"KILL"},operation);}}
