#!/usr/bin/env python3
import hashlib,json,os,sys,urllib.request
from pathlib import Path
from urllib.parse import urlparse
from playwright.sync_api import sync_playwright, expect
HERE=Path(__file__).resolve().parent; EVIDENCE=HERE/'evidence'; SHOTS=EVIDENCE/'screenshots'; API='http://127.0.0.1:4481'; WEB='http://127.0.0.1:4480'
def sha(path): return hashlib.sha256(Path(path).read_bytes()).hexdigest()
def control(**data): return json.loads(urllib.request.urlopen(urllib.request.Request(API+'/control',data=json.dumps(data).encode(),headers={'Content-Type':'application/json'},method='POST')).read())
def snap(): return json.loads(urllib.request.urlopen(API+'/control/state').read())
def mark(cases,cid,ok,*obs): cases[cid].update(status='pass' if ok else 'fail',observations=list(obs))
def inside(page,selector): return page.evaluate("s=>{const r=document.querySelector(s);return !!r&&r.contains(document.activeElement)}",selector)
def main():
 definition=json.loads((HERE/'definition.json').read_text()); cases={x['id']:{**x,'status':'not-executed','observations':[]} for x in definition['cases']}; network=[]
 tested=os.environ['VANSTRO_TESTED_COMMIT']; assert tested==os.popen('git rev-parse HEAD').read().strip()
 control(profile='full',context=1,p09Delay=False,p09Mode='normal',p10Mode='multiple',resetRequests=True,resetRelease=True); initial=snap(); actor=initial['actor']; import_id=initial['importId']
 with sync_playwright() as pw:
  browser=pw.chromium.launch(headless=True,executable_path='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args=['--disable-background-networking','--no-first-run']); page=browser.new_page(viewport=definition['viewport']); page.on('request',lambda r:network.append({'method':r.method,'url':r.url}))
  page.goto(WEB+'/dashboard/data-jobs?view=imports&objectKey=foundation.sample'); expect(page.get_by_text('VanStro 管理后台')).to_be_visible(); expect(page.get_by_role('banner').get_by_text('Cross F1 QA')).to_be_visible(); mark(cases,'F1-X01',page.get_by_role('navigation',name='管理后台主要导航').count()==1,'server-authoritative actor and shell visible')
  csv=HERE/'sample.csv'; page.locator('input[type=file]').set_input_files(str(csv)); page.get_by_role('button',name='上传并解析').click(); expect(page.get_by_text('上传已提交，解析状态将由服务器更新。')).to_be_visible(); put=next(r for r in snap()['state']['requests'] if r['method']=='PUT' and r['path'].endswith('/content')); h=put['headers']; exact=h['Content-Type']=='text/csv' and h['Content-Length']==str(csv.stat().st_size) and h['If-Match']=='1' and bool(h['Idempotency-Key']) and bool(h['X-Data-Job-Upload-Token']); mark(cases,'F1-X02',exact and snap()['state']['jobs']==1 and snap()['state']['artifacts']==1,'exact PUT headers','one Job/Artifact')
  before=snap()['state']; alt=page.evaluate("async p=>{const r=await fetch(p,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});return {status:r.status,body:await r.json()}}",API+f'/api/v1/dashboard/data-jobs/imports/{import_id}/upload-complete'); after=snap()['state']; zero=all(before[k]==after[k] for k in ['importStatus','jobs','artifacts','finalizeIdentity']); mark(cases,'F1-X03',alt['status']==404 and zero,repr(alt),'state unchanged')
  p09_before=sum(r['url'].startswith(API+'/api/v1/dashboard/runtime/') for r in network); control(profile='denied-p09',context=2); page.goto(WEB+'/dashboard/runtime?view=config'); expect(page.get_by_text('当前操作员没有此视图的读取权限。')).to_be_visible(); mark(cases,'F1-X04',sum(r['url'].startswith(API+'/api/v1/dashboard/runtime/') for r in network)==p09_before,'denied P09 zero protected fetch')
  p10_before=sum('/dashboard/analytics/releases/' in r['url'] for r in network); control(profile='denied-p10',context=3); page.goto(WEB+'/dashboard/analytics-foundation?view=release&releaseDay=2026-08-03'); expect(page.get_by_role('button',name='密封发布')).to_be_disabled(); mark(cases,'F1-X05',sum('/dashboard/analytics/releases/' in r['url'] for r in network)==p10_before,'denied P10 zero protected fetch')
  control(profile='full',context=4,p09Delay=True,resetRelease=True); page.goto(WEB+'/dashboard/runtime?view=config',wait_until='domcontentloaded'); page.wait_for_function("()=>performance.getEntriesByType('resource').some(e=>e.name.includes('/dashboard/runtime/config'))"); control(context=5,p09Delay=False,p09Mode='empty'); page.reload(); expect(page.get_by_text('读取成功，当前集合为空')).to_be_visible(); control(releaseP09=True); expect(page.get_by_text('读取成功，当前集合为空')).to_be_visible(); mark(cases,'F1-X06',page.get_by_text('安全有效值：compact').count()==0,'late response fenced')
  control(profile='full',context=6,p09Mode='normal'); page.goto(WEB+'/dashboard/data-jobs?view=imports&objectKey=foundation.sample'); page.get_by_role('button',name='查看详情').click(); modal_trigger=page.get_by_role('button',name='提交有效行'); modal_trigger.click(); modal=page.get_by_role('dialog'); expect(modal).to_be_visible(); page.keyboard.press('Shift+Tab'); trapped=inside(page,'[role="dialog"]'); page.keyboard.press('Escape'); expect(modal).to_have_count(0); restored=modal_trigger.evaluate('(e)=>document.activeElement===e'); live=' '.join(page.locator('[role=status]').all_inner_texts()); mark(cases,'F1-X08',trapped and restored and bool(live.strip()),'desktop modal trap/Escape/restore','live='+live); page.screenshot(path=str(SHOTS/'desktop-final.png'),full_page=True)
  parsed=[]; violations=[]
  for row in network:
   u=urlparse(row['url']); item={'scheme':u.scheme,'hostname':u.hostname,'port':u.port,'method':row['method'],'url':row['url']}; parsed.append(item)
   if u.scheme not in ('http','https') or u.hostname not in ('127.0.0.1','localhost') or u.port not in (4480,4481) or row['method'] not in ('GET','POST','PUT','OPTIONS'): violations.append(item)
  mark(cases,'F1-X11',not violations,'parsed='+str(len(parsed)),'violations='+repr(violations)); browser.close()
 counts={s:sum(x['status']==s for x in cases.values()) for s in ['pass','fail','intentional-skip','not-executed']}; final=snap(); report={'schemaVersion':1,'suiteId':definition['suiteId'],'profile':definition['profile'],'testedCommit':tested,'includedCaseIds':definition['includedCaseIds'],'outOfV1ScopeCaseIds':definition['outOfV1ScopeCaseIds'],'definitionSha256':sha(HERE/'definition.json'),'fixtureSha256':sha(HERE/'fixture.py'),'harnessSha256':sha(HERE/'acceptance.py'),'runnerSha256':sha(HERE/'run.py'),'viewport':definition['viewport'],'counts':counts,'cases':list(cases.values()),'requestCount':len(final['state']['requests']),'networkCount':len(parsed),'unexpectedNetwork':violations}
 (EVIDENCE/'result.partial.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n'); print(json.dumps(counts)); return 1 if counts!={'pass':8,'fail':0,'intentional-skip':0,'not-executed':0} else 0
if __name__=='__main__': sys.exit(main())
