import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { existsSync } from "node:fs";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { generate, readInputs, writeArtifacts } from "./generate.mjs";
import { verifyModel } from "./semantic-verify.mjs";

const localModel=new URL("./clarification-model.yaml",import.meta.url);
const packaged=!existsSync(localModel);
const sourceModel=packaged?new URL("../source/clarification-model.yaml",import.meta.url):localModel;
const sourceSchema=new URL(packaged?"../source/clarification-model.schema.json":"./clarification-model.schema.json",import.meta.url);
const load=async()=>JSON.parse(await readFile(sourceModel,"utf8"));
async function fixture(model){model ??= await load();const root=await mkdtemp(join(tmpdir(),"f1-clarification-"));const modelPath=join(root,"clarification-model.yaml"),schemaPath=join(root,"schema.json"),output=join(root,"generated");await writeFile(modelPath,`${JSON.stringify(model,null,2)}\n`);await writeFile(schemaPath,await readFile(sourceSchema));return{root,modelPath,schemaPath,output};}
async function expectMutation(name,mutate,code){await test(name,async()=>{const m=await load();mutate(m);const f=await fixture(m);try{await assert.rejects(async()=>{const i=await readInputs(f);verifyModel(i);},new RegExp(code));}finally{await rm(f.root,{recursive:true,force:true});}});}

test("frozen schema semantic generation and byte verification close",async()=>{const f=await fixture();try{const i=await readInputs(f);const s=verifyModel(i);assert.equal(s.old68Count,31);assert.equal(s.sqlBodyCount,30);assert.equal(s.objectCount,237);const g=generate(i);assert.equal(g.artifacts.size,13);await writeArtifacts(f.output,g);await writeArtifacts(f.output,g,true);for(const [p,t] of g.artifacts)assert.deepEqual(await readFile(join(f.output,p)),Buffer.from(t));}finally{await rm(f.root,{recursive:true,force:true});}});

await expectMutation("reject parent manifest drift",m=>m.parentAuthority.manifestSha256="0".repeat(64),"PARENT_AUTHORITY_BINDING_MISMATCH");
await expectMutation("reject candidate rollback after freeze",m=>m.package.status="CANDIDATE — NOT AUTHORITY","SCHEMA_VALIDATION_FAILED");
await expectMutation("reject missing Contract freeze review",m=>delete m.package.freezeReviews.contract,"SCHEMA_VALIDATION_FAILED|FREEZE_REVIEW_EVIDENCE_INVALID");
await expectMutation("reject unresolved Contract High",m=>m.package.freezeReviews.contract.high=1,"FREEZE_REVIEW_EVIDENCE_INVALID");
await expectMutation("reject missing accepted Medium followup",m=>m.package.acceptedFollowups=[],"SCHEMA_VALIDATION_FAILED|FREEZE_FOLLOWUP_DISPOSITION_INVALID");
await expectMutation("reject P09 permission implication drift",m=>m.p09ReadAuthority.nonImplication=false,"P09_READ_STRATEGY_MISMATCH");
await expectMutation("reject readiness priority drift",m=>m.readinessTruthTable.orderedReasons.reverse(),"READINESS_REASON_ORDER_MISMATCH");
await expectMutation("reject all-workers-stale mapping drift",m=>m.readinessTruthTable.orderedReasons[4].status="not_ready","READINESS_STATUS_MAPPING_MISMATCH");
await expectMutation("reject P10 direct Audit INSERT privilege",m=>m.p10AuditAuthority.p10GuardDirectAuditEventsPrivileges.push("INSERT"),"P10_P04_AUTHORITY_MISMATCH");
await expectMutation("reject P10 audit replay duplication",m=>m.p10AuditAuthority.replayAddsAudit=true,"P10_P04_AUTHORITY_MISMATCH");
await expectMutation("reject open resolver registry",m=>m.p02ResolverAuthority.registryClosed=false,"P02_HELPER_AUTHORITY_MISMATCH");
await expectMutation("reject dynamic resolver SQL",m=>m.p02ResolverAuthority.resolvers[0].dynamicSql=true,"P02_RESOLVER_INVALID");
await expectMutation("reject missing worker heartbeat child",m=>m.workerHeartbeats.children.pop(),"WORKER_HEARTBEAT_CHILD_MISSING");
await expectMutation("reject migration-created Worker LOGIN",m=>m.workerLogin.migrationCreates=true,"WORKER_LOGIN_BOUNDARY_MISMATCH");
await expectMutation("reject old68 omission",m=>m.old68RuntimeSurface.pop(),"SCHEMA_VALIDATION_FAILED|OLD68_SURFACE_COUNT_MISMATCH");
await expectMutation("reject incomplete old68 revoke partition",m=>m.old68RuntimeSurface.find(x=>x.name==="p09_config_list").disposition="permanent","OLD68_REVOKE_PARTITION_MISMATCH");
await expectMutation("reject SQL body drift",m=>m.sqlFunctionBodies[0].canonicalSql+=" ","SQL_BODY_HASH_MISMATCH");
await expectMutation("reject dynamic SQL",m=>{const f=m.sqlFunctionBodies[0];f.canonicalSql=f.canonicalSql.replace("BEGIN","BEGIN\nEXECUTE FORMAT('SELECT 1');");f.canonicalSqlSha256=createHash("sha256").update(f.canonicalSql).digest("hex");},"DYNAMIC_SQL_FORBIDDEN");
await expectMutation("reject P10 direct audit insert body",m=>{const f=m.sqlFunctionBodies.find(x=>x.name==="p10_get_release_day_v2");f.canonicalSql=f.canonicalSql.replace("BEGIN","BEGIN\nINSERT INTO public.audit_events DEFAULT VALUES;");f.canonicalSqlSha256=createHash("sha256").update(f.canonicalSql).digest("hex");},"P10_DIRECT_AUDIT_INSERT_FORBIDDEN");
await expectMutation("reject duplicate UNIQUE backing index authority",m=>m.uniqueRepresentation.duplicateIndexDefinitionForbidden=false,"UNIQUE_BACKING_INDEX_RULE_MISMATCH");
await expectMutation("reject ambiguous constraint action",m=>m.constraintActions[0].action="add_or_replace","SCHEMA_VALIDATION_FAILED");
await expectMutation("reject history rewrite",m=>m.constraintActions[0].historyRewrite=true,"SCHEMA_VALIDATION_FAILED|HISTORY_REWRITE_FORBIDDEN");
await expectMutation("reject DDL dependency cycle",m=>m.ddlNodes[0].dependsOn=[m.ddlNodes[1].id],"DDL_CYCLE");
await expectMutation("reject migration70 order drift",m=>m.migration70Order.reverse(),"DDL_ORDER_DEPENDENCY_MISMATCH|MIGRATION70_ORDER_MISMATCH");
await expectMutation("reject upload-complete restoration",m=>m.frontendReplacement.p08.uploadCompleteRoute="exists","FRONTEND_REPLACEMENT_MISMATCH");
await expectMutation("reject raw-event suppression bypass",m=>m.frontendReplacement.p10.suppressionWireRequired=false,"FRONTEND_REPLACEMENT_MISMATCH");
await expectMutation("reject missing HTTP response wire",m=>m.wireDtos=m.wireDtos.filter(x=>x.id!=="wire.p10.sealed.release.v1"),"WIRE_MISSING|HTTP_WIRE_DANGLING");
await expectMutation("reject inherited HMAC drift",m=>m.p10InheritedAuthority.hmac.algorithm="SHA-256","P10_INHERITED_AUTHORITY_MISMATCH");
await expectMutation("reject inherited suppression drift",m=>m.p10InheritedAuthority.suppression.k=2,"P10_INHERITED_AUTHORITY_MISMATCH");
await expectMutation("reject incomplete constraint ledger",m=>m.constraintActions.pop(),"CONSTRAINT_LEDGER_INCOMPLETE");
await expectMutation("reject old68 source migration omission",m=>delete m.old68RuntimeSurface[0].sourceMigration,"OLD68_SOURCE_PROBE_MISMATCH");
await expectMutation("reject ACL ledger omission",m=>m.aclDelta.pop(),"ACL_LEDGER_COUNT_MISMATCH");
await expectMutation("reject incomplete attestation protocol",m=>m.attestation.transactionIsolation="READ COMMITTED","ATTESTATION_PROTOCOL_INCOMPLETE");
await expectMutation("reject DDL object omission",m=>m.ddlNodes[0].objectRefs=[],"DDL_OBJECT_REFS_MISSING");
await expectMutation("reject plaintext key storage",m=>m.migration69AdditionsSql=m.migration69AdditionsSql.replace('providerKeyRef','keyBytes'),"MIGRATION69_ADDITIONS_INCOMPLETE|P10_INHERITED_AUTHORITY_MISMATCH");
await expectMutation("reject P02 provenance removal",m=>m.p02ResolverAuthority.returnsGrantProvenance=false,"P02_HELPER_AUTHORITY_MISMATCH");
await expectMutation("reject Worker seal permission reuse",m=>m.workerPermissions.seal='analytics.release.read',"WORKER_PERMISSION_BOUNDARY_MISMATCH");
await expectMutation("reject readiness route collision",m=>m.httpContracts.find(x=>x.responseEnvelope.success.data==='wire.p09.readiness.detail.v2').path='/api/v1/dashboard/runtime/readiness/summary',"HTTP_ROUTE_DUPLICATE");
await expectMutation("reject migration70 attestation node omission",m=>m.ddlNodes.find(x=>x.migration===70&&x.operation==='attest_no_old_instances').sqlStatements=[],"MIGRATION70_INCOMPLETE");
await expectMutation("reject exact frontend symbol omission",m=>m.frontendReplacement.exactSourceSymbols.pop(),"FRONTEND_SYMBOLS_INCOMPLETE");
await expectMutation("reject Goal SHA drift",m=>m.parentAuthority.goalSha256="0".repeat(64),"PARENT_AUTHORITY_BINDING_MISMATCH");
await expectMutation("reject missing old call protocol",m=>m.oldCallAuditProtocol.expectedCount=30,"OLD_CALL_PROTOCOL_INCOMPLETE");
await expectMutation("reject unsigned subject purpose",m=>m.cryptoAssertions.subjectPurpose="subject_assertion","CRYPTO_ASSERTION_INCOMPLETE");
await expectMutation("reject dispatcher omission",m=>m.workerDispatcherAuthority.descriptors.pop(),"WORKER_DISPATCHER_INCOMPLETE");
await expectMutation("reject SQL wire name drift",m=>m.wireDtos[0].sqlFields[0][0]="wrong", "WIRE_SQL_RETURN_MISMATCH");
await expectMutation("reject blocking concurrent phase",m=>m.concurrentSql=m.concurrentSql.replace("CONCURRENTLY",""),"SCHEMA_VALIDATION_FAILED|EXECUTION_PHASES_INCOMPLETE|CONCURRENT_RECOVERY_INCOMPLETE");
await expectMutation("reject migration role creation",m=>m.migration69AdditionsSql="CREATE ROLE bad;"+m.migration69AdditionsSql,"EXECUTION_PHASES_INCOMPLETE");
await expectMutation("reject missing signer lifecycle",m=>m.sqlFunctionBodies=m.sqlFunctionBodies.filter(x=>x.name!=="p10_manage_trusted_signer_v1"),"LIFECYCLE_FUNCTIONS_MISSING|SQL_BODY_MISSING");
await expectMutation("reject missing DSAR",m=>m.sqlFunctionBodies=m.sqlFunctionBodies.filter(x=>x.name!=="p10_dsar_purge_subject_v1"),"LIFECYCLE_FUNCTIONS_MISSING|SQL_BODY_MISSING");
await expectMutation("reject consent insert arity drift",m=>{const f=m.sqlFunctionBodies.find(x=>x.name==="p10_write_authenticated_consent_v1");f.canonicalSql=f.canonicalSql.replace(',"expiresAt"','');},"SQL_BODY_HASH_MISMATCH|CONSENT_COMMAND_ARITY_INCOMPLETE");
await expectMutation("reject bootstrap self attestation",m=>m.bootstrapSql=m.bootstrapSql.replace('DO $baseline$','TRUNCATE public.f1_source_migration_manifest;DO $baseline$'),"BOOTSTRAP_SELF_ATTESTATION_FORBIDDEN");
await expectMutation("reject attestation future bound",m=>{const f=m.sqlFunctionBodies.find(x=>x.name==="f1_consume_no_old_instances_v2");f.canonicalSql=f.canonicalSql.replace(" AND a.\"observedAt\"<=CURRENT_TIMESTAMP+interval '5 seconds'","");},"SQL_BODY_HASH_MISMATCH|ATTESTATION_FRAME_INCOMPLETE");
await expectMutation("reject cleanup eligibility ledger",m=>{const f=m.sqlFunctionBodies.find(x=>x.name==="p10_cleanup_source_events_v2");f.canonicalSql=f.canonicalSql.replaceAll('analytics_foundation_release_event','missing_ledger');},"SQL_BODY_HASH_MISMATCH|CLEANUP_ELIGIBILITY_LEDGER_MISSING");
await expectMutation("reject concurrent recovery",m=>m.concurrentSql=m.concurrentSql.replace('DROP INDEX CONCURRENTLY IF EXISTS',''),"CONCURRENT_RECOVERY_INCOMPLETE");
await expectMutation("reject external verifier migration creation",m=>m.externalCryptoEvidence.migrationCreates=true,"CRYPTO_EVIDENCE_ADAPTER_MISSING");
await expectMutation("reject merged security principals",m=>m.securityPrincipals.kmsRotation.role=m.securityPrincipals.signerAdmin.role,"SECURITY_PRINCIPAL_POOLS_NOT_SPLIT");
await expectMutation("reject stale shared capability metadata",m=>m.securityCapabilities.kmsRotation=m.securityCapabilities.signer,"SECURITY_CAPABILITIES_NOT_SPLIT");
await expectMutation("reject signed telemetry writer omission",m=>m.sqlFunctionBodies=m.sqlFunctionBodies.filter(x=>x.name!=="f1_ingest_signed_old_call_report_v1"),"SIGNED_TELEMETRY_INGESTION_MISSING");
await expectMutation("reject external baseline capture",m=>m.baselineEvidence.capturedExternally=false,"BASELINE_EVIDENCE_MISMATCH");
await expectMutation("reject erasure token authority",m=>m.privacyRetention.erasureToken="raw digest", "ERASURE_AUTHORITY_INCOMPLETE");
await expectMutation("reject non-final supersession entry",m=>m.parentSupersedes.push({...m.parentSupersedes[0],id:"supersedes.legacy"}),"SUPERSEDES_VOCABULARY_INCOMPLETE");
await expectMutation("reject consent claim subject binding omission",m=>{const f=m.sqlFunctionBodies.find(x=>x.name==="p10_write_authenticated_consent_v1");f.canonicalSql=f.canonicalSql.replace(',\"subjectDigest\",\"expiresAt\"',',\"expiresAt\"').replace(',subject_digest,CURRENT_TIMESTAMP',',CURRENT_TIMESTAMP');},"SQL_BODY_HASH_MISMATCH");
await expectMutation("reject telemetry signer provisioning purpose",m=>{const f=m.sqlFunctionBodies.find(x=>x.name==="p10_manage_trusted_signer_v1");f.canonicalSql=f.canonicalSql.replace(",'old_call_telemetry'","");},"SQL_BODY_HASH_MISMATCH");
await expectMutation("reject stale signed telemetry window",m=>{const f=m.sqlFunctionBodies.find(x=>x.name==="f1_ingest_signed_old_call_report_v1");f.canonicalSql=f.canonicalSql.replace(" OR window_ended_at<CURRENT_TIMESTAMP-interval '2 minutes'","");},"SQL_BODY_HASH_MISMATCH|TELEMETRY_WINDOW_INCOMPLETE");
await expectMutation("reject KMS generation fence omission",m=>{const f=m.sqlFunctionBodies.find(x=>x.name==="p10_rotate_subject_kid_v1");f.canonicalSql=f.canonicalSql.replace(' AND j.\"retryGeneration\"=retry_generation',"");},"SQL_BODY_HASH_MISMATCH|KMS_ROTATION_FENCE_INCOMPLETE");
await expectMutation("reject mutable frozen old68 registry",m=>m.migration69AdditionsSql=m.migration69AdditionsSql.replace('CREATE TRIGGER f1_old_function_registry_immutable','CREATE TRIGGER removed_registry_guard'),"OLD68_REGISTRY_MUTABLE");
await expectMutation("reject bootstrap crypto KAT omission",m=>m.bootstrapSql=m.bootstrapSql.replace('EXTERNAL_CRYPTO_IMPLEMENTATION_EVIDENCE_REQUIRED','missing_crypto_evidence'),"BOOTSTRAP_HANDOFF_INCONSISTENT");
await expectMutation("reject replay before erasure check",m=>{const f=m.sqlFunctionBodies.find(x=>x.name==="p10_ingest_event_v5");f.canonicalSql=f.canonicalSql.replace('SELECT * INTO claim FROM public.f1_p10_idempotency','SELECT * INTO claim FROM public.f1_p10_idempotency /* moved */').replace('PERFORM pg_advisory_xact_lock','SELECT * INTO claim FROM public.f1_p10_idempotency;PERFORM pg_advisory_xact_lock');},"SQL_BODY_HASH_MISMATCH|ERASURE_REPLAY_ORDER_INVALID");
await expectMutation("reject non-repeat-safe temp authorization",m=>{const f=m.sqlFunctionBodies.find(x=>x.name==="p10_dsar_purge_subject_v1");f.canonicalSql=f.canonicalSql.replace('CREATE TEMP TABLE IF NOT EXISTS','CREATE TEMP TABLE').replace('TRUNCATE pg_temp.p10_authorized_delete_event_ids;','');},"SQL_BODY_HASH_MISMATCH|TEMP_DELETE_AUTHORITY_INCOMPLETE");
await expectMutation("reject raw digest DSAR Audit",m=>{const f=m.sqlFunctionBodies.find(x=>x.name==="p10_dsar_purge_subject_v1");f.canonicalSql=f.canonicalSql.replace("encode(erasure_token,'hex'),'succeeded'","encode(subject_digest,'hex'),'succeeded'");},"SQL_BODY_HASH_MISMATCH|DSAR_ERASURE_AUDIT_INVALID");
await expectMutation("reject telemetry lastCalled inconsistency",m=>{const f=m.sqlFunctionBodies.find(x=>x.name==="f1_ingest_signed_old_call_report_v1");f.canonicalSql=f.canonicalSql.replace('t.\"callCount\"=0 AND t.\"lastCalledAt\" IS NOT NULL','false');},"SQL_BODY_HASH_MISMATCH|TELEMETRY_LAST_CALLED_INCONSISTENT");
await expectMutation("reject unpinned external crypto evidence",m=>m.externalCryptoEvidence.artifact.pinnedVerifierBinarySha256='0'.repeat(64),"CRYPTO_EVIDENCE_ISSUER_UNBOUND");
await expectMutation("reject circular crypto evidence verifier",m=>m.bootstrapSql=m.bootstrapSql.replace('e."attestationDigest"=encode(digest(e."signedPayload"||e."evidenceSignature",\'sha256\'),\'hex\')','public.vanstro_verify_ed25519_v1(e."signedPayload",e."evidenceSignature",decode(repeat(\'00\',32),\'hex\'))'),"CRYPTO_EVIDENCE_ISSUER_UNBOUND");
await expectMutation("reject aggregate-only readiness",m=>{const f=m.sqlFunctionBodies.find(x=>x.name==="p09_observe_readiness_internal_v2");f.canonicalSql=f.canonicalSql.replace(' OR missing_family>0','');},"SQL_BODY_HASH_MISMATCH|READINESS_PRINCIPAL_CAPACITY_INCOMPLETE");
await expectMutation("reject stale principal capacity acceptance",m=>{const f=m.sqlFunctionBodies.find(x=>x.name==="p09_observe_readiness_internal_v2");f.canonicalSql=f.canonicalSql.replace('c.\"observedAt\">now_at-interval \'15 seconds\'','true');},"SQL_BODY_HASH_MISMATCH|READINESS_PRINCIPAL_CAPACITY_INCOMPLETE");
await expectMutation("reject DSAR committed replay omission",m=>{const f=m.sqlFunctionBodies.find(x=>x.name==="p10_dsar_purge_subject_v1");f.canonicalSql=f.canonicalSql.replace('RETURN prior.\"purgedRows\";','RAISE EXCEPTION \'NO_REPLAY\';');},"SQL_BODY_HASH_MISMATCH|DSAR_COMMITTED_REPLAY_INCOMPLETE");

await expectMutation("reject DSAR attempt-bound stable intent",m=>{const f=m.sqlFunctionBodies.find(x=>x.name==="p10_dsar_purge_subject_v1");f.canonicalSql=f.canonicalSql.replace("request_id||'|'||extract(epoch from retention_cutoff)","request_id||'|'||lease_owner||'|'||extract(epoch from retention_cutoff)");},"SQL_BODY_HASH_MISMATCH|DSAR_COMMITTED_REPLAY_INCOMPLETE");
await expectMutation("reject unstaged DSAR tombstone",m=>{const f=m.sqlFunctionBodies.find(x=>x.name==="p10_dsar_purge_subject_v1");f.canonicalSql=f.canonicalSql.replace(' AND "retentionCutoff"=retention_cutoff','');},"SQL_BODY_HASH_MISMATCH|DSAR_COMMITTED_REPLAY_INCOMPLETE");
await expectMutation("reject incomplete crypto evidence frame",m=>m.externalCryptoEvidence.artifact.signedFrame.pop(),"CRYPTO_EVIDENCE_ISSUER_UNBOUND");
await expectMutation("reject caller-selected capacity generation",m=>{const f=m.sqlFunctionBodies.find(x=>x.name==="p09_report_principal_job_capacity_v1");f.canonicalSql=f.canonicalSql.replace('next_generation:=current_generation+1','next_generation:=expected_generation');},"SQL_BODY_HASH_MISMATCH|READINESS_PRINCIPAL_CAPACITY_INCOMPLETE");
await expectMutation("reject inflated Worker job declaration",m=>{const f=m.sqlFunctionBodies.find(x=>x.name==="p09_worker_startup_v2");f.canonicalSql=f.canonicalSql.replace("ARRAY['analytics.release.seal','analytics.source.cleanup']","ARRAY['analytics.release.seal','analytics.source.cleanup','analytics.subject-key.rotate']");},"SQL_BODY_HASH_MISMATCH|WORKER_ACTUAL_JOB_SET_INCOMPLETE");
await expectMutation("reject general-only total capacity",m=>{const f=m.sqlFunctionBodies.find(x=>x.name==="p09_observe_readiness_internal_v2");f.canonicalSql=f.canonicalSql.replace('a,st,family_capacity','a,st,cap');},"SQL_BODY_HASH_MISMATCH|READINESS_PRINCIPAL_CAPACITY_INCOMPLETE");
await expectMutation("reject unsigned telemetry report identity",m=>{const f=m.sqlFunctionBodies.find(x=>x.name==="f1_ingest_signed_old_call_report_v1");f.canonicalSql=f.canonicalSql.replace("||int4send(length(convert_to(report_id::text,'UTF8')))||convert_to(report_id::text,'UTF8')",'');},"SQL_BODY_HASH_MISMATCH|TELEMETRY_FRAME_INCOMPLETE");
await expectMutation("reject missing pool incarnation fence",m=>{const f=m.sqlFunctionBodies.find(x=>x.name==="p09_report_principal_job_capacity_v1");f.canonicalSql=f.canonicalSql.replace(' AND \"incarnationId\"=incarnation_id','');},"SQL_BODY_HASH_MISMATCH|READINESS_PRINCIPAL_CAPACITY_INCOMPLETE");
await expectMutation("reject shared pool capacity duplication",m=>{const f=m.sqlFunctionBodies.find(x=>x.name==="p09_observe_readiness_internal_v2");f.canonicalSql=f.canonicalSql.replace('sum(c.\"capacity\")','sum(c.\"capacity\"*cardinality(c.\"supportedJobTypes\"))');},"SQL_BODY_HASH_MISMATCH|READINESS_PRINCIPAL_CAPACITY_INCOMPLETE");
await expectMutation("reject always-true crypto root",m=>m.bootstrapSql=m.bootstrapSql.replace(' OR public.vanstro_verify_crypto_root_v1(convert_to(\'vanstro.crypto-root-kat.v1\',\'UTF8\'),decode(\'00\'||repeat(\'11\',63),\'hex\'),decode(repeat(\'22\',32),\'hex\'))',''),"SIGNED_TRUST_FRAME_INCOMPLETE");
await expectMutation("reject unsigned crypto evidence signature",m=>m.bootstrapSql=m.bootstrapSql.replaceAll(' AND public.vanstro_verify_crypto_root_v1(e.\"signedPayload\",e.\"evidenceSignature\",(SELECT decode(\"publicKeyDigest\",\'hex\') FROM public.f1_crypto_evidence_issuer i WHERE i.issuer=e.issuer))',''),"SIGNED_TRUST_FRAME_INCOMPLETE");
await expectMutation("reject incomplete subject signed frame",m=>m.cryptoAssertions.subjectSignedFrame.order.pop(),"SIGNED_TRUST_FRAME_INCOMPLETE");
await expectMutation("reject root probin provenance omission",m=>m.bootstrapSql=m.bootstrapSql.replace(" AND x.\"probin\"=COALESCE(p.probin,'')",''),"SIGNED_TRUST_FRAME_INCOMPLETE");
await expectMutation("reject second root forged KAT omission",m=>m.bootstrapSql=m.bootstrapSql.replace(" OR public.vanstro_verify_crypto_root_v1(convert_to('vanstro.crypto-root-kat.v2','UTF8'),decode('00'||repeat('33',63),'hex'),decode(repeat('44',32),'hex'))",''),"SIGNED_TRUST_FRAME_INCOMPLETE");
await expectMutation("reject migrator root provenance DML",m=>m.bootstrapSql=m.bootstrapSql.replace(" OR has_table_privilege('vanstro_migrator','public.f1_crypto_root_provenance','INSERT,UPDATE,DELETE')",''),"SIGNED_TRUST_FRAME_INCOMPLETE");
await test("all generated members carry frozen status",async()=>{const f=await fixture();try{const i=await readInputs(f);const g=generate(i);for(const [path,text] of g.artifacts)assert.ok(text.includes('FROZEN'),`missing FROZEN status: ${path}`);}finally{await rm(f.root,{recursive:true,force:true});}});
