-- P10 bounded Analytics Event / Metric Foundation. Forward-only; migrations1-66 immutable.
DO $$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_roles WHERE rolname='vanstro_p10_guard_owner') THEN RAISE EXCEPTION 'migration67 requires vanstro_p10_guard_owner'; END IF; END $$;
CREATE TABLE public.analytics_foundation_event(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),"eventName" text NOT NULL,"eventVersion" text NOT NULL,"schemaVersion" text NOT NULL,"schemaFingerprint" text NOT NULL,producer text NOT NULL,source text NOT NULL,"occurredAt" timestamptz(3) NOT NULL,"observedAt" timestamptz(3) NOT NULL,"ingestedAt" timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"subjectClass" text NOT NULL,"subjectDigest" text NOT NULL,"contextRevision" text NOT NULL,"authorizationScopeKind" text NOT NULL,"dealerIds" text[] NOT NULL,"locationIds" text[] NOT NULL,"scopeFingerprint" text NOT NULL,"fieldVisibilityFingerprint" text NOT NULL,"resourceType" text NOT NULL,"resourceId" text NOT NULL,dimensions jsonb NOT NULL,"idempotencyKeyHash" text NOT NULL,"eventIntentHash" text NOT NULL,"occurrenceIdentity" text NOT NULL,sequence integer NOT NULL,provenance text NOT NULL,"consentClass" text NOT NULL,"consentVersion" text NOT NULL,late boolean NOT NULL DEFAULT false,"expiresAt" timestamptz(3) NOT NULL,
 CONSTRAINT analytics_event_registry CHECK("eventName"='foundation.analytics.observed.v1' AND "eventVersion"='analytics-event-schema.v1' AND "schemaVersion"='analytics-event-schema.v1'),
 CONSTRAINT analytics_event_hashes CHECK("schemaFingerprint"~'^[0-9a-f]{64}$' AND "subjectDigest"~'^[0-9a-f]{64}$' AND "scopeFingerprint"~'^[0-9a-f]{64}$' AND "fieldVisibilityFingerprint"~'^[0-9a-f]{64}$' AND "idempotencyKeyHash"~'^[0-9a-f]{64}$' AND "eventIntentHash"~'^[0-9a-f]{64}$'),
 CONSTRAINT analytics_event_authority CHECK(producer='dashboard_admin' AND source='dashboard_api' AND "subjectClass"='admin_user' AND "resourceType"='foundation_sample' AND provenance='p10-owned-conformance' AND "consentClass"='analytics'),
 CONSTRAINT analytics_event_scope CHECK("authorizationScopeKind" IN('global','dealer','location') AND array_position("dealerIds",NULL) IS NULL AND array_position("locationIds",NULL) IS NULL),
 CONSTRAINT analytics_event_dimensions CHECK(jsonb_typeof(dimensions)='object' AND dimensions ? 'category' AND dimensions ? 'value' AND dimensions-(ARRAY['category','value']::text[])='{}'::jsonb AND dimensions->>'category' IN('view','engage') AND (dimensions->>'value')~'^[0-9]+$' AND (dimensions->>'value')::integer BETWEEN 0 AND 100),
 CONSTRAINT analytics_event_bounded CHECK(sequence>=0 AND sequence<=2147483647 AND char_length("resourceId") BETWEEN 1 AND 64 AND char_length("occurrenceIdentity") BETWEEN 8 AND 128 AND char_length("consentVersion") BETWEEN 1 AND 64),
 CONSTRAINT analytics_event_time CHECK("observedAt">="occurredAt"-interval '5 minutes' AND "observedAt"<="occurredAt"+interval '5 minutes' AND "expiresAt"="ingestedAt"+interval '30 days'),
 UNIQUE("eventName",producer,"subjectDigest","scopeFingerprint","resourceType","resourceId","idempotencyKeyHash")
);
CREATE INDEX analytics_event_scope_time_idx ON public.analytics_foundation_event("authorizationScopeKind","dealerIds","locationIds","ingestedAt" DESC,id DESC);
CREATE INDEX analytics_event_name_time_idx ON public.analytics_foundation_event("eventName","occurredAt",id);
CREATE INDEX analytics_event_resource_order_idx ON public.analytics_foundation_event("resourceType","resourceId",sequence,"occurredAt",id);
CREATE INDEX analytics_event_expiry_idx ON public.analytics_foundation_event("expiresAt");
REVOKE ALL ON public.analytics_foundation_event FROM PUBLIC,vanstro_runtime;
GRANT USAGE,CREATE ON SCHEMA public TO vanstro_p10_guard_owner;
GRANT SELECT,INSERT ON public.analytics_foundation_event TO vanstro_p10_guard_owner;
GRANT SELECT ON public.refresh_sessions,public.users,public.user_roles,public.roles,public.role_permissions,public.permissions,public.dealer_memberships,public.dealer_membership_roles,public.dealer_membership_locations,public.dealer_locations,public.privacy_consent_events TO vanstro_p10_guard_owner;
SET ROLE vanstro_p10_guard_owner;ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
CREATE FUNCTION public.p10_ingest_event(session_hash text,actor_id text,context_revision text,scope_kind text,dealer_ids text[],location_ids text[],scope_fingerprint text,field_fingerprint text,event_id uuid,event_name text,event_version text,schema_fingerprint text,occurred_at timestamptz,observed_at timestamptz,subject_digest text,resource_id text,dimensions jsonb,idempotency_hash text,intent_hash text,occurrence_identity text,sequence_value integer,consent_id text,consent_version text)
RETURNS TABLE(id uuid,replayed boolean,late boolean,ingested_at timestamptz)
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $fn$
DECLARE existing public.analytics_foundation_event%ROWTYPE; now_value timestamptz:=CURRENT_TIMESTAMP; authorized boolean; consent_ok boolean;
BEGIN
 IF current_user<>'vanstro_p10_guard_owner' OR current_database()!~*'(test|smoke|disposable)' OR event_name<>'foundation.analytics.observed.v1' OR event_version<>'analytics-event-schema.v1' OR schema_fingerprint!~'^[0-9a-f]{64}$' OR subject_digest!~'^[0-9a-f]{64}$' OR idempotency_hash!~'^[0-9a-f]{64}$' OR intent_hash!~'^[0-9a-f]{64}$' OR scope_kind NOT IN('global','dealer','location') OR occurred_at>now_value+interval '5 minutes' OR occurred_at<now_value-interval '30 days' OR observed_at>now_value+interval '5 minutes' THEN RAISE EXCEPTION 'P10_EVENT_INVALID'; END IF;
 SELECT EXISTS(SELECT 1 FROM refresh_sessions s JOIN users u ON u.id=s."userId" JOIN user_roles ur ON ur."userId"=u.id JOIN role_permissions rp ON rp."roleId"=ur."roleId" JOIN permissions p ON p.id=rp."permissionId" WHERE s."tokenHash"=session_hash AND s."userId"=actor_id AND s."revokedAt" IS NULL AND s."expiresAt">now_value AND u.status='active' AND p.key='analytics.events.read_summary') INTO authorized;
 SELECT EXISTS(SELECT 1 FROM privacy_consent_events c WHERE c."anonymousId"=consent_id AND c.id=(SELECT id FROM privacy_consent_events WHERE "anonymousId"=consent_id ORDER BY "createdAt" DESC LIMIT 1) AND c.preferences->>'analytics'='true') INTO consent_ok;
 IF NOT authorized OR NOT consent_ok THEN RAISE EXCEPTION 'P10_RESOURCE_UNAVAILABLE'; END IF;
 SELECT * INTO existing FROM analytics_foundation_event e WHERE e."eventName"=event_name AND e.producer='dashboard_admin' AND e."subjectDigest"=subject_digest AND e."scopeFingerprint"=scope_fingerprint AND e."resourceType"='foundation_sample' AND e."resourceId"=resource_id AND e."idempotencyKeyHash"=idempotency_hash;
 IF FOUND THEN IF existing."eventIntentHash"<>intent_hash THEN RAISE EXCEPTION 'P10_IDEMPOTENCY_CONFLICT'; END IF; RETURN QUERY SELECT existing.id,true,existing.late,existing."ingestedAt";RETURN;END IF;
 INSERT INTO analytics_foundation_event(id,"eventName","eventVersion","schemaVersion","schemaFingerprint",producer,source,"occurredAt","observedAt","ingestedAt","subjectClass","subjectDigest","contextRevision","authorizationScopeKind","dealerIds","locationIds","scopeFingerprint","fieldVisibilityFingerprint","resourceType","resourceId",dimensions,"idempotencyKeyHash","eventIntentHash","occurrenceIdentity",sequence,provenance,"consentClass","consentVersion",late,"expiresAt") VALUES(event_id,event_name,event_version,event_version,schema_fingerprint,'dashboard_admin','dashboard_api',occurred_at,observed_at,now_value,'admin_user',subject_digest,context_revision,scope_kind,dealer_ids,location_ids,scope_fingerprint,field_fingerprint,'foundation_sample',resource_id,dimensions,idempotency_hash,intent_hash,occurrence_identity,sequence_value,'p10-owned-conformance','analytics',consent_version,occurred_at<now_value-interval '1 minute',now_value+interval '30 days') RETURNING analytics_foundation_event.id, false, analytics_foundation_event.late, analytics_foundation_event."ingestedAt" INTO id,replayed,late,ingested_at;RETURN NEXT;
END $fn$;
REVOKE CREATE ON SCHEMA public FROM vanstro_p10_guard_owner;REVOKE ALL ON FUNCTION public.p10_ingest_event(text,text,text,text,text[],text[],text,text,uuid,text,text,text,timestamptz,timestamptz,text,text,jsonb,text,text,text,integer,text,text) FROM PUBLIC;GRANT EXECUTE ON FUNCTION public.p10_ingest_event(text,text,text,text,text[],text[],text,text,uuid,text,text,text,timestamptz,timestamptz,text,text,jsonb,text,text,text,integer,text,text) TO vanstro_runtime;RESET ROLE;
