import assert from "node:assert/strict";
import test from "node:test";
import { randomUUID } from "node:crypto";
import { PrismaClient, prisma } from "@vanstro/db";
import { createSession } from "../auth/session.js";
import { createApp } from "../app.js";
import { anonymousDeniedAuditContext, recordAuditEvent, recordDeniedAuditEvent, serviceAuditContext, systemAuditContext, workerAuditContext } from "./foundation.js";

const app=createApp();
const setup = new PrismaClient({ datasources: { db: { url: process.env.VANSTRO_TEST_SETUP_DATABASE_URL! } } });
async function actor(keys:string[]){const permissions=await Promise.all(keys.map(key=>setup.permission.upsert({where:{key},update:{},create:{key,description:key}})));const suffix=randomUUID(),role=await setup.role.create({data:{key:`p04-proof-${suffix}`,name:"P04 proof",rolePermissions:{create:permissions.map(permission=>({permissionId:permission.id}))}}}),user=await setup.user.create({data:{email:`p04-proof-${suffix}@example.test`,kind:"admin",status:"active",userRoles:{create:{roleId:role.id}}}}),session=await createSession(user.id);return{user,token:session.accessToken}}
function disposable(t:test.TestContext){const name=new URL(process.env.DATABASE_URL??"postgresql://localhost/unknown").pathname.slice(1).toLowerCase();if(!/(test|smoke|disposable)/.test(name)){t.skip("immutable Audit proof requires an owned disposable database");return false}return true}

test("Category proof is transaction-bound and unauthorized writes do not mutate",async(t)=>{if(!disposable(t))return;const allowed=await actor(["dashboard.access","categories.write"]),denied=await actor(["dashboard.access"]),slug=`p04-${randomUUID()}`;const created=await app.request("/api/v1/dashboard/categories",{method:"POST",headers:{authorization:`Bearer ${allowed.token}`,"content-type":"application/json","x-request-id":`req-${slug}`},body:JSON.stringify({name:"P04 Category",slug})});assert.equal(created.status,201);const category=(await created.json() as {data:{id:string}}).data;const event=await setup.auditEvent.findFirstOrThrow({where:{resourceType:"category",resourceId:category.id,action:"create"}});assert.deepEqual((event.permissionGrants as Array<{permissionKey:string}>).map(x=>x.permissionKey),["categories.write","dashboard.access"]);assert.equal((event.afterSummary as any).values.slug,slug);
 const before=await setup.category.count();const rejected=await app.request("/api/v1/dashboard/categories",{method:"POST",headers:{authorization:`Bearer ${denied.token}`,"content-type":"application/json"},body:JSON.stringify({name:"Denied",slug:`denied-${slug}`})});assert.equal(rejected.status,403);assert.equal(await setup.category.count(),before);
});

test("recorder rejects caller-asserted machine and anonymous provenance",async(t)=>{if(!disposable(t))return;const context={res:{headers:new Headers({"X-Request-Id":`req-${randomUUID()}`})}} as any;const auth={effectiveRoles:[{roleKey:"service",scope:"global" as const}],permissionGrants:[{permissionKey:"categories.write",scope:{kind:"global" as const}}],scope:{kind:"global" as const},contextRevision:"service-r1",authorizationContractVersion:"service-authorization.v1" as const};const input={action:"create" as const,resource:{type:"category" as const,id:randomUUID()},result:"succeeded" as const,requiredPermissions:["categories.write"],primaryPermission:"categories.write",afterSummary:{schemaVersion:"audit-change-summary.v1" as const,changedFields:["slug"],values:{slug:"safe"}},dedupKey:`dedup-${randomUUID()}`};await assert.rejects(()=>recordAuditEvent(context,serviceAuditContext("service-a",auth),input),/AUDIT_PERSISTED_MACHINE_AUTHORITY_REQUIRED/);await assert.rejects(()=>recordAuditEvent(context,workerAuditContext("worker-a","categories.write"),{...input,dedupKey:undefined,resource:{...input.resource,id:randomUUID()}}),/AUDIT_PERSISTED_MACHINE_AUTHORITY_REQUIRED/);await assert.rejects(()=>recordAuditEvent(context,systemAuditContext("system-a","categories.write"),{...input,dedupKey:undefined,resource:{...input.resource,id:randomUUID()}}),/AUDIT_PERSISTED_MACHINE_AUTHORITY_REQUIRED/);await assert.rejects(()=>recordDeniedAuditEvent(context,anonymousDeniedAuditContext("login"),{action:"login",resource:{type:"user"},requiredPermissions:["login"],primaryPermission:"login"}),/AUDIT_PERSISTED_MACHINE_AUTHORITY_REQUIRED/)});

test("recorder persists dual P02 permission provenance",async(t)=>{if(!disposable(t))return;const auth={actorId:randomUUID(),globalRoleKeys:["super_admin"],scopedRoleKeys:[],contextRevision:"revision",permissionGrants:[{permissionKey:"users.manage",global:true,dealerIds:[],locationIds:[]},{permissionKey:"settings.write",global:true,dealerIds:[],locationIds:[]}]};const context={res:{headers:new Headers({"X-Request-Id":`req-${randomUUID()}`})}} as any;const row=await recordAuditEvent(context,auth,{action:"create",resource:{type:"membership",id:randomUUID()},result:"succeeded",requiredPermissions:["users.manage","settings.write"],primaryPermission:"users.manage",afterSummary:{schemaVersion:"audit-change-summary.v1",changedFields:["status"],values:{status:"invited"}}},{auditEvent:setup.auditEvent} as never);assert.deepEqual((row.permissionGrants as Array<{permissionKey:string}>).map(x=>x.permissionKey),["settings.write","users.manage"])});
