"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { asyncJobDetailApiPath, asyncJobQueryHref, emptyAsyncJobQueryState, validateAsyncJobDetail, type AsyncJobItem, type AsyncJobQueryState, type LegacyJobAdapter } from "@/lib/dashboard/p05-jobs";
import { DetailDrawer, Table } from "./shared/primitives";

const statusLabels: Record<AsyncJobItem["status"], string> = { queued: "排队中", running: "运行中", succeeded: "已成功", partially_succeeded: "部分成功", failed: "失败", cancelled: "已取消" };
const actorLabels = { admin_user: "管理员", service_account: "服务账号", worker: "Worker", system: "系统" } as const;
const stageLabels: Record<string, string> = { prepare: "准备", execute: "执行", finalize: "收尾" };
const adapterLabels: Record<LegacyJobAdapter["source"], string> = { email: "邮件投递", erp: "ERP 同步", catalog: "目录同步" };
const dateTime = (value?: string) => value ? new Intl.DateTimeFormat("zh-CN", { dateStyle: "medium", timeStyle: "medium" }).format(new Date(value)) : "—";
function scopeLabel(scope: AsyncJobItem["authorizationScope"]) { return scope.kind === "global" ? "全局" : scope.kind === "dealer" ? `经销商 ${scope.dealerIds.length} 个` : `位置 ${scope.locationIds.length} 个`; }
function progressLabel(progress: AsyncJobItem["progress"]) { if (progress.kind === "current_total") return `${progress.current} / ${progress.total}`; if (progress.kind === "processed_failed") return `已处理 ${progress.processed}，失败 ${progress.failed}${progress.total === undefined ? "" : `，共 ${progress.total}`}`; return "进行中"; }
function localInput(value: string) { if (!value) return ""; const date = new Date(value); if (!Number.isFinite(date.getTime())) return ""; return new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 16); }
function toRfc3339(value: string) { if (!value) return ""; const date = new Date(value); return Number.isFinite(date.getTime()) ? date.toISOString() : ""; }

export function AsyncJobsFoundationPanel(props: { jobs: AsyncJobItem[]; adapters: LegacyJobAdapter[]; adapterState: "complete" | "partial" | "unavailable"; query: AsyncJobQueryState; state: string; capturedAt?: string; hasNext: boolean; hasPrevious: boolean; onNext: () => Promise<void>; onPrevious: () => Promise<void>; onRestart: () => Promise<void>; onNavigate: (state: AsyncJobQueryState) => void; apiFetch: <T>(path: string, init?: RequestInit) => Promise<T>; actorKey: string; sensitive: boolean }) {
  const [detail, setDetail] = useState<AsyncJobItem | null>(null), [message, setMessage] = useState("");
  const [draft, setDraft] = useState(props.query); const requestRef = useRef(0); const queryIdentity = useMemo(() => JSON.stringify(props.query), [props.query]);
  useEffect(() => { setDraft(props.query); setDetail(null); setMessage(""); requestRef.current += 1; }, [props.actorKey, queryIdentity]);
  const open = async (id: string) => { const request = ++requestRef.current; setMessage(""); try { const result = validateAsyncJobDetail(await props.apiFetch<unknown>(asyncJobDetailApiPath(id)), props.sensitive); if (request === requestRef.current) setDetail(result.data); } catch { if (request === requestRef.current) setMessage("无法读取任务详情。") } };
  const apply = () => { const createdFrom = toRfc3339(draft.createdFrom), createdTo = toRfc3339(draft.createdTo); if (Boolean(createdFrom) !== Boolean(createdTo)) { setMessage("开始和结束时间必须同时填写。"); return; } props.onNavigate({ ...draft, createdFrom, createdTo }); };
  const status = props.state === "stale" ? `显示 ${props.capturedAt ?? "未知时间"} 的缓存数据` : props.state === "partial" ? "部分任务数据不可用" : props.state === "filtered-empty" ? "筛选结果为空" : props.state === "empty" ? "暂无原生任务" : props.state === "exhausted" ? "没有更多结果" : "任务数据已载入";
  const rows = props.jobs.map(job => [job.typeLabel, statusLabels[job.status], progressLabel(job.progress), `${job.attempt} / ${job.maxAttempts}`, scopeLabel(job.authorizationScope), dateTime(job.updatedAt), <button key={job.id} onClick={() => void open(job.id)} type="button">查看</button>]);
  return <section aria-busy={props.state === "refreshing"} aria-label="异步任务基础设施"><header><h2>异步任务</h2><p>只读展示服务器任务状态、进度、执行尝试与安全摘要。</p></header>
    <form onSubmit={(event) => { event.preventDefault(); apply(); }}><fieldset><legend>筛选</legend><label>状态<select onChange={(event) => setDraft(current => ({ ...current, statuses: event.target.value ? [event.target.value as AsyncJobItem["status"]] : [] }))} value={draft.statuses[0] ?? ""}><option value="">全部</option>{Object.entries(statusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>任务类型<select onChange={(event) => setDraft(current => ({ ...current, jobTypes: event.target.value ? [event.target.value] : [] }))} value={draft.jobTypes[0] ?? ""}><option value="">全部</option><option value="foundation.probe">基础设施验证任务</option></select></label><label>创建者<select onChange={(event) => setDraft(current => ({ ...current, createdByActorType: event.target.value as AsyncJobQueryState["createdByActorType"] }))} value={draft.createdByActorType}><option value="">全部</option>{Object.entries(actorLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>开始时间<input onChange={(event) => setDraft(current => ({ ...current, createdFrom: event.target.value }))} type="datetime-local" value={localInput(draft.createdFrom)} /></label><label>结束时间<input onChange={(event) => setDraft(current => ({ ...current, createdTo: event.target.value }))} type="datetime-local" value={localInput(draft.createdTo)} /></label><label>可请求取消<select onChange={(event) => setDraft(current => ({ ...current, cancellable: event.target.value as AsyncJobQueryState["cancellable"] }))} value={draft.cancellable}><option value="">全部</option><option value="true">是</option><option value="false">否</option></select></label><label>可请求重试<select onChange={(event) => setDraft(current => ({ ...current, retryable: event.target.value as AsyncJobQueryState["retryable"] }))} value={draft.retryable}><option value="">全部</option><option value="true">是</option><option value="false">否</option></select></label><button type="submit">应用</button><button onClick={() => props.onNavigate(emptyAsyncJobQueryState())} type="button">清除</button></fieldset></form>
    <p role="status">{status}</p>{message ? <p role="alert">{message}</p> : null}<Table caption="异步任务列表" columns={["类型", "状态", "进度", "尝试", "范围", "更新时间", "详情"]} emptyMessage="暂无原生任务" rows={rows} /><div><button disabled={!props.hasPrevious} onClick={() => void props.onPrevious()} type="button">上一页</button><button disabled={!props.hasNext} onClick={() => void props.onNext()} type="button">下一页</button>{props.state === "exhausted" ? <button onClick={() => void props.onRestart()} type="button">重新开始</button> : null}</div>
    <section aria-labelledby="legacy-job-adapters"><h3 id="legacy-job-adapters">旧系统适配器</h3><p>{props.adapterState === "partial" ? "部分旧系统摘要暂时不可用。" : props.adapterState === "unavailable" ? "旧系统摘要暂时不可用。" : props.adapters.length ? "以下摘要与原生任务列表及游标完全分离。" : "当前范围没有可读取的旧系统适配器。"}</p><div>{props.adapters.map(adapter => <article key={adapter.source}><h4>{adapterLabels[adapter.source]}</h4><p>{adapter.status === "ready" ? "只读摘要" : "不可用"}</p><dl><div><dt>最早排队</dt><dd>{dateTime(adapter.oldestQueuedAt)}</dd></div><div><dt>最近更新</dt><dd>{dateTime(adapter.latestUpdatedAt)}</dd></div>{Object.entries(adapter.counts).map(([key, value]) => <div key={key}><dt>{statusLabels[key as AsyncJobItem["status"]]}</dt><dd>{value}</dd></div>)}</dl></article>)}</div></section>
    <DetailDrawer closeLabel="关闭任务详情" onClose={() => { requestRef.current += 1; setDetail(null); }} open={Boolean(detail)} title="任务详情">{detail ? <><dl><div><dt>任务 ID</dt><dd>{detail.id}</dd></div><div><dt>类型</dt><dd>{detail.typeLabel}</dd></div><div><dt>状态</dt><dd>{statusLabels[detail.status]}</dd></div><div><dt>进度</dt><dd>{progressLabel(detail.progress)} · {stageLabels[detail.progress.stage] ?? detail.progress.stage}</dd></div><div><dt>尝试</dt><dd>{detail.attempt} / {detail.maxAttempts}</dd></div><div><dt>创建者</dt><dd>{actorLabels[detail.createdBy.actorType]}{detail.createdBy.actorId ? ` · ${detail.createdBy.actorId}` : ""}</dd></div><div><dt>授权范围</dt><dd>{scopeLabel(detail.authorizationScope)}</dd></div><div><dt>创建时间</dt><dd>{dateTime(detail.createdAt)}</dd></div><div><dt>开始时间</dt><dd>{dateTime(detail.startedAt)}</dd></div><div><dt>结束时间</dt><dd>{dateTime(detail.finishedAt)}</dd></div><div><dt>取消请求</dt><dd>{detail.cancellationRequestedAt ? `已于 ${dateTime(detail.cancellationRequestedAt)} 请求，等待 Worker 确认` : "未请求"}</dd></div><div><dt>可请求取消</dt><dd>{detail.cancellable ? "是（仅能力指示）" : "否"}</dd></div><div><dt>可请求重试</dt><dd>{detail.retryable ? "是（仅能力指示）" : "否"}</dd></div><div><dt>请求 ID</dt><dd>{detail.requestId}</dd></div></dl>{detail.resultSummary ? <section><h4>结果摘要</h4><dl>{Object.entries(detail.resultSummary.entries).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{String(value)}</dd></div>)}</dl></section> : null}{detail.errorSummary ? <section><h4>错误摘要</h4><p>{detail.errorSummary.code} · {detail.errorSummary.failureClass}</p><dl>{Object.entries(detail.errorSummary.entries).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{String(value)}</dd></div>)}</dl></section> : null}<section><h4>产物元数据</h4>{detail.artifacts.length ? <ul>{detail.artifacts.map(artifact => <li key={artifact.id}><strong>{artifact.displayName}</strong><span>{artifact.contentType} · {artifact.byteCount} 字节 · {artifact.available ? "可用元数据" : artifact.deletedAt ? "已删除" : "已过期"}</span></li>)}</ul> : <p>无产物元数据。</p>}</section></> : null}</DetailDrawer>
  </section>;
}
export function navigateAsyncJobState(pathname: string, state: AsyncJobQueryState) { const parsed = asyncJobQueryHref(pathname, state); if (parsed.kind !== "valid") return; window.history.pushState(window.history.state, "", parsed.canonicalHref); window.dispatchEvent(new PopStateEvent("popstate")); }
