"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { auditDetailApiPath, auditQueryHref, validateAuditDetail, type AuditEventItem, type AuditQueryState } from "@/lib/dashboard/p04-audit";
import { DetailDrawer, Table } from "./shared/primitives";

type Props={events:AuditEventItem[];query:AuditQueryState;state:string;capturedAt?:string;hasNext:boolean;hasPrevious:boolean;onNext:()=>Promise<void>;onPrevious:()=>Promise<void>;onRestart:()=>Promise<void>;onNavigate:(state:AuditQueryState)=>void;apiFetch:<T>(path:string,init?:RequestInit)=>Promise<T>;actorKey:string;sensitive:boolean};
const actorLabel=(type:string)=>({admin_user:"管理员",dealer_user:"经销商用户",customer:"客户",service_account:"服务账号",worker:"Worker",system:"系统",anonymous:"匿名"}[type]??"未知");
const actionLabel=(value:string)=>({create:"创建",update:"更新",archive:"归档",restore:"恢复",delete:"删除",publish:"发布",approve:"批准",reject:"拒绝",assign:"分配",retry:"重试",login:"登录",logout:"登出",session_revoke:"撤销会话",permission_grant:"授予权限",permission_revoke:"撤销权限",config_publish:"发布配置",read_sensitive:"读取敏感字段"}[value]??value);
const resourceLabel=(value:string)=>({user:"用户",role:"角色",permission:"权限",dealer:"经销商",dealer_location:"经销商位置",membership:"成员关系",product:"产品",category:"分类",inventory:"库存",order:"订单",payment_session:"支付会话",refund:"退款",customer:"客户",content:"内容",audit_event:"审计事件"}[value]??value);
const resultLabel=(value:string)=>({succeeded:"成功",failed:"失败",denied:"拒绝",partially_succeeded:"部分成功",cancelled:"已取消"}[value]??value);
const reasonLabel=(value:string)=>({completed:"完成",validation_rejected:"校验拒绝",permission_required:"需要权限",scope_mismatch:"范围不匹配",field_permission_required:"需要字段权限",resource_not_available:"资源不可用",state_conflict:"状态冲突",idempotent_replay:"幂等重放",idempotency_conflict:"幂等冲突",transaction_rolled_back:"事务已回滚",dependency_unavailable:"依赖不可用",internal_failure:"内部失败",operator_requested:"操作员请求"}[value]??value);
const sourceLabel=(value:string)=>({dashboard_api:"管理后台 API",public_api:"公共 API",worker:"Worker",service_api:"服务 API",system:"系统"}[value]??value);
const metadataLabel=(value:string)=>({roleCount:"角色数量",locationCount:"位置数量",dealerId:"经销商 ID",status:"状态",isActive:"是否启用",sortOrder:"排序"}[value]??value);
function scopeLabel(scope:AuditEventItem["authorization"]["scope"]){switch(scope.kind){case"global":return"全局";case"none":return"无授权范围";case"dealer":return`经销商 ${scope.dealerIds.length} 个`;case"location":return`位置 ${scope.locationIds.length} 个`;}}
function localInput(value:string){if(!value)return"";const date=new Date(value);if(!Number.isFinite(date.getTime()))return"";const local=new Date(date.getTime()-date.getTimezoneOffset()*60000);return local.toISOString().slice(0,16)}
function toRfc3339(value:string){if(!value)return"";const date=new Date(value);return Number.isFinite(date.getTime())?date.toISOString():""}
export function AuditFoundationPanel(props:Props){
 const[detail,setDetail]=useState<AuditEventItem|null>(null),[detailError,setDetailError]=useState("");
 const[draft,setDraft]=useState(props.query);const requestRef=useRef(0);const queryIdentity=useMemo(()=>JSON.stringify(props.query),[props.query]);
 useEffect(()=>{setDraft(props.query);setDetail(null);setDetailError("");requestRef.current+=1},[props.actorKey,queryIdentity]);
 const open=async(id:string)=>{const request=++requestRef.current;setDetailError("");try{const response=validateAuditDetail(await props.apiFetch<unknown>(auditDetailApiPath(id)),props.sensitive);if(request===requestRef.current)setDetail(response.data)}catch{if(request===requestRef.current)setDetailError("无法读取审计详情。")}};
 const apply=()=>{const occurredFrom=toRfc3339(draft.occurredFrom),occurredTo=toRfc3339(draft.occurredTo);if(Boolean(occurredFrom)!==Boolean(occurredTo)){setDetailError("开始和结束时间必须同时填写。");return}props.onNavigate({...draft,occurredFrom,occurredTo})};
 const clear=()=>props.onNavigate({resource:"auditLogs",occurredFrom:"",occurredTo:"",actorType:"",actions:[],resourceTypes:[],results:[],resourceId:"",requestId:"",sources:[],sensitive:""});
 const status=props.state==="stale"?`显示 ${props.capturedAt??"未知时间"} 的缓存数据`:props.state==="partial"?"部分数据不可用":props.state==="filtered-empty"?"筛选结果为空":props.state==="empty"?"暂无审计事件":props.state==="exhausted"?"没有更多结果":"审计数据已载入";
 const rows=props.events.map(event=>[new Intl.DateTimeFormat("zh-CN",{dateStyle:"medium",timeStyle:"medium"}).format(new Date(event.occurredAt)),actorLabel(event.actor.type),actionLabel(event.action),resourceLabel(event.resource.type),resultLabel(event.result),event.requestId,scopeLabel(event.authorization.scope),<button key={event.id} onClick={()=>void open(event.id)} type="button">查看</button>]);
 return <section aria-busy={props.state==="refreshing"} aria-label="审计事件"><header><h2>审计事件</h2><p>只读展示服务器记录的操作、授权范围与安全摘要。</p></header>
 <form onSubmit={event=>{event.preventDefault();apply()}}><fieldset><legend>筛选</legend><label>开始时间<input onChange={e=>setDraft(current=>({...current,occurredFrom:e.target.value}))} type="datetime-local" value={localInput(draft.occurredFrom)} /></label><label>结束时间<input onChange={e=>setDraft(current=>({...current,occurredTo:e.target.value}))} type="datetime-local" value={localInput(draft.occurredTo)} /></label><label>Actor 类型<select onChange={e=>setDraft(current=>({...current,actorType:e.target.value as AuditQueryState["actorType"]}))} value={draft.actorType}><option value="">全部</option><option value="admin_user">管理员</option><option value="service_account">服务账号</option><option value="worker">Worker</option><option value="system">系统</option><option value="anonymous">匿名</option></select></label><label>操作<select onChange={e=>setDraft(current=>({...current,actions:e.target.value?[e.target.value as AuditQueryState["actions"][number]]:[]}))} value={draft.actions[0]??""}><option value="">全部</option><option value="create">创建</option><option value="update">更新</option><option value="archive">归档</option><option value="permission_grant">授予权限</option><option value="permission_revoke">撤销权限</option><option value="read_sensitive">读取敏感字段</option></select></label><label>资源<select onChange={e=>setDraft(current=>({...current,resourceTypes:e.target.value?[e.target.value as AuditQueryState["resourceTypes"][number]]:[]}))} value={draft.resourceTypes[0]??""}><option value="">全部</option><option value="user">用户</option><option value="membership">成员关系</option><option value="category">分类</option><option value="product">产品</option><option value="audit_event">审计事件</option></select></label><label>结果<select onChange={e=>setDraft(current=>({...current,results:e.target.value?[e.target.value as AuditQueryState["results"][number]]:[]}))} value={draft.results[0]??""}><option value="">全部</option><option value="succeeded">成功</option><option value="failed">失败</option><option value="denied">拒绝</option><option value="cancelled">取消</option></select></label><label>请求 ID<input maxLength={128} onChange={e=>setDraft(current=>({...current,requestId:e.target.value}))} value={draft.requestId} /></label>{props.sensitive?<label><input checked={draft.sensitive==="true"} onChange={e=>setDraft(current=>({...current,sensitive:e.target.checked?"true":""}))} type="checkbox" />仅敏感事件</label>:draft.sensitive==="true"?<p role="status">仅筛选敏感标记；敏感字段仍已隐藏。</p>:null}<button type="submit">应用</button><button onClick={clear} type="button">清除</button></fieldset></form>
 <p role="status">{status}</p>{detailError?<p role="alert">{detailError}</p>:null}<Table caption="审计事件列表" columns={["时间","Actor","操作","资源","结果","请求 ID","范围","详情"]} emptyMessage="暂无审计事件" rows={rows} /><div><button disabled={!props.hasPrevious} onClick={()=>void props.onPrevious()} type="button">上一页</button><button disabled={!props.hasNext} onClick={()=>void props.onNext()} type="button">下一页</button>{props.state==="exhausted"?<button onClick={()=>void props.onRestart()} type="button">重新开始</button>:null}</div>
 <DetailDrawer closeLabel="关闭审计详情" onClose={()=>{requestRef.current+=1;setDetail(null)}} open={Boolean(detail)} title="审计详情">{detail?<><dl><div><dt>事件 ID</dt><dd>{detail.id}</dd></div><div><dt>时间</dt><dd>{detail.occurredAt}</dd></div><div><dt>Actor</dt><dd>{actorLabel(detail.actor.type)}</dd></div><div><dt>操作</dt><dd>{actionLabel(detail.action)}</dd></div><div><dt>资源</dt><dd>{resourceLabel(detail.resource.type)}</dd></div><div><dt>结果</dt><dd>{resultLabel(detail.result)}</dd></div><div><dt>原因</dt><dd>{detail.reason?reasonLabel(detail.reason):"无"}</dd></div><div><dt>来源</dt><dd>{sourceLabel(detail.source)}</dd></div><div><dt>所需权限</dt><dd>{detail.authorization.permissionGrants.map((grant)=>grant.permissionKey).join("、")}</dd></div><div><dt>请求 ID</dt><dd>{detail.requestId}</dd></div><div><dt>授权范围</dt><dd>{scopeLabel(detail.authorization.scope)}</dd></div><div><dt>变更字段</dt><dd>{detail.changeSummary?.changedFields.join("、")||"无"}</dd></div><div><dt>已脱敏字段</dt><dd>{detail.changeSummary?.redactedFields.join("、")||"无"}</dd></div></dl>{detail.metadata?<dl>{Object.entries(detail.metadata.entries).map(([key,value])=><div key={key}><dt>{metadataLabel(key)}</dt><dd>{String(value)}</dd></div>)}</dl>:null}</>:null}</DetailDrawer></section>
}
export function navigateAuditState(pathname:string,state:AuditQueryState){const parsed=auditQueryHref(pathname,state);if(parsed.kind!=="valid")return;window.history.pushState(window.history.state,"",parsed.canonicalHref);window.dispatchEvent(new PopStateEvent("popstate"))}
