"use client";
import { useCallback,useEffect,useState } from "react";
import { Button } from "@/components/ui/button";
import { StatusMessage,StatusMessageContent,StatusMessageTitle } from "@/components/ui/status-message";
import { API_ENDPOINTS,COMMERCE_SETTINGS_DESCRIPTOR_KEY,type CommerceSettingsValueV1,type S03Draft,type S03HistoryEntry,type S03ImpactPreviewResult,type S03Overview,type S03Publication,type S03Readiness,type S03SafeDiff,type S03ValidationResult,type SettingsCenterCapability } from "@/lib/api/api-contract";
import { arrayOf,validateApiResult,validateS03Draft,validateS03HistoryEntry,validateS03ImpactPreviewResult,validateS03Overview,validateS03Publication,validateS03Readiness,validateS03SafeDiff,validateS03ValidationResult,type RuntimeValidator } from "@/lib/api/runtime-validation";
import { DASHBOARD_API_BASE_URL } from "@/lib/dashboard/api";
import { authorizeS03Operation } from "@/lib/dashboard/s03-settings-transport";
import { bindCreatedS03Draft,bindPublishedS03,bindRollbackS03Draft,bindS03Diff,bindS03Readiness,bindS03Validation,bindUpdatedS03Draft,isStructurallyValidS03Value,isValidS03Reason,S03_COMPILED_VALUE,type S03Location } from "@/lib/dashboard/s03-settings";
import type { SiteLocale } from "@/lib/i18n/locale";
import styles from "./CommerceSettingsPanel.module.css";

type Props={actorKey:string;capability:SettingsCenterCapability;location:Extract<S03Location,{kind:"valid"}>;locale:SiteLocale;apiRequest:(path:string,init?:RequestInit)=>Promise<Response>;onUnauthorized:()=>void};
type LoadState="loading"|"ready"|"empty"|"forbidden"|"error";
const labels:Record<string,string>={implemented_ready:"已实现且就绪",implemented_degraded:"已实现但降级",future_obligation:"未来义务",ready:"就绪",degraded:"降级",draft:"草稿",validated:"已验证",invalid:"验证未通过",published:"已发布",superseded:"已取代",rolled_back:"已回滚",activation_failed:"激活失败"};
const consumerLabels:Record<string,string>={"checkout-availability":"结账可用性","checkout-guest-minimum":"访客与最低订单额","tax-totals":"税额合计","shipping-fee-service-zone":"配送费与服务区","inventory-ttl-stale":"库存预留与陈旧策略","order-transitions":"订单状态转换"};
const clone=(value:CommerceSettingsValueV1)=>JSON.parse(JSON.stringify(value)) as CommerceSettingsValueV1;
const key=(action:string)=>`settings-s03-${action}-${Date.now()}-${Math.random().toString(16).slice(2)}`;
const money=(cents:number)=>new Intl.NumberFormat("zh-CN",{style:"currency",currency:"CAD"}).format(cents/100);

export function CommerceSettingsPanel({actorKey,capability,location,apiRequest,onUnauthorized}:Props){
 // The dashboard shell transport is intentionally read-only (GET/HEAD). S03
 // lifecycle writes (create/update/validate/publish/rollback) go directly to
 // the settings API base with the same credentials; reads keep the shell
 // transport so the read-only preview contract is preserved.
 const writeRequest=async(path:string,init?:RequestInit):Promise<Response>=>{const method=init?.method??"GET";if(method==="GET"||method==="HEAD")return apiRequest(path,init);return fetch(`${DASHBOARD_API_BASE_URL}${path}`,{...init,credentials:"include",cache:"no-store",redirect:"error"});};
 const getData=async <T,>(path:string,validator:RuntimeValidator<T>,init?:RequestInit):Promise<T>=>{const response=await writeRequest(path,init);if(!response.ok)throw new Error(`请求失败：HTTP ${response.status}`);return validateApiResult(await response.json(),validator).data;};
 const[loadState,setLoadState]=useState<LoadState>("loading"),[overview,setOverview]=useState<S03Overview|null>(null),[draft,setDraft]=useState<S03Draft|null>(null),[form,setForm]=useState(()=>clone(S03_COMPILED_VALUE)),[reason,setReason]=useState(""),[validation,setValidation]=useState<S03ValidationResult|null>(null),[diff,setDiff]=useState<S03SafeDiff|null>(null),[preview,setPreview]=useState<S03ImpactPreviewResult|null>(null),[readiness,setReadiness]=useState<S03Readiness|null>(null),[history,setHistory]=useState<S03HistoryEntry[]>([]),[busy,setBusy]=useState(""),[message,setMessage]=useState(""),[error,setError]=useState("");
 const load=useCallback(async()=>{setLoadState("loading");setError("");try{const[o,d,r,h]=await Promise.all([getData(API_ENDPOINTS.dashboardS03SettingsOverview,validateS03Overview),getData(API_ENDPOINTS.dashboardS03SettingsDrafts,arrayOf(validateS03Draft)),getData(API_ENDPOINTS.dashboardS03SettingsReadiness,validateS03Readiness),getData(API_ENDPOINTS.dashboardS03SettingsHistory,arrayOf(validateS03HistoryEntry))]);setOverview(o);setReadiness(bindS03Readiness(r));setHistory(h);const open=d[0]??null;setDraft(open);setForm(clone(open?.value??o.effective));setReason(open?.changeReason??"");setLoadState(o?"ready":"empty");}catch(e){const text=e instanceof Error?e.message:"载入失败";if(/401|403|forbidden/i.test(text)){setLoadState("forbidden");onUnauthorized();}else{setError(text);setLoadState("error");}}},[apiRequest,onUnauthorized]);
 useEffect(()=>{void load();},[load,location.canonicalHref,actorKey]);
 const execute=async<T,>(name:string,path:string,validator:RuntimeValidator<T>,init:RequestInit)=>{setBusy(name);setError("");setMessage("");try{return await getData(path,validator,init);}catch(e){setError(e instanceof Error?e.message:"操作失败");return null;}finally{setBusy("");}};
 const operation=(input:Parameters<typeof authorizeS03Operation>[0])=>authorizeS03Operation(input);
 const shared={actorKey,expectedActorKey:actorKey,capability};
 const save=async()=>{if(!isStructurallyValidS03Value(form)||!isValidS03Reason(reason)){setError("请修正五个策略族的字段，并填写 8–500 字变更原因。");return;}if(draft){const req=operation({...shared,kind:"updateDraft",draftId:draft.id,status:draft.status,input:{expectedVersion:draft.version,value:form,changeReason:reason,idempotencyKey:key("update")}});const next=await execute("save",req.path,validateS03Draft,req.init);if(next){setDraft(bindUpdatedS03Draft(next,draft,form,reason));setValidation(null);setDiff(null);setMessage("草稿已保存。");}}else{const req=operation({...shared,kind:"createDraft",input:{descriptorKey:COMMERCE_SETTINGS_DESCRIPTOR_KEY,expectedPublishedVersion:overview?.publication?.cas??0,value:form,changeReason:reason,idempotencyKey:key("create")}});const next=await execute("save",req.path,validateS03Draft,req.init);if(next){setDraft(bindCreatedS03Draft(next,{expectedPublishedVersion:overview?.publication?.cas??0,value:form,changeReason:reason}));setMessage("草稿已创建。");}}};
 const validate=async()=>{if(!draft)return;const req=operation({...shared,kind:"validateDraft",draftId:draft.id,status:draft.status,input:{expectedVersion:draft.version,idempotencyKey:key("validate")}});const result=await execute("validate",req.path,validateS03ValidationResult,req.init);if(!result)return;const bound=bindS03Validation(result,draft.id,draft.version,draft.status);setValidation(bound);setDraft({...draft,status:bound.status,version:bound.draftVersion,validationRevision:bound.validationRevision});if(bound.status==="validated"){const safe=await getData(API_ENDPOINTS.dashboardS03SettingsDraftDiff(draft.id),validateS03SafeDiff);setDiff(bindS03Diff(safe,bound));}setMessage(bound.status==="validated"?"验证通过，可检查差异后发布。":"验证未通过。");};
 const impact=async()=>{const req=operation({...shared,kind:"impactPreview",input:{candidate:form}});const result=await execute("preview",req.path,validateS03ImpactPreviewResult,req.init);if(result){setPreview(result);setMessage("只读影响预览已更新；未创建订单、支付或库存预留。");}};
 const publish=async()=>{if(!draft||draft.status!=="validated"||!diff)return;const req=operation({...shared,kind:"publishDraft",draftId:draft.id,status:draft.status,input:{expectedVersion:draft.version,idempotencyKey:key("publish")}});const result=await execute("publish",req.path,validateS03Publication,req.init);if(result){bindPublishedS03(result,draft.id,draft.version);setMessage("策略已发布；发布本身没有执行业务动作。");await load();}};
 const rollback=async(target:S03HistoryEntry)=>{if(!overview?.publication)return;const req=operation({...shared,kind:"createRollbackDraft",publicationId:target.publicationId,sourceStatus:target.status,input:{expectedPublishedVersion:overview.publication.cas ?? 0,changeReason:`回滚到发布版本 ${target.version}`,idempotencyKey:key("rollback")}});const result=await execute("rollback",req.path,validateS03Draft,req.init);if(result){setDraft(bindRollbackS03Draft(result,target,overview.publication.cas ?? 0));setForm(clone(result.value));setReason(result.changeReason);setMessage("已创建回滚草稿；不会反转订单、支付、税务、运输或库存业务事实。");}};
 const update=<K extends keyof CommerceSettingsValueV1>(family:K,patch:Partial<CommerceSettingsValueV1[K]>)=>setForm(current=>({...current,[family]:{...current[family],...patch}}));
 if(loadState==="loading")return <section aria-busy="true" aria-label="Commerce 设置" className={styles.panel} role="status"><h2>正在载入 Commerce 设置</h2><div className={styles.skeleton}/><div className={styles.skeleton}/></section>;
 if(loadState==="forbidden")return <section aria-label="Commerce 设置" className={styles.panel} role="alert"><h2>没有 Commerce 设置读取权限</h2><p>请联系管理员确认 settings.read。</p></section>;
 if(loadState==="error")return <section aria-label="Commerce 设置" className={styles.panel} role="alert"><h2>Commerce 设置暂时无法载入</h2><p>{error}</p><Button onClick={()=>void load()}>重试</Button></section>;
 return <section aria-label="Commerce 设置" className={styles.panel}>
  <header className={styles.header}><div><h2>Commerce 设置</h2><p>统一管理结账、税务、配送、库存与订单策略。当前生效值来自{overview?.projectionState==="compiled_default"?"编译默认值":"已发布版本"}。</p></div><span className={styles.badge}>{readiness?labels[readiness.state]:"未知"}</span></header>
  {message?<StatusMessage role="status"><StatusMessageTitle>状态更新</StatusMessageTitle><StatusMessageContent>{message}</StatusMessageContent></StatusMessage>:null}{error?<StatusMessage role="alert" variant="error"><StatusMessageTitle>操作未完成</StatusMessageTitle><StatusMessageContent>{error}</StatusMessageContent></StatusMessage>:null}
  <div className={styles.summary}><div><span>描述符</span><strong>settings.commerce</strong></div><div><span>当前发布</span><strong>{overview?.publication?`v${overview.publication.version}`:"默认值"}</strong></div><div><span>生效 generation</span><strong>{overview?.publishedGeneration??0}</strong></div><div><span>开放草稿</span><strong>{draft?`${labels[draft.status]??draft.status} · v${draft.version}`:"无"}</strong></div></div>
  <form className={styles.form} onSubmit={e=>{e.preventDefault();void save();}}>
   <fieldset><legend>结账策略</legend><label>最低订单金额（CAD 分）<input min="0" onChange={e=>update("commercePolicy",{minimumOrderAmountCents:Number(e.target.value)})} type="number" value={form.commercePolicy.minimumOrderAmountCents}/><small>{money(form.commercePolicy.minimumOrderAmountCents)}</small></label><label className={styles.check}><input checked={form.commercePolicy.checkoutEnabled} onChange={e=>update("commercePolicy",{checkoutEnabled:e.target.checked})} type="checkbox"/>启用结账</label><label className={styles.check}><input checked={form.commercePolicy.guestCheckoutEnabled} onChange={e=>update("commercePolicy",{guestCheckoutEnabled:e.target.checked})} type="checkbox"/>允许访客结账</label></fieldset>
   <fieldset><legend>税务策略</legend><label>启用省码（逗号分隔）<input onChange={e=>update("taxPolicy",{enabledProvinceCodes:e.target.value.split(",").map(x=>x.trim().toUpperCase()).filter(Boolean)})} value={form.taxPolicy.enabledProvinceCodes.join(", ")}/></label><label>计算模式<select onChange={e=>update("taxPolicy",{calculationMode:e.target.value as CommerceSettingsValueV1["taxPolicy"]["calculationMode"]})} value={form.taxPolicy.calculationMode}><option value="current-tax-rate-table">当前税率表</option><option value="disabled">禁用</option></select></label><p>舍入模式：最近分（固定）</p></fieldset>
   <fieldset><legend>配送策略</legend><label className={styles.check}><input checked={form.shippingPolicy.pickupEnabled} onChange={e=>update("shippingPolicy",{pickupEnabled:e.target.checked})} type="checkbox"/>允许自取</label><label className={styles.check}><input checked={form.shippingPolicy.deliveryEnabled} onChange={e=>update("shippingPolicy",{deliveryEnabled:e.target.checked})} type="checkbox"/>允许配送</label><label>配送固定费（CAD 分）<input min="0" onChange={e=>update("shippingPolicy",{deliveryFlatFeeCents:Number(e.target.value)})} type="number" value={form.shippingPolicy.deliveryFlatFeeCents}/></label><label>服务区<select onChange={e=>update("shippingPolicy",{serviceZoneMode:e.target.value as CommerceSettingsValueV1["shippingPolicy"]["serviceZoneMode"]})} value={form.shippingPolicy.serviceZoneMode}><option value="dealer-location-only">经销商位置</option><option value="postal-prefix">邮编前缀</option></select></label><label>回退<select onChange={e=>update("shippingPolicy",{fallbackMode:e.target.value as CommerceSettingsValueV1["shippingPolicy"]["fallbackMode"]})} value={form.shippingPolicy.fallbackMode}><option value="reject">拒绝</option><option value="pickup-only">仅自取</option></select></label></fieldset>
   <fieldset><legend>库存策略</legend><label className={styles.check}><input checked={form.inventoryPolicy.reservationEnabled} onChange={e=>update("inventoryPolicy",{reservationEnabled:e.target.checked})} type="checkbox"/>启用预留策略读取</label><label>预留 TTL（分钟）<input max="1440" min="5" onChange={e=>update("inventoryPolicy",{reservationTtlMinutes:Number(e.target.value)})} type="number" value={form.inventoryPolicy.reservationTtlMinutes}/></label><label>可用性<select onChange={e=>update("inventoryPolicy",{availabilityMode:e.target.value as "manual"|"erp"})} value={form.inventoryPolicy.availabilityMode}><option value="manual">手动</option><option value="erp">ERP</option></select></label><label>陈旧阈值（秒）<input max="86400" min="30" onChange={e=>update("inventoryPolicy",{staleAfterSeconds:Number(e.target.value)})} type="number" value={form.inventoryPolicy.staleAfterSeconds}/></label><label>陈旧处理<select onChange={e=>update("inventoryPolicy",{staleBehavior:e.target.value as CommerceSettingsValueV1["inventoryPolicy"]["staleBehavior"]})} value={form.inventoryPolicy.staleBehavior}><option value="degraded-reject">降级拒绝</option><option value="manual-fallback">手动回退</option></select></label></fieldset>
   <fieldset><legend>订单策略</legend><label className={styles.check}><input checked={form.orderPolicy.guestLookupEnabled} onChange={e=>update("orderPolicy",{guestLookupEnabled:e.target.checked})} type="checkbox"/>允许访客查询</label><label>取消模式<select onChange={e=>update("orderPolicy",{cancellationMode:e.target.value as CommerceSettingsValueV1["orderPolicy"]["cancellationMode"]})} value={form.orderPolicy.cancellationMode}><option value="erp-confirmed-only">仅 ERP 确认</option><option value="disabled">禁用</option></select></label><div className={styles.transitionList}>{Object.entries(form.orderPolicy.allowedLifecycleTransitions).map(([from,to])=><p key={from}><strong>{from}</strong> → {to.length?to.join("、"):"终态"}</p>)}</div></fieldset>
   <label className={styles.reason}>变更原因<textarea maxLength={500} onChange={e=>setReason(e.target.value)} value={reason}/><small>8–500 字；写入安全审计元数据。</small></label>
   <div className={styles.actions}><Button disabled={busy!==""||!capability.actions.createDraft} type="submit">{busy==="save"?"保存中…":draft?"保存草稿":"创建草稿"}</Button><Button disabled={!draft||busy!==""||!capability.actions.validate} onClick={()=>void validate()} type="button" variant="secondary">验证</Button><Button disabled={busy!==""} onClick={()=>void impact()} type="button" variant="secondary">只读影响预览</Button><Button disabled={!draft||draft.status!=="validated"||!diff||busy!==""||!capability.actions.publish} onClick={()=>void publish()} type="button">发布</Button></div>
  </form>
  <section className={styles.section}><h3>验证与安全差异</h3>{validation?<ul>{validation.issues.map((x,i)=><li key={`${x.code}-${i}`}><strong>{x.severity}</strong> · {x.field}：{x.message}</li>)}</ul>:<p>尚未验证当前草稿。</p>}{diff?<table><caption>公开字段安全差异</caption><thead><tr><th>字段</th><th>之前</th><th>之后</th></tr></thead><tbody>{diff.changes.map(x=><tr key={x.field}><th scope="row">{x.field}</th><td>{JSON.stringify(x.before)}</td><td>{JSON.stringify(x.after)}</td></tr>)}</tbody></table>:null}</section>
  <section className={styles.section}><h3>只读 quote 影响预览</h3><p>聚合结果，不包含 PII、支付材料、库存明细或 ERP 凭据，也不会调用真实 provider。</p>{preview?<dl className={styles.preview}><div><dt>候选可接受</dt><dd>{preview.candidateAccepted?"是":"否"}</dd></div><div><dt>结账 / 访客</dt><dd>{preview.quoteImpact.checkoutAvailable?"可用":"关闭"} / {preview.quoteImpact.guestCheckoutAvailable?"可用":"关闭"}</dd></div><div><dt>税务</dt><dd>{preview.quoteImpact.taxMode} · {preview.quoteImpact.enabledProvinceCount} 省区</dd></div><div><dt>配送</dt><dd>{preview.quoteImpact.deliveryAvailable?money(preview.quoteImpact.deliveryFlatFeeCents):"关闭"}</dd></div><div><dt>库存</dt><dd>{preview.quoteImpact.inventoryMode} · TTL {preview.quoteImpact.reservationTtlMinutes} 分钟</dd></div><div><dt>订单转换规则</dt><dd>{preview.quoteImpact.orderTransitionRuleCount}</dd></div></dl>:<p>运行预览后显示聚合 quote 变化。</p>}</section>
  <section className={styles.section}><h3>Consumer readiness</h3><p>只有 implemented_ready 且 generation 精确匹配才计为完成。</p><table><thead><tr><th>Consumer</th><th>状态</th><th>Generation</th><th>原因</th></tr></thead><tbody>{(readiness?.consumers??overview?.consumerMatrix??[]).map(c=><tr key={c.id}><th scope="row">{consumerLabels[c.id]}</th><td><span className={c.state==="implemented_ready"?styles.ready:styles.degraded}>{labels[c.state]}</span></td><td>{c.generation??"—"}</td><td>{c.reasonCode??"—"}</td></tr>)}</tbody></table></section>
  <section className={styles.section}><h3>发布历史与回滚</h3>{history.length?<ul className={styles.history}>{history.map(item=><li key={item.publicationId}><div><strong>v{item.version} · {labels[item.status]??item.status}</strong><span>{new Date(item.publishedAt).toLocaleString("zh-CN")}</span><p>{item.changeReason}</p></div><Button disabled={busy!==""||!capability.actions.rollback||!["published","superseded"].includes(item.status)} onClick={()=>void rollback(item)} size="sm" variant="secondary">创建回滚草稿</Button></li>)}</ul>:<p>尚无发布历史。首次发布后可从这里创建回滚草稿。</p>}</section>
 </section>;
}
