"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useModalFocus } from "@/lib/accessibility/useModalFocus";
import type { DashboardAuthorization } from "@/lib/api/api-contract";
import { dataJobsHref, detailApiPath, isDataJobFresh, listApiPath, previewApiPath, validateExportDetail, validateExportList, validateImportDetail, validateImportList, validatePreview, validateUploadIntent, type DataJobsLocation, type ExportRequest, type ImportBatch, type ImportPreviewRow } from "@/lib/dashboard/p08-data-jobs";
import type { DataJobOperation } from "@/lib/dashboard/p08-data-jobs-transport";
import styles from "./MediaFoundationPanel.module.css";

type Props = { actorKey: string; apiRequest: (path: string, init?: RequestInit) => Promise<Response>; dataJobRequest: (operation: DataJobOperation) => Promise<{ response: Response; responseKind: "json" | "bytes"; payload: unknown }>; authorization: DashboardAuthorization; location: Extract<DataJobsLocation, { kind: "valid" }>; onUnauthorized: () => void };
const labels = { awaiting_upload: "等待上传", uploaded: "已上传", parsing: "解析中", preview_ready: "预览就绪", preview_failed: "预览失败", commit_queued: "等待提交", committing: "提交中", completed: "已完成", completed_with_errors: "部分完成", failed: "失败", cancelled: "已取消", expired: "已过期", queued: "已排队", running: "运行中" } as Record<string, string>;
const idempotency = () => crypto.randomUUID();

export function DataJobsFoundationPanel({ actorKey, apiRequest, dataJobRequest, authorization, location, onUnauthorized }: Props) {
  const [imports, setImports] = useState<ImportBatch[]>([]), [exports, setExports] = useState<ExportRequest[]>([]), [preview, setPreview] = useState<{ rows: ImportPreviewRow[]; summary: ImportBatch["summary"]; version: number } | null>(null);
  const [selectedImport, setSelectedImport] = useState<ImportBatch | null>(null), [selectedExport, setSelectedExport] = useState<ExportRequest | null>(null), [status, setStatus] = useState("loading"), [message, setMessage] = useState(""), [file, setFile] = useState<File | null>(null), [commitOpen, setCommitOpen] = useState(false), [commitError, setCommitError] = useState(""), [, setCursorRevision] = useState(0);
  const actor = `${authorization.actor.id}:${authorization.contextRevision}`, selectedFile = useRef<HTMLInputElement>(null), commitDialog = useRef<HTMLDivElement>(null), commitTrigger = useRef<HTMLButtonElement>(null);
  const actorIdentity = useRef(actorKey), listGeneration = useRef(0), detailGeneration = useRef(0), operationGeneration = useRef(0), listController = useRef<AbortController | null>(null), detailController = useRef<AbortController | null>(null), operationController = useRef<AbortController | null>(null), staleTimer = useRef<ReturnType<typeof setTimeout> | null>(null), listCursors = useRef({ imports: { current: undefined as string | undefined, next: undefined as string | undefined, previous: [] as Array<string | undefined> }, exports: { current: undefined as string | undefined, next: undefined as string | undefined, previous: [] as Array<string | undefined> } }), previewCursor = useRef({ current: undefined as string | undefined, next: undefined as string | undefined, previous: [] as Array<string | undefined> });
  actorIdentity.current = actorKey;
  const closeCommit = useCallback(() => { setCommitError(""); setCommitOpen(false); }, []);
  useModalFocus({ active: commitOpen, containerRef: commitDialog, onEscape: closeCommit, resolveReturnFocus: () => commitTrigger.current });
  const gates = useMemo(() => { const actions = authorization.modules.find(module => module.module === "content")?.actions ?? []; const byKey = new Map(actions.map(action => [action.permissionKey, action.decision === "allow"])); return { importRead: byKey.get("dashboard.import.foundation_sample.read") === true, importCreate: byKey.get("dashboard.import.foundation_sample.create") === true, importCommit: byKey.get("dashboard.import.foundation_sample.commit") === true, exportRead: byKey.get("dashboard.export.foundation_sample.read") === true, exportCreate: byKey.get("dashboard.export.foundation_sample.create") === true, exportDownload: byKey.get("dashboard.export.foundation_sample.download") === true }; }, [authorization]);
  const execute = useCallback(async (operation: DataJobOperation) => { const generation = ++operationGeneration.current, requestActor = actorKey, controller = new AbortController(); operationController.current?.abort(); operationController.current = controller; const boundOperation = { ...operation, signal: controller.signal } as DataJobOperation; const { response, payload } = await dataJobRequest(boundOperation); if (controller.signal.aborted || generation !== operationGeneration.current || actorIdentity.current !== requestActor) throw new DOMException("Operation aborted", "AbortError"); if (!response.ok) throw new Error("服务器未接受该数据任务操作。"); if (controller.signal.aborted || generation !== operationGeneration.current || actorIdentity.current !== requestActor) throw new DOMException("Operation aborted", "AbortError"); if (operationController.current === controller) operationController.current = null; return payload; }, [actorKey, dataJobRequest]);
  const load = useCallback(async (after?: string) => { const generation = ++listGeneration.current, requestActor = actorKey, controller = new AbortController(); listController.current?.abort(); listController.current = controller; setStatus("loading"); setMessage(""); try { const view = location.view, allowed = view === "imports" ? gates.importRead : gates.exportRead; if (!allowed) { setImports([]); setExports([]); setStatus("ready"); return; } const wire = await apiRequest(listApiPath(view, location.filters, after), { signal: controller.signal }).then(response => { if (!response.ok) throw new Error(`HTTP ${response.status}`); return response.json(); }); if (controller.signal.aborted || generation !== listGeneration.current || actorIdentity.current !== requestActor) return; const result = view === "imports" ? validateImportList(wire, location.filters.sort) : validateExportList(wire, location.filters.sort), capturedAt = result.meta.snapshot.capturedAt; if (view === "imports") setImports(result.data as ImportBatch[]); else setExports(result.data as ExportRequest[]); listCursors.current[view].current = after; listCursors.current[view].next = result.meta.pagination.nextCursor; setCursorRevision(value => value + 1); setStatus("ready"); if (staleTimer.current) clearTimeout(staleTimer.current); if (capturedAt) staleTimer.current = setTimeout(() => { if (generation !== listGeneration.current || actorIdentity.current !== requestActor || isDataJobFresh(capturedAt)) return; setImports([]); setExports([]); setSelectedImport(null); setSelectedExport(null); setPreview(null); setStatus("unavailable"); setMessage("数据快照已超过 60 秒并已清除，请重新载入。"); }, Math.max(0, Date.parse(capturedAt) + 60_000 - Date.now())); } catch (error) { if (controller.signal.aborted || generation !== listGeneration.current || actorIdentity.current !== requestActor) return; setStatus("error"); setMessage(error instanceof Error ? error.message : "数据任务暂时不可用。"); } finally { if (listController.current === controller) listController.current = null; } }, [actorKey, apiRequest, gates.exportRead, gates.importRead, location.filters]);
  useEffect(() => { listCursors.current[location.view] = { current: undefined, next: undefined, previous: [] }; void load(); return () => { listGeneration.current += 1; detailGeneration.current += 1; operationGeneration.current += 1; listController.current?.abort(); detailController.current?.abort(); operationController.current?.abort(); if (staleTimer.current) clearTimeout(staleTimer.current); }; }, [load, location.listHref, location.view]);
  const navigate = (view: "imports" | "exports", resourceId?: string) => { window.history.pushState(window.history.state, "", dataJobsHref(window.location.pathname, view, location.filters, resourceId)); window.dispatchEvent(new PopStateEvent("popstate")); };
  const createExport = async () => { try { await execute({ kind: "createExport", actorKey, expectedActorKey: actor, sort: "external_key:asc", idempotencyKey: idempotency() }); setMessage("导出已排队；完成后才会显示受控下载。"); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "导出创建失败。"); } };
  const cancelImport = async (item: ImportBatch) => { try { await execute({ kind: "cancelImport", actorKey, expectedActorKey: actor, resource: item, importId: item.id, capabilities: item.capabilities, expectedVersion: item.version, idempotencyKey: idempotency() }); setMessage("取消请求已提交，运行中的任务会在安全检查点停止。"); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "当前导入不可取消。"); } };
  const cancelExport = async (item: ExportRequest) => { try { await execute({ kind: "cancelExport", actorKey, expectedActorKey: actor, resource: item, exportId: item.id, capabilities: item.capabilities, expectedVersion: item.version, idempotencyKey: idempotency() }); setMessage("导出取消请求已提交。"); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "当前导出不可取消。"); } };
  const createImport = async () => { if (!file) return; try { const intentWire = await execute({ kind: "createImport", actorKey: actorKey, expectedActorKey: actor, filename: file.name, byteSize: file.size, contentType: "text/csv", idempotencyKey: idempotency() }); const intent = validateUploadIntent(intentWire).data; await execute({ kind: "uploadContent", actorKey, expectedActorKey: actor, intent, importId: intent.id, file, expectedVersion: intent.version, idempotencyKey: idempotency() }); setFile(null); if (selectedFile.current) selectedFile.current.value = ""; await load(); setMessage("上传已提交，解析状态将由服务器更新。"); } catch (error) { setMessage(error instanceof Error ? error.message : "上传失败。"); } };
  const loadPreview = useCallback(async (importId: string, after?: string, navigation?: "next" | "previous" | "restart") => { const generation = ++detailGeneration.current, requestActor = actorKey, controller = new AbortController(); detailController.current?.abort(); detailController.current = controller; const parsed = validatePreview(await apiRequest(previewApiPath(importId, after), { signal: controller.signal }).then(response => response.json())), value = parsed.data; if (controller.signal.aborted || generation !== detailGeneration.current || actorIdentity.current !== requestActor) return; if (navigation === "next") previewCursor.current.previous.push(previewCursor.current.current); else if (navigation === "previous") previewCursor.current.previous.pop(); else if (navigation === "restart") previewCursor.current.previous = []; previewCursor.current.current = after; previewCursor.current.next = parsed.page.next_cursor ?? undefined; setPreview({ rows: value.rows, summary: value.summary, version: value.version }); setCursorRevision(revision => revision + 1); }, [actorKey, apiRequest]);
  const openImport = useCallback(async (item: Pick<ImportBatch, "id">) => { const generation = ++detailGeneration.current, requestActor = actorKey, controller = new AbortController(); detailController.current?.abort(); detailController.current = controller; try { const detail = validateImportDetail(await apiRequest(detailApiPath("imports", item.id), { signal: controller.signal }).then(response => response.json())).data; if (controller.signal.aborted || generation !== detailGeneration.current || actorIdentity.current !== requestActor) return; setSelectedImport(detail); setSelectedExport(null); if (["preview_ready", "completed", "completed_with_errors", "failed"].includes(detail.status)) { const parsed = validatePreview(await apiRequest(previewApiPath(item.id), { signal: controller.signal }).then(response => response.json())), value = parsed.data; if (controller.signal.aborted || generation !== detailGeneration.current || actorIdentity.current !== requestActor) return; previewCursor.current = { current: undefined, next: parsed.page.next_cursor ?? undefined, previous: [] }; setPreview({ rows: value.rows, summary: value.summary, version: value.version }); setCursorRevision(revision => revision + 1); } else setPreview(null); } catch (error) { if (!controller.signal.aborted && generation === detailGeneration.current && actorIdentity.current === requestActor) setMessage(error instanceof Error ? error.message : "导入详情暂时不可用。"); } finally { if (detailController.current === controller) detailController.current = null; } }, [actorKey, apiRequest]);
  const openExport = useCallback(async (item: Pick<ExportRequest, "id">) => { const generation = ++detailGeneration.current, requestActor = actorKey, controller = new AbortController(); detailController.current?.abort(); detailController.current = controller; try { const detail = validateExportDetail(await apiRequest(detailApiPath("exports", item.id), { signal: controller.signal }).then(response => response.json())).data; if (controller.signal.aborted || generation !== detailGeneration.current || actorIdentity.current !== requestActor) return; setSelectedExport(detail); setSelectedImport(null); setPreview(null); } catch (error) { if (!controller.signal.aborted && generation === detailGeneration.current && actorIdentity.current === requestActor) setMessage(error instanceof Error ? error.message : "导出详情暂时不可用。"); } finally { if (detailController.current === controller) detailController.current = null; } }, [actorKey, apiRequest]);
  useEffect(() => { if (!location.resourceId) return; if (location.view === "imports" && gates.importRead) void openImport({ id: location.resourceId }); if (location.view === "exports" && gates.exportRead) void openExport({ id: location.resourceId }); }, [location.resourceId, location.view, gates.importRead, gates.exportRead, openImport, openExport]);
  const commit = async () => { if (!selectedImport || !preview) return; setCommitError(""); try { await execute({ kind: "commitImport", actorKey, expectedActorKey: actor, resource: selectedImport, importId: selectedImport.id, capabilities: selectedImport.capabilities, expectedVersion: preview.version, confirmation: { validRows: preview.summary.valid_row_count, invalidRows: preview.summary.invalid_row_count, acknowledgedPartialOutcome: true }, idempotencyKey: idempotency() }); setCommitOpen(false); setMessage("提交已排队；有效行会逐行处理，部分失败会保留并显示。"); await load(); } catch (error) { setCommitError(error instanceof Error ? error.message : "提交失败，预览可能已过期。"); } };
  const download = async (item: ExportRequest) => { const requestActor = actorKey; try { const blob = await execute({ kind: "downloadExport", actorKey, expectedActorKey: actor, resource: item, exportId: item.id, capabilities: item.capabilities }); if (actorIdentity.current !== requestActor) return; const url = URL.createObjectURL(blob as Blob); if (actorIdentity.current !== requestActor) { URL.revokeObjectURL(url); return; } const link = document.createElement("a"); link.href = url; link.download = "foundation-sample.csv"; link.click(); URL.revokeObjectURL(url); setMessage("受控下载已开始；没有创建公开 URL。"); } catch (error) { if (actorIdentity.current === requestActor) setMessage(error instanceof Error ? error.message : "下载失败或文件已过期。"); } };
  const active = location.view === "imports" ? imports : exports;
  return <section className={styles.panel} aria-label="导入导出基础设施"><header className={styles.header}><div><h2>导入 / 导出基础设施</h2><p>仅启用 foundation.sample；CSV 仅用于非个人、非订单、非支付的基础数据。</p></div><span>当前对象：foundation.sample</span></header>
    {message ? <p role="alert" className={`${styles.status} ${styles.error}`}>{message}</p> : null}<p role="status" aria-live="polite">{status === "loading" ? "正在读取数据任务" : status === "error" ? "数据任务读取失败" : `当前${location.view === "imports" ? "导入" : "导出"}记录 ${active.length} 项`}</p>
    <div className={styles.toolbar}><button className={styles.button} onClick={() => navigate("imports")} aria-pressed={location.view === "imports"} type="button">导入</button><button className={styles.button} onClick={() => navigate("exports")} aria-pressed={location.view === "exports"} type="button">导出</button><button className={styles.button} disabled={!listCursors.current[location.view].previous.length} onClick={() => { const previous = listCursors.current[location.view].previous.at(-1); void load(previous); listCursors.current[location.view].previous.pop(); }} type="button">上一页</button><button className={styles.button} disabled={!listCursors.current[location.view].next} onClick={() => { const state = listCursors.current[location.view]; state.previous.push(state.current); void load(state.next); }} type="button">下一页</button><button className={styles.button} onClick={() => { listCursors.current[location.view] = { current: undefined, next: undefined, previous: [] }; void load(); }} type="button">重新开始</button><button className={styles.button} onClick={() => void load(listCursors.current[location.view].current)} type="button">刷新</button></div>
    {location.view === "exports" && gates.exportCreate ? <section className={styles.upload} aria-labelledby="new-export-title"><h3 id="new-export-title">新建 CSV 导出</h3><p className={styles.help}>对象固定为 foundation.sample，格式固定为 CSV，默认按 external_key 升序；服务器会冻结查询与公式版本。</p><button className={`${styles.button} ${styles.primary}`} onClick={() => void createExport()} type="button">创建导出</button></section> : null}
    {location.view === "imports" && gates.importCreate ? <fieldset className={styles.upload}><legend>新建 CSV 导入</legend><p className={styles.help}>仅支持 CSV；服务器会再次检查字节、编码、表头、行数和禁止字段。上传上限由服务器决定。</p><label>CSV 文件<input ref={selectedFile} accept="text/csv,.csv" onChange={event => setFile(event.target.files?.[0] ?? null)} type="file" /></label><button className={`${styles.button} ${styles.primary}`} disabled={!file} onClick={() => void createImport()} type="button">上传并解析</button></fieldset> : null}
    <div className={styles.grid}>{active.map(item => <article className={styles.card} key={item.id}><h3>{item.id}</h3><p>foundation.sample · {labels[item.status] ?? item.status}</p><p>{"summary" in item ? `总行数 ${item.summary.row_count}，有效 ${item.summary.valid_row_count}，无效 ${item.summary.invalid_row_count}` : `公式 ${item.formula_version} · ${item.row_count ?? "—"} 行`}</p>{item.progress ? <p role="status" aria-atomic="true" aria-live="polite">进度：{item.progress.completed}{item.progress.total === null ? "" : ` / ${item.progress.total}`} {item.progress.unit === "rows" ? "行" : "字节"}</p> : null}<p>有效期至：{new Date(item.expires_at).toLocaleString("zh-CN")}</p><div className={styles.actions}><button className={styles.button} onClick={() => location.view === "imports" ? void openImport(item as ImportBatch) : void openExport(item as ExportRequest)} type="button">查看详情</button>{location.view === "imports" && (item as ImportBatch).capabilities.cancel ? <button className={styles.button} onClick={() => void cancelImport(item as ImportBatch)} type="button">取消</button> : null}{location.view === "exports" && (item as ExportRequest).capabilities.cancel ? <button className={styles.button} onClick={() => void cancelExport(item as ExportRequest)} type="button">取消</button> : null}{location.view === "exports" && gates.exportDownload && (item as ExportRequest).capabilities.download && (item as ExportRequest).status === "completed" ? <button className={styles.button} onClick={() => void download(item as ExportRequest)} type="button">受控下载</button> : null}</div></article>)}</div>
    {location.view === "imports" && selectedImport ? <section className={styles.preview} aria-labelledby="import-detail-title"><h3 id="import-detail-title">导入详情：{selectedImport.id}</h3><p>状态：{labels[selectedImport.status] ?? selectedImport.status}；版本：{selectedImport.version}</p>{preview ? <><h4>预览摘要</h4><p>总行数 {preview.summary.row_count}；有效 {preview.summary.valid_row_count}；无效 {preview.summary.invalid_row_count}</p><ul>{preview.rows.map(row => <li key={row.row_number}><strong>第 {row.row_number} 行</strong><span>：验证 {row.validation_status === "valid" ? "通过" : "失败"}</span>{row.validation_errors.length ? <ul aria-label={`第 ${row.row_number} 行验证错误`}>{row.validation_errors.map((error, index) => <li key={`validation-${index}`}>验证错误：{error.field ? `字段 ${error.field}，` : ""}{error.code}</li>)}</ul> : null}<span>；提交 {row.commit_status}</span>{row.commit_errors.length ? <ul aria-label={`第 ${row.row_number} 行提交错误`}>{row.commit_errors.map((error, index) => <li key={`commit-${index}`}>提交错误：{error.field ? `字段 ${error.field}，` : ""}{error.code}</li>)}</ul> : null}</li>)}</ul><div className={styles.actions}><button className={styles.button} disabled={!previewCursor.current.previous.length} onClick={() => void loadPreview(selectedImport.id, previewCursor.current.previous.at(-1), "previous")} type="button">预览上一页</button><button className={styles.button} disabled={!previewCursor.current.next} onClick={() => void loadPreview(selectedImport.id, previewCursor.current.next, "next")} type="button">预览下一页</button><button className={styles.button} onClick={() => void loadPreview(selectedImport.id, undefined, "restart")} type="button">预览重新开始</button></div>{selectedImport.status === "preview_ready" && gates.importCommit && selectedImport.capabilities.commit ? <button ref={commitTrigger} className={`${styles.button} ${styles.danger}`} onClick={() => { setCommitError(""); setCommitOpen(true); }} type="button">提交有效行</button> : null}</> : <p>当前没有可用预览；提交按钮不会显示。</p>}</section> : null}
    {selectedExport ? <section className={styles.preview} aria-labelledby="export-detail-title"><h3 id="export-detail-title">导出详情：{selectedExport.id}</h3><p>状态：{labels[selectedExport.status] ?? selectedExport.status}；公式：{selectedExport.formula_version}</p><p>行数：{selectedExport.row_count ?? "—"}；字节：{selectedExport.byte_size ?? "—"}；有效期：{new Date(selectedExport.expires_at).toLocaleString("zh-CN")}</p><p>{isDataJobFresh(selectedExport.created_at) ? "记录状态由服务器决定。" : "记录快照需要重新获取。"}</p></section> : null}
    {commitOpen ? <div ref={commitDialog} role="dialog" aria-modal="true" aria-labelledby="commit-title" className={styles.preview} tabIndex={-1}><h3 id="commit-title">确认提交有效行</h3>{commitError ? <p role="alert" className={`${styles.status} ${styles.error}`}>{commitError}</p> : null}<p>这会写入基础样本记录，仅提交 {preview?.summary.valid_row_count ?? 0} 行有效数据；{preview?.summary.invalid_row_count ?? 0} 行无效数据不会提交。行级冲突或目标约束失败可能产生部分完成结果，且不会回滚已成功行。</p><div className={styles.actions}><button className={`${styles.button} ${styles.danger}`} onClick={() => void commit()} type="button">确认提交</button><button className={styles.button} onClick={closeCommit} type="button">取消</button></div></div> : null}
  </section>;
}
