"use client";

import { useEffect, useRef, useState, type ChangeEvent } from "react";
import type { DashboardAuthorization } from "@/lib/api/api-contract";
import { MEDIA_USAGE_ENTITY_TYPES, canonicalMediaTags, mediaDownloadApiPath, mediaPreviewApiPath, mediaUsagesApiPath, validateMediaDetail, validateMediaRetryResult, validateMediaUploadIntent, validateMediaUploadResult, validateMediaUsages, type MediaAsset, type MediaUsage } from "@/lib/dashboard/p07-media";
import type { MediaMetadataWrite, MediaUsageWrite, MediaWriteOperation } from "@/lib/dashboard/p07-media-write";
import { Table } from "./shared/primitives";
import styles from "./MediaFoundationPanel.module.css";

const usageText = { product: "产品", product_variant: "产品变体", category: "分类", cms_module: "内容模块", article: "文章", dealer: "经销商" } as const;
const slots: Record<MediaUsage["entityType"], readonly string[]> = { product: ["gallery", "primary"], product_variant: ["gallery", "primary"], category: ["hero", "tile"], cms_module: ["media", "hero"], article: ["hero", "inline"], dealer: ["logo", "gallery"] };
type Failure = Error & { status?: number };
type ApiRequest = (path: string, init?: RequestInit) => Promise<Response>;
type MediaWriteRequest = (operation: MediaWriteOperation) => Promise<Response>;
async function responseJson(response: Response) { const body = await response.json().catch(() => null); if (!response.ok) { const error = new Error("媒体操作失败。") as Failure; error.status = response.status; throw error; } return body; }
async function json(apiRequest: ApiRequest, path: string, init?: RequestInit) { return responseJson(await apiRequest(path, { ...init, headers: { Accept: "application/json", ...(init?.body ? { "Content-Type": "application/json" } : {}), ...init?.headers } })); }
async function writeJson(mediaWriteRequest: MediaWriteRequest, operation: MediaWriteOperation) { return responseJson(await mediaWriteRequest(operation)); }
async function blob(apiRequest: ApiRequest, path: string, signal?: AbortSignal) { const response = await apiRequest(path, { signal }); if (!response.ok) throw new Error("受控读取失败。"); return response.blob(); }

export function MediaUploadControl({ actorKey, mediaWriteRequest, capability, sensitive, onAccepted }: { actorKey: string; mediaWriteRequest: MediaWriteRequest; capability: DashboardAuthorization["mediaFoundationV1"]; sensitive: boolean; onAccepted: () => void }) {
  const [progress, setProgress] = useState(0), [expiry, setExpiry] = useState(""), [message, setMessage] = useState(""), [busy, setBusy] = useState(false); const uploadController = useRef<AbortController | null>(null), identity = useRef(actorKey); identity.current = actorKey;
  useEffect(() => () => uploadController.current?.abort(), [actorKey]);
  const upload = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; event.target.value = ""; if (!file || !capability.actions.create || !capability.upload.enabled) return; const kind = file.type === "application/pdf" ? "pdf" : "image", supported = file.type === "application/pdf" ? capability.upload.pdf : ["image/jpeg", "image/png", "image/webp"].includes(file.type) && capability.upload.image, limit = capability.upload.maxBytes[kind]; if (!supported || file.size < 1 || file.size > limit) { setMessage("仅支持 JPEG、PNG、WebP 或 PDF，并须符合服务器公布的大小限制。浏览器提示不是安全验证。"); return; } const actor = actorKey, controller = new AbortController(); uploadController.current?.abort(); uploadController.current = controller; setBusy(true); setProgress(0); setMessage("正在创建一次性上传意图……"); try { const intent = validateMediaUploadIntent(await writeJson(mediaWriteRequest, { kind: "createUploadIntent", actorKey: actor, filename: file.name, mediaKind: kind, declaredContentType: file.type as "image/jpeg" | "image/png" | "image/webp" | "application/pdf", expectedBytes: file.size, signal: controller.signal }), sensitive).data; if (controller.signal.aborted || identity.current !== actor) return; setExpiry(intent.expiresAt); setProgress(50); const response = await mediaWriteRequest({ kind: "uploadIntentContent", actorKey: actor, intent, assetId: intent.asset.id, body: file, signal: controller.signal }); const result = await response.json().catch(() => null); if (!response.ok) throw new Error("upload rejected"); if (controller.signal.aborted || identity.current !== actor) return; validateMediaUploadResult(result, sensitive); setProgress(100); setMessage("字节已受控接收，服务器正在处理；这不代表资源已可用。"); onAccepted(); } catch { if (!controller.signal.aborted && identity.current === actor) { setProgress(0); setMessage(expiry && Date.now() >= Date.parse(expiry) ? "上传意图已过期，未假定成功。" : "上传中断或被服务器拒绝，未假定成功。"); } } finally { if (identity.current === actor) setBusy(false); if (uploadController.current === controller) uploadController.current = null; } };
  return <section className={styles.upload} aria-labelledby="media-upload-title"><h3 id="media-upload-title">单文件受控上传</h3><p className={styles.help}>格式与大小仅是浏览器提示；签名、解析和安全状态由服务器决定。</p><div className={styles.uploadRow}><label>选择文件<input accept="image/jpeg,image/png,image/webp,application/pdf" disabled={busy || !capability.upload.enabled} onChange={event => void upload(event)} type="file" /></label>{busy && expiry ? <button className={styles.button} onClick={() => uploadController.current?.abort()} type="button">取消上传</button> : null}</div>{expiry ? <p>意图到期：{new Intl.DateTimeFormat("zh-CN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(expiry))}</p> : null}<progress aria-label="上传进度" className={styles.progress} max="100" value={progress}>{progress}%</progress><span aria-live="polite">{progress}%</span><p role={message.includes("失败") || message.includes("过期") ? "alert" : "status"}>{message || (!capability.upload.enabled ? "服务器处理能力尚未就绪，上传已关闭。" : "等待选择文件。")}</p></section>;
}

export function MediaAssetControls({ actorKey, apiRequest, mediaWriteRequest, asset, capability, sensitive, onChanged }: { actorKey: string; apiRequest: ApiRequest; mediaWriteRequest: MediaWriteRequest; asset: MediaAsset; capability: DashboardAuthorization["mediaFoundationV1"]; sensitive: boolean; onChanged: (asset?: MediaAsset) => void }) {
  const locale = (key: "en-CA" | "fr-CA") => asset.locales.find(value => value.locale === key) ?? { locale: key, altText: null, caption: null }; const [en, setEn] = useState(locale("en-CA")), [fr, setFr] = useState(locale("fr-CA")), [decorative, setDecorative] = useState(asset.decorative), [credit, setCredit] = useState(asset.credit ?? ""), [copyright, setCopyright] = useState(asset.copyright ?? ""), [tags, setTags] = useState(asset.tags.join(", ")), [x, setX] = useState(asset.focalPoint?.x.toString() ?? ""), [y, setY] = useState(asset.focalPoint?.y.toString() ?? "");
  const [usages, setUsages] = useState<MediaUsage[]>([]), [usageState, setUsageState] = useState<"loading" | "ready" | "error">("loading"), [message, setMessage] = useState(""), [busy, setBusy] = useState(false), [preview, setPreview] = useState(""), [entityType, setEntityType] = useState<MediaUsage["entityType"]>("product"), [entityId, setEntityId] = useState(""), [slot, setSlot] = useState("gallery"); const identity = useRef(actorKey), previewGeneration = useRef(0), downloadGeneration = useRef(0), previewController = useRef<AbortController | null>(null), downloadController = useRef<AbortController | null>(null); identity.current = actorKey;
  useEffect(() => { let active = true; setUsageState("loading"); void json(apiRequest, mediaUsagesApiPath(asset.id)).then(validateMediaUsages).then(value => { if (active) { setUsages(value.data); setUsageState("ready"); } }).catch(() => { if (active) { setUsageState("error"); setMessage("使用关系暂时无法载入。"); } }); return () => { active = false; previewGeneration.current += 1; downloadGeneration.current += 1; previewController.current?.abort(); downloadController.current?.abort(); setPreview(value => { if (value) URL.revokeObjectURL(value); return ""; }); }; }, [actorKey, asset.id, capability.actions.downloadOriginal, asset.capabilities.downloadOriginal]);
  const mutateAsset = async (kind: "updateMetadata" | "archive" | "restore", body: unknown) => { const actor = actorKey; setBusy(true); setMessage(""); try { const next = validateMediaDetail(await writeJson(mediaWriteRequest, kind === "updateMetadata" ? { kind, actorKey: actor, asset, assetId: asset.id, expectedScope: asset.authorizationScope, metadata: body as MediaMetadataWrite } : { kind, actorKey: actor, asset, assetId: asset.id, expectedScope: asset.authorizationScope, expectedAssetVersion: asset.version }), sensitive).data; if (identity.current === actor) { onChanged(next); setMessage("更改已保存。"); } } catch { if (identity.current === actor) setMessage("操作未完成，未假定服务器已成功。"); } finally { if (identity.current === actor) setBusy(false); } };
  const refreshUsages = async () => setUsages(validateMediaUsages(await json(apiRequest, mediaUsagesApiPath(asset.id))).data);
  const retryVariants = async () => { const actor = actorKey; setBusy(true); setMessage(""); try { const key = crypto.randomUUID(); const response = await mediaWriteRequest({ kind: "retryVariant", actorKey: actor, asset, assetId: asset.id, expectedScope: asset.authorizationScope, idempotencyKey: key }); if (response.status === 409) { if (identity.current === actor) { setMessage("资源状态已变化，已刷新详情；不会自动重试。"); onChanged(); } return; } const result = validateMediaRetryResult(await responseJson(response)); if (result.data.assetId !== asset.id) throw new TypeError("retry asset mismatch"); if (identity.current === actor) { setMessage("已提交安全变体重试；服务器状态将刷新。"); onChanged(); } } catch { if (identity.current === actor) setMessage("安全变体重试未提交，未假定成功。"); } finally { if (identity.current === actor) setBusy(false); } };
  const changeUsage = async (kind: "attachUsage", body: unknown): Promise<void> => { setBusy(true); setMessage(""); try { await writeJson(mediaWriteRequest, { kind, actorKey, asset, assetId: asset.id, expectedScope: asset.authorizationScope, usageTarget: body as MediaUsageWrite }); await refreshUsages(); onChanged(); setMessage("使用关系已关联。"); } catch { setMessage("使用关系未更改，请检查对象权限、范围、槽位与双语元数据。"); } finally { setBusy(false); } };
  const detachUsage = async (usage: MediaUsage) => { setBusy(true); setMessage(""); try { await writeJson(mediaWriteRequest, { kind: "detachUsage", actorKey, asset, assetId: asset.id, expectedScope: asset.authorizationScope, usage, usageId: usage.id }); await refreshUsages(); onChanged(); setMessage("使用关系已解除。"); } catch { setMessage("使用关系未更改，请检查对象权限、范围、槽位与双语元数据。"); } finally { setBusy(false); } };
  const showPreview = async () => { const variant = asset.variants.find(value => value.role !== "original" && value.status === "ready"); if (!variant) return; const generation = ++previewGeneration.current, actor = actorKey, assetId = asset.id, controller = new AbortController(); previewController.current?.abort(); previewController.current = controller; setMessage("正在载入受控预览。"); try { const data = await blob(apiRequest, mediaPreviewApiPath(assetId, variant.id), controller.signal); if (controller.signal.aborted || generation !== previewGeneration.current || identity.current !== actor || asset.id !== assetId) return; const url = URL.createObjectURL(data); if (controller.signal.aborted || generation !== previewGeneration.current || identity.current !== actor || asset.id !== assetId) { URL.revokeObjectURL(url); return; } setPreview(current => { if (current) URL.revokeObjectURL(current); return url; }); setMessage("受控预览已载入。"); } catch { if (!controller.signal.aborted && generation === previewGeneration.current && identity.current === actor) setMessage("受控预览不可用。"); } finally { if (previewController.current === controller) previewController.current = null; } };
  const download = async () => { const generation = ++downloadGeneration.current, actor = actorKey, assetId = asset.id, controller = new AbortController(); downloadController.current?.abort(); downloadController.current = controller; setMessage("正在准备原始文件下载。"); try { const data = await blob(apiRequest, mediaDownloadApiPath(assetId), controller.signal); if (controller.signal.aborted || generation !== downloadGeneration.current || identity.current !== actor || asset.id !== assetId) return; const url = URL.createObjectURL(data), link = document.createElement("a"); link.href = url; link.download = asset.safeDisplayName; link.rel = "noopener"; link.click(); URL.revokeObjectURL(url); setMessage("原始文件下载已开始。"); } catch { if (!controller.signal.aborted && generation === downloadGeneration.current && identity.current === actor) setMessage("原始文件下载不可用。"); } finally { if (downloadController.current === controller) downloadController.current = null; } };
  return <div><p role={message ? "alert" : "status"}>{message}</p>{asset.kind === "image" && asset.status === "ready" && asset.variants.some(value => value.role !== "original" && value.status === "ready") ? <section className={styles.preview}><h4>受控预览</h4>{preview ? <img alt={asset.decorative ? "" : en.altText ?? asset.safeDisplayName} src={preview} /> : null}<button className={styles.button} onClick={() => void showPreview()} type="button">{preview ? "重新载入预览" : "载入预览"}</button></section> : null}<div className={styles.actions}>{capability.actions.downloadOriginal && asset.capabilities.downloadOriginal && (asset.status === "ready" || asset.status === "archived") ? <button className={styles.button} onClick={() => void download()} type="button">下载原始文件</button> : null}{capability.actions.archive && asset.capabilities.archive && ["ready", "failed", "quarantined"].includes(asset.status) ? <button className={`${styles.button} ${styles.danger}`} disabled={busy} onClick={() => void mutateAsset("archive", { version: asset.version })} type="button">归档</button> : null}{capability.actions.restore && asset.capabilities.restore && asset.status === "archived" ? <button className={styles.button} disabled={busy} onClick={() => void mutateAsset("restore", { version: asset.version })} type="button">恢复</button> : null}</div>{capability.actions.manageVariants && asset.capabilities.manageVariants && asset.retryBinding && asset.status === "failed" ? <button className={styles.button} disabled={busy} onClick={() => void retryVariants()} type="button">重试失败变体</button> : null}
    {capability.actions.update && asset.capabilities.update ? <section><h4>英语、法语与资源元数据</h4><form className={styles.metadata} onSubmit={event => { event.preventDefault(); void mutateAsset("updateMetadata", { version: asset.version, decorative, focalPoint: x && y ? { x: Number(x), y: Number(y) } : undefined, credit: credit || null, copyright: copyright || null, tags: canonicalMediaTags(tags), locales: [{ locale: "en-CA", altText: decorative ? null : en.altText || null, caption: en.caption || null }, { locale: "fr-CA", altText: decorative ? null : fr.altText || null, caption: fr.caption || null }] }); }}><label><input checked={decorative} onChange={event => setDecorative(event.target.checked)} type="checkbox" />装饰性图片（双语替代文本将清空）</label><div className={styles.localeGrid}><fieldset><legend>英语（加拿大）</legend><label>替代文本<textarea disabled={decorative || asset.kind !== "image"} maxLength={500} onChange={event => setEn(value => ({ ...value, altText: event.target.value }))} value={en.altText ?? ""} /></label><label>说明<textarea maxLength={1000} onChange={event => setEn(value => ({ ...value, caption: event.target.value }))} value={en.caption ?? ""} /></label></fieldset><fieldset><legend>法语（加拿大）</legend><label>替代文本<textarea disabled={decorative || asset.kind !== "image"} maxLength={500} onChange={event => setFr(value => ({ ...value, altText: event.target.value }))} value={fr.altText ?? ""} /></label><label>说明<textarea maxLength={1000} onChange={event => setFr(value => ({ ...value, caption: event.target.value }))} value={fr.caption ?? ""} /></label></fieldset></div><label>署名<input maxLength={500} onChange={event => setCredit(event.target.value)} value={credit} /></label><label>版权<input maxLength={500} onChange={event => setCopyright(event.target.value)} value={copyright} /></label><label>标签（逗号分隔）<input onChange={event => setTags(event.target.value)} value={tags} /></label>{asset.kind === "image" ? <div className={styles.localeGrid}><label>焦点 X（0–1）<input max="1" min="0" onChange={event => setX(event.target.value)} step="0.01" type="number" value={x} /></label><label>焦点 Y（0–1）<input max="1" min="0" onChange={event => setY(event.target.value)} step="0.01" type="number" value={y} /></label></div> : null}<button className={`${styles.button} ${styles.primary}`} disabled={busy} type="submit">保存元数据</button></form></section> : null}
    <section aria-busy={usageState === "loading"}><h4>使用关系</h4>{usageState === "loading" ? <p role="status">正在载入使用关系。</p> : null}<Table caption="媒体使用关系" columns={["对象", "对象 ID", "槽位", "必需语言", "操作"]} emptyMessage={usageState === "ready" ? "没有授权范围内的使用关系" : "使用关系尚未载入"} rows={usages.map(usage => [usageText[usage.entityType], usage.entityId, usage.slot, usage.requiredLocales.join("、") || "无", capability.actions.update && asset.capabilities.update ? <button aria-label={`解除 ${usageText[usage.entityType]} ${usage.entityId} 的使用关系`} className={styles.button} disabled={busy} key={usage.id} onClick={() => void detachUsage(usage)} type="button">解除关系</button> : "只读"])} />{capability.actions.update && asset.capabilities.update && asset.status === "ready" ? <form className={styles.usageForm} onSubmit={event => { event.preventDefault(); void changeUsage("attachUsage", { expectedAssetVersion: asset.version, entityType, entityId: entityId.trim(), slot }); }}><fieldset><legend>新增使用关系</legend><label>对象类型<select onChange={event => { const next = event.target.value as MediaUsage["entityType"]; setEntityType(next); setSlot(slots[next][0]!); }} value={entityType}>{MEDIA_USAGE_ENTITY_TYPES.map(value => <option key={value} value={value}>{usageText[value]}</option>)}</select></label><label>对象 ID<input onChange={event => setEntityId(event.target.value)} required value={entityId} /></label><label>槽位<select onChange={event => setSlot(event.target.value)} value={slot}>{slots[entityType].map(value => <option key={value} value={value}>{value}</option>)}</select></label><p className={styles.help}>必需语言由目标对象与服务器规则确定，关联后显示在表格中。</p><button className={styles.button} disabled={busy} type="submit">关联资源</button></fieldset></form> : null}</section>
  </div>;
}
