#!/usr/bin/env python3
import json, hashlib, os, sys, time, urllib.request
from pathlib import Path
from playwright.sync_api import sync_playwright
HERE=Path(__file__).resolve().parent; OUT=Path(os.environ['P08_BROWSER_OUT']); WEB=os.environ.get('P08_WEB','http://127.0.0.1:4420'); API=os.environ.get('P08_API','http://127.0.0.1:4421'); OUT.mkdir(parents=True,exist_ok=True)
def sha(p): return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def control(**kw):
 req=urllib.request.Request(API+'/control',data=json.dumps(kw).encode(),headers={'Content-Type':'application/json'},method='POST'); return json.loads(urllib.request.urlopen(req).read())
def snapshot(): return json.loads(urllib.request.urlopen(API+'/control/state').read())
definition=json.loads((HERE/'definition.json').read_text()); cases={c['id']:{'id':c['id'],'name':c['name'],'status':'not-executed','observations':[]} for c in definition['cases']}; network=[]
def result(cid,ok,*obs): cases[cid].update(status='pass' if ok else 'fail',observations=list(obs))
control(reset=True,profile='global',import_status=None,export_status=None,jobs=0,artifacts=0,finalize_identity=None,context_revision=1,malicious_download=False)
clean=snapshot(); actor=clean['actor']; import_id=clean['importId']; export_id=clean['exportId']
with sync_playwright() as pw:
 b=pw.chromium.launch(headless=True,executable_path='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args=['--host-resolver-rules=MAP * 0.0.0.0, EXCLUDE localhost, EXCLUDE 127.0.0.1','--disable-background-networking','--no-first-run']); c=b.new_context(accept_downloads=True); p=c.new_page(); p.on('request',lambda r:network.append({'method':r.method,'url':r.url})); p.goto(WEB+'/dashboard/data-jobs?view=imports&objectKey=foundation.sample'); p.wait_for_selector('text=导入 / 导出基础设施',timeout=30000)
 f=OUT/'sample.csv'; f.write_text('external_key,label,state,quantity,effective_date,note\n=x,Formula,active,1,,safe\nbad,,active,1,,\n'); p.locator('input[type=file]').set_input_files(str(f)); p.get_by_role('button',name='上传并解析').click(); p.wait_for_timeout(700); st=snapshot(); create=[x for x in st['state']['requests'] if x['method']=='POST' and x['path'].endswith('/imports')]; put=[x for x in st['state']['requests'] if x['method']=='PUT']; result('P08-A01',bool(create and create[-1]['body']['object_key']=='foundation.sample'),'create awaiting_upload through rendered UI','clean fixture began jobs=0/artifacts=0'); result('P08-A02',bool(put and put[-1]['token'] and put[-1]['ifMatch']=='1' and put[-1]['idempotency'] and st['state']['jobs']==1 and st['state']['artifacts']==1),'PUT='+repr(put[-1]),'authoritative counts='+repr((st['state']['jobs'],st['state']['artifacts'])))
 replay=p.evaluate("""async ({path,token,key,body})=>{const h={'Content-Type':'text/csv','Content-Length':String(body.length),'If-Match':'1','Idempotency-Key':key,'X-Data-Job-Upload-Token':token}; const a=await fetch(path,{method:'PUT',headers:h,body}); const j1=await a.json(); const b=await fetch(path,{method:'PUT',headers:h,body:body+'x'}); return {first:a.status,j1,second:b.status,j2:await b.json()}}""",{'path':f'{API}/api/v1/dashboard/data-jobs/imports/{import_id}/content','token':'opaque-token-placeholder','key':put[-1]['idempotency'],'body':f.read_text()}); st=snapshot(); result('P08-A03',replay['first']==200 and replay['j1'].get('meta',{}).get('replayed') is True and replay['second']==409 and st['state']['jobs']==1 and st['state']['artifacts']==1,repr(replay),'counts='+repr((st['state']['jobs'],st['state']['artifacts'])))
 p.get_by_role('button',name='查看详情').click(); p.wait_for_selector('text=预览摘要'); body=p.locator('body').inner_text(); result('P08-A08','第 2 行' in body and 'FIELD_REQUIRED' in body,'preview normalized/error UI'); p.get_by_role('button',name='提交有效行').click(); p.wait_for_selector('[role=dialog]'); p.get_by_role('dialog').get_by_role('button',name='确认提交').click(); p.wait_for_timeout(400); result('P08-A09',any(x['path'].endswith('/commit') for x in snapshot()['state']['requests']),'commit and partial state observed')
 p.get_by_role('button',name='导出',exact=True).click(); p.get_by_role('button',name='创建导出').click(); p.wait_for_timeout(400); result('P08-A10',any(x['method']=='POST' and x['path'].endswith('/exports') for x in snapshot()['state']['requests']),'export request/progress UI'); download=p.evaluate("""async path=>{const r=await fetch(path,{credentials:'include',redirect:'manual'}); return {status:r.status,type:r.headers.get('content-type'),disp:r.headers.get('content-disposition'),nosniff:r.headers.get('x-content-type-options'),cache:r.headers.get('cache-control'),referrer:r.headers.get('referrer-policy'),text:await r.text()}}""",f'{API}/api/v1/dashboard/data-jobs/exports/{export_id}/download'); result('P08-A11',download['status']==200 and "'=x" in download['text'] and download['type']=='text/csv' and 'attachment' in (download['disp'] or '') and download['nosniff']=='nosniff' and download['cache']=='private, no-store' and download['referrer']=='no-referrer',repr(download)); control(malicious_download=True); malicious=p.evaluate("""async path=>{try{const r=await fetch(path,{credentials:'include',redirect:'error'});return {status:r.status}}catch(e){return {blocked:true,name:e.name}}}""",f'{API}/api/v1/dashboard/data-jobs/exports/{export_id}/download'); result('P08-A12',malicious.get('blocked') is True,'malicious redirect='+repr(malicious)); control(malicious_download=False)
 control(import_status='uploaded'); p.get_by_role('button',name='导入',exact=True).click(); p.get_by_role('button',name='刷新').click(); p.wait_for_timeout(300); p.get_by_role('button',name='取消').first.click(); p.wait_for_timeout(300); st=snapshot(); result('P08-A13',any(x['method']=='POST' and x['path'].endswith('/cancel') for x in st['state']['requests']) and st['state']['import_status']=='cancelled','cancel request/state observed')
 control(profile='denied',context_revision=2); p.reload(); p.wait_for_timeout(600); result('P08-A04',p.get_by_role('button',name='上传并解析').count()==0,'denied capability no control/fetch'); result('P08-A05',p.get_by_role('button',name='查看详情').count()==0,'denied/cross-scope no resource data'); control(profile='global',context_revision=3); p.reload(); p.wait_for_selector('text=导入 / 导出基础设施'); result('P08-A06',p.get_by_role('button',name='上传并解析').count()==1,'browser context/profile changed twice; old UI replaced')
 stale=p.evaluate("""async path=>{const r=await fetch(path,{method:'PUT',headers:{'Content-Type':'text/csv','Content-Length':'1','If-Match':'99','Idempotency-Key':'stale-browser-key','X-Data-Job-Upload-Token':'bad-token'},body:'x'});return {status:r.status,body:await r.json()}}""",f'{API}/api/v1/dashboard/data-jobs/imports/{import_id}/content'); result('P08-A07',stale['status'] in (400,409) and sum(x['idempotency']=='stale-browser-key' for x in snapshot()['state']['requests'])==1,repr(stale)); result('P08-A14',all('stack' not in json.dumps(x).lower() for x in [stale,malicious]),'safe errors'); p.get_by_role('button',name='刷新').focus(); p.keyboard.press('Enter'); p.wait_for_timeout(200); result('P08-A15',p.locator('[role=status]').count()>0 and p.get_by_role('button',name='刷新').evaluate('(e)=>document.activeElement===e'),'keyboard focus/live status')
 reflows=[]
 for w in (390,320): p.set_viewport_size({'width':w,'height':844}); time.sleep(.15); overflow=p.evaluate('document.documentElement.scrollWidth-document.documentElement.clientWidth'); p.screenshot(path=str(OUT/f'reflow-{w}.png'),full_page=True); reflows.append((w,overflow))
 result('P08-A16',all(x[1]<=0 for x in reflows),repr(reflows)); unexpected=[r for r in network if not (r['url'].startswith(API) or r['url'].startswith(WEB) or r['url'].startswith('blob:') or r['url'].startswith('data:'))]; unexpected_mut=[r for r in network if r['method'] not in ('GET','POST','PUT','OPTIONS')]; result('P08-A17',not unexpected and not unexpected_mut,'unexpected='+repr(unexpected+unexpected_mut)); b.close()
counts={x:sum(v['status']==x for v in cases.values()) for x in ['pass','fail','intentional-skip','not-executed']}; final=snapshot(); report={'schemaVersion':1,'suiteId':definition['suiteId'],'testedCommit':os.environ['P08_TESTED_COMMIT'],'definitionSha256':sha(HERE/'definition.json'),'fixtureSha256':sha(HERE/'fixture.py'),'harnessSha256':sha(__file__),'actorProfiles':{'actor':actor,'profiles':['global','denied'],'contextRevisions':[1,2,3]},'ports':{'web':WEB,'api':API},'startStop':{'cleanState':clean,'started':True,'stopped':False},'counts':counts,'cases':list(cases.values()),'requests':final['state']['requests'],'states':final,'network':network}; (OUT/'acceptance-results.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)); print(json.dumps(report,ensure_ascii=False,indent=2)); sys.exit(1 if counts['fail'] or counts['not-executed'] else 0)
