#!/usr/bin/env python3
import json, sys, uuid, urllib.parse
from datetime import datetime, timezone, timedelta
from http.server import ThreadingHTTPServer, BaseHTTPRequestHandler
PORT=int(sys.argv[1]); ACTOR=str(uuid.uuid4()); IMP='imp_'+uuid.uuid4().hex[:12]; EXP='exp_'+uuid.uuid4().hex[:12]; TOKEN='opaque-token-'+uuid.uuid4().hex; NOW=lambda:datetime.now(timezone.utc).isoformat().replace('+00:00','Z')
state={'requests':[],'profile':'global','import_status':None,'export_status':None,'jobs':0,'artifacts':0,'finalize_identity':None,'context_revision':1,'delay_once':False,'malicious_download':False,'unauth_once':False}
def caps(**kw): return {'read':True,'create':True,'commit':True,'cancel':False,'download':False,**kw}
def imp(status=None):
 s=status or state['import_status'] or 'awaiting_upload'; return {'id':IMP,'object_key':'foundation.sample','status':s,'original_filename':'sample.csv','content_type':'text/csv','byte_size':78,'summary':{'row_count':2 if s not in ('awaiting_upload','uploaded','parsing') else 0,'valid_row_count':1 if s not in ('awaiting_upload','uploaded','parsing') else 0,'invalid_row_count':1 if s not in ('awaiting_upload','uploaded','parsing') else 0,'committed_row_count':1 if s=='completed_with_errors' else 0,'failed_commit_row_count':0},'created_at':NOW(),'expires_at':(datetime.now(timezone.utc)+timedelta(days=7)).isoformat().replace('+00:00','Z'),**({'previewed_at':NOW(),'preview_expires_at':(datetime.now(timezone.utc)+timedelta(days=7)).isoformat().replace('+00:00','Z')} if s in ('preview_ready','completed_with_errors') else {}),**({'completed_at':NOW()} if s=='completed_with_errors' else {}),'version':2 if s=='preview_ready' else 1,'request_id':'req-import','capabilities':caps(commit=s=='preview_ready',cancel=s=='uploaded')}
def exp(): return {'id':EXP,'object_key':'foundation.sample','status':state['export_status'] or 'completed','formula_version':'foundation.sample.export.v1','requested_format':'csv','row_count':2,'byte_size':95,'sha256':'a'*64,'created_at':NOW(),'completed_at':NOW(),'expires_at':(datetime.now(timezone.utc)+timedelta(days=7)).isoformat().replace('+00:00','Z'),'version':3,'request_id':'req-export','capabilities':caps(download=True)}
def foundation(): return {'data':{'contractVersion':'dashboard-foundation.v1','actor':{'id':ACTOR,'displayLabel':'P08 QA','roleLabels':['qa']},'modules':[{'module':'overview','route':'/dashboard','readAllowed':True},{'module':'content','route':'/dashboard/content','readAllowed':True}],'visibility':{'scope':'unavailable','fields':'permission-only'},'shell':{'flag':'dashboard.shell.v2','mode':'internal','enabled':True,'code':'DASHBOARD_SHELL_READY','readOnly':True},'readiness':'ready','requestId':'f-'+ACTOR[:8]}}
def auth():
 perms=([] if state['profile']=='denied' else ['dashboard.access','content.read','dashboard.import.foundation_sample.read','dashboard.import.foundation_sample.create','dashboard.import.foundation_sample.commit','dashboard.export.foundation_sample.read','dashboard.export.foundation_sample.create','dashboard.export.foundation_sample.download']); actions=[{'action':'read','permissionKey':p,'decision':'allow','reason':'granted_by_persisted_permission','scope':{'kind':'global'}} for p in perms]
 return {'data':{'contractVersion':'dashboard-authorization.v1','status':'ready','requestId':'a-'+ACTOR[:8],'issuedAt':NOW(),'expiresAt':(datetime.now(timezone.utc)+timedelta(minutes=30)).isoformat().replace('+00:00','Z'),'contextRevision':'rev-'+state['profile']+'-'+str(state['context_revision']),'actor':{'principalType':'user','id':ACTOR,'kind':'admin','status':'active','roleKeys':['qa']},'effectiveRoles':[{'roleKey':'qa','scope':'global'}],'modules':[{'module':'overview','route':'/dashboard','status':'allowed','actions':[actions[0]]},{'module':'content','route':'/dashboard/content','status':'allowed','actions':actions[1:]}],'scope':{'kind':'global','source':'persisted_grants'},'fieldVisibility':[],'commonQueryV1':{'products':{'enabled':False},'dealers':{'enabled':False}},'auditFoundationV1':{'enabled':False,'queryProfile':'dashboard.audit-events.v1','eventVersion':'audit-event.v1','sensitive':{'enabled':False}},'asyncJobFoundationV1':{'enabled':False,'contractVersion':'async-job.v1','queryProfile':'dashboard.async-jobs.v1','registryVersion':'async-job-registry.v1','sensitive':{'enabled':False},'mutations':{'create':False,'cancel':False,'retry':False},'artifacts':{'metadata':False,'download':False}},'workQueueFoundationV1':{'enabled':False,'contractVersion':'work-queue-item.v1','queryProfile':'dashboard.work-queue.v1','registryVersion':'work-queue-registry.v1','sensitive':{'enabled':False},'actions':{'assign':False,'acknowledge':False,'resolve':False,'dismiss':False,'reopen':False},'notifications':{'enabled':False,'contractVersion':'in-app-notification.v1','queryProfile':'dashboard.in-app-notifications.v1','markRead':False,'externalDelivery':False}},'mediaFoundationV1':{'enabled':False,'contractVersion':'media-asset.v1','queryProfile':'dashboard.media-assets.v1','registryVersion':'media-registry.v1','safeProfile':'dashboard.media-assets.safe.v1','sensitiveProfile':{'enabled':False,'profileId':'dashboard.media-assets.sensitive.v1'},'actions':{k:False for k in ['create','update','archive','restore','downloadOriginal','manageVariants']},'upload':{'enabled':False,'image':False,'pdf':False,'maxBytes':{'image':10485760,'pdf':26214400},'intentLifetimeSeconds':600,'directControlledApi':True},'preview':{'controlled':True,'pdfInline':False},'legacyAdapters':{'enabled':True,'partial':True},'externalDelivery':False,'ai':False,'bulkImportExport':False},'dataJobFoundationV1':{'enabled':state['profile']!='denied','contractVersion':'dashboard.data-jobs.v1','registryVersion':'dashboard.data-jobs.registry.v1','objectKey':'foundation.sample','imports':{'read':state['profile']!='denied','create':state['profile']!='denied','commit':state['profile']!='denied'},'exports':{'read':state['profile']!='denied','create':state['profile']!='denied','download':state['profile']!='denied'},'upload':{'controlled':True,'directAuthenticatedApi':True},'download':{'controlled':True,'directAuthenticatedApi':True},'tenantPartition':False}}}
def meta(): return {'requestId':'r-'+uuid.uuid4().hex,'queryContractVersion':'common-query.v1','pagination':{'mode':'cursor','limit':50,'hasMore':False},'sort':[{'field':'created_at','direction':'desc','nulls':'last'},{'field':'recordId','direction':'asc','nulls':'last'}],'snapshot':{'consistency':'statement','capturedAt':NOW()},'visibility':{'profileId':'dashboard.data-jobs.v1'}}
class H(BaseHTTPRequestHandler):
 def log_message(self,*a): pass
 def cors(self):
  self.send_header('Access-Control-Allow-Origin','http://127.0.0.1:4420'); self.send_header('Access-Control-Allow-Credentials','true'); self.send_header('Access-Control-Allow-Headers','Content-Type,Content-Length,If-Match,Idempotency-Key,X-Data-Job-Upload-Token,Accept'); self.send_header('Access-Control-Allow-Methods','GET,POST,PUT,OPTIONS'); self.send_header('Access-Control-Expose-Headers','Content-Disposition,X-Content-Type-Options,Cache-Control,Referrer-Policy')
 def sendj(self,o,st=200): b=json.dumps(o).encode(); self.send_response(st); self.cors(); self.send_header('Content-Type','application/json'); self.send_header('Content-Length',str(len(b))); self.end_headers(); self.wfile.write(b)
 def sendb(self,b): self.send_response(200); self.cors(); self.send_header('Content-Type','text/csv'); self.send_header('Content-Disposition','attachment; filename="foundation-sample.csv"'); self.send_header('X-Content-Type-Options','nosniff'); self.send_header('Cache-Control','private, no-store'); self.send_header('Referrer-Policy','no-referrer'); self.send_header('Content-Length',str(len(b))); self.end_headers(); self.wfile.write(b)
 def body(self): return self.rfile.read(int(self.headers.get('Content-Length','0') or 0))
 def record(self,b=None): state['requests'].append({'method':self.command,'path':self.path,'body':b,'token':bool(self.headers.get('X-Data-Job-Upload-Token')),'idempotency':self.headers.get('Idempotency-Key'),'ifMatch':self.headers.get('If-Match'),'length':self.headers.get('Content-Length'),'actor':ACTOR,'scope':state['profile']})
 def do_OPTIONS(self): self.send_response(204); self.cors(); self.end_headers()
 def do_GET(self):
  self.record(); u=urllib.parse.urlparse(self.path); p=u.path
  if p=='/control/state': return self.sendj({'actor':ACTOR,'importId':IMP,'exportId':EXP,'state':state})
  if p=='/api/v1/dashboard/foundation': return self.sendj(foundation())
  if p=='/api/v1/dashboard/authorization': return self.sendj(auth())
  if p=='/api/v1/dashboard/data-jobs/imports': return self.sendj({'data':([] if not state['import_status'] else [imp()]),'meta':meta()})
  if p==f'/api/v1/dashboard/data-jobs/imports/{IMP}': return self.sendj({'data':imp()})
  if p==f'/api/v1/dashboard/data-jobs/imports/{IMP}/preview': return self.sendj({'data':{'id':IMP,'status':'preview_ready','summary':imp('preview_ready')['summary'],'rows':[{'row_number':2,'normalized':{'external_key':'safe','label':'Safe','state':'active','quantity':1,'effective_date':None,'note':'safe'},'validation_status':'valid','validation_errors':[],'commit_status':'pending','commit_errors':[]},{'row_number':3,'normalized':{'external_key':'bad'},'validation_status':'invalid','validation_errors':[{'code':'FIELD_REQUIRED','field':'label'}],'commit_status':'skipped','commit_errors':[]}],'version':2,'capabilities':caps(commit=True)},'page':{'limit':50,'next_cursor':None}})
  if p=='/api/v1/dashboard/data-jobs/exports': return self.sendj({'data':([exp()] if state['export_status'] else []),'meta':meta()})
  if p==f'/api/v1/dashboard/data-jobs/exports/{EXP}': return self.sendj({'data':exp()})
  if p==f'/api/v1/dashboard/data-jobs/exports/{EXP}/download' and state['malicious_download']: self.send_response(302); self.cors(); self.send_header('Location','https://storage.invalid/evil.csv'); self.end_headers(); return
  if p==f'/api/v1/dashboard/data-jobs/exports/{EXP}/download': return self.sendb(b'external_key,label,state,quantity,effective_date,note\r\n\'=x,Safe,active,1,,\r\n')
  return self.sendj({'code':'DASHBOARD_NOT_FOUND'},404)
 def do_POST(self):
  raw=self.body(); data=json.loads(raw or b'{}'); self.record(data); p=urllib.parse.urlparse(self.path).path
  if p=='/control': state.update({k:v for k,v in data.items() if k in state}); state['requests']=[] if data.get('reset') else state['requests']; return self.sendj({'ok':True})
  if p=='/api/v1/dashboard/data-jobs/imports': state['import_status']='awaiting_upload'; return self.sendj({'data':{'id':IMP,'object_key':'foundation.sample','status':'awaiting_upload','upload':{'method':'PUT','endpoint':f'/dashboard/data-jobs/imports/{IMP}/content','token':TOKEN,'expires_at':(datetime.now(timezone.utc)+timedelta(minutes=5)).isoformat().replace('+00:00','Z')},'version':1}},201)
  if p==f'/api/v1/dashboard/data-jobs/imports/{IMP}/commit' and state['import_status']=='awaiting_upload': return self.sendj({'code':'IMPORT_NOT_READY'},409)
  if p==f'/api/v1/dashboard/data-jobs/imports/{IMP}/commit': state['import_status']='completed_with_errors'; return self.sendj({'data':imp()})
  if p=='/api/v1/dashboard/data-jobs/exports': state['export_status']='completed'; return self.sendj({'data':exp()},202)
  if p.endswith('/cancel'): state['import_status']='cancelled' if '/imports/' in p else state['import_status']; state['export_status']='cancelled' if '/exports/' in p else state['export_status']; return self.sendj({'data':imp() if '/imports/' in p else exp()})
  return self.sendj({'code':'DASHBOARD_NOT_FOUND'},404)
 def do_PUT(self):
  raw=self.body(); self.record({'bytes':len(raw)}); p=urllib.parse.urlparse(self.path).path
  if p==f'/api/v1/dashboard/data-jobs/imports/{IMP}/content':
   identity=(self.headers.get('Idempotency-Key'),raw.hex())
   if state['finalize_identity'] is None: state['finalize_identity']=identity; state['jobs']=1; state['artifacts']=1; state['import_status']='preview_ready'; result=imp('uploaded'); result['version']=2; return self.sendj({'data':result,'meta':{'replayed':False}})
   if state['finalize_identity']==identity: result=imp('uploaded'); result['version']=2; return self.sendj({'data':result,'meta':{'replayed':True}})
   return self.sendj({'code':'IDEMPOTENCY_CONFLICT'},409)
  return self.sendj({'code':'DASHBOARD_NOT_FOUND'},404)
ThreadingHTTPServer(('127.0.0.1',PORT),H).serve_forever()
