-- P10 Audit atomicity closure. Migration67 remains immutable.
ALTER TABLE public.audit_events DROP CONSTRAINT audit_events_resource_type_check;
ALTER TABLE public.audit_events ADD CONSTRAINT audit_events_resource_type_check CHECK ("resourceType" IN ('user','role','permission','dealer','dealer_location','membership','product','category','inventory','price','promotion','order','shipment','checkout_session','payment_session','refund','customer','content','review','lead','support','email','erp_job','runtime_config','feature_flag','audit_event','async_job','job_artifact','work_queue_item','in_app_notification','work_queue_source_state','media_asset','media_variant','media_usage','media_upload_intent','media_storage_operation','analytics_event'));
SET ROLE vanstro_p10_guard_owner;
REVOKE EXECUTE ON FUNCTION public.p10_ingest_event(text,text,text,text,text[],text[],text,text,uuid,text,text,text,timestamptz,timestamptz,text,text,jsonb,text,text,text,integer,text,text) FROM PUBLIC,vanstro_runtime;
RESET ROLE;
GRANT INSERT ON public.audit_events TO vanstro_p10_guard_owner;
GRANT SELECT,INSERT,UPDATE ON public.analytics_foundation_event TO vanstro_p10_guard_owner;
SET ROLE vanstro_p10_guard_owner;ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
CREATE FUNCTION public.p10_audit(actor_id text,context_revision text,scope_kind text,dealer_ids text[],location_ids text[],event_name text,schema_fingerprint text,scope_fingerprint text,resource_id text,idempotency_hash text,request_id text,result_value text,reason_value text)
RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $fn$
DECLARE audit_id uuid:=gen_random_uuid();BEGIN
 IF current_user<>'vanstro_p10_guard_owner' OR result_value NOT IN('succeeded','failed','denied') OR reason_value NOT IN('completed','idempotent_replay','idempotency_conflict','permission_required','scope_mismatch','validation_rejected','internal_failure') OR request_id!~'^[A-Za-z0-9._:-]{1,128}$' THEN RAISE EXCEPTION 'P10_AUDIT_INVALID';END IF;
 INSERT INTO public.audit_events(id,"eventVersion","occurredAt","actorType","actorId","actorDisplayClass","effectiveRoles","permissionGrants","authorizationScopeKind","dealerIds","locationIds","contextRevision","authorizationContractVersion",action,"resourceType","resourceId",result,reason,"requestId",source,"idempotencyKeyHash","eventIntentHash",metadata,sensitive,"retentionClass","retentionPolicyVersion","expiresAt","createdAt") VALUES(audit_id,'audit-event.v1',CURRENT_TIMESTAMP,'admin_user',actor_id,'staff','[]'::jsonb,jsonb_build_array(jsonb_build_object('permissionKey','analytics.events.read_summary','scope',jsonb_build_object('kind',scope_kind,'dealerIds',dealer_ids,'locationIds',location_ids))),scope_kind,to_jsonb(dealer_ids),to_jsonb(location_ids),context_revision,'dashboard-authorization.v1','create','analytics_event',resource_id,result_value,reason_value,request_id,'dashboard_api',NULL,NULL,jsonb_build_object('schemaVersion','audit-metadata.v1','entries',jsonb_build_object('eventType',event_name,'schemaFingerprint',schema_fingerprint,'scopeFingerprint',scope_fingerprint,'consentClass','analytics','result',result_value,'reasonCode',reason_value)),false,'default','audit-retention.v1',CURRENT_TIMESTAMP+interval '730 days',CURRENT_TIMESTAMP);RETURN audit_id;END $fn$;

CREATE FUNCTION public.p10_ingest_event_v2(session_hash text,actor_id text,context_revision text,scope_kind text,dealer_ids text[],location_ids text[],scope_fingerprint text,field_fingerprint text,event_id uuid,event_name text,event_version text,schema_fingerprint text,occurred_at timestamptz,observed_at timestamptz,subject_digest text,resource_id text,dimensions jsonb,idempotency_hash text,intent_hash text,occurrence_identity text,sequence_value integer,consent_id text,consent_version text,request_id text)
RETURNS TABLE(id uuid,outcome text,late boolean,ingested_at timestamptz,audit_id uuid)
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $fn$
DECLARE existing public.analytics_foundation_event%ROWTYPE;now_value timestamptz:=CURRENT_TIMESTAMP;authorized boolean;consent_ok boolean;aid uuid;
BEGIN
 SELECT EXISTS(SELECT 1 FROM public.refresh_sessions s JOIN public.users u ON u.id=s."userId" JOIN public.user_roles ur ON ur."userId"=u.id JOIN public.role_permissions rp ON rp."roleId"=ur."roleId" JOIN public.permissions p ON p.id=rp."permissionId" WHERE s."tokenHash"=session_hash AND s."userId"=actor_id AND s."revokedAt" IS NULL AND s."expiresAt">now_value AND u.status='active' AND p.key='analytics.events.read_summary') INTO authorized;
 SELECT EXISTS(SELECT 1 FROM public.privacy_consent_events c WHERE c."anonymousId"=consent_id AND c.id=(SELECT latest.id FROM public.privacy_consent_events latest WHERE latest."anonymousId"=consent_id ORDER BY latest."createdAt" DESC LIMIT 1) AND c.preferences->>'analytics'='true') INTO consent_ok;
 IF NOT authorized OR NOT consent_ok THEN aid:=public.p10_audit(actor_id,context_revision,scope_kind,dealer_ids,location_ids,event_name,schema_fingerprint,scope_fingerprint,resource_id,idempotency_hash,request_id,'denied',CASE WHEN NOT authorized THEN 'permission_required' ELSE 'validation_rejected' END);RETURN QUERY SELECT NULL::uuid,'denied',false,NULL::timestamptz,aid;RETURN;END IF;
 IF current_database()!~*'(test|smoke|disposable)' OR event_name<>'foundation.analytics.observed.v1' OR event_version<>'analytics-event-schema.v1' OR schema_fingerprint!~'^[0-9a-f]{64}$' OR subject_digest!~'^[0-9a-f]{64}$' OR idempotency_hash!~'^[0-9a-f]{64}$' OR intent_hash!~'^[0-9a-f]{64}$' OR scope_kind NOT IN('global','dealer','location') OR occurred_at>now_value+interval '5 minutes' OR occurred_at<now_value-interval '30 days' OR observed_at>now_value+interval '5 minutes' THEN aid:=public.p10_audit(actor_id,context_revision,scope_kind,dealer_ids,location_ids,event_name,schema_fingerprint,scope_fingerprint,resource_id,idempotency_hash,request_id,'denied','validation_rejected');RETURN QUERY SELECT NULL::uuid,'invalid',false,NULL::timestamptz,aid;RETURN;END IF;
 SELECT * INTO existing FROM public.analytics_foundation_event e WHERE e."eventName"=event_name AND e.producer='dashboard_admin' AND e."subjectDigest"=subject_digest AND e."scopeFingerprint"=scope_fingerprint AND e."resourceType"='foundation_sample' AND e."resourceId"=resource_id AND e."idempotencyKeyHash"=idempotency_hash FOR UPDATE;
 IF FOUND THEN IF existing."eventIntentHash"<>intent_hash THEN aid:=public.p10_audit(actor_id,context_revision,scope_kind,dealer_ids,location_ids,event_name,schema_fingerprint,scope_fingerprint,resource_id,idempotency_hash,request_id,'failed','idempotency_conflict');RETURN QUERY SELECT existing.id,'conflict',existing.late,existing."ingestedAt",aid;RETURN;END IF;aid:=public.p10_audit(actor_id,context_revision,scope_kind,dealer_ids,location_ids,event_name,schema_fingerprint,scope_fingerprint,resource_id,idempotency_hash,request_id,'succeeded','idempotent_replay');RETURN QUERY SELECT existing.id,'replayed',existing.late,existing."ingestedAt",aid;RETURN;END IF;
 INSERT INTO public.analytics_foundation_event(id,"eventName","eventVersion","schemaVersion","schemaFingerprint",producer,source,"occurredAt","observedAt","ingestedAt","subjectClass","subjectDigest","contextRevision","authorizationScopeKind","dealerIds","locationIds","scopeFingerprint","fieldVisibilityFingerprint","resourceType","resourceId",dimensions,"idempotencyKeyHash","eventIntentHash","occurrenceIdentity",sequence,provenance,"consentClass","consentVersion",late,"expiresAt") VALUES(event_id,event_name,event_version,event_version,schema_fingerprint,'dashboard_admin','dashboard_api',occurred_at,observed_at,now_value,'admin_user',subject_digest,context_revision,scope_kind,dealer_ids,location_ids,scope_fingerprint,field_fingerprint,'foundation_sample',resource_id,dimensions,idempotency_hash,intent_hash,occurrence_identity,sequence_value,'p10-owned-conformance','analytics',consent_version,occurred_at<now_value-interval '1 minute',now_value+interval '30 days') RETURNING * INTO existing;
 aid:=public.p10_audit(actor_id,context_revision,scope_kind,dealer_ids,location_ids,event_name,schema_fingerprint,scope_fingerprint,resource_id,idempotency_hash,request_id,'succeeded','completed');RETURN QUERY SELECT existing.id,'accepted',existing.late,existing."ingestedAt",aid;
END $fn$;
REVOKE CREATE ON SCHEMA public FROM vanstro_p10_guard_owner;
ALTER FUNCTION public.p10_audit(text,text,text,text[],text[],text,text,text,text,text,text,text,text) OWNER TO vanstro_p10_guard_owner;
ALTER FUNCTION public.p10_ingest_event_v2(text,text,text,text,text[],text[],text,text,uuid,text,text,text,timestamptz,timestamptz,text,text,jsonb,text,text,text,integer,text,text,text) OWNER TO vanstro_p10_guard_owner;
REVOKE ALL ON FUNCTION public.p10_audit(text,text,text,text[],text[],text,text,text,text,text,text,text,text),public.p10_ingest_event_v2(text,text,text,text,text[],text[],text,text,uuid,text,text,text,timestamptz,timestamptz,text,text,jsonb,text,text,text,integer,text,text,text) FROM PUBLIC;GRANT EXECUTE ON FUNCTION public.p10_ingest_event_v2(text,text,text,text,text[],text[],text,text,uuid,text,text,text,timestamptz,timestamptz,text,text,jsonb,text,text,text,integer,text,text,text) TO vanstro_runtime;RESET ROLE;
