import assert from "node:assert/strict";
import test from "node:test";
import { COMMON_QUERY_ENDPOINT_MANIFEST, COMMON_QUERY_PROFILES, CommonQueryError, canonicalOrder, createCursorCodec, domainFingerprint, fieldProfileFingerprint, formatCursorMeta, formatOffsetMeta, grantFingerprint, jcsCanonicalize, parseCommonQuery, parseCursorKeyset, queryFingerprint, type CursorBindings } from "./common-query.js";
function code(run:()=>unknown){try{run();}catch(e){return (e as CommonQueryError).code}throw Error("expected error")}
test("registry freezes eight profiles and exact proof semantics",()=>{assert.equal(COMMON_QUERY_ENDPOINT_MANIFEST.length,8);assert.deepEqual(COMMON_QUERY_PROFILES.products.search&&COMMON_QUERY_PROFILES.products.search.fields,["name","slug","manufacturerPartNumber","skuCode"]);assert.equal(COMMON_QUERY_PROFILES.dealers.defaultSort,"recordId");assert.deepEqual(canonicalOrder(COMMON_QUERY_PROFILES.dealers,parseCommonQuery(COMMON_QUERY_PROFILES.dealers,"queryVersion=common-query.v1")),[{field:"recordId",direction:"asc",nulls:"last"}])});
test("strict parser occurrence precedence and immutable typed normalization",()=>{const p=COMMON_QUERY_PROFILES.products;assert.equal(code(()=>parseCommonQuery(p,`queryVersion=x&q=${"a".repeat(2100)}`)),"QUERY_VERSION_UNSUPPORTED");assert.equal(code(()=>parseCommonQuery(p,`queryVersion=x&limit=1&limit=2&q=${"a".repeat(2100)}`)),"QUERY_INVALID");assert.equal(code(()=>parseCommonQuery(p,`queryVersion=common-query.v1&q=${"a".repeat(2100)}`)),"QUERY_INVALID");assert.equal(code(()=>parseCommonQuery(p,`queryVersion=common-query.v1&offset=bad&q=${"a".repeat(2100)}`)),"QUERY_INVALID");assert.equal(code(()=>parseCommonQuery(p,`queryVersion=common-query.v1&status=active&padding=${"a".repeat(2100)}`)),"QUERY_FILTER_UNSUPPORTED");assert.equal(code(()=>parseCommonQuery(p,"queryVersion=x&limit=abc")),"QUERY_VERSION_UNSUPPORTED");assert.equal(code(()=>parseCommonQuery(p,"queryVersion=x&limit=1&limit=2")),"QUERY_INVALID");assert.equal(code(()=>parseCommonQuery(p,"queryVersion=common-query.v1&queryVersion=x")),"QUERY_INVALID");assert.equal(code(()=>parseCommonQuery(p,"queryVersion=common-query.v1&status=unknown")),"QUERY_FILTER_UNSUPPORTED");assert.equal(code(()=>parseCommonQuery(p,"queryVersion=common-query.v1&q=Stra%C3%9Fe")),"QUERY_SEARCH_UNSUPPORTED");assert.equal(code(()=>parseCommonQuery(p,"queryVersion=common-query.v1&includeSummary=true")),"QUERY_FILTER_UNSUPPORTED");const q=parseCommonQuery(p,"queryVersion=common-query.v1&status=draft&status=active&isUncategorized=false&q=%20ABC%20");assert.deepEqual(q.filters,{isUncategorized:false,status:["active","draft"]});assert.equal(q.q,"abc");assert.equal(q.includeSummary,false)});
test("JCS domain fingerprints have stable framing",()=>{const value={z:2,a:[true,"x"]};assert.equal(jcsCanonicalize(value),'{"a":[true,"x"],"z":2}');assert.equal(domainFingerprint("example",value),domainFingerprint("example",{a:[true,"x"],z:2}));assert.notEqual(domainFingerprint("example",value),domainFingerprint("other",value))});
const rawKey=Buffer.alloc(32,9);const keyset=parseCursorKeyset(JSON.stringify({activeKid:"k1",keys:[{kid:"k1",key:rawKey.toString("base64"),mode:"active"},{kid:"old",key:Buffer.alloc(32,8).toString("base64url"),mode:"decrypt-only"}]}));
const query=parseCommonQuery(COMMON_QUERY_PROFILES.dealers,"queryVersion=common-query.v1&limit=25");const bindings:CursorBindings={resource:"dealers",profileVersion:"dashboard.dealers.v1",permissionKey:"dealers.read",actorId:"actor-a",contextRevision:"revision-a",grantFingerprint:grantFingerprint({permissionKey:"dealers.read",global:false,dealerIds:["a"],locationIds:[]}),fieldProfileHash:fieldProfileFingerprint(COMMON_QUERY_PROFILES.dealers),queryHash:queryFingerprint(COMMON_QUERY_PROFILES.dealers,query),order:canonicalOrder(COMMON_QUERY_PROFILES.dealers,query)};
test("cq1 AES-GCM wire, time, AAD and previous key behavior",()=>{const now=1_800_000_000_000;const codec=createCursorCodec(keyset,{now:()=>now,randomBytes:()=>Buffer.alloc(12,7)});const token=codec.seal(bindings,["dealer-id"]);assert.match(token,/^cq1\.k1\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+$/);assert.doesNotMatch(token,/actor|dealer-id/);assert.deepEqual(codec.open(token,bindings).position,["dealer-id"]);assert.equal(code(()=>codec.open(token.slice(0,-1)+(token.endsWith("A")?"B":"A"),bindings)),"CURSOR_INVALID");assert.equal(code(()=>createCursorCodec(keyset,{now:()=>now+900_000}).open(token,bindings)),"CURSOR_INVALID");const oldSet=parseCursorKeyset(JSON.stringify({activeKid:"old",keys:[{kid:"old",key:Buffer.alloc(32,8).toString("base64"),mode:"active"},{kid:"k1",key:rawKey.toString("base64"),mode:"decrypt-only"}]}));const oldToken=createCursorCodec(oldSet,{now:()=>now,randomBytes:()=>Buffer.alloc(12,6)}).seal(bindings,["id"]);assert.deepEqual(createCursorCodec(keyset,{now:()=>now}).open(oldToken,bindings).position,["id"])});
test("query hash excludes after and offset but binds profile",()=>{const a=parseCommonQuery(COMMON_QUERY_PROFILES.dealers,"queryVersion=common-query.v1&after=a");const b=parseCommonQuery(COMMON_QUERY_PROFILES.dealers,"queryVersion=common-query.v1&after=b");assert.equal(queryFingerprint(COMMON_QUERY_PROFILES.dealers,a),queryFingerprint(COMMON_QUERY_PROFILES.dealers,b));assert.notEqual(queryFingerprint(COMMON_QUERY_PROFILES.dealers,a),queryFingerprint(COMMON_QUERY_PROFILES.inventory,a))});
test("strict meta preserves empty and out-of-range semantics",()=>{const t="2026-08-02T00:00:00.000Z";const q=parseCommonQuery(COMMON_QUERY_PROFILES.products,"queryVersion=common-query.v1&offset=25");assert.deepEqual(formatOffsetMeta({requestId:"r",profile:COMMON_QUERY_PROFILES.products,query:q as never,total:0,capturedAt:t}).pagination,{mode:"offset",limit:25,offset:25,hasNext:false,hasPrevious:false});const c=parseCommonQuery(COMMON_QUERY_PROFILES.dealers,"queryVersion=common-query.v1");assert.equal(formatCursorMeta({requestId:"r",profile:COMMON_QUERY_PROFILES.dealers,query:c as never,capturedAt:t,hasMore:false}).snapshot.capturedAt,t)});
