import { prisma, type Prisma } from "@vanstro/db";
import { Hono, type Context } from "hono";
import { promoteContactToErp } from "../crm/service.js";
import { publicError } from "../public-errors.js";
import { type DashboardEnv, writeAudit } from "./access.js";
import { permissionGrant, resolveDashboardAuthorization } from "./authorization.js";
import { badRequest, notFound, optionalString, pageMeta, parsePagination, readBody } from "./request.js";
const CRM_STAGES = new Set(["registered","engaged","checkout_started","customer","high_intent","archived"]);
function noStore(context: Context){context.header("Cache-Control","private, no-store")}
async function pii(context: Context<DashboardEnv>){return permissionGrant(context.get("p02Authorization"),"customers.pii.read")?.global===true}
function baseSelect(canReadPii:boolean){return {id:true,stage:true,source:true,erpSyncStatus:true,lastActivityAt:true,createdAt:true,updatedAt:true,userId:true,owner:{select:{id:true,adminProfile:{select:{displayName:true}}}},...(canReadPii?{email:true,firstName:true,lastName:true,phone:true}:{})} satisfies Prisma.CrmContactSelect}
function baseDto(contact:any){return {id:contact.id,stage:contact.stage,source:contact.source,erpSyncStatus:contact.erpSyncStatus,lastActivityAt:contact.lastActivityAt.toISOString(),createdAt:contact.createdAt.toISOString(),updatedAt:contact.updatedAt.toISOString(),promotionEligible:!contact.userId,...(contact.owner?{owner:{id:contact.owner.id,...(contact.owner.adminProfile?.displayName?{displayLabel:contact.owner.adminProfile.displayName}:{})}}:{}),...("email" in contact?{email:contact.email,firstName:contact.firstName,lastName:contact.lastName,phone:contact.phone}:{})}}
const detailRelations={notes:{select:{id:true,createdAt:true},orderBy:[{createdAt:"desc" as const},{id:"desc" as const}]},events:{select:{id:true,type:true,createdAt:true},orderBy:[{createdAt:"desc" as const},{id:"desc" as const}]},tasks:{select:{id:true,status:true,dueAt:true,completedAt:true,createdAt:true,updatedAt:true},orderBy:[{status:"asc" as const},{dueAt:"asc" as const},{createdAt:"desc" as const},{id:"desc" as const}]}};
function detailDto(contact:any){return {...baseDto(contact),notes:contact.notes.map((n:any)=>({id:n.id,createdAt:n.createdAt.toISOString()})),events:contact.events.map((e:any)=>({id:e.id,type:e.type,createdAt:e.createdAt.toISOString()})),tasks:contact.tasks.map(taskDto)}}
function taskDto(task:any){return {id:task.id,status:task.status,dueAt:task.dueAt?.toISOString()??null,completedAt:task.completedAt?.toISOString()??null,createdAt:task.createdAt.toISOString(),updatedAt:task.updatedAt.toISOString()}}
async function loadDetail(id:string,canReadPii:boolean){return prisma.crmContact.findUnique({where:{id},select:{...baseSelect(canReadPii),...detailRelations}})}
export function createDashboardCrmRoutes(){const routes=new Hono<DashboardEnv>();routes.use("/dashboard/crm/*",async(c,n)=>{noStore(c);await n()});
routes.get("/dashboard/crm/contacts",async c=>{if(new URL(c.req.url).searchParams.has("q"))return publicError(c,400,"QUERY_SEARCH_UNSUPPORTED","CRM search is not supported.",{q:"unsupported"});const pagination=parsePagination(c),canReadPii=await pii(c),stage=c.req.query("stage");const where:Prisma.CrmContactWhereInput=stage&&CRM_STAGES.has(stage)?{stage:stage as never}:{};const [contacts,total]=await Promise.all([prisma.crmContact.findMany({where,select:baseSelect(canReadPii),orderBy:[{lastActivityAt:"desc"},{id:"desc"}],skip:pagination.skip,take:pagination.take}),prisma.crmContact.count({where})]);return c.json({data:contacts.map(baseDto),meta:pageMeta(pagination,total)})});
routes.get("/dashboard/crm/contacts/:id",async c=>{const contact=await loadDetail(c.req.param("id"),await pii(c));if(!contact)return notFound(c,"CRM contact not found.");return c.json({data:detailDto(contact)})});
routes.patch("/dashboard/crm/contacts/:id",async c=>{const body=await readBody(c);if(!body)return badRequest(c,"JSON body is required.");const stage=optionalString(body,"stage"),ownerUserId=optionalString(body,"ownerUserId");if(stage&&!CRM_STAGES.has(stage))return badRequest(c,"stage is invalid.");if(ownerUserId&&!await prisma.user.findFirst({where:{id:ownerUserId,kind:"admin",status:"active"}}))return badRequest(c,"ownerUserId must reference an active admin.");const contact=await prisma.crmContact.update({where:{id:c.req.param("id")},data:{stage:stage as never,phone:optionalString(body,"phone"),firstName:optionalString(body,"firstName"),lastName:optionalString(body,"lastName"),...(body.ownerUserId===null?{ownerUserId:null}:ownerUserId?{ownerUserId}:{}),lastActivityAt:new Date()}});if(stage)await prisma.crmContactEvent.create({data:{contactId:contact.id,type:"stage_change",payload:{to:stage,source:"dashboard"},actorUserId:c.get("actorUserId")}});await writeAudit(c,"dashboard.crm.contacts.update","crm_contact",contact.id,{stage});const loaded=await loadDetail(contact.id,await pii(c));return c.json({data:detailDto(loaded!)})});
routes.post("/dashboard/crm/contacts/:id/tasks",async c=>{const body=await readBody(c),title=body?optionalString(body,"title"):undefined;if(!body||!title)return badRequest(c,"title is required.");const dueValue=optionalString(body,"dueAt"),dueAt=dueValue?new Date(dueValue):undefined;if(dueAt&&Number.isNaN(dueAt.getTime()))return badRequest(c,"dueAt must be valid.");const task=await prisma.crmTask.create({data:{contactId:c.req.param("id"),assigneeUserId:optionalString(body,"assigneeUserId"),title,description:optionalString(body,"description"),dueAt}});await prisma.crmContact.update({where:{id:c.req.param("id")},data:{lastActivityAt:new Date()}});await writeAudit(c,"dashboard.crm.contacts.tasks.create","crm_contact",c.req.param("id"));return c.json({data:taskDto(task)},201)});
routes.patch("/dashboard/crm/tasks/:id",async c=>{const body=await readBody(c);if(!body)return badRequest(c,"JSON body is required.");const status=optionalString(body,"status");if(status&&!["open","completed","cancelled"].includes(status))return badRequest(c,"status is invalid.");const task=await prisma.crmTask.update({where:{id:c.req.param("id")},data:{...(status?{status}:{}),...(status==="completed"?{completedAt:new Date()}:status?{completedAt:null}:{}),...(optionalString(body,"description")?{description:optionalString(body,"description")}:{})}});await writeAudit(c,"dashboard.crm.tasks.update","crm_task",task.id);return c.json({data:taskDto(task)})});
routes.post("/dashboard/crm/contacts/:id/notes",async c=>{const body=await readBody(c),note=body?optionalString(body,"note"):undefined;if(!body||!note)return badRequest(c,"note is required.");const record=await prisma.crmContactNote.create({data:{contactId:c.req.param("id"),authorUserId:c.get("actorUserId"),note}});await prisma.$transaction([prisma.crmContact.update({where:{id:c.req.param("id")},data:{lastActivityAt:new Date()}}),prisma.crmContactEvent.create({data:{contactId:c.req.param("id"),type:"note",actorUserId:c.get("actorUserId"),payload:{noteId:record.id}}})]);await writeAudit(c,"dashboard.crm.contacts.notes.create","crm_contact",c.req.param("id"));return c.json({data:{id:record.id,createdAt:record.createdAt.toISOString()}},201)});
routes.post("/dashboard/crm/contacts/:id/promote-to-erp",async c=>{try{const result=await prisma.$transaction(tx=>promoteContactToErp(tx,c.req.param("id"),c.get("actorUserId")));if(!result)return notFound(c,"CRM contact not found.");await writeAudit(c,"dashboard.crm.contacts.promote_to_erp","crm_contact",result.id);const loaded=await loadDetail(result.id,await pii(c));return c.json({data:detailDto(loaded!)})}catch{return publicError(c,400,"DASHBOARD_INVALID","Unable to promote CRM contact.")}});return routes}
