BEGIN;

CREATE OR REPLACE FUNCTION public.auth_issue_password_reset_v1(user_email text,token_hash text,expires_at timestamptz) RETURNS boolean LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog,public AS $fn$ DECLARE uid text;BEGIN IF token_hash!~'^[0-9a-f]{64}$' OR expires_at<=CURRENT_TIMESTAMP OR expires_at>CURRENT_TIMESTAMP+interval '31 minutes' THEN RAISE EXCEPTION 'AUTH_RESET_INVALID';END IF;SELECT u.id INTO uid FROM public.users u JOIN public.password_credentials c ON c."userId"=u.id WHERE u.email=user_email AND u.status='active' FOR UPDATE OF u;IF uid IS NULL THEN RETURN false;END IF;UPDATE public.password_reset_tokens SET "usedAt"=CURRENT_TIMESTAMP WHERE "userId"=uid AND "usedAt" IS NULL;INSERT INTO public.password_reset_tokens(id,"userId","tokenHash","expiresAt","createdAt") VALUES(gen_random_uuid()::text,uid,token_hash,expires_at,CURRENT_TIMESTAMP);RETURN true;END $fn$;
CREATE OR REPLACE FUNCTION public.auth_consume_password_reset_v1(token_hash text,algorithm text,password_hash text,password_salt text,iterations integer) RETURNS text LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog,public AS $fn$ DECLARE uid text;BEGIN SELECT "userId" INTO uid FROM public.password_reset_tokens WHERE "tokenHash"=token_hash AND "usedAt" IS NULL AND "expiresAt">CURRENT_TIMESTAMP FOR UPDATE;IF uid IS NULL THEN RETURN NULL;END IF;UPDATE public.password_reset_tokens SET "usedAt"=CURRENT_TIMESTAMP WHERE "userId"=uid AND "usedAt" IS NULL;INSERT INTO public.password_credentials(id,"userId",algorithm,"passwordHash","passwordSalt",iterations,"createdAt","updatedAt") VALUES(gen_random_uuid()::text,uid,algorithm,password_hash,password_salt,iterations,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT("userId") DO UPDATE SET algorithm=EXCLUDED.algorithm,"passwordHash"=EXCLUDED."passwordHash","passwordSalt"=EXCLUDED."passwordSalt",iterations=EXCLUDED.iterations,"updatedAt"=CURRENT_TIMESTAMP;UPDATE public.refresh_sessions SET "revokedAt"=CURRENT_TIMESTAMP WHERE "userId"=uid AND "revokedAt" IS NULL;RETURN uid;END $fn$;
CREATE OR REPLACE FUNCTION public.auth_register_customer_session_v1(user_id text,user_email text,first_name text,last_name text,algorithm text,password_hash text,password_salt text,iterations integer,token_hash text,user_agent text,ip_address text,expires_at timestamptz) RETURNS text LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog,public AS $fn$ BEGIN IF user_email IS NULL OR first_name IS NULL OR last_name IS NULL OR algorithm<>'pbkdf2_sha256' OR iterations<100000 OR token_hash!~'^[0-9a-f]{64}$' OR expires_at<=CURRENT_TIMESTAMP OR expires_at>CURRENT_TIMESTAMP+interval '8 days' THEN RAISE EXCEPTION 'AUTH_REGISTER_INVALID';END IF;INSERT INTO public.users(id,email,kind,status,"createdAt","updatedAt") VALUES(user_id,user_email,'customer','active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);INSERT INTO public.customer_profiles(id,"userId","firstName","lastName","createdAt","updatedAt") VALUES(gen_random_uuid()::text,user_id,first_name,last_name,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);INSERT INTO public.password_credentials(id,"userId",algorithm,"passwordHash","passwordSalt",iterations,"createdAt","updatedAt") VALUES(gen_random_uuid()::text,user_id,algorithm,password_hash,password_salt,iterations,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);INSERT INTO public.refresh_sessions(id,"userId","tokenHash","userAgent","ipAddress","expiresAt","createdAt") VALUES(gen_random_uuid()::text,user_id,token_hash,user_agent,ip_address,expires_at,CURRENT_TIMESTAMP);RETURN user_id;END $fn$;
CREATE OR REPLACE FUNCTION public.auth_password_challenge_v1(user_email text) RETURNS TABLE(user_id text,algorithm text,password_salt text,iterations integer) LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,public AS $fn$ SELECT u.id,c.algorithm,c."passwordSalt",c.iterations FROM public.users u JOIN public.password_credentials c ON c."userId"=u.id WHERE u.email=user_email AND u.status='active' $fn$;
CREATE OR REPLACE FUNCTION public.auth_authenticate_create_session_v1(user_email text,candidate_hash text,new_token_hash text,user_agent text,ip_address text,expires_at timestamptz) RETURNS text LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog,public AS $fn$ DECLARE uid text;BEGIN SELECT u.id INTO uid FROM public.users u JOIN public.password_credentials c ON c."userId"=u.id WHERE u.email=user_email AND u.status='active' AND c.algorithm='pbkdf2_sha256' AND c."passwordHash"=candidate_hash FOR UPDATE OF u;IF uid IS NULL THEN RETURN NULL;END IF;IF new_token_hash!~'^[0-9a-f]{64}$' OR expires_at<=CURRENT_TIMESTAMP OR expires_at>CURRENT_TIMESTAMP+interval '8 days' THEN RAISE EXCEPTION 'AUTH_SESSION_INVALID';END IF;INSERT INTO public.refresh_sessions(id,"userId","tokenHash","userAgent","ipAddress","expiresAt","createdAt") VALUES(gen_random_uuid()::text,uid,new_token_hash,user_agent,ip_address,expires_at,CURRENT_TIMESTAMP);RETURN uid;END $fn$;
CREATE OR REPLACE FUNCTION public.auth_rotate_session_v1(old_token_hash text,new_token_hash text,user_agent text,ip_address text,expires_at timestamptz) RETURNS text LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog,public AS $fn$ DECLARE uid text;BEGIN UPDATE public.refresh_sessions s SET "revokedAt"=CURRENT_TIMESTAMP FROM public.users u WHERE s."tokenHash"=old_token_hash AND s."userId"=u.id AND s."revokedAt" IS NULL AND s."expiresAt">CURRENT_TIMESTAMP AND u.status='active' RETURNING s."userId" INTO uid;IF uid IS NULL THEN RETURN NULL;END IF;IF new_token_hash!~'^[0-9a-f]{64}$' OR expires_at<=CURRENT_TIMESTAMP OR expires_at>CURRENT_TIMESTAMP+interval '8 days' THEN RAISE EXCEPTION 'AUTH_SESSION_INVALID';END IF;INSERT INTO public.refresh_sessions(id,"userId","tokenHash","userAgent","ipAddress","expiresAt","createdAt") VALUES(gen_random_uuid()::text,uid,new_token_hash,user_agent,ip_address,expires_at,CURRENT_TIMESTAMP);RETURN uid;END $fn$;
CREATE OR REPLACE FUNCTION public.auth_session_projection_v1(token_hash text) RETURNS TABLE(session_id text,session_token_hash text,user_id text,email text,kind text,status text,roles text[],permissions text[]) LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,public AS $fn$ SELECT s.id,s."tokenHash",u.id,u.email,u.kind::text,u.status::text,COALESCE((SELECT array_agg(DISTINCT r.key ORDER BY r.key) FROM public.user_roles ur JOIN public.roles r ON r.id=ur."roleId" WHERE ur."userId"=u.id),ARRAY[]::text[]),COALESCE((SELECT array_agg(DISTINCT p.key ORDER BY p.key) FROM public.user_roles ur JOIN public.role_permissions rp ON rp."roleId"=ur."roleId" JOIN public.permissions p ON p.id=rp."permissionId" WHERE ur."userId"=u.id),ARRAY[]::text[]) FROM public.refresh_sessions s JOIN public.users u ON u.id=s."userId" WHERE s."tokenHash"=token_hash AND s."revokedAt" IS NULL AND s."expiresAt">CURRENT_TIMESTAMP AND u.status='active' $fn$;
CREATE OR REPLACE FUNCTION public.auth_revoke_self_session_v1(token_hash text) RETURNS boolean LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog,public AS $fn$ DECLARE n bigint;BEGIN UPDATE public.refresh_sessions SET "revokedAt"=CURRENT_TIMESTAMP WHERE "tokenHash"=token_hash AND "revokedAt" IS NULL;GET DIAGNOSTICS n=ROW_COUNT;RETURN n=1;END $fn$;
CREATE OR REPLACE FUNCTION public.auth_revoke_all_self_sessions_v1(token_hash text) RETURNS bigint LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog,public AS $fn$ DECLARE uid text;n bigint;BEGIN SELECT "userId" INTO uid FROM public.refresh_sessions WHERE "tokenHash"=token_hash AND "revokedAt" IS NULL AND "expiresAt">CURRENT_TIMESTAMP FOR UPDATE;IF uid IS NULL THEN RETURN 0;END IF;UPDATE public.refresh_sessions SET "revokedAt"=CURRENT_TIMESTAMP WHERE "userId"=uid AND "revokedAt" IS NULL;GET DIAGNOSTICS n=ROW_COUNT;RETURN n;END $fn$;
CREATE OR REPLACE FUNCTION public.auth_admin_revoke_user_sessions_v1(session_token_hash text,expected_actor_id text,target_user_id text) RETURNS bigint LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog,public AS $fn$ DECLARE context jsonb;n bigint;BEGIN context:=public.p02_dashboard_authorization_context_v1(session_token_hash,expected_actor_id);IF NOT EXISTS(SELECT 1 FROM jsonb_array_elements(context->'permissionGrants') g WHERE g->>'permissionKey'='sessions.revoke' AND (g->>'global')::boolean) THEN RAISE EXCEPTION 'AUTH_SESSION_REVOKE_DENIED' USING ERRCODE='42501';END IF;UPDATE public.refresh_sessions SET "revokedAt"=CURRENT_TIMESTAMP WHERE "userId"=target_user_id AND "revokedAt" IS NULL;GET DIAGNOSTICS n=ROW_COUNT;RETURN n;END $fn$;


CREATE OR REPLACE FUNCTION public.p02_dashboard_authorization_context_v1(
  session_token_hash text,
  expected_actor_id text
) RETURNS jsonb
LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path = pg_catalog, public
AS $fn$
DECLARE
  actor public.users%ROWTYPE;
  global_roles jsonb;
  scoped_roles jsonb;
  grants jsonb;
  revision_input jsonb;
BEGIN
  IF session_token_hash !~ '^[0-9a-f]{64}$' OR expected_actor_id IS NULL THEN
    RAISE EXCEPTION 'P02_DASHBOARD_CONTEXT_INVALID' USING ERRCODE='22023';
  END IF;
  SELECT u.* INTO actor
  FROM public.refresh_sessions s
  JOIN public.users u ON u.id=s."userId"
  WHERE s."tokenHash"=session_token_hash AND s."userId"=expected_actor_id
    AND s."revokedAt" IS NULL AND s."expiresAt">CURRENT_TIMESTAMP
    AND u.kind='admin' AND u.status='active';
  IF NOT FOUND THEN
    RETURN jsonb_build_object('actorId',expected_actor_id,'globalRoleKeys','[]'::jsonb,'scopedRoleKeys','[]'::jsonb,'permissionGrants','[]'::jsonb,'contextRevision','unavailable');
  END IF;

  WITH rows AS (
    SELECT r.key role_key,p.key permission_key,ur.id source_id
    FROM public.user_roles ur JOIN public.roles r ON r.id=ur."roleId"
    JOIN public.role_permissions rp ON rp."roleId"=r.id JOIN public.permissions p ON p.id=rp."permissionId"
    WHERE ur."userId"=actor.id AND r.key<>'dealer_admin' AND p.key IN ('dashboard.access','users.read','users.manage','content.read','content.write','products.read','products.write','categories.write','pricing.write','inventory.read','inventory.write','orders.read','orders.update','orders.assign','payments.recover','leads.read','leads.update','dealer_applications.read','dealer_applications.update','reviews.read','reviews.moderate','support.read','support.update','email.templates.read','email.templates.write','email.outbox.read','email.outbox.retry','email.provider.read','email.provider.write','analytics.read','erp.sync.read','erp.sync.retry','erp.catalog.read','erp.catalog.sync','erp.webhooks.read','crm.read','crm.update','crm.promote','mcp.access','mcp.tools.execute','cli.access','settings.read','settings.write','service_accounts.manage','audit_logs.read','customers.pii.read','payments.reference.read','audit.read_sensitive','sessions.revoke','dealers.read','jobs.read','jobs.create','jobs.cancel','jobs.retry','jobs.read_sensitive','job_artifacts.download','work_queue.read','work_queue.assign','work_queue.acknowledge','work_queue.resolve','work_queue.dismiss','work_queue.reopen','work_queue.read_sensitive','notifications.read','notifications.mark_read','media.read','media.read_sensitive','media.create','media.update','media.archive','media.restore','media.download_original','media.manage_variants','dashboard.import.foundation_sample.read','dashboard.import.foundation_sample.create','dashboard.import.foundation_sample.commit','dashboard.export.foundation_sample.read','dashboard.export.foundation_sample.create','dashboard.export.foundation_sample.download','config.read','config.manage','config.activate','flags.read','flags.manage','flags.kill_switch','readiness.read_summary','readiness.read_detail','analytics.ingest','analytics.release.read','analytics.events.read_summary','analytics.metrics.read','analytics.metrics.read_detail','analytics.export','analytics.registry.read','analytics.operations.read')
  ) SELECT COALESCE((SELECT jsonb_agg(key ORDER BY key) FROM (SELECT DISTINCT r.key FROM public.user_roles ur JOIN public.roles r ON r.id=ur."roleId" WHERE ur."userId"=actor.id AND r.key<>'dealer_admin') q),'[]'::jsonb) INTO global_roles;

  WITH active AS (
    SELECT m.id,m."dealerId",m.revision,m.status,m."validFrom",m."expiresAt",d.status dealer_status
    FROM public.dealer_memberships m JOIN public.dealers d ON d.id=m."dealerId"
    WHERE m."userId"=actor.id AND m.status='active' AND m."revokedAt" IS NULL AND m."validFrom"<=CURRENT_TIMESTAMP
      AND (m."expiresAt" IS NULL OR m."expiresAt">CURRENT_TIMESTAMP) AND d.status='active'
  ), rows AS (
    SELECT DISTINCT r.key role_key FROM active m JOIN public.dealer_membership_roles mr ON mr."membershipId"=m.id JOIN public.roles r ON r.id=mr."roleId" WHERE r.key='dealer_admin'
  ) SELECT COALESCE(jsonb_agg(role_key ORDER BY role_key),'[]'::jsonb) INTO scoped_roles FROM rows;

  WITH direct_grants AS (
    SELECT p.key permission_key,true is_global,NULL::text dealer_id,NULL::text location_id
    FROM public.user_roles ur JOIN public.roles r ON r.id=ur."roleId"
    JOIN public.role_permissions rp ON rp."roleId"=r.id JOIN public.permissions p ON p.id=rp."permissionId"
    WHERE ur."userId"=actor.id AND r.key<>'dealer_admin' AND p.key IN ('dashboard.access','users.read','users.manage','content.read','content.write','products.read','products.write','categories.write','pricing.write','inventory.read','inventory.write','orders.read','orders.update','orders.assign','payments.recover','leads.read','leads.update','dealer_applications.read','dealer_applications.update','reviews.read','reviews.moderate','support.read','support.update','email.templates.read','email.templates.write','email.outbox.read','email.outbox.retry','email.provider.read','email.provider.write','analytics.read','erp.sync.read','erp.sync.retry','erp.catalog.read','erp.catalog.sync','erp.webhooks.read','crm.read','crm.update','crm.promote','mcp.access','mcp.tools.execute','cli.access','settings.read','settings.write','service_accounts.manage','audit_logs.read','customers.pii.read','payments.reference.read','audit.read_sensitive','sessions.revoke','dealers.read','jobs.read','jobs.create','jobs.cancel','jobs.retry','jobs.read_sensitive','job_artifacts.download','work_queue.read','work_queue.assign','work_queue.acknowledge','work_queue.resolve','work_queue.dismiss','work_queue.reopen','work_queue.read_sensitive','notifications.read','notifications.mark_read','media.read','media.read_sensitive','media.create','media.update','media.archive','media.restore','media.download_original','media.manage_variants','dashboard.import.foundation_sample.read','dashboard.import.foundation_sample.create','dashboard.import.foundation_sample.commit','dashboard.export.foundation_sample.read','dashboard.export.foundation_sample.create','dashboard.export.foundation_sample.download','config.read','config.manage','config.activate','flags.read','flags.manage','flags.kill_switch','readiness.read_summary','readiness.read_detail','analytics.ingest','analytics.release.read','analytics.events.read_summary','analytics.metrics.read','analytics.metrics.read_detail','analytics.export','analytics.registry.read','analytics.operations.read')
  ), scoped_grants AS (
    SELECT p.key,false,m."dealerId",dl.id
    FROM public.dealer_memberships m JOIN public.dealers d ON d.id=m."dealerId" AND d.status='active'
    JOIN public.dealer_membership_roles mr ON mr."membershipId"=m.id JOIN public.roles r ON r.id=mr."roleId" AND r.key='dealer_admin'
    JOIN public.role_permissions rp ON rp."roleId"=r.id JOIN public.permissions p ON p.id=rp."permissionId"
    LEFT JOIN public.dealer_membership_locations ml ON ml."membershipId"=m.id AND ml."dealerId"=m."dealerId"
    LEFT JOIN public.dealer_locations dl ON dl.id=ml."dealerLocationId" AND dl."dealerId"=m."dealerId" AND dl.status='active'
    WHERE m."userId"=actor.id AND m.status='active' AND m."revokedAt" IS NULL AND m."validFrom"<=CURRENT_TIMESTAMP AND (m."expiresAt" IS NULL OR m."expiresAt">CURRENT_TIMESTAMP) AND p.key IN ('dashboard.access','users.read','users.manage','content.read','content.write','products.read','products.write','categories.write','pricing.write','inventory.read','inventory.write','orders.read','orders.update','orders.assign','payments.recover','leads.read','leads.update','dealer_applications.read','dealer_applications.update','reviews.read','reviews.moderate','support.read','support.update','email.templates.read','email.templates.write','email.outbox.read','email.outbox.retry','email.provider.read','email.provider.write','analytics.read','erp.sync.read','erp.sync.retry','erp.catalog.read','erp.catalog.sync','erp.webhooks.read','crm.read','crm.update','crm.promote','mcp.access','mcp.tools.execute','cli.access','settings.read','settings.write','service_accounts.manage','audit_logs.read','customers.pii.read','payments.reference.read','audit.read_sensitive','sessions.revoke','dealers.read','jobs.read','jobs.create','jobs.cancel','jobs.retry','jobs.read_sensitive','job_artifacts.download','work_queue.read','work_queue.assign','work_queue.acknowledge','work_queue.resolve','work_queue.dismiss','work_queue.reopen','work_queue.read_sensitive','notifications.read','notifications.mark_read','media.read','media.read_sensitive','media.create','media.update','media.archive','media.restore','media.download_original','media.manage_variants','dashboard.import.foundation_sample.read','dashboard.import.foundation_sample.create','dashboard.import.foundation_sample.commit','dashboard.export.foundation_sample.read','dashboard.export.foundation_sample.create','dashboard.export.foundation_sample.download','config.read','config.manage','config.activate','flags.read','flags.manage','flags.kill_switch','readiness.read_summary','readiness.read_detail','analytics.ingest','analytics.release.read','analytics.events.read_summary','analytics.metrics.read','analytics.metrics.read_detail','analytics.export','analytics.registry.read','analytics.operations.read')
  ), combined AS (SELECT * FROM direct_grants UNION ALL SELECT * FROM scoped_grants), keys AS (SELECT DISTINCT permission_key FROM combined)
  SELECT COALESCE(jsonb_agg(jsonb_build_object('permissionKey',k.permission_key,'global',EXISTS(SELECT 1 FROM combined c WHERE c.permission_key=k.permission_key AND c.is_global),'dealerIds',COALESCE((SELECT jsonb_agg(DISTINCT c.dealer_id ORDER BY c.dealer_id) FROM combined c WHERE c.permission_key=k.permission_key AND c.dealer_id IS NOT NULL),'[]'::jsonb),'locationIds',COALESCE((SELECT jsonb_agg(DISTINCT c.location_id ORDER BY c.location_id) FROM combined c WHERE c.permission_key=k.permission_key AND c.location_id IS NOT NULL),'[]'::jsonb)) ORDER BY k.permission_key),'[]'::jsonb) INTO grants FROM keys k;

  SELECT jsonb_build_object('policyVersion','dashboard-authorization-policy.v4','actor',jsonb_build_object('id',actor.id,'status',actor.status),'globalRoleKeys',global_roles,'scopedRoleKeys',scoped_roles,'permissionGrants',grants,
    'memberships',COALESCE((SELECT jsonb_agg(value ORDER BY value->>'id') FROM (
      SELECT jsonb_build_object('id',m.id,'dealerId',m."dealerId",'revision',m.revision,'status',m.status,'validFrom',m."validFrom",'expiresAt',m."expiresAt",'dealerStatus',d.status,
        'roles',COALESCE((SELECT jsonb_agg(jsonb_build_object('key',r.key,'permissions',(SELECT COALESCE(jsonb_agg(p.key ORDER BY p.key),'[]'::jsonb) FROM public.role_permissions rp JOIN public.permissions p ON p.id=rp."permissionId" WHERE rp."roleId"=r.id AND p.key IN ('dashboard.access','users.read','users.manage','content.read','content.write','products.read','products.write','categories.write','pricing.write','inventory.read','inventory.write','orders.read','orders.update','orders.assign','payments.recover','leads.read','leads.update','dealer_applications.read','dealer_applications.update','reviews.read','reviews.moderate','support.read','support.update','email.templates.read','email.templates.write','email.outbox.read','email.outbox.retry','email.provider.read','email.provider.write','analytics.read','erp.sync.read','erp.sync.retry','erp.catalog.read','erp.catalog.sync','erp.webhooks.read','crm.read','crm.update','crm.promote','mcp.access','mcp.tools.execute','cli.access','settings.read','settings.write','service_accounts.manage','audit_logs.read','customers.pii.read','payments.reference.read','audit.read_sensitive','sessions.revoke','dealers.read','jobs.read','jobs.create','jobs.cancel','jobs.retry','jobs.read_sensitive','job_artifacts.download','work_queue.read','work_queue.assign','work_queue.acknowledge','work_queue.resolve','work_queue.dismiss','work_queue.reopen','work_queue.read_sensitive','notifications.read','notifications.mark_read','media.read','media.read_sensitive','media.create','media.update','media.archive','media.restore','media.download_original','media.manage_variants','dashboard.import.foundation_sample.read','dashboard.import.foundation_sample.create','dashboard.import.foundation_sample.commit','dashboard.export.foundation_sample.read','dashboard.export.foundation_sample.create','dashboard.export.foundation_sample.download','config.read','config.manage','config.activate','flags.read','flags.manage','flags.kill_switch','readiness.read_summary','readiness.read_detail','analytics.ingest','analytics.release.read','analytics.events.read_summary','analytics.metrics.read','analytics.metrics.read_detail','analytics.export','analytics.registry.read','analytics.operations.read'))) ORDER BY r.key) FROM public.dealer_membership_roles mr JOIN public.roles r ON r.id=mr."roleId" WHERE mr."membershipId"=m.id),'[]'::jsonb),
        'locations',COALESCE((SELECT jsonb_agg((dl.id||':'||dl.status) ORDER BY dl.id) FROM public.dealer_membership_locations ml JOIN public.dealer_locations dl ON dl.id=ml."dealerLocationId" AND dl."dealerId"=ml."dealerId" WHERE ml."membershipId"=m.id AND dl.status='active'),'[]'::jsonb)) value
      FROM public.dealer_memberships m JOIN public.dealers d ON d.id=m."dealerId" WHERE m."userId"=actor.id AND m.status='active' AND m."revokedAt" IS NULL AND m."validFrom"<=CURRENT_TIMESTAMP AND (m."expiresAt" IS NULL OR m."expiresAt">CURRENT_TIMESTAMP) AND d.status='active') q),'[]'::jsonb)) INTO revision_input;
  RETURN jsonb_build_object('actorId',actor.id,'globalRoleKeys',global_roles,'scopedRoleKeys',scoped_roles,'permissionGrants',grants,'contextRevision',encode(public.digest(convert_to(revision_input::text,'UTF8'),'sha256'),'hex'));
END $fn$;

CREATE OR REPLACE FUNCTION public.p02_lock_dashboard_principals_v1(session_token_hash text,expected_actor_id text,principal_ids text[])
RETURNS boolean LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog,public AS $fn$
DECLARE context jsonb;
BEGIN
 context:=public.p02_dashboard_authorization_context_v1(session_token_hash,expected_actor_id);IF context->>'contextRevision'='unavailable' OR principal_ids IS NULL OR cardinality(principal_ids) NOT BETWEEN 1 AND 16 OR cardinality(principal_ids)<>(SELECT count(DISTINCT value) FROM unnest(principal_ids) value) OR EXISTS(SELECT 1 FROM unnest(principal_ids) value WHERE value IS NULL) OR EXISTS(SELECT 1 FROM unnest(principal_ids) value WHERE NOT EXISTS(SELECT 1 FROM public.users u WHERE u.id=value)) THEN RAISE EXCEPTION 'P02_PRINCIPAL_LOCK_DENIED' USING ERRCODE='42501';END IF;
 PERFORM 1 FROM public.users WHERE id=ANY(principal_ids) ORDER BY id FOR UPDATE;PERFORM 1 FROM public.dealer_memberships WHERE "userId"=ANY(principal_ids) ORDER BY id FOR UPDATE;RETURN true;
END $fn$;

CREATE OR REPLACE FUNCTION public.p02_lock_membership_v1(session_token_hash text,expected_actor_id text,membership_id text)
RETURNS TABLE(id text,revision integer) LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog,public AS $fn$
DECLARE context jsonb;
BEGIN
 context:=public.p02_dashboard_authorization_context_v1(session_token_hash,expected_actor_id);
 IF NOT EXISTS(SELECT 1 FROM jsonb_array_elements(context->'permissionGrants') g WHERE g->>'permissionKey'='users.manage' AND (g->>'global')::boolean) OR NOT EXISTS(SELECT 1 FROM jsonb_array_elements(context->'permissionGrants') g WHERE g->>'permissionKey'='settings.write' AND (g->>'global')::boolean) THEN RAISE EXCEPTION 'P02_MEMBERSHIP_MANAGEMENT_DENIED' USING ERRCODE='42501'; END IF;
 RETURN QUERY SELECT m.id,m.revision FROM public.dealer_memberships m WHERE m.id=membership_id FOR UPDATE;
END $fn$;

CREATE OR REPLACE FUNCTION public.p02_update_membership_v1(session_token_hash text,expected_actor_id text,membership_id text,expected_revision integer,next_status text,role_keys text[],location_ids text[])
RETURNS jsonb LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog,public AS $fn$
DECLARE context jsonb;m public.dealer_memberships%ROWTYPE;role_ids text[];valid_locations text[];
BEGIN
 context:=public.p02_dashboard_authorization_context_v1(session_token_hash,expected_actor_id);
 IF NOT EXISTS(SELECT 1 FROM jsonb_array_elements(context->'permissionGrants') g WHERE g->>'permissionKey'='users.manage' AND (g->>'global')::boolean) OR NOT EXISTS(SELECT 1 FROM jsonb_array_elements(context->'permissionGrants') g WHERE g->>'permissionKey'='settings.write' AND (g->>'global')::boolean) THEN RAISE EXCEPTION 'P02_MEMBERSHIP_MANAGEMENT_DENIED' USING ERRCODE='42501'; END IF;
 SELECT * INTO m FROM public.dealer_memberships WHERE id=membership_id FOR UPDATE;IF NOT FOUND THEN RETURN NULL;END IF;IF m.revision<>expected_revision THEN RAISE EXCEPTION 'P02_REVISION_CHANGED' USING ERRCODE='40001';END IF;
 IF next_status IS NOT NULL AND next_status NOT IN('invited','active','suspended','revoked') THEN RAISE EXCEPTION 'P02_MEMBERSHIP_INVALID';END IF;
 IF role_keys IS NOT NULL THEN SELECT array_agg(id ORDER BY id) INTO role_ids FROM public.roles WHERE key=ANY(role_keys) AND key='dealer_admin';IF cardinality(COALESCE(role_ids,ARRAY[]::text[]))<>cardinality(role_keys) THEN RAISE EXCEPTION 'P02_MEMBERSHIP_REFERENCE_INVALID';END IF;DELETE FROM public.dealer_membership_roles WHERE "membershipId"=m.id;INSERT INTO public.dealer_membership_roles("membershipId","roleId") SELECT m.id,unnest(role_ids);END IF;
 IF location_ids IS NOT NULL THEN SELECT array_agg(id ORDER BY id) INTO valid_locations FROM public.dealer_locations WHERE id=ANY(location_ids) AND "dealerId"=m."dealerId" AND status='active';IF cardinality(COALESCE(valid_locations,ARRAY[]::text[]))<>cardinality(location_ids) THEN RAISE EXCEPTION 'P02_MEMBERSHIP_REFERENCE_INVALID';END IF;DELETE FROM public.dealer_membership_locations WHERE "membershipId"=m.id;INSERT INTO public.dealer_membership_locations("membershipId","dealerId","dealerLocationId") SELECT m.id,m."dealerId",unnest(valid_locations);END IF;
 UPDATE public.dealer_memberships SET status=COALESCE(next_status,status::text)::"DealerMembershipStatus","revokedAt"=CASE WHEN COALESCE(next_status,status::text)='revoked' THEN CURRENT_TIMESTAMP ELSE NULL END,revision=revision+1,"updatedAt"=CURRENT_TIMESTAMP WHERE id=m.id RETURNING * INTO m;
 RETURN jsonb_build_object('id',m.id,'revision',m.revision);
END $fn$;

CREATE OR REPLACE FUNCTION public.p02_dashboard_subject_context_v1(session_token_hash text,expected_actor_id text,subject_actor_id text)
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public AS $fn$
DECLARE caller jsonb;subject_session text;
BEGIN
 caller:=public.p02_dashboard_authorization_context_v1(session_token_hash,expected_actor_id);IF NOT EXISTS(SELECT 1 FROM jsonb_array_elements(caller->'permissionGrants') g WHERE g->>'permissionKey'='users.read' AND (g->>'global')::boolean) THEN RAISE EXCEPTION 'P02_SUBJECT_CONTEXT_DENIED' USING ERRCODE='42501';END IF;
 SELECT s."tokenHash" INTO subject_session FROM public.refresh_sessions s JOIN public.users u ON u.id=s."userId" WHERE s."userId"=subject_actor_id AND s."revokedAt" IS NULL AND s."expiresAt">CURRENT_TIMESTAMP AND u.kind='admin' AND u.status='active' ORDER BY s."createdAt" DESC LIMIT 1;
 IF subject_session IS NULL THEN RETURN jsonb_build_object('actorId',subject_actor_id,'globalRoleKeys','[]'::jsonb,'scopedRoleKeys','[]'::jsonb,'permissionGrants','[]'::jsonb,'contextRevision','unavailable');END IF;
 RETURN public.p02_dashboard_authorization_context_v1(subject_session,subject_actor_id);
END $fn$;

CREATE OR REPLACE FUNCTION public.p10_has_anonymous_analytics_consent_v1(anonymous_id text)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,public AS $fn$
  SELECT COALESCE((SELECT (e.preferences->>'analytics')::boolean FROM public.privacy_consent_events e WHERE e."anonymousId"=anonymous_id ORDER BY e."createdAt" DESC LIMIT 1),false)
$fn$;

CREATE OR REPLACE FUNCTION public.p04_append_audit_event_v1(session_token_hash text,expected_actor_id text,event jsonb)
RETURNS public.audit_events LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog,public AS $fn$
DECLARE context jsonb; inserted_id uuid; existing record;
BEGIN
  IF jsonb_typeof(event)<>'object' OR event->>'eventVersion'<>'audit-event.v1' THEN RAISE EXCEPTION 'P04_EVENT_INVALID' USING ERRCODE='22023'; END IF;
  IF event->>'actorType'='admin_user' THEN
    context:=public.p02_dashboard_authorization_context_v1(session_token_hash,expected_actor_id);
    IF context->>'contextRevision'='unavailable' OR event->>'actorId'<>expected_actor_id THEN RAISE EXCEPTION 'P04_EVENT_AUTHORITY_STALE' USING ERRCODE='42501'; END IF;
  END IF;
  INSERT INTO public.audit_events("id","eventVersion","occurredAt","actorType","actorId","actorDisplayClass","effectiveRoles","permissionGrants","authorizationScopeKind","dealerIds","locationIds","contextRevision","authorizationContractVersion","action","resourceType","resourceId","result","reason","requestId","source","correlationId","parentEventId","idempotencyKeyHash","eventIntentHash","beforeSummary","afterSummary","metadata","sensitive","retentionClass","retentionPolicyVersion","expiresAt","createdAt")
  VALUES(gen_random_uuid(),event->>'eventVersion',CURRENT_TIMESTAMP,event->>'actorType',event->>'actorId',event->>'actorDisplayClass',event->'effectiveRoles',event->'permissionGrants',event->>'authorizationScopeKind',event->'dealerIds',event->'locationIds',event->>'contextRevision',event->>'authorizationContractVersion',event->>'action',event->>'resourceType',event->>'resourceId',event->>'result',event->>'reason',event->>'requestId',event->>'source',event->>'correlationId',NULLIF(event->>'parentEventId','')::uuid,event->>'idempotencyKeyHash',event->>'eventIntentHash',NULLIF(event->'beforeSummary','null'::jsonb),NULLIF(event->'afterSummary','null'::jsonb),NULLIF(event->'metadata','null'::jsonb),COALESCE((event->>'sensitive')::boolean,false),CASE WHEN event->>'retentionClass'='high_risk' THEN 'high_risk' ELSE 'default' END,'audit-retention.v1',CURRENT_TIMESTAMP+CASE WHEN event->>'retentionClass'='high_risk' THEN interval '2555 days' ELSE interval '730 days' END,CURRENT_TIMESTAMP)
  ON CONFLICT("eventVersion","source","idempotencyKeyHash") WHERE "idempotencyKeyHash" IS NOT NULL DO NOTHING RETURNING id INTO inserted_id;
  IF inserted_id IS NOT NULL THEN RETURN (SELECT a FROM public.audit_events a WHERE a.id=inserted_id); END IF;
  SELECT id,"eventIntentHash" INTO existing FROM public.audit_events WHERE "eventVersion"=event->>'eventVersion' AND source=event->>'source' AND "idempotencyKeyHash"=event->>'idempotencyKeyHash';
  IF NOT FOUND OR existing."eventIntentHash" IS DISTINCT FROM event->>'eventIntentHash' THEN RAISE EXCEPTION 'P04_IDEMPOTENCY_CONFLICT' USING ERRCODE='23505'; END IF;
  RETURN (SELECT a FROM public.audit_events a WHERE a.id=existing.id);
END $fn$;

CREATE OR REPLACE FUNCTION public.p04_audit_list_v1(session_token_hash text,expected_actor_id text,occurred_from timestamptz,occurred_to timestamptz,range_anchor timestamptz,limit_rows integer,after_occurred_at timestamptz,after_id uuid,actor_type_filter text,actor_id_filter text,action_filter text[],resource_type_filter text[],resource_id_filter text,result_filter text[],request_id_filter text,source_filter text[],sensitive_filter boolean)
RETURNS SETOF public.audit_events LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public AS $fn$
DECLARE context jsonb; auth_grant jsonb; sensitive_grant jsonb; dealer_ids text[]; location_ids text[]; is_global boolean;
BEGIN
  context:=public.p02_dashboard_authorization_context_v1(session_token_hash,expected_actor_id); auth_grant:=(SELECT value FROM jsonb_array_elements(context->'permissionGrants') value WHERE value->>'permissionKey'='audit_logs.read');
  IF auth_grant IS NULL OR limit_rows NOT BETWEEN 1 AND 101 OR occurred_from>=occurred_to OR occurred_to>range_anchor THEN RAISE EXCEPTION 'P04_AUDIT_LIST_DENIED' USING ERRCODE='42501'; END IF;
  is_global:=COALESCE((auth_grant->>'global')::boolean,false); dealer_ids:=ARRAY(SELECT jsonb_array_elements_text(auth_grant->'dealerIds')); location_ids:=ARRAY(SELECT jsonb_array_elements_text(auth_grant->'locationIds'));
  RETURN QUERY SELECT a.* FROM public.audit_events a WHERE a."occurredAt">=occurred_from AND a."occurredAt"<occurred_to AND a."expiresAt">range_anchor
    AND (is_global OR (a."authorizationScopeKind" IN('dealer','location') AND EXISTS(SELECT 1 FROM jsonb_array_elements_text(a."dealerIds") d WHERE d=ANY(dealer_ids)) AND (a."authorizationScopeKind"='dealer' OR EXISTS(SELECT 1 FROM jsonb_array_elements_text(a."locationIds") l WHERE l=ANY(location_ids)))))
    AND (actor_type_filter IS NULL OR a."actorType"=actor_type_filter) AND (actor_id_filter IS NULL OR a."actorId"=actor_id_filter) AND (cardinality(action_filter)=0 OR a.action=ANY(action_filter)) AND (cardinality(resource_type_filter)=0 OR a."resourceType"=ANY(resource_type_filter)) AND (resource_id_filter IS NULL OR a."resourceId"=resource_id_filter) AND (cardinality(result_filter)=0 OR a.result=ANY(result_filter)) AND (request_id_filter IS NULL OR a."requestId"=request_id_filter) AND (cardinality(source_filter)=0 OR a.source=ANY(source_filter)) AND (sensitive_filter IS NULL OR a.sensitive=sensitive_filter) AND (after_occurred_at IS NULL OR (a."occurredAt",a.id)<(after_occurred_at,after_id)) ORDER BY a."occurredAt" DESC,a.id DESC LIMIT limit_rows;
END $fn$;

CREATE OR REPLACE FUNCTION public.p04_audit_detail_v1(session_token_hash text,expected_actor_id text,audit_id uuid,observed_at timestamptz)
RETURNS SETOF public.audit_events LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public AS $fn$
DECLARE context jsonb; auth_grant jsonb; dealer_ids text[]; location_ids text[]; is_global boolean;
BEGIN
  context:=public.p02_dashboard_authorization_context_v1(session_token_hash,expected_actor_id); auth_grant:=(SELECT value FROM jsonb_array_elements(context->'permissionGrants') value WHERE value->>'permissionKey'='audit_logs.read'); IF auth_grant IS NULL THEN RETURN; END IF;
  is_global:=COALESCE((auth_grant->>'global')::boolean,false); dealer_ids:=ARRAY(SELECT jsonb_array_elements_text(auth_grant->'dealerIds')); location_ids:=ARRAY(SELECT jsonb_array_elements_text(auth_grant->'locationIds'));
  RETURN QUERY SELECT a.* FROM public.audit_events a WHERE a.id=audit_id AND a."expiresAt">observed_at AND (is_global OR (a."authorizationScopeKind" IN('dealer','location') AND EXISTS(SELECT 1 FROM jsonb_array_elements_text(a."dealerIds") d WHERE d=ANY(dealer_ids)) AND (a."authorizationScopeKind"='dealer' OR EXISTS(SELECT 1 FROM jsonb_array_elements_text(a."locationIds") l WHERE l=ANY(location_ids)))));
END $fn$;

GRANT USAGE,CREATE ON SCHEMA public TO vanstro_p02_guard_owner,vanstro_p04_guard_owner;
GRANT SELECT ON TABLE public.audit_events TO vanstro_p04_guard_owner;
GRANT UPDATE ON TABLE public.users,public.dealer_memberships,public.refresh_sessions TO vanstro_p02_guard_owner;
GRANT INSERT ON TABLE public.users,public.customer_profiles,public.password_credentials,public.password_reset_tokens,public.refresh_sessions TO vanstro_p02_guard_owner;
GRANT SELECT,UPDATE ON TABLE public.password_reset_tokens,public.password_credentials TO vanstro_p02_guard_owner;
GRANT SELECT ON TABLE public.privacy_consent_events TO vanstro_p10_guard_owner;
ALTER FUNCTION public.auth_consume_password_reset_v1(text,text,text,text,integer) OWNER TO vanstro_p02_guard_owner;
ALTER FUNCTION public.auth_issue_password_reset_v1(text,text,timestamptz) OWNER TO vanstro_p02_guard_owner;
ALTER FUNCTION public.auth_register_customer_session_v1(text,text,text,text,text,text,text,integer,text,text,text,timestamptz) OWNER TO vanstro_p02_guard_owner;
ALTER FUNCTION public.auth_password_challenge_v1(text) OWNER TO vanstro_p02_guard_owner;
ALTER FUNCTION public.auth_authenticate_create_session_v1(text,text,text,text,text,timestamptz) OWNER TO vanstro_p02_guard_owner;
ALTER FUNCTION public.auth_rotate_session_v1(text,text,text,text,timestamptz) OWNER TO vanstro_p02_guard_owner;
ALTER FUNCTION public.auth_session_projection_v1(text) OWNER TO vanstro_p02_guard_owner;
ALTER FUNCTION public.auth_revoke_self_session_v1(text) OWNER TO vanstro_p02_guard_owner;
ALTER FUNCTION public.auth_revoke_all_self_sessions_v1(text) OWNER TO vanstro_p02_guard_owner;
ALTER FUNCTION public.auth_admin_revoke_user_sessions_v1(text,text,text) OWNER TO vanstro_p02_guard_owner;
ALTER FUNCTION public.p02_dashboard_authorization_context_v1(text,text) OWNER TO vanstro_p02_guard_owner;
ALTER FUNCTION public.p02_lock_dashboard_principals_v1(text,text,text[]) OWNER TO vanstro_p02_guard_owner;
ALTER FUNCTION public.p02_lock_membership_v1(text,text,text) OWNER TO vanstro_p02_guard_owner;
ALTER FUNCTION public.p02_update_membership_v1(text,text,text,integer,text,text[],text[]) OWNER TO vanstro_p02_guard_owner;
ALTER FUNCTION public.p02_dashboard_subject_context_v1(text,text,text) OWNER TO vanstro_p02_guard_owner;
ALTER FUNCTION public.p10_has_anonymous_analytics_consent_v1(text) OWNER TO vanstro_p10_guard_owner;
ALTER FUNCTION public.p04_append_audit_event_v1(text,text,jsonb) OWNER TO vanstro_p04_guard_owner;
ALTER FUNCTION public.p04_audit_list_v1(text,text,timestamptz,timestamptz,timestamptz,integer,timestamptz,uuid,text,text,text[],text[],text,text[],text,text[],boolean) OWNER TO vanstro_p04_guard_owner;
ALTER FUNCTION public.p04_audit_detail_v1(text,text,uuid,timestamptz) OWNER TO vanstro_p04_guard_owner;
SET ROLE vanstro_p02_guard_owner;
REVOKE ALL ON FUNCTION public.auth_consume_password_reset_v1(text,text,text,text,integer),public.auth_issue_password_reset_v1(text,text,timestamptz),public.auth_register_customer_session_v1(text,text,text,text,text,text,text,integer,text,text,text,timestamptz),public.auth_password_challenge_v1(text),public.auth_authenticate_create_session_v1(text,text,text,text,text,timestamptz),public.auth_rotate_session_v1(text,text,text,text,timestamptz),public.auth_session_projection_v1(text),public.auth_revoke_self_session_v1(text),public.auth_revoke_all_self_sessions_v1(text),public.auth_admin_revoke_user_sessions_v1(text,text,text),public.p02_dashboard_authorization_context_v1(text,text),public.p02_lock_dashboard_principals_v1(text,text,text[]),public.p02_lock_membership_v1(text,text,text),public.p02_update_membership_v1(text,text,text,integer,text,text[],text[]),public.p02_dashboard_subject_context_v1(text,text,text) FROM PUBLIC,vanstro_runtime,vanstro_worker_runtime;
GRANT EXECUTE ON FUNCTION public.auth_consume_password_reset_v1(text,text,text,text,integer),public.auth_register_customer_session_v1(text,text,text,text,text,text,text,integer,text,text,text,timestamptz),public.auth_password_challenge_v1(text),public.auth_authenticate_create_session_v1(text,text,text,text,text,timestamptz),public.auth_rotate_session_v1(text,text,text,text,timestamptz),public.auth_session_projection_v1(text),public.auth_revoke_self_session_v1(text),public.auth_revoke_all_self_sessions_v1(text),public.auth_issue_password_reset_v1(text,text,timestamptz),public.auth_admin_revoke_user_sessions_v1(text,text,text),public.p02_dashboard_authorization_context_v1(text,text),public.p02_lock_dashboard_principals_v1(text,text,text[]),public.p02_lock_membership_v1(text,text,text),public.p02_update_membership_v1(text,text,text,integer,text,text[],text[]),public.p02_dashboard_subject_context_v1(text,text,text) TO vanstro_runtime;
GRANT EXECUTE ON FUNCTION public.p02_dashboard_authorization_context_v1(text,text) TO vanstro_p04_guard_owner;
RESET ROLE;
SET ROLE vanstro_p10_guard_owner;
REVOKE ALL ON FUNCTION public.p10_has_anonymous_analytics_consent_v1(text) FROM PUBLIC,vanstro_runtime,vanstro_worker_runtime;
GRANT EXECUTE ON FUNCTION public.p10_has_anonymous_analytics_consent_v1(text) TO vanstro_runtime;
RESET ROLE;
SET ROLE vanstro_p04_guard_owner;
REVOKE ALL ON FUNCTION public.p04_append_audit_event_v1(text,text,jsonb),public.p04_audit_list_v1(text,text,timestamptz,timestamptz,timestamptz,integer,timestamptz,uuid,text,text,text[],text[],text,text[],text,text[],boolean),public.p04_audit_detail_v1(text,text,uuid,timestamptz) FROM PUBLIC,vanstro_runtime,vanstro_worker_runtime;
GRANT EXECUTE ON FUNCTION public.p04_append_audit_event_v1(text,text,jsonb),public.p04_audit_list_v1(text,text,timestamptz,timestamptz,timestamptz,integer,timestamptz,uuid,text,text,text[],text[],text,text[],text,text[],boolean),public.p04_audit_detail_v1(text,text,uuid,timestamptz) TO vanstro_runtime;
RESET ROLE;
REVOKE CREATE ON SCHEMA public FROM vanstro_p02_guard_owner;

DO $assert$
BEGIN
  IF (SELECT count(*) FROM pg_proc WHERE pronamespace='public'::regnamespace AND proname IN('p02_dashboard_authorization_context_v1','p02_lock_dashboard_principals_v1','p02_lock_membership_v1','p02_update_membership_v1','p02_dashboard_subject_context_v1','p04_append_audit_event_v1','p04_audit_list_v1','p04_audit_detail_v1','p10_has_anonymous_analytics_consent_v1'))<>9 THEN RAISE EXCEPTION 'M72_OVERLOAD_ASSERT'; END IF;
  IF has_table_privilege('vanstro_runtime','public.users','SELECT') OR has_table_privilege('vanstro_runtime','public.dealer_memberships','SELECT') OR has_table_privilege('vanstro_runtime','public.audit_events','SELECT') OR has_table_privilege('vanstro_runtime','public.audit_events','INSERT') OR has_table_privilege('vanstro_runtime','public.audit_events','UPDATE') OR has_table_privilege('vanstro_runtime','public.audit_events','DELETE') THEN RAISE EXCEPTION 'M72_DIRECT_TABLE_ASSERT'; END IF;
  IF NOT has_function_privilege('vanstro_runtime','public.p02_dashboard_authorization_context_v1(text,text)','EXECUTE') OR NOT has_function_privilege('vanstro_runtime','public.p04_append_audit_event_v1(text,text,jsonb)','EXECUTE') OR NOT has_function_privilege('vanstro_runtime','public.p04_audit_detail_v1(text,text,uuid,timestamptz)','EXECUTE') THEN RAISE EXCEPTION 'M72_EXECUTE_ASSERT'; END IF;
END $assert$;

GRANT SELECT,INSERT,UPDATE ON public.async_jobs TO vanstro_p04_guard_owner;
GRANT SELECT ON public.async_job_attempts,public.job_artifacts,public.media_variants TO vanstro_p04_guard_owner;
GRANT SELECT,UPDATE ON public.media_assets,public.work_queue_items TO vanstro_p04_guard_owner;
GRANT SELECT ON public.users TO vanstro_p04_guard_owner;
GRANT SELECT,INSERT ON public.in_app_notifications TO vanstro_p04_guard_owner;
GRANT SELECT,INSERT,UPDATE ON public.work_queue_source_states TO vanstro_p04_guard_owner;
SET ROLE vanstro_p02_guard_owner;
GRANT EXECUTE ON FUNCTION public.p02_dashboard_authorization_context_v1(text,text),public.p02_dashboard_subject_context_v1(text,text,text) TO vanstro_p04_guard_owner;
RESET ROLE;

CREATE FUNCTION public.p05_api_create_probe_v1(session_token_hash text,expected_actor_id text,job jsonb,idempotency_candidates text[],event_intent_hash text)
RETURNS TABLE(job_id uuid,replayed boolean) LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog,public AS $fn$
DECLARE context jsonb;g jsonb;j public.async_jobs%ROWTYPE;existing public.async_jobs%ROWTYPE;
BEGIN
 context:=public.p02_dashboard_authorization_context_v1(session_token_hash,expected_actor_id);g:=(SELECT value FROM jsonb_array_elements(context->'permissionGrants') value WHERE value->>'permissionKey'='jobs.create');
 IF g IS NULL THEN RAISE EXCEPTION 'P05_CREATE_DENIED' USING ERRCODE='42501';END IF;
 j:=jsonb_populate_record(NULL::public.async_jobs,job);j.version:=COALESCE(j.version,0);j."createdAt":=COALESCE(j."createdAt",CURRENT_TIMESTAMP);j."updatedAt":=COALESCE(j."updatedAt",CURRENT_TIMESTAMP);j."bindingRevision":=COALESCE(j."bindingRevision",0);j.attempt:=COALESCE(j.attempt,0);j."generationAttempt":=COALESCE(j."generationAttempt",0);j."retryGeneration":=COALESCE(j."retryGeneration",0);j."leaseRevision":=COALESCE(j."leaseRevision",0);j."processedCount":=COALESCE(j."processedCount",0);j."failedCount":=COALESCE(j."failedCount",0);
 IF j."jobType"<>'foundation.probe' OR j.status<>'queued' OR j."createdByActorType"<>'admin_user' OR j."createdByActorId"<>expected_actor_id OR j."contextRevision"<>context->>'contextRevision' OR j."eventIntentHash"<>event_intent_hash OR j."leaseOwner" IS NOT NULL OR NOT ((g->>'global')::boolean AND j."authorizationScopeKind"='global' OR NOT (g->>'global')::boolean AND j."authorizationScopeKind" IN('dealer','location') AND j."dealerIds"=g->'dealerIds' AND j."locationIds"=g->'locationIds') THEN RAISE EXCEPTION 'P05_CREATE_INVALID';END IF;
 SELECT * INTO existing FROM public.async_jobs WHERE "jobType"=j."jobType" AND "idempotencyKeyHash"=ANY(idempotency_candidates) FOR UPDATE;
 IF FOUND THEN IF existing."eventIntentHash"<>event_intent_hash THEN RAISE EXCEPTION 'P05_IDEMPOTENCY_CONFLICT' USING ERRCODE='23505';END IF;RETURN QUERY SELECT existing.id,true;RETURN;END IF;
 INSERT INTO public.async_jobs SELECT j.* RETURNING * INTO j;RETURN QUERY SELECT j.id,false;
END $fn$;

CREATE FUNCTION public.p05_api_list_v1(session_token_hash text,expected_actor_id text,scope_kind text,dealer_ids text[],location_ids text[],created_from timestamptz,created_to timestamptz,limit_rows integer,after_created_at timestamptz,after_id uuid,status_filter text[],job_type_filter text[],actor_filter text,cancellable_filter boolean,retryable_filter boolean)
RETURNS SETOF public.async_jobs LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public AS $fn$
DECLARE context jsonb;g jsonb;
BEGIN context:=public.p02_dashboard_authorization_context_v1(session_token_hash,expected_actor_id);g:=(SELECT value FROM jsonb_array_elements(context->'permissionGrants') value WHERE value->>'permissionKey'='jobs.read');IF g IS NULL OR limit_rows NOT BETWEEN 1 AND 101 THEN RAISE EXCEPTION 'P05_READ_DENIED' USING ERRCODE='42501';END IF;
 IF scope_kind<>(CASE WHEN (g->>'global')::boolean THEN 'global' WHEN jsonb_array_length(g->'locationIds')>0 THEN 'location' ELSE 'dealer' END) OR dealer_ids<>ARRAY(SELECT value FROM jsonb_array_elements_text(g->'dealerIds') value ORDER BY value) OR location_ids<>ARRAY(SELECT value FROM jsonb_array_elements_text(g->'locationIds') value ORDER BY value) THEN RAISE EXCEPTION 'P05_SCOPE_MISMATCH' USING ERRCODE='42501';END IF;
 RETURN QUERY SELECT j.* FROM public.async_jobs j WHERE j."createdAt">=created_from AND j."createdAt"<created_to AND ((g->>'global')::boolean OR (j."authorizationScopeKind" IN('dealer','location') AND EXISTS(SELECT 1 FROM jsonb_array_elements_text(g->'dealerIds') gd WHERE j."dealerIds" ? gd) AND (j."authorizationScopeKind"='dealer' OR EXISTS(SELECT 1 FROM jsonb_array_elements_text(g->'locationIds') gl WHERE j."locationIds" ? gl)))) AND (cardinality(status_filter)=0 OR j.status=ANY(status_filter)) AND (cardinality(job_type_filter)=0 OR j."jobType"=ANY(job_type_filter)) AND (actor_filter IS NULL OR j."createdByActorType"=actor_filter) AND (cancellable_filter IS NULL OR cancellable_filter=(j.status IN('queued','running'))) AND (retryable_filter IS NULL OR retryable_filter=(j.status='failed' AND j."retryGeneration"<j."maxRetryGenerations")) AND (after_created_at IS NULL OR (j."createdAt",j.id)<(after_created_at,after_id)) ORDER BY j."createdAt" DESC,j.id DESC LIMIT limit_rows;
END $fn$;

CREATE FUNCTION public.p05_api_detail_v1(session_token_hash text,expected_actor_id text,job_id uuid)
RETURNS SETOF public.async_jobs LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public AS $fn$
DECLARE context jsonb;g jsonb;BEGIN context:=public.p02_dashboard_authorization_context_v1(session_token_hash,expected_actor_id);g:=(SELECT value FROM jsonb_array_elements(context->'permissionGrants') value WHERE value->>'permissionKey'='jobs.read');IF g IS NULL THEN RETURN;END IF;RETURN QUERY SELECT j.* FROM public.async_jobs j WHERE j.id=job_id AND ((g->>'global')::boolean OR (j."authorizationScopeKind" IN('dealer','location') AND EXISTS(SELECT 1 FROM jsonb_array_elements_text(g->'dealerIds') d WHERE j."dealerIds" ? d) AND (j."authorizationScopeKind"='dealer' OR EXISTS(SELECT 1 FROM jsonb_array_elements_text(g->'locationIds') l WHERE j."locationIds" ? l))));END $fn$;

CREATE FUNCTION public.p05_api_artifacts_v1(session_token_hash text,expected_actor_id text,job_id uuid)
RETURNS SETOF public.job_artifacts LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public AS $fn$
BEGIN IF NOT EXISTS(SELECT 1 FROM public.p05_api_detail_v1(session_token_hash,expected_actor_id,job_id)) THEN RETURN;END IF;RETURN QUERY SELECT a.* FROM public.job_artifacts a WHERE a."jobId"=job_id ORDER BY a."createdAt",a.id;END $fn$;

CREATE FUNCTION public.p05_api_cancel_v1(session_token_hash text,expected_actor_id text,job_id uuid,expected_version integer)
RETURNS SETOF public.async_jobs LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog,public AS $fn$
DECLARE context jsonb;j public.async_jobs%ROWTYPE;g jsonb;BEGIN context:=public.p02_dashboard_authorization_context_v1(session_token_hash,expected_actor_id);g:=(SELECT value FROM jsonb_array_elements(context->'permissionGrants') value WHERE value->>'permissionKey'='jobs.cancel');IF g IS NULL THEN RAISE EXCEPTION 'P05_CANCEL_DENIED' USING ERRCODE='42501';END IF;SELECT * INTO j FROM public.async_jobs WHERE id=job_id FOR UPDATE;IF NOT FOUND OR NOT ((g->>'global')::boolean OR (j."authorizationScopeKind" IN('dealer','location') AND EXISTS(SELECT 1 FROM jsonb_array_elements_text(g->'dealerIds') d WHERE j."dealerIds" ? d) AND (j."authorizationScopeKind"='dealer' OR EXISTS(SELECT 1 FROM jsonb_array_elements_text(g->'locationIds') l WHERE j."locationIds" ? l)))) OR j.version<>expected_version OR j.status NOT IN('queued','running') OR j."jobType"<>'foundation.probe' THEN RAISE EXCEPTION 'P05_STATE_CONFLICT';END IF;UPDATE public.async_jobs SET status=CASE WHEN status='queued' THEN 'cancelled' ELSE status END,"cancellationRequestedAt"=CURRENT_TIMESTAMP,"cancellationRequestedBy"=expected_actor_id,"cancellationReason"='operator_requested',"cancelledAt"=CASE WHEN status='queued' THEN CURRENT_TIMESTAMP ELSE "cancelledAt" END,"finishedAt"=CASE WHEN status='queued' THEN CURRENT_TIMESTAMP ELSE "finishedAt" END,version=version+1,"updatedAt"=CURRENT_TIMESTAMP WHERE id=job_id RETURNING * INTO j;RETURN NEXT j;END $fn$;

CREATE FUNCTION public.p05_api_retry_v1(session_token_hash text,expected_actor_id text,job_id uuid,expected_version integer)
RETURNS SETOF public.async_jobs LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog,public AS $fn$
DECLARE context jsonb;g jsonb;j public.async_jobs%ROWTYPE;
BEGIN context:=public.p02_dashboard_authorization_context_v1(session_token_hash,expected_actor_id);g:=(SELECT value FROM jsonb_array_elements(context->'permissionGrants') value WHERE value->>'permissionKey'='jobs.retry');IF g IS NULL THEN RAISE EXCEPTION 'JOB_NOT_RETRYABLE';END IF;SELECT * INTO j FROM public.async_jobs WHERE id=job_id FOR UPDATE;IF NOT FOUND OR j."jobType"<>'foundation.probe' OR j.status<>'failed' OR j.version<>expected_version OR j."retryGeneration">=j."maxRetryGenerations" OR NOT ((g->>'global')::boolean OR (j."authorizationScopeKind" IN('dealer','location') AND EXISTS(SELECT 1 FROM jsonb_array_elements_text(g->'dealerIds') d WHERE j."dealerIds" ? d) AND (j."authorizationScopeKind"='dealer' OR EXISTS(SELECT 1 FROM jsonb_array_elements_text(g->'locationIds') l WHERE j."locationIds" ? l)))) THEN RAISE EXCEPTION 'JOB_NOT_RETRYABLE';END IF;UPDATE public.async_jobs SET status='queued',"retryGeneration"="retryGeneration"+1,"generationAttempt"=0,"nextRetryAt"=NULL,"finishedAt"=NULL,"failureClass"=NULL,"errorSummary"=NULL,version=version+1,"updatedAt"=CURRENT_TIMESTAMP WHERE id=job_id RETURNING * INTO j;RETURN NEXT j;END $fn$;

CREATE FUNCTION public.p06_api_mutate_item_v1(session_token_hash text,expected_actor_id text,item_id uuid,expected_version integer,operation text,reason text,target_user_id text,deduplication_candidates text[])
RETURNS SETOF public.work_queue_items LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog,public AS $fn$
DECLARE context jsonb;permission_key text;g jsonb;source_g jsonb;subject jsonb;subject_access jsonb;subject_read jsonb;subject_source jsonb;j public.work_queue_items%ROWTYPE;now_at timestamptz:=CURRENT_TIMESTAMP;clear_assignee boolean:=false;
BEGIN
 IF operation NOT IN('assign','unassign','acknowledge','resolve','dismiss','reopen') THEN RAISE EXCEPTION 'WORK_ITEM_STATE_CONFLICT';END IF;
 permission_key:=CASE WHEN operation IN('assign','unassign') THEN 'work_queue.assign' ELSE 'work_queue.'||operation END;
 context:=public.p02_dashboard_authorization_context_v1(session_token_hash,expected_actor_id);
 g:=(SELECT value FROM jsonb_array_elements(context->'permissionGrants') value WHERE value->>'permissionKey'=permission_key);
 SELECT * INTO j FROM public.work_queue_items WHERE id=item_id FOR UPDATE;
 IF NOT FOUND OR g IS NULL THEN RAISE EXCEPTION 'WORK_ITEM_SCOPE_CHANGED' USING ERRCODE='42501';END IF;
 source_g:=(SELECT value FROM jsonb_array_elements(context->'permissionGrants') value WHERE value->>'permissionKey'=j."sourcePermission");
 IF source_g IS NULL OR NOT ((g->>'global')::boolean OR (j."authorizationScopeKind" IN('dealer','location') AND NOT EXISTS(SELECT 1 FROM jsonb_array_elements_text(j."dealerIds") d WHERE NOT (g->'dealerIds' ? d)) AND (j."authorizationScopeKind"='dealer' OR NOT EXISTS(SELECT 1 FROM jsonb_array_elements_text(j."locationIds") l WHERE NOT (g->'locationIds' ? l))))) OR NOT ((source_g->>'global')::boolean OR (j."authorizationScopeKind" IN('dealer','location') AND NOT EXISTS(SELECT 1 FROM jsonb_array_elements_text(j."dealerIds") d WHERE NOT (source_g->'dealerIds' ? d)) AND (j."authorizationScopeKind"='dealer' OR NOT EXISTS(SELECT 1 FROM jsonb_array_elements_text(j."locationIds") l WHERE NOT (source_g->'locationIds' ? l))))) THEN RAISE EXCEPTION 'WORK_ITEM_SCOPE_CHANGED' USING ERRCODE='42501';END IF;
 IF j.version<>expected_version THEN RAISE EXCEPTION 'WORK_ITEM_STATE_CONFLICT';END IF;
 IF operation IN('assign','unassign') THEN
  IF j.status NOT IN('open','acknowledged') OR (operation='assign' AND target_user_id IS NULL) OR (operation='unassign' AND target_user_id IS NOT NULL) THEN RAISE EXCEPTION 'WORK_ITEM_NOT_ACTIONABLE';END IF;
  IF target_user_id IS NOT NULL THEN
   IF NOT EXISTS(SELECT 1 FROM public.users u WHERE u.id=target_user_id AND u.kind='admin' AND u.status='active') THEN RAISE EXCEPTION 'WORK_ITEM_ASSIGNEE_INVALID';END IF;
   subject:=public.p02_dashboard_subject_context_v1(session_token_hash,expected_actor_id,target_user_id::text);
   subject_access:=(SELECT value FROM jsonb_array_elements(subject->'permissionGrants') value WHERE value->>'permissionKey'='dashboard.access');subject_read:=(SELECT value FROM jsonb_array_elements(subject->'permissionGrants') value WHERE value->>'permissionKey'='work_queue.read');subject_source:=(SELECT value FROM jsonb_array_elements(subject->'permissionGrants') value WHERE value->>'permissionKey'=j."sourcePermission");
   IF subject_access IS NULL OR subject_read IS NULL OR subject_source IS NULL OR NOT ((subject_read->>'global')::boolean OR (j."authorizationScopeKind" IN('dealer','location') AND NOT EXISTS(SELECT 1 FROM jsonb_array_elements_text(j."dealerIds") d WHERE NOT (subject_read->'dealerIds' ? d)) AND (j."authorizationScopeKind"='dealer' OR NOT EXISTS(SELECT 1 FROM jsonb_array_elements_text(j."locationIds") l WHERE NOT (subject_read->'locationIds' ? l))))) OR NOT ((subject_source->>'global')::boolean OR (j."authorizationScopeKind" IN('dealer','location') AND NOT EXISTS(SELECT 1 FROM jsonb_array_elements_text(j."dealerIds") d WHERE NOT (subject_source->'dealerIds' ? d)) AND (j."authorizationScopeKind"='dealer' OR NOT EXISTS(SELECT 1 FROM jsonb_array_elements_text(j."locationIds") l WHERE NOT (subject_source->'locationIds' ? l))))) THEN RAISE EXCEPTION 'WORK_ITEM_ASSIGNEE_INVALID';END IF;
  END IF;
  UPDATE public.work_queue_items SET "assignedToUserId"=target_user_id,"assignedAt"=CASE WHEN target_user_id IS NULL THEN NULL ELSE now_at END,"assignedByActorType"=CASE WHEN target_user_id IS NULL THEN NULL ELSE 'admin_user' END,"assignedByActorId"=CASE WHEN target_user_id IS NULL THEN NULL ELSE expected_actor_id END,version=version+1,"updatedAt"=now_at WHERE id=item_id RETURNING * INTO j;
 ELSIF operation='acknowledge' THEN
  IF reason IS NOT NULL AND reason<>'operator_acknowledged' OR j.health='orphaned' OR j.status<>'open' THEN RAISE EXCEPTION 'WORK_ITEM_STATE_CONFLICT';END IF;
  UPDATE public.work_queue_items SET status='acknowledged',"acknowledgedAt"=now_at,"acknowledgedByActorType"='admin_user',"acknowledgedByActorId"=expected_actor_id,"lastTransitionReason"=COALESCE(reason,'operator_acknowledged'),version=version+1,"updatedAt"=now_at WHERE id=item_id RETURNING * INTO j;
 ELSIF operation IN('resolve','dismiss') THEN
  IF reason<>(CASE WHEN operation='resolve' THEN 'operator_resolved' ELSE 'not_actionable' END) OR j.status NOT IN('open','acknowledged') OR (operation='resolve' AND j.health='orphaned') THEN RAISE EXCEPTION 'WORK_ITEM_STATE_CONFLICT';END IF;
  IF operation='resolve' THEN UPDATE public.work_queue_items SET status='resolved',"acknowledgedAt"=NULL,"acknowledgedByActorType"=NULL,"acknowledgedByActorId"=NULL,"resolvedAt"=now_at,"resolvedByActorType"='admin_user',"resolvedByActorId"=expected_actor_id,"resolutionReason"=reason,"retentionExpiresAt"=now_at+interval '180 days',"lastTransitionReason"=reason,version=version+1,"updatedAt"=now_at WHERE id=item_id RETURNING * INTO j;
  ELSE UPDATE public.work_queue_items SET status='dismissed',"acknowledgedAt"=NULL,"acknowledgedByActorType"=NULL,"acknowledgedByActorId"=NULL,"dismissedAt"=now_at,"dismissedByActorType"='admin_user',"dismissedByActorId"=expected_actor_id,"dismissalReason"=reason,"retentionExpiresAt"=now_at+interval '180 days',"lastTransitionReason"=reason,version=version+1,"updatedAt"=now_at WHERE id=item_id RETURNING * INTO j;END IF;
 ELSE
  IF reason<>'operator_correction' OR j.health='orphaned' OR j.status NOT IN('resolved','dismissed') OR cardinality(deduplication_candidates)=0 OR EXISTS(SELECT 1 FROM public.work_queue_items newer WHERE newer.type=j.type AND newer."deduplicationKeyHash"=ANY(deduplication_candidates) AND newer.id<>j.id AND (newer.status IN('open','acknowledged') OR newer.occurrence>j.occurrence)) THEN RAISE EXCEPTION 'WORK_ITEM_STATE_CONFLICT';END IF;
  IF j."assignedToUserId" IS NOT NULL THEN BEGIN subject:=public.p02_dashboard_subject_context_v1(session_token_hash,expected_actor_id,j."assignedToUserId"::text);subject_access:=(SELECT value FROM jsonb_array_elements(subject->'permissionGrants') value WHERE value->>'permissionKey'='dashboard.access');subject_read:=(SELECT value FROM jsonb_array_elements(subject->'permissionGrants') value WHERE value->>'permissionKey'='work_queue.read');subject_source:=(SELECT value FROM jsonb_array_elements(subject->'permissionGrants') value WHERE value->>'permissionKey'=j."sourcePermission");clear_assignee:=subject_access IS NULL OR subject_read IS NULL OR subject_source IS NULL;EXCEPTION WHEN OTHERS THEN clear_assignee:=true;END;END IF;
  UPDATE public.work_queue_items SET status='open',"assignedToUserId"=CASE WHEN clear_assignee THEN NULL ELSE "assignedToUserId" END,"assignedAt"=CASE WHEN clear_assignee THEN NULL ELSE "assignedAt" END,"assignedByActorType"=CASE WHEN clear_assignee THEN NULL ELSE "assignedByActorType" END,"assignedByActorId"=CASE WHEN clear_assignee THEN NULL ELSE "assignedByActorId" END,"resolvedAt"=NULL,"resolvedByActorType"=NULL,"resolvedByActorId"=NULL,"resolutionReason"=NULL,"dismissedAt"=NULL,"dismissedByActorType"=NULL,"dismissedByActorId"=NULL,"dismissalReason"=NULL,"acknowledgedAt"=NULL,"acknowledgedByActorType"=NULL,"acknowledgedByActorId"=NULL,"retentionExpiresAt"=NULL,"lastTransitionReason"=reason,version=version+1,"updatedAt"=now_at WHERE id=item_id RETURNING * INTO j;
 END IF;
 RETURN NEXT j;
END $fn$;

CREATE FUNCTION public.p06_api_create_notification_v1(session_token_hash text,expected_actor_id text,recipient_user_id text,item_id uuid,notification_type text,transition_version integer,deduplication_kid text,deduplication_hash text,deduplication_candidates text[])
RETURNS SETOF public.in_app_notifications LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog,public AS $fn$
DECLARE j public.work_queue_items%ROWTYPE;n public.in_app_notifications%ROWTYPE;subject jsonb;access_g jsonb;read_g jsonb;notify_g jsonb;source_g jsonb;now_at timestamptz:=CURRENT_TIMESTAMP;
BEGIN
 IF notification_type NOT IN('foundation.attention.assigned','foundation.attention.critical','foundation.attention.terminal','media.processing.failed') OR cardinality(deduplication_candidates)=0 OR NOT (deduplication_hash=ANY(deduplication_candidates)) THEN RAISE EXCEPTION 'NOTIFICATION_SCOPE_CHANGED';END IF;
 PERFORM public.p02_dashboard_authorization_context_v1(session_token_hash,expected_actor_id);SELECT * INTO j FROM public.work_queue_items WHERE id=item_id FOR SHARE;IF NOT FOUND OR j.version<>transition_version THEN RAISE EXCEPTION 'NOTIFICATION_SCOPE_CHANGED';END IF;
 subject:=public.p02_dashboard_subject_context_v1(session_token_hash,expected_actor_id,recipient_user_id);access_g:=(SELECT value FROM jsonb_array_elements(subject->'permissionGrants') value WHERE value->>'permissionKey'='dashboard.access');read_g:=(SELECT value FROM jsonb_array_elements(subject->'permissionGrants') value WHERE value->>'permissionKey'='work_queue.read');notify_g:=(SELECT value FROM jsonb_array_elements(subject->'permissionGrants') value WHERE value->>'permissionKey'='notifications.read');source_g:=(SELECT value FROM jsonb_array_elements(subject->'permissionGrants') value WHERE value->>'permissionKey'=j."sourcePermission");IF access_g IS NULL OR read_g IS NULL OR notify_g IS NULL OR source_g IS NULL THEN RAISE EXCEPTION 'NOTIFICATION_SCOPE_CHANGED';END IF;
 SELECT * INTO n FROM public.in_app_notifications WHERE "recipientUserId"=recipient_user_id AND type=notification_type AND "deduplicationKeyHash"=ANY(deduplication_candidates);IF FOUND THEN RETURN NEXT n;RETURN;END IF;
 INSERT INTO public.in_app_notifications(id,"contractVersion",type,"typeVersion","recipientUserId","workItemId",severity,"titleKey","messageKey","safeMessageArgs","resourceType","resourceId","deepLink","authorizationScopeKind","dealerIds","locationIds","deduplicationKeyKid","deduplicationKeyHash","expiresAt",version,"createdAt") VALUES(gen_random_uuid(),'in-app-notification.v1',notification_type,notification_type||'.v1',recipient_user_id,item_id,j.severity,'work_queue_transition','work_queue_transition',jsonb_build_object('status',j.status),j."resourceType",j."resourceId",j."deepLink",j."authorizationScopeKind",j."dealerIds",j."locationIds",deduplication_kid,deduplication_hash,LEAST(now_at+interval '30 days',COALESCE(j."retentionExpiresAt",now_at+interval '30 days')),0,now_at) RETURNING * INTO n;RETURN NEXT n;
END $fn$;

CREATE FUNCTION public.p06_api_get_source_state_v1(adapter_key text,adapter_version text)
RETURNS SETOF public.work_queue_source_states LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,public AS $fn$ SELECT * FROM public.work_queue_source_states WHERE "adapterKey"=adapter_key AND "adapterVersion"=adapter_version $fn$;

CREATE FUNCTION public.p06_api_update_source_state_v1(adapter_key text,adapter_version text,next_health text,safe_error_code text)
RETURNS SETOF public.work_queue_source_states LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog,public AS $fn$
DECLARE s public.work_queue_source_states%ROWTYPE;now_at timestamptz:=CURRENT_TIMESTAMP;
BEGIN IF adapter_key NOT IN('runtime_alerts','email_delivery','erp_sync','payment_reconciliation','refund_attention','low_inventory','dealer_applications','contact_leads','product_reviews','support_handoffs','async_jobs','readiness','worker_heartbeat','content_readiness') OR adapter_version<>'v1' OR next_health NOT IN('ready','stale','unavailable') OR safe_error_code IS NOT NULL AND safe_error_code!~'^[A-Z][A-Z0-9_]{0,63}$' THEN RAISE EXCEPTION 'WORK_QUEUE_SOURCE_INVALID';END IF;
 SELECT * INTO s FROM public.work_queue_source_states WHERE "adapterKey"=adapter_key AND "adapterVersion"=adapter_version FOR UPDATE;IF FOUND AND s.health=next_health AND s."safeErrorCode" IS NOT DISTINCT FROM safe_error_code THEN RETURN;END IF;
 IF FOUND THEN UPDATE public.work_queue_source_states SET health=next_health,"capturedAt"=now_at,"lastSuccessAt"=CASE WHEN next_health='ready' THEN now_at ELSE "lastSuccessAt" END,"lastFailureAt"=CASE WHEN next_health='unavailable' THEN now_at ELSE "lastFailureAt" END,"safeErrorCode"=safe_error_code,revision=revision+1,"updatedAt"=now_at WHERE id=s.id RETURNING * INTO s;
 ELSE INSERT INTO public.work_queue_source_states(id,"adapterKey","adapterVersion",health,"lastSuccessAt","lastFailureAt","safeErrorCode","capturedAt",revision,"updatedAt") VALUES(gen_random_uuid(),adapter_key,adapter_version,next_health,CASE WHEN next_health='ready' THEN now_at END,CASE WHEN next_health='unavailable' THEN now_at END,safe_error_code,now_at,0,now_at) RETURNING * INTO s;END IF;RETURN NEXT s;END $fn$;

CREATE FUNCTION public.p07_api_create_media_job_v1(session_token_hash text,expected_actor_id text,job jsonb,idempotency_candidates text[],event_intent_hash text)
RETURNS TABLE(job_id uuid,replayed boolean) LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog,public AS $fn$
DECLARE context jsonb;g jsonb;j public.async_jobs%ROWTYPE;existing public.async_jobs%ROWTYPE;asset public.media_assets%ROWTYPE;
BEGIN context:=public.p02_dashboard_authorization_context_v1(session_token_hash,expected_actor_id);g:=(SELECT value FROM jsonb_array_elements(context->'permissionGrants') value WHERE value->>'permissionKey'='media.create');IF g IS NULL THEN RAISE EXCEPTION 'P07_CREATE_DENIED' USING ERRCODE='42501';END IF;
 j:=jsonb_populate_record(NULL::public.async_jobs,job);j.version:=COALESCE(j.version,0);j."createdAt":=COALESCE(j."createdAt",CURRENT_TIMESTAMP);j."updatedAt":=COALESCE(j."updatedAt",CURRENT_TIMESTAMP);j."bindingRevision":=COALESCE(j."bindingRevision",0);j.attempt:=COALESCE(j.attempt,0);j."generationAttempt":=COALESCE(j."generationAttempt",0);j."retryGeneration":=COALESCE(j."retryGeneration",0);j."leaseRevision":=COALESCE(j."leaseRevision",0);j."processedCount":=COALESCE(j."processedCount",0);j."failedCount":=COALESCE(j."failedCount",0);
 IF j."jobType"<>'media.process' OR j.status<>'queued' OR j."createdByActorType"<>'system' OR j."contextRevision"<>context->>'contextRevision' OR j."eventIntentHash"<>event_intent_hash OR j."leaseOwner" IS NOT NULL OR NOT (j.payload ? 'assetId') THEN RAISE EXCEPTION 'P07_CREATE_INVALID';END IF;
 SELECT * INTO asset FROM public.media_assets WHERE id=(j.payload->>'assetId')::uuid FOR SHARE;IF NOT FOUND OR asset.status<>'processing' OR asset."contextRevision"<>j."contextRevision" OR asset."authorizationScopeKind"<>j."authorizationScopeKind" OR asset."dealerIds"<>j."dealerIds" OR asset."locationIds"<>j."locationIds" OR NOT ((g->>'global')::boolean OR (asset."authorizationScopeKind" IN('dealer','location') AND NOT EXISTS(SELECT 1 FROM jsonb_array_elements_text(asset."dealerIds") d WHERE NOT (g->'dealerIds' ? d)) AND (asset."authorizationScopeKind"='dealer' OR NOT EXISTS(SELECT 1 FROM jsonb_array_elements_text(asset."locationIds") l WHERE NOT (g->'locationIds' ? l))))) THEN RAISE EXCEPTION 'P07_CREATE_INVALID';END IF;
 SELECT * INTO existing FROM public.async_jobs e WHERE e."jobType"='media.process' AND e."idempotencyKeyHash"=ANY(idempotency_candidates) FOR UPDATE;IF FOUND THEN IF existing."eventIntentHash"<>event_intent_hash THEN RAISE EXCEPTION 'IDEMPOTENCY_CONFLICT' USING ERRCODE='23505';END IF;RETURN QUERY SELECT existing.id,true;RETURN;END IF;
 INSERT INTO public.async_jobs SELECT j.*;RETURN QUERY SELECT j.id,false;END $fn$;

CREATE FUNCTION public.p07_api_media_job_detail_v1(session_token_hash text,expected_actor_id text,asset_id uuid,job_id uuid,required_permission text)
RETURNS SETOF public.async_jobs LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public AS $fn$
DECLARE context jsonb;g jsonb;BEGIN IF required_permission NOT IN('media.read','media.manage_variants','media.create') THEN RETURN;END IF;context:=public.p02_dashboard_authorization_context_v1(session_token_hash,expected_actor_id);g:=(SELECT value FROM jsonb_array_elements(context->'permissionGrants') value WHERE value->>'permissionKey'=required_permission);IF g IS NULL THEN RETURN;END IF;RETURN QUERY SELECT j.* FROM public.async_jobs j WHERE j.id=job_id AND j."jobType"='media.process' AND j.payload->>'assetId'=asset_id::text AND ((g->>'global')::boolean OR (j."authorizationScopeKind" IN('dealer','location') AND NOT EXISTS(SELECT 1 FROM jsonb_array_elements_text(j."dealerIds") d WHERE NOT (g->'dealerIds' ? d)) AND (j."authorizationScopeKind"='dealer' OR NOT EXISTS(SELECT 1 FROM jsonb_array_elements_text(j."locationIds") l WHERE NOT (g->'locationIds' ? l)))));END $fn$;

CREATE FUNCTION public.p07_api_lock_media_job_v1(session_token_hash text,expected_actor_id text,asset_id uuid,job_id uuid)
RETURNS boolean LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog,public AS $fn$ DECLARE j public.async_jobs%ROWTYPE;BEGIN PERFORM public.p02_dashboard_authorization_context_v1(session_token_hash,expected_actor_id);SELECT * INTO j FROM public.async_jobs WHERE id=job_id AND "jobType"='media.process' AND payload->>'assetId'=asset_id::text FOR UPDATE;RETURN FOUND;END $fn$;

CREATE FUNCTION public.p07_api_retry_media_job_v1(session_token_hash text,expected_actor_id text,asset_id uuid,job_id uuid,expected_job_version integer,expected_retry_generation integer,next_binding jsonb,next_binding_revision integer,next_binding_hash text)
RETURNS SETOF public.async_jobs LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog,public AS $fn$
DECLARE context jsonb;read_g jsonb;manage_g jsonb;j public.async_jobs%ROWTYPE;asset public.media_assets%ROWTYPE;
BEGIN context:=public.p02_dashboard_authorization_context_v1(session_token_hash,expected_actor_id);read_g:=(SELECT value FROM jsonb_array_elements(context->'permissionGrants') value WHERE value->>'permissionKey'='media.read');manage_g:=(SELECT value FROM jsonb_array_elements(context->'permissionGrants') value WHERE value->>'permissionKey'='media.manage_variants');IF read_g IS NULL OR manage_g IS NULL THEN RAISE EXCEPTION 'MEDIA_NOT_FOUND' USING ERRCODE='42501';END IF;
 SELECT * INTO asset FROM public.media_assets WHERE id=asset_id FOR UPDATE;SELECT * INTO j FROM public.async_jobs WHERE id=job_id FOR UPDATE;IF NOT FOUND OR asset.id IS NULL OR asset.status<>'processing' OR j."jobType"<>'media.process' OR j.status<>'failed' OR j.version<>expected_job_version OR j."retryGeneration"<>expected_retry_generation OR j."retryGeneration">=j."maxRetryGenerations" OR j."leaseOwner" IS NOT NULL OR j."leaseExpiresAt" IS NOT NULL OR j."attemptDeadline" IS NOT NULL OR j.payload->>'assetId'<>asset_id::text OR j."authorizationScopeKind"<>asset."authorizationScopeKind" OR j."dealerIds"<>asset."dealerIds" OR j."locationIds"<>asset."locationIds" OR next_binding_revision<>j."bindingRevision"+1 OR (next_binding->>'bindingRevision')::integer<>next_binding_revision OR (next_binding->>'retryGeneration')::integer<>j."retryGeneration"+1 OR next_binding_hash IS NULL THEN RAISE EXCEPTION 'MEDIA_VERSION_CONFLICT';END IF;
 UPDATE public.async_jobs SET status='queued',"retryGeneration"="retryGeneration"+1,"generationAttempt"=0,"nextRetryAt"=NULL,"finishedAt"=NULL,"failureClass"=NULL,"errorSummary"=NULL,"executionBinding"=next_binding,"bindingRevision"=next_binding_revision,"bindingHash"=next_binding_hash,version=version+1,"updatedAt"=CURRENT_TIMESTAMP WHERE id=job_id RETURNING * INTO j;RETURN NEXT j;END $fn$;

ALTER FUNCTION public.p05_api_create_probe_v1(text,text,jsonb,text[],text) OWNER TO vanstro_p04_guard_owner;
ALTER FUNCTION public.p05_api_list_v1(text,text,text,text[],text[],timestamptz,timestamptz,integer,timestamptz,uuid,text[],text[],text,boolean,boolean) OWNER TO vanstro_p04_guard_owner;
ALTER FUNCTION public.p05_api_detail_v1(text,text,uuid) OWNER TO vanstro_p04_guard_owner;
ALTER FUNCTION public.p05_api_artifacts_v1(text,text,uuid) OWNER TO vanstro_p04_guard_owner;
ALTER FUNCTION public.p05_api_cancel_v1(text,text,uuid,integer) OWNER TO vanstro_p04_guard_owner;
ALTER FUNCTION public.p05_api_retry_v1(text,text,uuid,integer) OWNER TO vanstro_p04_guard_owner;
ALTER FUNCTION public.p06_api_mutate_item_v1(text,text,uuid,integer,text,text,text,text[]) OWNER TO vanstro_p04_guard_owner;
ALTER FUNCTION public.p06_api_create_notification_v1(text,text,text,uuid,text,integer,text,text,text[]) OWNER TO vanstro_p04_guard_owner;
ALTER FUNCTION public.p06_api_get_source_state_v1(text,text) OWNER TO vanstro_p04_guard_owner;
ALTER FUNCTION public.p06_api_update_source_state_v1(text,text,text,text) OWNER TO vanstro_p04_guard_owner;
ALTER FUNCTION public.p07_api_create_media_job_v1(text,text,jsonb,text[],text) OWNER TO vanstro_p04_guard_owner;
ALTER FUNCTION public.p07_api_media_job_detail_v1(text,text,uuid,uuid,text) OWNER TO vanstro_p04_guard_owner;
ALTER FUNCTION public.p07_api_lock_media_job_v1(text,text,uuid,uuid) OWNER TO vanstro_p04_guard_owner;
ALTER FUNCTION public.p07_api_retry_media_job_v1(text,text,uuid,uuid,integer,integer,jsonb,integer,text) OWNER TO vanstro_p04_guard_owner;
SET ROLE vanstro_p04_guard_owner;
REVOKE ALL ON FUNCTION public.p05_api_create_probe_v1(text,text,jsonb,text[],text),public.p05_api_list_v1(text,text,text,text[],text[],timestamptz,timestamptz,integer,timestamptz,uuid,text[],text[],text,boolean,boolean),public.p05_api_detail_v1(text,text,uuid),public.p05_api_artifacts_v1(text,text,uuid),public.p05_api_cancel_v1(text,text,uuid,integer),public.p05_api_retry_v1(text,text,uuid,integer),public.p06_api_mutate_item_v1(text,text,uuid,integer,text,text,text,text[]),public.p06_api_create_notification_v1(text,text,text,uuid,text,integer,text,text,text[]),public.p06_api_get_source_state_v1(text,text),public.p06_api_update_source_state_v1(text,text,text,text),public.p07_api_create_media_job_v1(text,text,jsonb,text[],text),public.p07_api_media_job_detail_v1(text,text,uuid,uuid,text),public.p07_api_lock_media_job_v1(text,text,uuid,uuid),public.p07_api_retry_media_job_v1(text,text,uuid,uuid,integer,integer,jsonb,integer,text) FROM PUBLIC,vanstro_runtime,vanstro_worker_runtime;
GRANT EXECUTE ON FUNCTION public.p05_api_create_probe_v1(text,text,jsonb,text[],text),public.p05_api_list_v1(text,text,text,text[],text[],timestamptz,timestamptz,integer,timestamptz,uuid,text[],text[],text,boolean,boolean),public.p05_api_detail_v1(text,text,uuid),public.p05_api_artifacts_v1(text,text,uuid),public.p05_api_cancel_v1(text,text,uuid,integer),public.p05_api_retry_v1(text,text,uuid,integer),public.p06_api_mutate_item_v1(text,text,uuid,integer,text,text,text,text[]),public.p06_api_create_notification_v1(text,text,text,uuid,text,integer,text,text,text[]),public.p06_api_get_source_state_v1(text,text),public.p06_api_update_source_state_v1(text,text,text,text),public.p07_api_create_media_job_v1(text,text,jsonb,text[],text),public.p07_api_media_job_detail_v1(text,text,uuid,uuid,text),public.p07_api_lock_media_job_v1(text,text,uuid,uuid),public.p07_api_retry_media_job_v1(text,text,uuid,uuid,integer,integer,jsonb,integer,text) TO vanstro_runtime;
RESET ROLE;
REVOKE CREATE ON SCHEMA public FROM vanstro_p04_guard_owner;
COMMIT;
