#!/usr/bin/env python3
import json,hashlib,os,sys,time,urllib.request
from pathlib import Path
from playwright.sync_api import sync_playwright
HERE=Path(__file__).resolve().parent;OUT=Path(os.environ['P09_BROWSER_OUT']);WEB=os.environ.get('P09_WEB','http://127.0.0.1:4430');API=os.environ.get('P09_API','http://127.0.0.1:4431');OUT.mkdir(parents=True,exist_ok=True)
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def control(**kw):return json.loads(urllib.request.urlopen(urllib.request.Request(API+'/control',data=json.dumps(kw).encode(),headers={'Content-Type':'application/json'},method='POST')).read())
def snapshot():return json.loads(urllib.request.urlopen(API+'/control/state').read())
definition=json.loads((HERE/'p09-browser-v2-definition.json').read_text());cases={x['id']:{**x,'status':'not-executed','observations':[]}for x in definition['cases']};network=[]
def result(cid,ok,*obs):cases[cid].update(status='pass'if ok else'fail',observations=list(obs))
control(profile='global',context=1,readiness='degraded');initial=snapshot()
with sync_playwright()as pw:
 b=pw.chromium.launch(headless=True,executable_path='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args=['--host-resolver-rules=MAP * 0.0.0.0, EXCLUDE localhost, EXCLUDE 127.0.0.1','--disable-background-networking','--no-first-run']);c=b.new_context();p=c.new_page();p.on('request',lambda r:network.append({'method':r.method,'url':r.url}));p.goto(WEB+'/dashboard/runtime?view=config');p.wait_for_selector('text=运行时配置 / 功能开关 / 就绪状态',timeout=30000)
 body=p.locator('body').inner_text();result('P09-A01','刷新间隔' in body and'显示模式'in body and'安全来源'in body,'registry list rendered');p.get_by_role('button',name='查看详情').nth(1).click();p.wait_for_selector('text=期望值：');result('P09-A02',p.locator('body').inner_text().find('任意')<0,'typed form rendered; arbitrary keys absent')
 before=snapshot()['state']['config'].copy();p.get_by_label('新的期望值').select_option('compact');assert p.get_by_label('新的期望值').input_value()=='compact';p.get_by_role('button',name='保存期望值').click();p.wait_for_timeout(300);p.reload();p.wait_for_selector('text=期望值：');after=snapshot()['state']['config'];result('P09-A03',after['desiredValue']=='compact'and after['effectiveValue']==before['effectiveValue'],'desired changed; effective unchanged')
 p.get_by_role('button',name='激活',exact=True).click();p.wait_for_timeout(300);active=snapshot()['state']['config'];result('P09-A04',active['effectiveValue']=='compact'and active['generation']>before['generation'],'activation effective/generation')
 p.get_by_label('新的期望值').select_option('standard');assert p.get_by_label('新的期望值').input_value()=='standard';p.get_by_role('button',name='保存期望值').click();p.wait_for_timeout(200);p.reload();p.wait_for_selector('text=期望值：');p.get_by_role('button',name='测试激活失败').click();p.wait_for_timeout(250);failed=snapshot()['state']['config'];result('P09-A05',failed['desiredValue']=='standard'and failed['effectiveValue']=='compact'and failed['activationStatus']=='activation_failed','desired persisted/effective prior');p.get_by_role('button',name='重试激活').click();p.wait_for_timeout(250);result('P09-A06',snapshot()['state']['config']['effectiveValue']=='standard','explicit retry recovery')
 stale=p.evaluate("""async path=>{const r=await fetch(path,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json','Idempotency-Key':'stale-browser'},body:JSON.stringify({schemaVersion:'runtime-config-schema.v1',desiredValue:'compact',expectedVersion:0})});return{status:r.status,body:await r.json()}}""",API+'/api/v1/dashboard/runtime/config/foundation.runtime.display_mode/versions?scopeKind=global');result('P09-A07',stale['status']==409 and sum(x.get('idempotency')=='stale-browser'for x in snapshot()['state']['requests'])==1,repr(stale));p.reload();p.wait_for_selector('text=回滚到版本 1');p.get_by_role('button',name='回滚到版本 1').click();p.wait_for_timeout(250);result('P09-A08',snapshot()['state']['config']['version']>failed['version'] and snapshot()['state']['config']['version']>failed['version'],'rollback new version')
 control(precedence={'global':'standard','dealer':'compact','location':'standard'},profile='global');p.get_by_role('button',name='配置').click();p.wait_for_timeout(100);prec=snapshot()['state'].get('precedence',{});result('P09-A09',prec.get('global')=='standard' and prec.get('dealer')=='compact' and prec.get('location')=='standard','fixture established legal layers; UI selected global scope; effective global='+str(prec.get('global')))
 p.get_by_role('button',name='功能开关').click();p.get_by_role('button',name='查看详情').click();p.get_by_label('期望状态').select_option(label='enabled');p.get_by_role('button',name='保存期望状态').click();p.wait_for_timeout(200);p.reload();p.wait_for_selector('text=期望：');p.get_by_role('button',name='激活开关').click();p.wait_for_timeout(200);result('P09-A10',snapshot()['state']['flag']['effectiveState']=='enabled'and'功能开关不授予权限'in p.locator('body').inner_text(),'flag enabled; authorization warning')
 p.get_by_role('button',name='紧急关闭').click();p.wait_for_selector('[role=dialog]');p.get_by_label('输入 KILL').fill('KILL');p.get_by_role('dialog').get_by_role('button',name='确认紧急关闭').click();p.wait_for_timeout(250);result('P09-A11',snapshot()['state']['flag']['effectiveState']=='killed','kill dialog exact confirmation/fallback')
 control(profile='denied',context=2);p.reload();p.wait_for_timeout(500);result('P09-A12',p.get_by_role('button',name='紧急关闭').count()==0,'denied profile hides data/actions');control(profile='global',context=3);p.reload();p.wait_for_selector('text=运行时配置 / 功能开关 / 就绪状态');result('P09-A13',p.get_by_role('button',name='配置').count()==1,'actor/context projection replaced')
 p.get_by_role('button',name='就绪状态').click();p.wait_for_timeout(250);body=p.locator('body').inner_text();result('P09-A14','degraded'in body and'zero_capacity'in body and'可用容量'in body,'exact detail readiness and zero capacity rendered');public=p.evaluate("""async api=>{const a=await(await fetch(api+'/health/live')).json();const b=await(await fetch(api+'/health/ready')).json();return{a,b}}""",API);serialized=json.dumps(public);result('P09-A15',all(x not in serialized.lower()for x in['password','token','postgresql://','stack','filesystem']),'public health minimized; protected UI redacted')
 p.get_by_role('button',name='刷新').focus();p.keyboard.press('Enter');p.wait_for_timeout(150);reflows=[]
 for w in(390,320):p.set_viewport_size({'width':w,'height':844});time.sleep(.1);reflows.append((w,p.evaluate('document.documentElement.scrollWidth-document.documentElement.clientWidth')));p.screenshot(path=str(OUT/f'reflow-{w}.png'),full_page=True)
 result('P09-A16',p.locator('[role=status]').count()>0 and all(x[1]<=0 for x in reflows),'keyboard/live region/reflow='+repr(reflows));arbitrary=p.evaluate("""async api=>{const r=await fetch(api+'/api/v1/dashboard/runtime/config/unknown/versions?scopeKind=global',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':'arbitrary-browser'},body:'{}'});return r.status}""",API);unexpected=[x for x in network if not(x['url'].startswith(WEB)or x['url'].startswith(API)or x['url'].startswith('data:')or x['url'].startswith('blob:'))];result('P09-A17',arbitrary==404 and not unexpected and all(x['method']in('GET','POST','OPTIONS')for x in network),'unknown key denied; localhost-only network');b.close()
counts={x:sum(v['status']==x for v in cases.values())for x in['pass','fail','intentional-skip','not-executed']};report={'schemaVersion':1,'suiteId':definition['suiteId'],'testedCommit':os.environ['P09_TESTED_COMMIT'],'definitionSha256':sha(HERE/'p09-browser-v2-definition.json'),'fixtureSha256':sha(HERE/'p09-browser-v2-fixture.py'),'harnessSha256':sha(__file__),'actorProfiles':{'actor':initial['actor'],'profiles':['global','denied'],'contexts':[1,2,3]},'ports':{'web':WEB,'api':API},'counts':counts,'cases':list(cases.values()),'requests':snapshot()['state']['requests'],'network':network};(OUT/'acceptance-results.json').write_text(json.dumps(report,ensure_ascii=False,indent=2));print(json.dumps(counts));sys.exit(1 if counts['fail']or counts['not-executed']else 0)
