#!/usr/bin/env python3
import json,sys,uuid,urllib.parse
from datetime import datetime,timezone,timedelta
from http.server import ThreadingHTTPServer,BaseHTTPRequestHandler
PORT=int(sys.argv[1]);ACTOR=str(uuid.uuid4());NOW=lambda:datetime.now(timezone.utc).isoformat().replace('+00:00','Z')
state={'requests':[],'profile':'global','context':1,'precedence':{},'config':{'desiredValue':'standard','effectiveValue':'standard','desiredSource':'compiled_default','effectiveSource':'compiled_default','validationStatus':'validated','activationStatus':'active','version':0,'generation':0},'flag':{'desiredState':'disabled','effectiveState':'disabled','validationStatus':'validated','activationStatus':'active','version':0,'generation':0},'readiness':'degraded'}
def action(key):return{'action':'read','permissionKey':key,'decision':'allow','reason':'granted_by_persisted_permission','scope':{'kind':'global'}}
def foundation():return{'data':{'contractVersion':'dashboard-foundation.v1','actor':{'id':ACTOR,'displayLabel':'P09 QA','roleLabels':['qa']},'modules':[{'module':'overview','route':'/dashboard','readAllowed':True},{'module':'operations','route':'/dashboard/operations','readAllowed':True}],'visibility':{'scope':'unavailable','fields':'permission-only'},'shell':{'flag':'dashboard.shell.v2','mode':'internal','enabled':True,'code':'DASHBOARD_SHELL_READY','readOnly':True},'readiness':'ready','requestId':'f'}}
def auth():
 perms=['dashboard.access'] if state['profile']=='denied' else ['dashboard.access','config.read','config.manage','config.activate','flags.read','flags.manage','flags.kill_switch','readiness.read_summary','readiness.read_detail','analytics.registry.read','analytics.events.read_summary','analytics.metrics.read','analytics.metrics.read_detail','analytics.operations.read']
 actions=[action(x) for x in perms]
 disabled={'enabled':False};return{'data':{'contractVersion':'dashboard-authorization.v1','status':'ready','requestId':'a','issuedAt':NOW(),'expiresAt':(datetime.now(timezone.utc)+timedelta(minutes=30)).isoformat().replace('+00:00','Z'),'contextRevision':f"ctx-{state['profile']}-{state['context']}",'actor':{'principalType':'user','id':ACTOR,'kind':'admin','status':'active','roleKeys':['qa']},'effectiveRoles':[{'roleKey':'qa','scope':'global'}],'modules':[{'module':'overview','route':'/dashboard','status':'allowed','actions':[actions[0]]},{'module':'operations','route':'/dashboard/operations','status':'allowed','actions':actions[1:]}],'scope':{'kind':'global','source':'persisted_grants'},'fieldVisibility':[],'commonQueryV1':{'products':disabled,'dealers':disabled},'auditFoundationV1':{'enabled':False,'queryProfile':'dashboard.audit-events.v1','eventVersion':'audit-event.v1','sensitive':disabled},'asyncJobFoundationV1':{'enabled':False,'contractVersion':'async-job.v1','queryProfile':'dashboard.async-jobs.v1','registryVersion':'async-job-registry.v1','sensitive':disabled,'mutations':{'create':False,'cancel':False,'retry':False},'artifacts':{'metadata':False,'download':False}},'workQueueFoundationV1':{'enabled':False,'contractVersion':'work-queue-item.v1','queryProfile':'dashboard.work-queue.v1','registryVersion':'work-queue-registry.v1','sensitive':disabled,'actions':{'assign':False,'acknowledge':False,'resolve':False,'dismiss':False,'reopen':False},'notifications':{'enabled':False,'contractVersion':'in-app-notification.v1','queryProfile':'dashboard.in-app-notifications.v1','markRead':False,'externalDelivery':False}},'mediaFoundationV1':{'enabled':False,'contractVersion':'media-asset.v1','queryProfile':'dashboard.media-assets.v1','registryVersion':'media-registry.v1','safeProfile':'dashboard.media-assets.safe.v1','sensitiveProfile':disabled,'actions':{k:False for k in ['create','update','archive','restore','downloadOriginal','manageVariants']},'upload':{'enabled':False,'image':False,'pdf':False,'maxBytes':{'image':1,'pdf':1},'intentLifetimeSeconds':600,'directControlledApi':True},'preview':{'controlled':True,'pdfInline':False},'legacyAdapters':{'enabled':True,'partial':True},'externalDelivery':False,'ai':False,'bulkImportExport':False},'dataJobFoundationV1':{'enabled':False,'contractVersion':'dashboard.data-jobs.v1','registryVersion':'dashboard.data-jobs.registry.v1','objectKey':'foundation.sample','imports':{'read':False,'create':False,'commit':False},'exports':{'read':False,'create':False,'download':False},'upload':{'controlled':True,'directAuthenticatedApi':True},'download':{'controlled':True,'directAuthenticatedApi':True},'tenantPartition':False}}}
def descriptor():return{'key':'foundation.runtime.display_mode','type':'enum','defaultValue':'standard','scopes':['global'],'values':['standard','compact'],'label':'显示模式','owner':'P09'}
def config_list():return{'data':{'contractVersion':'runtime-foundation.v1','registryVersion':'runtime-foundation-registry.v1','registry':[descriptor()],'protected':[{'key':'database.connection','sensitivity':'secret','mutability':'immutable_deployment','activationMode':'restart_or_redeploy','runtimeOverrideAllowed':False,'state':'configured'}],'states':[{'configKey':'foundation.runtime.display_mode',**state['config']}],'contextRevision':f"ctx-{state['context']}",'scope':{'kind':'global','dealerIds':[],'locationIds':[]}}}
def config_detail():return{'data':{'contractVersion':'runtime-foundation.v1','descriptor':descriptor(),'state':{'configKey':'foundation.runtime.display_mode',**state['config']},'contextRevision':f"ctx-{state['context']}",'scope':{'kind':'global','dealerIds':[],'locationIds':[]}}}
def flag_list():return{'data':{'contractVersion':'runtime-foundation.v1','registry':[{'key':'foundation.runtime.sample_flag','defaultState':'disabled','scopes':['global'],'owner':'P09','reviewAt':'2026-09-03'}],'states':[{'flagKey':'foundation.runtime.sample_flag',**state['flag']}],'contextRevision':f"ctx-{state['context']}",'scope':{'kind':'global','dealerIds':[],'locationIds':[]}}}
def flag_detail():return{'data':{'descriptor':{'key':'foundation.runtime.sample_flag'},'state':{'flagKey':'foundation.runtime.sample_flag',**state['flag']},'evaluation':{'enabled':state['flag']['effectiveState']=='enabled','state':state['flag']['effectiveState'],'reasonCode':'effective_state'},'contextRevision':f"ctx-{state['context']}",'scope':{'kind':'global','dealerIds':[],'locationIds':[]}}}
def readiness():
 observed=datetime.now(timezone.utc);return{'data':{'contractVersion':'runtime-foundation.v1','registryVersion':'runtime-foundation-registry.v1','state':state['readiness'],'reasonCode':'optional_dependency_unavailable','observedAt':observed.isoformat().replace('+00:00','Z'),'staleAfter':(observed+timedelta(seconds=15)).isoformat().replace('+00:00','Z'),'generation':'fixture','dependencies':[{'key':'database','state':'ready','reasonCode':'configured'},{'key':'smtp','state':'not_configured','reasonCode':'missing'},{'key':'worker_capacity','state':'unavailable','reasonCode':'zero_capacity'}]}}
class H(BaseHTTPRequestHandler):
 def log_message(self,*a):pass
 def cors(self):self.send_header('Access-Control-Allow-Origin','http://127.0.0.1:4450');self.send_header('Access-Control-Allow-Credentials','true');self.send_header('Access-Control-Allow-Headers','Content-Type,Accept,Idempotency-Key');self.send_header('Access-Control-Allow-Methods','GET,POST,OPTIONS')
 def sendj(self,o,s=200):b=json.dumps(o).encode();self.send_response(s);self.cors();self.send_header('Content-Type','application/json');self.send_header('Content-Length',str(len(b)));self.end_headers();self.wfile.write(b)
 def body(self):return json.loads(self.rfile.read(int(self.headers.get('Content-Length','0')or 0))or b'{}')
 def record(self,b=None):state['requests'].append({'method':self.command,'path':self.path,'body':b,'idempotency':self.headers.get('Idempotency-Key')})
 def do_OPTIONS(self):self.send_response(204);self.cors();self.end_headers()
 def do_GET(self):
  self.record();p=urllib.parse.urlparse(self.path).path
  if p=='/control/state':return self.sendj({'actor':ACTOR,'state':state})
  if p=='/api/v1/dashboard/foundation':return self.sendj(foundation())
  if p=='/api/v1/dashboard/authorization':return self.sendj(auth())
  if state['profile']=='denied' and p.startswith('/api/v1/dashboard/runtime'):return self.sendj({'code':'DASHBOARD_NOT_FOUND'},404)
  if p=='/api/v1/dashboard/runtime/config':return self.sendj(config_list())
  if p=='/api/v1/dashboard/runtime/config/foundation.runtime.display_mode':return self.sendj(config_detail())
  if p=='/api/v1/dashboard/runtime/flags':return self.sendj(flag_list())
  if p=='/api/v1/dashboard/runtime/flags/foundation.runtime.sample_flag':return self.sendj(flag_detail())
  if p=='/api/v1/dashboard/runtime/readiness':return self.sendj(readiness())
  if p=='/api/v1/dashboard/analytics/foundation/registry':return self.sendj({'data':{'contractVersion':'analytics-foundation.v1','eventRegistryVersion':'analytics-event-registry.v1','metricRegistryVersion':'analytics-metric-registry.v1','events':[{'name':'foundation.analytics.observed.v1','version':'analytics-event-schema.v1'}],'metrics':[{'key':'foundation.events.count.v1','version':'metric-definition.v1','freshnessSeconds':60},{'key':'foundation.events.engagement_rate.v1','version':'metric-definition.v1','freshnessSeconds':60}],'providerSink':{'state':'disabled','network':False},'contextRevision':'ctx','scope':{'kind':'global','dealerIds':[],'locationIds':[]}}})
  if p=='/api/v1/dashboard/analytics/foundation/events':return self.sendj({'data':[],'meta':{'contractVersion':'common-query.v1'}})
  if p=='/api/v1/dashboard/analytics/foundation/metrics':return self.sendj({'data':[{'key':'foundation.events.count.v1','version':'metric-definition.v1','unit':'events','windows':['24h','7d'],'dimensions':['category'],'freshnessSeconds':60},{'key':'foundation.events.engagement_rate.v1','version':'metric-definition.v1','unit':'ratio','windows':['24h','7d'],'dimensions':[],'freshnessSeconds':60}],'meta':{'registryVersion':'analytics-metric-registry.v1','contextRevision':'ctx'}})
  if p=='/api/v1/dashboard/analytics/foundation/metrics/foundation.events.count.v1':return self.sendj({'data':{'key':'foundation.events.count.v1','definitionVersion':'metric-definition.v1','value':None,'unit':'events','window':'24h','scope':{'kind':'global'},'asOf':NOW(),'freshness':'fresh','completeness':'empty','source':'analytics_foundation_event','provenance':'request-time.v1','suppressed':False}})
  if p=='/api/v1/dashboard/analytics/foundation/readiness':return self.sendj({'data':{'state':'ready','reasonCode':'registry_and_store_available','observedAt':NOW(),'staleAfter':NOW(),'ingestion':'owned_test_only','aggregation':'request_time','providerSink':'disabled'}})
  if p=='/health/live':return self.sendj({'data':{'status':'ok','service':'vanstro-api','timestamp':NOW()}})
  if p=='/health/ready':return self.sendj({'data':{'status':'ok','service':'vanstro-api','database':'ok','readiness':state['readiness'],'contractVersion':'runtime-foundation.v1','observedAt':NOW(),'staleAfter':(datetime.now(timezone.utc)+timedelta(seconds=15)).isoformat().replace('+00:00','Z'),'timestamp':NOW()}})
  return self.sendj({'code':'DASHBOARD_NOT_FOUND'},404)
 def do_POST(self):
  data=self.body();self.record(data);p=urllib.parse.urlparse(self.path).path
  if p=='/control':state.update({k:v for k,v in data.items() if k in ('profile','context','readiness','precedence')});return self.sendj({'ok':True})
  if 'unknown' in p:return self.sendj({'code':'CONFIG_KEY_UNSUPPORTED'},404)
  if p.endswith('/config/foundation.runtime.display_mode/versions'):
   if data.get('expectedVersion')!=state['config']['version']:return self.sendj({'code':'VERSION_CONFLICT'},409)
   state['config'].update(desiredValue=data['desiredValue'],desiredSource='runtime_override',activationStatus='draft',version=state['config']['version']+1);return self.sendj({'data':{'configKey':'foundation.runtime.display_mode',**state['config']}},201)
  if p.endswith('/config/foundation.runtime.display_mode/activate'):
   if data.get('expectedVersion')!=state['config']['version']:return self.sendj({'code':'VERSION_CONFLICT'},409)
   if data.get('simulateFailure'):state['config'].update(activationStatus='activation_failed',failureReasonCode='synthetic_activation_failure');return self.sendj({'error':'The desired value was saved but activation failed.','code':'CONFIG_ACTIVATION_FAILED','data':{'configKey':'foundation.runtime.display_mode',**state['config']}},503)
   state['config'].update(effectiveValue=state['config']['desiredValue'],effectiveSource='runtime_override',activationStatus='active',generation=state['config']['generation']+1);state['config'].pop('failureReasonCode',None);return self.sendj({'data':{'configKey':'foundation.runtime.display_mode',**state['config']}})
  if p.endswith('/config/foundation.runtime.display_mode/retry'):state['config'].update(effectiveValue=state['config']['desiredValue'],effectiveSource='runtime_override',activationStatus='active',generation=state['config']['generation']+1);state['config'].pop('failureReasonCode',None);return self.sendj({'data':{'configKey':'foundation.runtime.display_mode',**state['config']}})
  if p.endswith('/config/foundation.runtime.display_mode/rollback'):state['config'].update(desiredValue='standard',effectiveValue='standard',activationStatus='active',version=state['config']['version']+1,generation=state['config']['generation']+1);return self.sendj({'data':{'configKey':'foundation.runtime.display_mode',**state['config']}})
  if p.endswith('/flags/foundation.runtime.sample_flag/versions'):state['flag'].update(desiredState=data['desiredState'],activationStatus='draft',version=state['flag']['version']+1);return self.sendj({'data':{'flagKey':'foundation.runtime.sample_flag',**state['flag']}},201)
  if p.endswith('/flags/foundation.runtime.sample_flag/activate'):state['flag'].update(effectiveState=state['flag']['desiredState'],activationStatus='active',generation=state['flag']['generation']+1);return self.sendj({'data':{'flagKey':'foundation.runtime.sample_flag',**state['flag']}})
  if p.endswith('/flags/foundation.runtime.sample_flag/kill'):
   if data.get('confirmation')!='KILL':return self.sendj({'code':'FLAG_KILL_CONFIRMATION_REQUIRED'},400)
   state['flag'].update(desiredState='killed',effectiveState='killed',activationStatus='active',generation=state['flag']['generation']+1);return self.sendj({'data':{'flagKey':'foundation.runtime.sample_flag',**state['flag']}})
  return self.sendj({'code':'DASHBOARD_NOT_FOUND'},404)
ThreadingHTTPServer(('127.0.0.1',PORT),H).serve_forever()
