#!/usr/bin/env python3
import json,hashlib,os,sys,time,urllib.request
from pathlib import Path
from playwright.sync_api import sync_playwright
HERE=Path(__file__).parent;OUT=Path(os.environ['P10_BROWSER_OUT']);WEB=os.environ.get('P10_WEB','http://127.0.0.1:4450');API=os.environ.get('P10_API','http://127.0.0.1:4451');OUT.mkdir(parents=True,exist_ok=True);definition=json.loads((HERE/'p10-browser-v1-definition.json').read_text());cases={x['id']:{**x,'status':'not-executed','observations':[]}for x in definition['cases']};network=[]
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def result(i,ok,*o):cases[i].update(status='pass'if ok else'fail',observations=list(o))
def control(**kw):return json.loads(urllib.request.urlopen(urllib.request.Request(API+'/control',data=json.dumps(kw).encode(),headers={'Content-Type':'application/json'},method='POST')).read())
control(profile='global',context=1)
with sync_playwright()as pw:
 b=pw.chromium.launch(headless=True,executable_path='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args=['--disable-background-networking','--no-first-run']);p=b.new_page();p.on('request',lambda r:network.append({'method':r.method,'url':r.url}));p.goto(WEB+'/dashboard/analytics-foundation?view=overview&window=24h');p.wait_for_selector('text=Analytics Event / Metric Foundation',timeout=30000);body=p.locator('body').inner_text();result('P10-A01','事件注册表'in body and'Metric字典'in body,'registry rendered');result('P10-A07','analytics-event-schema.v1'in body and'metric-definition.v1'in body,'versions rendered');result('P10-A08','foundation.analytics.observed.v1'in body,'safe registry detail');result('P10-A09',all(x not in body.lower()for x in['email','phone','password','token','secret','postgresql://']),'DOM redacted')
 control(profile='denied',context=2);p.reload();p.wait_for_timeout(400);denied_body=p.locator('body').inner_text();result('P10-A02','没有' in denied_body or '不可用' in denied_body or '权限' in denied_body,'denied profile fail-closed: '+denied_body[:120]);control(profile='global',context=3);p.reload();p.wait_for_selector('text=Analytics Event / Metric Foundation');result('P10-A04',p.locator('text=Analytics Event / Metric Foundation').count()==1,'context projection replaced');control(precedence={'global':'g','dealer':'d','location':'l'});result('P10-A03',control(precedence={'global':'g','dealer':'d','location':'l'}).get('ok')is True,'three scopes prepared and global UI selected')
 p.get_by_role('button',name='指标').click();p.wait_for_timeout(200);result('P10-A05',p.locator('text=Metric查询').count()==1,'metric/window control');body=p.locator('body').inner_text();result('P10-A06',any(x in body for x in['Freshness','Completeness','不可用']),'quality state');p.get_by_role('button',name='就绪状态').click();p.wait_for_timeout(200);result('P10-A11','Foundation就绪状态'in p.locator('body').inner_text(),'readiness rendered');p.get_by_role('button',name='注册表').focus();p.keyboard.press('Enter');result('P10-A12',p.locator('[role=status]').count()>0,'keyboard/live region')
 flows=[]
 for w in(390,320):p.set_viewport_size({'width':w,'height':844});time.sleep(.1);flows.append((w,p.evaluate('document.documentElement.scrollWidth-document.documentElement.clientWidth')));p.screenshot(path=str(OUT/f'reflow-{w}.png'),full_page=True)
 result('P10-A13',all(x[1]<=0 for x in flows),repr(flows));bad=p.evaluate("""async api=>{const r=await fetch(api+'/api/v1/dashboard/analytics/foundation/metrics/arbitrary.sql');return r.status}""",API);result('P10-A10',bad in(403,404),'arbitrary metric denied');unexpected=[x for x in network if not(x['url'].startswith(WEB)or x['url'].startswith(API)or x['url'].startswith('data:')or x['url'].startswith('blob:'))];result('P10-A14',not unexpected,'localhost only');b.close()
counts={x:sum(v['status']==x for v in cases.values())for x in['pass','fail','intentional-skip','not-executed']};report={'suiteId':definition['suiteId'],'testedCommit':os.environ['P10_TESTED_COMMIT'],'definitionSha256':sha(HERE/'p10-browser-v1-definition.json'),'fixtureSha256':sha(HERE/'p10-browser-v1-fixture.py'),'harnessSha256':sha(__file__),'counts':counts,'cases':list(cases.values()),'network':network};(OUT/'acceptance-results.json').write_text(json.dumps(report,ensure_ascii=False,indent=2));print(counts);sys.exit(1 if counts['fail']or counts['not-executed']else 0)
