#!/usr/bin/env python3
import json,hashlib,os,sys,time,urllib.request
from pathlib import Path
from playwright.sync_api import sync_playwright
HERE=Path(__file__).parent;OUT=Path(os.environ['P10_BROWSER_OUT']);WEB=os.environ.get('P10_WEB','http://127.0.0.1:4450');API=os.environ.get('P10_API','http://127.0.0.1:4451');OUT.mkdir(parents=True,exist_ok=True);definition=json.loads((HERE/'p10-browser-v2-definition.json').read_text());cases={x['id']:{**x,'status':'not-executed','observations':[]}for x in definition['cases']};network=[]
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def result(i,ok,*o):cases[i].update(status='pass'if ok else'fail',observations=list(o))
def control(**kw):return json.loads(urllib.request.urlopen(urllib.request.Request(API+'/control',data=json.dumps(kw).encode(),headers={'Content-Type':'application/json'},method='POST')).read())
control(profile='global',context=1)
with sync_playwright()as pw:
 b=pw.chromium.launch(headless=True,executable_path='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args=['--disable-background-networking','--no-first-run']);p=b.new_page();p.on('request',lambda r:network.append({'method':r.method,'url':r.url}));p.goto(WEB+'/dashboard/analytics-foundation?view=release&releaseDay=2026-08-03');p.wait_for_selector('text=Analytics 密封发布',timeout=30000);body=p.locator('body').inner_text();result('P10-A01','UTC 2026-08-03'in body,'sealed release rendered');result('P10-A03','受隐私保护'in body and'受隐私阈值抑制'in body,'suppressed nulls rendered');result('P10-A04','无贡献'in body and'受隐私保护'in body,'empty/suppressed copy distinct');result('P10-A05',all(x in body for x in['非互动主体','合格主体','互动主体','互动分子','互动率','浏览主体']),'six safe cells rendered')
 before=len([x for x in network if '/dashboard/analytics/'in x['url']]);control(profile='denied',context=2);p.reload();p.wait_for_timeout(500);after=len([x for x in network if '/dashboard/analytics/'in x['url']]);result('P10-A02',after==before and'没有读取密封Analytics发布的权限'in p.locator('body').inner_text(),'denied profile emitted zero analytics request')
 control(profile='global',context=3);p.goto(WEB+'/dashboard/analytics-foundation?view=events');p.wait_for_timeout(200);invalid=p.locator('body').inner_text();result('P10-A06','Analytics发布参数无效'in invalid and not any('/events'in x['url']or'/metrics'in x['url']for x in network),'legacy views rejected without request');result('P10-A08','清除视图'in invalid,'invalid route fail closed')
 p.goto(WEB+'/dashboard/analytics-foundation?view=release&releaseDay=2026-08-03');p.wait_for_selector('text=Analytics 密封发布');result('P10-A07',p.locator('text=Analytics 密封发布').count()==1,'new context rendered without stale data');p.get_by_role('button',name='刷新').focus();p.keyboard.press('Enter');p.wait_for_timeout(150);flows=[]
 for w in(390,320):p.set_viewport_size({'width':w,'height':844});time.sleep(.1);flows.append((w,p.evaluate('document.documentElement.scrollWidth-document.documentElement.clientWidth')));p.screenshot(path=str(OUT/f'reflow-{w}.png'),full_page=True)
 result('P10-A09',p.locator('[role=status]').count()>0 and all(x[1]<=0 for x in flows),'keyboard/live/reflow='+repr(flows));unexpected=[x for x in network if not(x['url'].startswith(WEB)or x['url'].startswith(API)or x['url'].startswith('data:')or x['url'].startswith('blob:'))];result('P10-A10',not unexpected,'localhost only');b.close()
counts={x:sum(v['status']==x for v in cases.values())for x in['pass','fail','intentional-skip','not-executed']};report={'suiteId':definition['suiteId'],'testedCommit':os.environ['P10_TESTED_COMMIT'],'definitionSha256':sha(HERE/'p10-browser-v2-definition.json'),'fixtureSha256':sha(HERE/'p10-browser-v2-fixture.py'),'harnessSha256':sha(__file__),'counts':counts,'cases':list(cases.values()),'network':network};(OUT/'acceptance-results.json').write_text(json.dumps(report,ensure_ascii=False,indent=2));print(counts);sys.exit(1 if counts['fail']or counts['not-executed']else 0)
